### ISSUE TITLE
[MOD]  CompilationDirectiveLost вешается на Начало области

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#1000]
## Диагностика
CompilationDirectiveLost

## Описание предлагаемых изменений
вешается на Начало области, а должна на Имя метода

``` bsl
#Область Имя // Вешается сюда
Процедура Метод(Параметр)
КонецПроцедуры
```

**Comment by nixel2007** [comment]
Давай делать, чего тут обсуждать)

**Comment by asosnoviy** [comment]
Это я не в тот шаблон ткнул(
