### ISSUE TITLE
FP на проверке одинаковости условий - разный регистр

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#101]
![image](https://user-images.githubusercontent.com/1132840/53800019-e1363000-3f4c-11e9-9d05-45cbe7c5cad6.png)

**Comment by lChagelishvili** [comment]
Разгребу текущие дела и попробую прогнать проверкой через деревья из #92

**Comment by nixel2007** [comment]
Проверю новую сборку

**Comment by theshadowco** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c3ed2ac92682f000f20d6a6/attachments/5da9be0cd9d3a5000fd517f9)

Ошибка не диагностируется. Закрываю, если повторится - будем раззбираться
