### ISSUE TITLE
[NEW]Не указан обязательный параметр метода

### ISSUE THREAD

**Issue by akabrr** [1c-syntax/bsl-language-server#1010]
## Описание проблемы, ошибки, которую надо диагностировать
Очередной косяк выявленный в проде, в функцию общего модуля не передали обязательный параметр, параметров было два - передали один. Синтаксический контроль проходит. 

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [x] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
1 минута

**Comment by nixel2007** [comment]
Дубль https://github.com/1c-syntax/bsl-language-server/issues/489

**Comment by akabrr** [comment]
Мне кажется, тут не дубль #489. Возможно я плохо описал ситуацию.
Была функция общего модуля, например: ОбщийМодуль.Сумма(А, Б) Экспорт
Её вызвали в таком виде ОбщийМодуль.Сумма(1);
Во время выполнения имеем ошибку "Не достаточно фактических параметров". Ошибку генерит платформа. То есть дело не в том что функция Сумма не рассчитана на параметр Неопределено, а в том что обязательный параметр вообще указан.

**Comment by nixel2007** [comment]
@zeegin? Что скажешь?

**Comment by zeegin** [comment]
Имеет право на жизнь.
При аннотации `ОбщийМодуль.Сумма(А, Б) Экспорт`
проверка из #489 будет ругаться на вызов `ОбщийМодуль.Сумма(, 1)` т.е. когда количество параметров обязательных фактически переданы но не указаны
эта проверка будет ругаться на вызов ``ОбщийМодуль.Сумма(1)` т.е. контракт вообще не соответствует вызову. На это ругаться должны и конфигуратор и едт. Но с целью поддержать vscode можно сделать.

**Comment by nixel2007** [comment]
Ага, различие в том, какие параметры опускаются, понятно, спасибо.

**Comment by nixel2007** [comment]
Я тогда пока открою, но возможно это будет сделано в рамках одной диагностики
