### ISSUE TITLE
Возможность конфигурировать диагностики по принципу "все кроме", "только" и т.д.

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#1020]
@otymko: Например: уровень diagnostics, там свойство mode: except, only, all. А дальше все по старинке

**Comment by nixel2007** [comment]
@otymko стоит ли добавить еще `mode: off` для выключения всего и `mode: on` для поведения по умолчанию?

**Comment by otymko** [comment]
@nixel2007 по идее вместо `off` можно применить пустой `only`, `on` - вполне имеет место жить. Так же можно подумать сделать `mode` необязательным и со значением по умолчанию `on`.

**Comment by nixel2007** [comment]
Mode точно должен быть не обязателен.
А вот off я думаю будет полезен, когда надо выключить все диагностики без ущерба для остального конфига.

**Comment by otymko** [comment]
@nixel2007 я не против `off` значения.
В итоге получается у `mode`:
* `on` (включить все разрешенные по умолчанию)
* `off` (выключить все диагностики)
* `except` (включить все, кроме)
* `only` (включить только)
* `all` (включить все)

**Comment by nixel2007** [comment]
Ситуация - в mode лежит on, и какая-то диагностика явно указана как false. Она (по старой логике) выключается. И это поведение сохраняется, да? Верно друг друга понимаем?

**Comment by nixel2007** [comment]
Как соотносятся except, only и activatedByDefault = false?

**Comment by otymko** [comment]
@nixel2007 да, верно друг друга поняли.

**Comment by otymko** [comment]
> Как соотносятся except, only и activatedByDefault = false?

Думаю надо игнорировать `activatedByDefault` при использовании данных значений.

**Comment by MinimaJack** [comment]
+1
