### ISSUE TITLE
[NEW] Метод Запрос.УстановитьПараметр не проверяется синтаксическим контролем на передачу всех необходимых параметров

### ISSUE THREAD

**Issue by akabrr** [1c-syntax/bsl-language-server#1021]
## Описание проблемы, ошибки, которую надо диагностировать
Описание ошибки в заголовке. 
Пример:
Запрос = Новый Запрос(КакойТоТекстЗапроса);
Запрос.УстановитьПараметр(1);// проходит синтаксический контроль, падает в проде

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [x] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
1

**Comment by asosnoviy** [comment]
#536

**Comment by artbear** [comment]
Данный тикет не является дублем #536, 

т.к. в той задаче речь об инициализации параметров, а в текущей задаче проблема в неверном использовании метода УстановитьПараметр - передали один параметр, а не 2, как положено.

Предлагаю переоткрыть задачу
@asosnoviy @KrapivinAndrey @nixel2007

**Comment by nixel2007** [comment]
кажется это должно ловиться диагностикой про передачу всех обязательных параметров метода
