### ISSUE TITLE
[BUG] для новой диагностики прекоммит-шаг из Градля работает неточно

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1032]
**Описание ошибки диагностики**
> Описание ошибки, замечачания
@TheShadoWCo @nixel2007 прекоммит-шаг из Градля работает неточно (
и для английского описания аналогично.

**Скриншоты**
> Скриншоты с подтверждением
![image](https://user-images.githubusercontent.com/2920817/79020911-d05de200-7b82-11ea-8747-d52a7f40855a.png)

**Comment by artbear** [comment]
еще @theshadowco 
- 1 избавиться от проверки на null внутри всех configure  
- 2 вот этот тест вроде как устарел - т.к. configure теперь никогда не принимает null
```java
  @Test
  void configureNullDryRun() {
    // given
    List<BSLDiagnostic> diagnosticInstances = DiagnosticSupplier.getDiagnosticClasses().stream()
      .map(diagnosticSupplier::getDiagnosticInstance)
      .collect(Collectors.toList());

    // when
    diagnosticInstances.forEach(diagnostic -> diagnostic.configure(null));

    // then
    // should run without runtime errors
  }
```

**Comment by asosnoviy** [comment]
> еще @theshadowco
> 
> * 2 вот этот тест вроде как устарел - т.к. configure теперь никогда не принимает null
> 
> ```java
>   @Test
>   void configureNullDryRun() {
>     // given
>     List<BSLDiagnostic> diagnosticInstances = DiagnosticSupplier.getDiagnosticClasses().stream()
>       .map(diagnosticSupplier::getDiagnosticInstance)
>       .collect(Collectors.toList());
> 
>     // when
>     diagnosticInstances.forEach(diagnostic -> diagnostic.configure(null));
> 
>     // then
>     // should run without runtime errors
>   }
> ```

Сегодня нет null, завтра есть. нормальный тест.

**Comment by nixel2007** [comment]
Это вот точно все не здесь должно обсуждаться

**Comment by artbear** [comment]
в АПИ сразу закладывается - null в этот параметр не передается и все.

никаких костыльных доп.проверок и тестов делать уже не нужно.

**Comment by artbear** [comment]
@theshadowco просил меня инфу выше по конфигурации добавить в этот ишуз из телеги, чтобы не забыть, я и добавил.

**Comment by theshadowco** [comment]
Ошибка градла не подтверждается
