### ISSUE TITLE
Обсудить - Явное указание параметров пакета в package-info.java - улучшение статического анализа кода

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1041]
**Описание проблемы**

начало обсуждения в https://github.com/1c-syntax/bsl-language-server/pull/1027#discussion_r407174809
цитаты из обсуждения @nixel2007 и @artbear 

@artbear
подскажи, а почему не юзаешь аннотации в package-info.java

Например, `import javax.annotation.ParametersAreNonnullByDefault;`
и т.п.
полезная же штука для статического анализа?

в проекте нигде не увидел. наверное, есть причина.

расскажешь?

 @nixel2007
Не увидел от неё пользы в современных идеях. NPE ловятся и светятся и без неё и в идее и в сонарлинте

 @artbear
вот мое исследование:

вижу, что Идея не ловит без явного указания NonNull в коде или в package-info.java

а вот СонарЛинт ловит, что странно, т.к. параметр метода нигде не определен как NonNull
пример кода
```java
  @Override
  public void configure(Map<String, Object> configuration) {
    super.configure(null); // явная передача NULL
```
и код базового интерфейса
```java
default void configure(Map<String, Object> configuration) {
    DiagnosticHelper.configureDiagnostic(this, configuration);
  }
```
- внутри метода  DiagnosticHelper.configureDiagnostic есть проверка на null, а configure нет, 
- вот СонарЛинт и ругается.

и вроде бы ЗРЯ ругается, т.к. вызов `super.configure(null);`  вполне себе валиден с учетом правильной его обработки в DiagnosticHelper.configureDiagnostic

а если в DiagnosticHelper.configureDiagnostic убрать проверку на null вообще
тогда совсем весело
- `уже ни СонарЛинт, ни Идея вообще не ругаются на явно ошибочную передачу null (`
- `а если в package-info ВКЛЮЧИТЬ параметр, тогда Идея ругается, а вот СонарЛинт не ругается вообще`

что и требовалось доказать.

ИМХО явное указание package-info все-таки неплохо помогает от NPE

проверишь? что скажешь?

- @nixel2007
А есть примеры без явной передачи null? Потому что это все же экстра случай

 @artbear
без явной передачи null посмотрю

**Пример кода**
> Пример кода (в блоке code или прикрепленный файл), на котором ошибка воспроизводится

вот хороший пример из боевого кода - нашлось, если включить параметр в package-info

- без включения этого параметра ситуация не ловится
- com/github/_1c_syntax/bsl/languageserver/diagnostics/CreateQueryInCycleDiagnostic.java
- 
- ![image](https://user-images.githubusercontent.com/2920817/79071330-d15a5500-7ce3-11ea-93e8-862fc57e5e09.png)

**Comment by artbear** [comment]
Пример явного указания
```java
@ParametersAreNonnullByDefault
package com.github._1c_syntax.bsl.languageserver.diagnostics;

import javax.annotation.ParametersAreNonnullByDefault;
```

**Comment by artbear** [comment]
Упс. плиз, уберите тег "type/bug", случайно из шаблона приехал (

@nixel2007 @theshadowco @otymko

**Comment by artbear** [comment]
@nixel2007 вот еще интересное

![image](https://user-images.githubusercontent.com/2920817/79072629-c22ad580-7cea-11ea-935e-4ddc6284e2cb.png)

**Comment by nixel2007** [comment]
Это опять про явную передачу null. От этого надо избавляться и без аннотации, видимо, просмотрел на ревью

**Comment by artbear** [comment]
С аннотацией-то, явно заданной в package-info, находить явно легче.

и как раз цель автоматического стат.анализа будет выполнена - найти ошибку, которую человек на ревью может и не увидеть.

цель моего ишуза именно в этом - добавить автопомощи.
