### ISSUE TITLE
[NEW] Запрет экспортных глобальных переменных модуля

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1043]
## Описание проблемы, ошибки, которую надо диагностировать

В статье с ИТС [Использование переменных в программных модулях](https://its.1c.ru/db/v8std#content:639:hdoc) написано так:
>В большинстве случаев, вместо переменных программных модулей следует использовать более подходящие средства разработки платформы 1С:Предприятие. Поскольку область видимости (использования) таких переменных сложно контролировать, то они зачастую становятся источником трудновоспроизводимых ошибок.

Также экспортные переменные модулей могут являться дырами в безопасности.

Диагностика применима к любым модулям, в которых могут быть объявлены экспортные переменные.

В указанной статье с ИТС есть много примеров обхода проблемы.

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

- [Использование переменных в программных модулях](https://its.1c.ru/db/v8std#content:639:hdoc)
- Также в правилах для Java есть аналогичное правило [Class variable fields should not have public accessibility - squid:ClassVariableVisibilityCheck](https://rules.sonarsource.com/java/RSPEC-1104)

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [x] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [x] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [x] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

5 минут

**Comment by alkoleft** [comment]
Возьмусь

**Comment by alkoleft** [comment]
Предлагаю, по умолчанию ее выключить

**Comment by nixel2007** [comment]
Может здесь как раз заодно сделать #1208 и построить диагностику на ней?

**Comment by nixel2007** [comment]
Ты как раз хотел немного харлкора

**Comment by alkoleft** [comment]
Попробую реализовать с прицелом на #1208, если не трудно, хотелось бы пару примеров существующих проверок подпадающих по #1208
