### ISSUE TITLE
[NEW] Ошибка неявного преобразования БезопасныйРежим к типу Булево

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1044]
## Описание проблемы, ошибки, которую надо диагностировать

В "1С:Предприятии 8.3" метод глобального контекста БезопасныйРежим() возвращает тип Строка, если безопасный режим был установлен с указанием имени профиля безопасности.

Для устранения несовместимости необходимо найти все места использования метода БезопасныйРежим(), в которых результат неявно преобразовывался к типу Булево, и исправить на код с явным сравнением результата со значением Ложь. Таким образом, при установленном профиле безопасности код будет выполняться так же, как и в безопасном режиме.

Например, было:
```bsl
Если БезопасныйРежим() Тогда
   
   
    // Логика выполнения в безопасном режиме...
КонецЕсли;
```

```bsl

Если БезопасныйРежим() <> Ложь Тогда
   
   
    // Логика выполнения в безопасном режиме...
КонецЕсли;
```

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

- [Раздел Изменение типа значения, возвращаемого методом глобального контекста "БезопасныйРежим()" в статье "Перевод конфигураций на платформу "1С:Предприятие 8.3" без режима совместимости с версией 8.2"](https://its.1c.ru/db/metod8dev#content:5293:hdoc:izmenenie_bezopasnyjrezhim)

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [x] `DEPRECATED` - "Устаревшая функциональность"
* [x] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

1 минута

**Comment by zeegin** [comment]
@nixel2007 а тега `SECURITY` нет?
Я бы поставил теги: `STANDARD`, `UNPREDICTABLE` , `SECURITY`

**Comment by artbear** [comment]
@zeegin а причем здесь SECURITY ?
эта диагностика должна ловить только ошибочное использование БезопасныйРежим

**Comment by zeegin** [comment]
`SECURITY` здесь в том, что в случае неправильной проверки `БезопасныйРежим` может возникнуть уязвимость приводящая к повышению привилегий. Из-за этого выполнится потенциально опасный код и будет нарушена безопасность кластера.
