### ISSUE TITLE
Неправильная ссылка на ИТС в диагностике FunctionNameStartsWithGet

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#1047]
![image](https://user-images.githubusercontent.com/11651847/79090416-d23ac780-7d73-11ea-862e-8027eb1c51ea.png)

Так же стоит проверить другие диагностики на корректность ссылок на ИТС.

**Comment by nixel2007** [comment]
Отловил вчера, сейчас пушну.
