### ISSUE TITLE
В Руководство контрибьютора нет ссылки на полезную статью "Структура диагностики, назначение и содержимое файлов"

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1048]
на другие статьи ссылки есть, а указанной статьи нет. ее не хватает.

- статья [Структура диагностики, назначение и содержимое файлов](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticStructure)

**Comment by theshadowco** [comment]
сенкс
