### ISSUE TITLE
[BUG] Падает sonar-scanner при проверке

### ISSUE THREAD

**Issue by dr-wut** [1c-syntax/bsl-language-server#1060]
**Версия**
> 1.5.0

**Описание ошибки диагностики**
> При проверке сонар-сканер падает при проверке этого модуля

**Пример кода**
> 
[error_files.zip](https://github.com/1c-syntax/bsl-language-server/files/4482807/error_files.zip) вывод работы и результат ошибки

**Comment by asosnoviy** [comment]
![image](https://user-images.githubusercontent.com/15638529/79373477-4ab1ac00-7f5f-11ea-83ad-14538416837c.png)
