### ISSUE TITLE
Упростить работу с комментариями

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1061]
**Проблематика**

1 В лексере есть несколько видов токенов-комментариев
```java
LINE_COMMENT: '//' ~[\r\n]* -> channel(HIDDEN);
PREPROC_LINE_COMMENT: '//' ~[\r\n]* -> channel(HIDDEN);
```
причем для аннотаций отдельных токенов-комментариев нет

цитата @nixel2007 
>В чем отличие от LINE_COMMENT - семантически наверное ни в чем и в лексере можно установить type(LINE_COMMENT). Но надо посмотреть, где он используется.

PREPROC_LINE_COMMENT используется всего в 2 местах и везде рядом LINE_COMMENT
- ![image](https://user-images.githubusercontent.com/2920817/79378652-5b195500-7f66-11ea-8390-4285743817c5.png)

2 в коде продукта в основном используется LINE_COMMENT. 

и похоже, при этом в разных диагностиках неверно отрабатываются комментарии препроцессора и аннотаций
- 1 ![image](https://user-images.githubusercontent.com/2920817/79378766-9451c500-7f66-11ea-9e0e-05b7242b3c3d.png)
-
- 2 ![image](https://user-images.githubusercontent.com/2920817/79378801-9ddb2d00-7f66-11ea-8498-f0341c94977a.png)

**Хотелось бы**

Было бы удобно использовать один вид токена через приведение типа
например, так сделано для пробелов
```java
PREPROC_WHITE_SPACE: [ \t\f]+ -> channel(HIDDEN), type(WHITE_SPACE);
```

в результате:
- код диагностик упростился 
- и они стал реагировать на комментарии в препроцессоре и в аннотациях

**Comment by theshadowco** [comment]
Можно делать после https://github.com/1c-syntax/bsl-parser/pull/144

**Comment by nixel2007** [comment]
@theshadowco кажется, можно закрывать?
