### ISSUE TITLE
[NEW] Имя переменной совпадает с именем общего модуля

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#1066]
## Описание проблемы, ошибки, которую надо диагностировать

Допустим существует вполне себе рабочий код в котором используется переменная с именем 
КоннекторHTTP
Когда я добавляю общий модуль с именем КоннекторHTTP
Тогда вполне рабочий код начинает падать с исключением в рантайме.

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [x] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

5 минут ?

**Comment by nixel2007** [comment]
https://github.com/1c-syntax/bsl-language-server/issues/1045

не?

**Comment by asosnoviy** [comment]
Там про все, тут конкретно.

**Comment by asosnoviy** [comment]
На этот кейс был конкретный запрос из конкретного упавшего продакта.

**Comment by nixel2007** [comment]
я скорее про то, что может все эти кейсы свести в одну диагностику? просто кидать разные мессаджи, например.
критичной и тип такой ошибки везде одинаковый - это бага с крашем в рантайме.
и можно будет постепенно ее дорабатывать.

**Comment by asosnoviy** [comment]
способы определения разные и области поиска. Например ридонли Свойства форм надо искать в формах по регулярки, а общие моддули везде и поиском в списке. Там где поиск одинаковый, конечно же надо объединять.
