### ISSUE TITLE
[NEW] [ОбщийМодуль] В имени модуля пропущен постфикс "ВызовСервера"

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#1069]
## Описание проблемы, ошибки, которую надо диагностировать
Серверные общие модули для вызова с клиента содержат серверные процедуры и функции, доступные для использования из клиентского кода. Они составляют клиентский программный интерфейс сервера приложения.
Такие процедуры и функции размещаются в общих модулях с признаком:

- **Сервер** (флажок **Вызов сервера** установлен)

Серверные общие модули для вызова с клиента называются по общим правилам именования объектов метаданных и должны именоваться с постфиксом **"ВызовСервера"** (англ. **"ServerCall"**).

Например: РаботаСФайламиВызовСервера, CommonServerCall

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы
https://its.1c.ru/db/v8std#content:469:hdoc:2.2

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [x] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [x] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
5 минут

**Comment by artbear** [comment]
@Stepa86 @nixel2007 @theshadowco @asosnoviy @otymko @zeegin Предлагаю все ишузы по неверному наименованию общих модулей объединить в **одну** диагностику.
для пользователей будет удобней иметь одну диагностику, которое проверяет именование модуля согласно стандарту образования имен модулей,
а не кучу почти одинаковых диагностик.

**Comment by otymko** [comment]
Если тип и важность одинаковая, то можно в одной диагностике реализовать правило проверки наименования общих модулей.

**Comment by Stepa86** [comment]
Вопрос в детальности. На именования все диагностики типы, важности, теги и время на исправление должны быть одинаковы. 

Можно указывать стандарт с точностью до пункта и конкретно ругаться - вы тут не написали "ВызовСервера", вот ссылка и вообще можете ее отдельно отключить в профиле. А можно более оптом "Неправильное имя общего модуля", вот общий стандарт, в сообщение детальная ошибка и в профиле можно либо отключить полностью либо нет.

ЗЫ еще есть момент с количеством диагностик в продукте =)

**Comment by artbear** [comment]
Само собой, собрать в одну диагностику только те проблемы наименования общих модулей, у которых одинаковые характеристики. сейчас вроде бы так и есть в тех ишузах, что сделал @Stepa86 

ну и по увеличению количества диагности вопрос есть. поэтому я на всех и сделал оповещение выше.

повторю его - @Stepa86 @nixel2007 @theshadowco @asosnoviy @otymko @zeegin

**Comment by nixel2007** [comment]
Не будут ли нужны в таком случае флаги включения анализа определённых типов модулей?

**Comment by asosnoviy** [comment]
А в чем проявляется удобство одной диагностики?

**Comment by artbear** [comment]
у меня есть опыт использования кучи диагностик проверки наименования модулей, сами знаете.

- одной диагностикой управлять удобнее\проще, чем кучей почти одинаковых диагностик.
- В профили включить\исключить легче одну, чем кучу.
- ну одна диагностика будет чуть-чуть быстрее работать, чем куча похожих, пусть даже от общего абстрактного класса.

**Comment by asosnoviy** [comment]
* Разными диагностиками можно управлять, одной нет.
* Бесспорно легче, но зачем?
* Утверждение сомнительно

**Comment by theshadowco** [comment]
нафиг одну, разными как раз проще, можно указать критичность для них. Я например у себя использую несколько отличное именование для некоторых типов модулей.
