### ISSUE TITLE
[NEW] [ОбщийМодуль] Модуль недопустимого типа

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#1072]
## Описание проблемы, ошибки, которую надо диагностировать
Модуль может быть только одним из 4х типов.

|Тип общего модуля | Пример наименования | Вызов сервера | Сервер | Внешнее соединение | Клиент(обычное приложение) | Клиент(управляемое приложение)|
-- | -- | -- | -- | -- | -- | --|
| Серверный | ОбщегоНазначения (или ОбщегоНазначенияСервер) |   | + | + | + |  
| Серверный для вызова с клиента | ОбщегоНазначенияВызовСервера | + | + |   |   |  
| Клиентский | ОбщегоНазначенияКлиент (или ОбщегоНазначенияГлобальный) |   |   |   | + | +
| Клиент-серверный | ОбщегоНазначенияКлиентСервер |   | + | + | + | +|

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

https://its.1c.ru/db/v8std#content:469:hdoc:1.2

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [x] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
5 минут

**Comment by zeegin** [comment]
Должна быть настройка которая отключает проверку обычного приложения, а случае если конфигурация заявляет что обычное приложение вообще не поддерживается.
Так же флажок обычное приложение отсутствует в случае разработки мобильного приложения.
