### ISSUE TITLE
Проверка уровня вложенности синтаксических конструкций друг в друга

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#108]
Если в Цикле В Попытке В Если и т.д.
Покурить лимиты, проверяющиеся конструкции и описания диагностики в других языках.

**Comment by Stepa86** [comment]
А разве не для этого цикломатическая сложность нужна?

**Comment by nixel2007** [comment]
цикломатика растет и из-за последовательных условий. три или четыре уровня вложенности Если и твой мозг уже плывет. А цикломатика при этом - 3/4 и умещается в лимит 10.

**Comment by nixel2007** [comment]
https://rules.sonarsource.com/java/RSPEC-134

**Comment by asosnoviy** [comment]
@nixel2007 @zeegin @otymko @lChagelishvili  По дефулту Максимально допустимый 3 или 4?
