### ISSUE TITLE
[MOD] InvalidCharacterInFileDiagnostic работает медленно 

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1081]
## Диагностика

- InvalidCharacterInFileDiagnostic

## Описание предлагаемых изменений

правило работает довольно медленно.
что видно, например, из исследования https://gist.github.com/MinimaJack/0bc90fe19964b4cd5ede092c9fba91d9

- ![image](https://user-images.githubusercontent.com/2920817/79499020-f972ec80-8032-11ea-909a-7ddfea0f8940.png)

**Comment by asosnoviy** [comment]
А что значат эти цифры?

**Comment by MinimaJack** [comment]
@asosnoviy ms потрачено процессорного времени на диагностику при анализе SSL 3.1
