### ISSUE TITLE
[FP] Ложное срабатывание CreateQueryInCycle

### ISSUE THREAD

**Issue by proDOOMman** [1c-syntax/bsl-language-server#1083]
## Диагностика
CreateQueryInCycle

## Версия
1.5.0

## Описание ложного срабатывания диагностики
См. код

## Пример кода
```
Запрос = Новый Запрос("ВЫБРАТЬ Код ИЗ Справочник.СтраныМира ГДЕ Предопределенный");
Для Каждого СтрокаПредопределенного Из Запрос.Выполнить().Выгрузить() Цикл
КонецЦикла;
```

## Скриншоты
https://prnt.sc/s0i3ac

## Дополнительная информация
Код типовой из БСП 3.0

**Comment by MinimaJack** [comment]
Дубль #1018
