### ISSUE TITLE
Ошибки при расчете строк для покрытия

### ISSUE THREAD

**Issue by yukon39** [1c-syntax/bsl-language-server#1089]
При включенной настройке sonar.bsl.calculateLineCover в расчет строк которые должны быть покрыты ошибочно включаются операторы:
* `#КонецОбласти`
* `Попытка`
* `#КонецЕсли`

Версия плагина 1.5.0
Версия SQ: 7.9.3 LTS

**Comment by asosnoviy** [comment]
Надо ли убрать все Инструкции препроцессору?

**Comment by nixel2007** [comment]
да, можно убрать весь препроцессор. и директивы компиляции/аннотации тоже, если вдруг они попадают в текущие данные метрики.

**Comment by Stepa86** [comment]
Я у себя за код не считаю все, что начинается с:
- `//`
- `Перем`
- `#`
- `&`
- `Процедура`
- `Функция`
- `Иначе`
- `Попытка`
- `Исключение`

и отдельные извраты для переносов строки и переносов выражений

**Comment by yukon39** [comment]
Тут нужно исходить из того, что включать нужно только те операторы, которые вообще МОГУТ быть выполнены.

**Comment by asosnoviy** [comment]
Кстати тестам не верить, они там врут.

**Comment by artbear** [comment]
Еще в некоторых случаях КонецПроцедуры\КонецФункции включается в покрытие, а в некоторых нет (
похоже, если попали в метод, то включается, если не попали, не включается, хотя прочие строки метода исключаются.

![image](https://user-images.githubusercontent.com/2920817/122561973-28c42580-d04b-11eb-8fd5-ed75c85a94eb.png)

**Comment by artbear** [comment]
Аналогично попадает\не попадает КонецЕсли

**Comment by artbear** [comment]
Еще КонецЕсли не включен в покрытие, если перед ним есть зеленый Возврат

![image](https://user-images.githubusercontent.com/2920817/122562535-d8999300-d04b-11eb-9ed1-695f360b0d0b.png)
