### ISSUE TITLE
Процедура не может возвращать значение

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#109]
Платформой/оскриптом оно, конечно, не скомпилируется, но мы могли бы ругаться. Или лучше пускай парсер это разруливает?

Ключевое отличие - платформа/движок/парсер напишут об этом один раз, а диагностика - на каждое использование.

/discuss

**Comment by asosnoviy** [comment]
С парсером бяда что скажет не внятно, и ещё надо понять о чем это. Имхо если линтер бросит диагностик мессадж красивее.

**Comment by otymko** [comment]
Я взял в работу ишуз
