### ISSUE TITLE
Функция всегда возвращает одно и то же булево значение

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#110]
Если результат функции не нужен, то нужно переписывать на процедуру, а если нужен, то подозрительно, если она всегда возвращает одно и то же.

```bsl
Функция ПроверитьСтроку(Знач СтрокаТаблицы)

    Если ЭтоХорошаяСтрока( СтрокаТаблицы ) Тогда

        ДелаемЧтоТоЧтобыНеРугаласьПроверкаНаПовтор();
        Возврат Истина;

    ИначеЕсли ЭтоТожеНеплохаяСтрока( СтрокаТаблицы ) Тогда

        ДелаемДругоеЧтоТоЧтобыНеРугаласьПроверкаНаПовтор();
        Возврат Истина;

     Иначе

        Возврат Истина;

    КонецЕсли;

КонецФункции
```

Можно развить до диагностики "Функция всегда возвращает одно и то же", если это возможно сделать

**Comment by asosnoviy** [comment]
А в жизни такое встречается?=)

**Comment by Stepa86** [comment]
Нужно написать проверку и узнать...

Эта ошибка из той же серии, что и дублирование условий или дублирование блока текста - возникает из-за копипаста

**Comment by lChagelishvili** [comment]
Не у компьютера, но вроде обработчики подключаемых команд в бсп как-то так и написаны.

**Comment by zeegin** [comment]
Ой сколько будет ложных срабатываний...

`Вычислить` работает в веб-клиенте. `Выполнить` не работает. При этом выполнить процедуру через вычислить нельзя. Потому почти весь подключаемый функционал клиента, так где должны были быть процедуры, сделан функциями с возвратом (а иногда и без него).

Нужно ждать доработку от платформы по выполнить в веб-клиенте, потом исправлять апи библиотек, потом конфигураци с вызовом апи, и только потом эта проверка будет показывать без FP.

Делаю ставку на 5-7 лет.

**Comment by Stepa86** [comment]
То есть мы имеем костыль для обхода недоработок платформы, поэтому нам не нужна проверка, которая будет показывать и реальные ошибки?

Ну и ошибка направлена на поиск нескольких одинаковых возвратов, один `Возврат Истина` ошибкой скорей всего не стоит считать

**Comment by zeegin** [comment]
Я это говорю почему, потому что с очень большой вероятностью большинство отключат проверку. Потому что слишком много будет ложных срабатываний. Сложно фильтровать. Когда много ложных срабатываний у разработчиков теряется мотивация искать среди них реальные ошибки.

**Comment by theshadowco** [comment]
Нужно будет анализировать ф-ии вида

```bsl
Функция НекаяКонстанта() 
Возврат "СтроковаяКонстанта";
КонецФункции
```

**Comment by theshadowco** [comment]
иначе fp просто море будет

**Comment by artbear** [comment]
Такое правило хорошо работает, если добавить к нему проверку наличия минимального количества Возвратов - 2 или 3.
тогда простые случаи вроде указанных @zeegin исключаются и остаются только настоящие подозрительные методы

**Comment by artbear** [comment]
@zeegin ⬆️

**Comment by artbear** [comment]
а зачем вообще проверять\исключать подключаемые методы?
в них чаще всего всего как раз один возврат и они будут исключаться автоматически.

а если уже 2 одинаковых возврата, то вот тогда это уже проблема и лучше ловить, а не исключать
Предлагаю вообще убрать исключение подключаемых методов из-за бессмысленности.

**Comment by asosnoviy** [comment]
Коммент от @artbear 
Такое правило хорошо работает, если добавить к нему проверку наличия минимального количества Возвратов - 2 или 3.
тогда простые случаи вроде указанных @zeegin исключаются и остаются только настоящие подозрительные методы
