### ISSUE TITLE
[MOD] Метод не должен содержать много возвратов (отдельно задавать Max для функций и процедур)

### ISSUE THREAD

**Issue by Evg-lylyk** [1c-syntax/bsl-language-server#1102]
## Диагностика
Метод не должен содержать много возвратов

## Описание предлагаемых изменений
Было бы удобно задавать ограничение отдельно на функции отдельно на процедуры
Мне удобно для функций задать 1, но для процедур я бы задал 3
Понятно что есть функции где в начале возврат, но я так делаю очень редко
Хорошая практика когда у функции один возврат в конце

**Comment by asosnoviy** [comment]
А почему в процедуре 3? Мне кажется, что нет разницы  возвращает метод значение или нет, возвраты в нем это примерно одно и тоже. 
Хотя если развить, то в процедуре на один "неявный"  возврат больше =).

**Comment by Evg-lylyk** [comment]
"Хотя если развить, то в процедуре на один "неявный" возврат больше =)."
Согласен
Мне удобно для функций 1 редкие исключения я осмотрю
А вот для процедур кажется разумным 2

**Comment by asosnoviy** [comment]
@Evg-lylyk необходимость не отпала? Кажется там достаточно простое изменение, что бы сделать самостоятельно.

**Comment by Evg-lylyk** [comment]
Да, не стоит делать, поставил 1 возврат и те редкие случае где более 1 и считаю обоснованными добавляю в исключения

**Comment by asosnoviy** [comment]
хм, а я намекал на PR =)

**Comment by Evg-lylyk** [comment]
> хм, а я намекал на PR =)
Да я понял, не знаю Java. Сосредоточен на своих проектах.
