### ISSUE TITLE
[BUG] ошибка фонового задания NullPointerException

### ISSUE THREAD

**Issue by Alk0k0** [1c-syntax/bsl-language-server#1110]
**1.5.0**

Периодически при работе фонового задания Сонар появляется ошибка java.lang.NullPointerException: null
[ce.log](https://github.com/1c-syntax/bsl-language-server/files/4524782/ce.log)
![Ошибка Sonar](https://user-images.githubusercontent.com/53838986/80141560-3f7f0180-8599-11ea-8e6d-a7c1c55e37a5.png)

**Возникает не постоянно, где-то каждую четвертую проверку.**

**Comment by nixel2007** [comment]
Здесь бсл лс или коммьюнити сонар плагин не причём, они не выполняют действий на стороне CE.
Попробуйте обновиться до последней версии сервера или зарепортить ошибку на community.sonarsource.org

**Comment by Alk0k0** [comment]
Попробую, спасибо.
