### ISSUE TITLE
Неверно заполняется путь к исходным файлам при формировании отчета

### ISSUE THREAD

**Issue by yukon39** [1c-syntax/bsl-language-server#1114]
**Наблюдается в версии 14.1**

При формировании отчета средствами командной строки (`--analyze`) в случае когда указывается путь к файлам проекта в отчет попадают некорректные пути файлов.

**Пример**
Структура проекта:

> ```
> src/
>     cf
>         module.os
>     otherstuff
> tools
> ```

Если указываем в качестве каталога исходников путь `src/cf`:
`--analyze --srcDir src/cf`
 то в отчет путь к `module.os` выводится как `module.os` вместо `src/cf/module.os`

Единственный способ вывести корректный путь к модулю относительно корневой папки, это указать в качестве каталога исходников саму корневую папку (или, что то же самое не указывать параметр). Но в этом случае избыточно анализируется содержимое всех папок проекта (включая tools и otherstuff).

**Предлагаемое решение**
Добавить параметр `workspaceDir` - каталог проекта относительно которого и должны указываться пути к исходным файлам.

В этом случае выполнение команды
`--analyze --srcDir src/cf --workspaceDir .`
Укажет пути как `src/cf/module.os`
Выполнение команды
`--analyze --srcDir src/cf --workspaceDir src/cf`
Укажет пути как `module.os`

**Comment by nixel2007** [comment]
Это запланированное поведение, скажем так, и оно было специально изменено с CWD на путь относительно srcDir.
Призываю @TheShadoWCo

**Comment by yukon39** [comment]
Тут более функциональное решение - можно и так и так в итоге. Можно даже так:
`--analyze --srcDir src/cf --workspaceDir src`
Получим пути к файлам вида `cf/module.os`

В текущей парадигме или избыточно проверять весь корень проекта, и потом вычищать ненужное из отчета, или указать папку и потом опять же лезть в отчет дополнять пути к файлам. Оба варианта, мягко сказать, костыльны.

**Comment by yukon39** [comment]
MVP реализации: https://github.com/yukon39/bsl-language-server/commit/59e6ef58918094a628a01db4757d3fc214570b7a

**Comment by nixel2007** [comment]
В целом согласен, да. Можно добавить
