### ISSUE TITLE
Информация о директиве компиляции в MethodSymbol

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1115]
Сейчас эта информация отсутствует.

после ее вычисления можно доработать следующие диагностики, убрав поиск директивы компиляции

- [ ] SeveralCompilerDirectivesDiagnostic
- [ ] UsingSynchronousCallsDiagnostic

- [x] FormDataToValueDiagnostic

**Comment by theshadowco** [comment]
@artbear 
Сейчас есть. Запостишь отдельными тасками доработки, которые ты хотел бы видеть?

**Comment by artbear** [comment]
Связанный ПР https://github.com/1c-syntax/bsl-language-server/pull/1858

**Comment by theshadowco** [comment]
👍🏻
