### ISSUE TITLE
[NEW] Избыточное обращение к объекту

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#1124]
## Описание проблемы, ошибки, которую надо диагностировать

В формах и модулях объектов избыточно обращаться к реквизитам через **ЭтотОбъект**. В формах еще **ЭтаФорма**.

`ЭтотОбъект.Контрагент = ПолучитьКонтрагента();`

В общих модулях избыточно обращаться к методам через свое имя, кроме модулей с **ПовтИсп**.

В Модуле ОбщегоНазначения плохо писать
`ОбщегоНазначения.СообщитьПользователю(`

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [x] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [x] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
1

**Comment by asosnoviy** [comment]
Использование Этот объект.Реквизмт мой любимый способ указания показать, что это именно реквизит объекта. ЭтаФорма депрекейтед. Имхо это какой-то вредный совет

**Comment by Stepa86** [comment]
> Использование Этот объект.Реквизмт мой любимый способ указания показать, что это именно реквизит объекта. ЭтаФорма депрекейтед. Имхо это какой-то вредный совет

Всегда можно выключить диагностику у себя.

**Comment by Stepa86** [comment]
Я это разделяю регистром букв в именовании. `контрагент = ПолучитьКонтрагента()` это переменная, а `Контрагент = ПолучитьКонтрагента()` это реквизит.
