### ISSUE TITLE
Заполнение время исправления диагностик для SonarQube

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#113]
Заполняю усредненное время исправления диагностик для SonarQube. **Нужно объективное мнение**. Текущий список:
- CanonicalSpellingKeywordsDiagnostic / Каноническое написание ключевых слов / **1min**
- EmptyCodeBlockDiagnostic / Пустой блок кода/ **5min?**
- EmptyStatementDiagnostic / Пустой оператор / **1min**
- FunctionShouldHaveReturnDiagnostic / Функция должна содержать возврат / **5min**
- IfElseDuplicatedCodeBlockDiagnostic / Повторяющийся блок кода / **5min?**
- IfElseDuplicatedConditionDiagnostic / Повторяющееся условие / **2min**
- IfElseIfEndsWithElseDiagnostic / Использование синтаксической конструкции Если...Тогда...ИначеЕсли... / **5min**
- LineLengthDiagnostic / Ограничение на длину строки / **2min**
- MethodSizeDiagnostic / Ограничение на размер метода / **3min ?**
- NestedTernaryOperatorDiagnostic / Вложенный тернарный оператор / **2min**
- NumberOfOptionalParamsDiagnostic / Ограничение на количество не обязательных параметров метода / **10min**
- NumberOfParamsDiagnostic/ Ограничение на количество параметров метода / **10min**
- OneStatementPerLineDiagnostic / Одно выражение в одной строке / **1min**
- OrderOfParamsDiagnostic / Порядок параметров метода / **10min**
- SelfAssignDiagnostic / Присвоение переменной самой себе / **5min**
- SemicolonPresenceDiagnostic / Выражение должно заканчиваться ";" / **1min**
- UnknownPreprocessorSymbolDiagnostic / Неизвестный символ препроцессора / **5min?**
- UsingCancelParameterDiagnostic / Работа с параметром "Отказ" / **2min**
- YoLetterUsageDiagnostic / Использование буквы “ё” в текстах модулей / **1min**

**Comment by Stepa86** [comment]
Мой вариант:

- CanonicalSpellingKeywordsDiagnostic / Каноническое написание ключевых слов / **5min**
- EmptyCodeBlockDiagnostic / Пустой блок кода/ **10min**
- EmptyStatementDiagnostic / Пустой оператор / **10min**
- FunctionShouldHaveReturnDiagnostic / Функция должна содержать возврат / **10min**
- IfElseDuplicatedCodeBlockDiagnostic / Повторяющийся блок кода / **10min**
- IfElseDuplicatedConditionDiagnostic / Повторяющееся условие / **10min**
- IfElseIfEndsWithElseDiagnostic / Использование синтаксической конструкции Если...Тогда...ИначеЕсли... / **20min**
- LineLengthDiagnostic / Ограничение на длину строки / **20min**
- MethodSizeDiagnostic / Ограничение на размер метода / **60min**
- NestedTernaryOperatorDiagnostic / Вложенный тернарный оператор / **10min**
- NumberOfOptionalParamsDiagnostic / Ограничение на количество не обязательных параметров метода / **60min**
- NumberOfParamsDiagnostic/ Ограничение на количество параметров метода / **60min**
- OneStatementPerLineDiagnostic / Одно выражение в одной строке / **5min**
- OrderOfParamsDiagnostic / Порядок параметров метода / **30min**
- SelfAssignDiagnostic / Присвоение переменной самой себе / **10min**
- SemicolonPresenceDiagnostic / Выражение должно заканчиваться ";" / **5min**
- UnknownPreprocessorSymbolDiagnostic / Неизвестный символ препроцессора / **5min**
- UsingCancelParameterDiagnostic / Работа с параметром "Отказ" / **10min**
- YoLetterUsageDiagnostic / Использование буквы “ё” в текстах модулей / **10min**

**Comment by Stepa86** [comment]
В случае отсутствия линтера любое исправление ошибки начинается с поиска в конфигураторе, а это иногда больше времени отнимает, чем исправление

**Comment by otymko** [comment]
@Stepa86 Спасибо. Сейчас усредню.

**Comment by otymko** [comment]
Минимальное время исправления 5мин.

**Comment by otymko** [comment]
#114
