### ISSUE TITLE
[NEW] [Мета] Объекту присвоено запрещенное имя

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#1130]
## Описание проблемы, ошибки, которую надо диагностировать

2.5. Также рекомендуется не использовать имена, которые применяются при именовании таблиц языка запросов (например, Документ, Справочник, РегистрСведений и т.д.). Такие имена могут приводить к ошибкам при исполнении запроса, затрудняют использование конструктора запроса и снижают наглядность текста запроса. Например, выполнение данного запроса вызывает ошибку:

```
ВЫБРАТЬ
Сведения.Сведения
ИЗ
РегистрСведений.Сведения КАК Сведения
```

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

https://its.1c.ru/db/v8std#content:474:hdoc:2.5

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [x] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [x] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [x] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

## Дополнительная информация
Запрещенные имена:

AccountingRegister
AccountingRegisters
AccumulationRegister
AccumulationRegisters
BusinessProcess
BusinessProcesses
CalculationRegister
CalculationRegisters
Catalog
Catalogs
ChartOfAccounts
ChartOfCalculationTypes
ChartOfCharacteristicTypes
ChartsOfAccounts
ChartsOfCalculationTypes
ChartsOfCharacteristicTypes
Constant
Constants
Document
DocumentJournal
DocumentJournals
Documents
Enum
Enums
ExchangePlan
ExchangePlans
FilterCriteria
FilterCriterion
InformationRegister
InformationRegisters
Task
Tasks
БизнесПроцесс
БизнесПроцессы
Документ
Документы
ЖурналДокументов
ЖурналыДокументов
Задача
Задачи
Константа
Константы
КритерииОтбора
КритерийОтбора
Перечисление
Перечисления
ПланВидовРасчета
ПланВидовХарактеристик
ПланОбмена
ПланСчетов
ПланыВидовРасчета
ПланыВидовХарактеристик
ПланыОбмена
ПланыСчетов
РегистрБухгалтерии
РегистрНакопления
РегистрРасчета
РегистрСведений
РегистрыБухгалтерии
РегистрыНакопления
РегистрыРасчета
РегистрыСведений
Справочник
Справочники

**Comment by zeegin** [comment]
Добавь с список `Представление` и `Команда`
