### ISSUE TITLE
[NEW] CodeAction "Объединить последовательные Если" без диагностики или с информационной диагностикой

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1167]
## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

Есть полезный квик-фикс - Объединить последовательные Если
но диагностика для него не нужна или она должна быть информационной

Например, есть одинаковый код внутри Если
```bsl
Если Условие Тогда
  ЧтоТо();
КонецЕсли;

Если Условие2 Тогда
  ЧтоТо();
КонецЕсли;
```
его бы отрефакторить в один блок
```bsl
Если Условие Или Условие2 Тогда
  ЧтоТо();
КонецЕсли;
```
или еще пример, когда нужно объединять Если\ИначеЕсли
НомерПараметраПутьКТестам = 1; 
совпадает в коде ниже
```bsl
Если КомандаЗапуска = СтруктураПараметровЗапуска.ПоказатьСписок Тогда
  ПутьКТестам = МассивПараметров[1];
ИначеЕсли КомандаЗапуска = СтруктураПараметровЗапуска.Запустить Тогда
  НомерПараметраПутьКТестам = 1;
ИначеЕсли КомандаЗапуска = СтруктураПараметровЗапуска.ЗапуститьКаталог Тогда
  НомерПараметраПутьКТестам = 1;

Иначе
  НомерПараметраПутьКТестам = 0;
КонецЕсли;
```
В итоге есть полезный квик-фикс, как в других ИДЕ, но диагностика для него, скорее всего, будет никому не нужна.

Теги не поставлены. Подходящего не нашел )

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [x] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [x] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

1 минута

**Comment by artbear** [comment]
дополнил кейсом, когда `нужно объединять Если\ИначеЕсли`

**Comment by asosnoviy** [comment]
#959

**Comment by artbear** [comment]
Закрываю текущий ишуз, т.к. есть более ранний и полный https://github.com/1c-syntax/bsl-language-server/issues/959

перенес туда кейсы.
