### ISSUE TITLE
[MOD] CodeAction для "Слишком сложные условия" - выделить такое условие в отдельный метод

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1168]
## Диагностика

IfConditionComplexity
## Описание предлагаемых изменений

Исходное правило #290 и ПР для него #301

QuickFix "выделить такое условие в отдельный метод" был бы полезен для рефакторинга.

**Comment by asosnoviy** [comment]
CodeAction Extract Method

**Comment by asosnoviy** [comment]
#1170
