### ISSUE TITLE
[NEW] CodeAction рефакторинг "Переименование метода"

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1172]
Сделать для приватных методов любых модулей

**Comment by nixel2007** [comment]
это не код экшен. за это отвечает `textDocument/rename`

**Comment by artbear** [comment]
Не знал, буду знать.

**Comment by zeegin** [comment]
Переименовать? Закрыть?

**Comment by artbear** [comment]
Реализовано в https://github.com/1c-syntax/bsl-language-server/pull/2788
