### ISSUE TITLE
Вызов устаревших методов

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#1177]
## Описание проблемы, ошибки, которую надо диагностировать

Вызов методов помеченных как "Устарело." в описании метода

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [x] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Время на исправление (минут)

1 минута

**Comment by zeegin** [comment]
Обязательно нужно учесть следующий факт:

- Устаревшие методы запрещено вызывать из не устаревших.
- Устаревшие методы разрешено вызывать из методов помеченных как устаревшие.

Это важный FP который возникнет на методах которые оставлены для обратной совместимости.

**Comment by nixel2007** [comment]
Ох ты ж, спасибо.
