### ISSUE TITLE
[FP] UnusedLocalMethod на обработках оповещения

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#1191]
## Диагностика

UnusedLocalMethod вешается на метод обработчик оповещения

## Описание ложного срабатывания диагностики

```bsl
Обработчик = Новый ОписаниеОповещения("ДобавитьИзФайловойСистемыБезРасширенияПослеОтветаНаВопросПовторить", ЭтотОбъект, ПараметрыВыполнения);
```
## Скриншоты

![image](https://user-images.githubusercontent.com/15638529/81845678-943ee800-9559-11ea-95eb-8244d12743d7.png)

**Comment by alkoleft** [comment]
Возьмусь

**Comment by asosnoviy** [comment]
> Возьмусь.
> На всякий случай, в bslls нет dataflow analysis? (граф присвоений, возможные значения/типы и тд)

Нету, но очень хочется что бы был

**Comment by nixel2007** [comment]
Может подождём базы контекстов, чтобы все в нормальный апи завернуть?

**Comment by asosnoviy** [comment]
> Может подождём базы контекстов, чтобы все в нормальный апи завернуть?

А контексты разве помогут? Это же обработчик описания оповещения.

**Comment by nixel2007** [comment]
> А контексты разве помогут? Это же обработчик описания оповещения.

мы ж там хотели добавить третий уровень, с локальными контекстами. и метод а-ля isHandler

**Comment by nixel2007** [comment]
можно, впрочем, начать втягивать API-классы контекста и сформировать контекст уровня bsl ls. 
но тогда надо зафинализировать и зафиксировать API движков контекста.
