### ISSUE TITLE
Прямое указание в руководстве по стилю соглашения по возвращаемым значениям

### ISSUE THREAD

**Issue by EightM** [1c-syntax/bsl-language-server#1200]
В целях унификации существующей и будущей кодовой базы предлагается внести следующее изменение в руководство контрибьютора - руководство по стилю:
`Если метод на законных основаниях может возвращать null, следует возвращать Optional<T>, вместо явного возврата null.`

Почему это необходимо:
Сейчас все пишут вразнобой, кто-то в своих методах возвращает null, кто-то Optional. В результате код рвется на разные по стилю лоскуты. 
Зафиксировав единственный вариант, код будет читаться и писаться проще.

**Comment by theshadowco** [comment]
нужен PR :-)
