### ISSUE TITLE
[MOD] Изменение диагностики  NonStandardRegion

### ISSUE THREAD

**Issue by kuzja086** [1c-syntax/bsl-language-server#1207]
## Диагностика
NonStandardRegion

## Описание предлагаемых изменений
Необходимо расширить диагностику и в модуле HTTP-сервиса сделать две разрешенные области:
-ОбработчикиСобытий
-СлужебныеПроцедурыИФункции

**Comment by EightM** [comment]
@nixel2007 У вас задача отклеилась

**Comment by nixel2007** [comment]
Мерси
