### ISSUE TITLE
Новый тип диагностики на основе перебора Symbol tree

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#1208]
Некоторые диагностики работают на базе символьного дерева, часто - на базе MethodSymbol и им не нужна информация о дереве разбора. Было бы удобно иметь абстрактную диагностику, в которой были бы методы в духе `visitMethodSymbol(MethodSymbol symbol)`

**Comment by nixel2007** [comment]
NonExportMethodsInApiRegionDiagnostic, MethodSizeDiagnostic и т.п.

**Comment by alkoleft** [comment]
С точки зрения производительности, ИМХО, лучше предоставить методы геттеры, ExportVariables, NonExport. Или реализовать у *Symbol классов методы проверок, isExport, InRegion - добавит удобства при работе со stream.

**Comment by nixel2007** [comment]
Эм... Не знаю, как это может повлиять на производительность, если честно. Это классический gof-овский visitter, который должен рекурсивно перебрать все символьное дерево и вызвать visit* в зависимости от типа символа
