### ISSUE TITLE
[MOD] Имена объектов метаданных не должны превышать 80 символов, для объектов без модулей

### ISSUE THREAD

**Issue by alkoleft** [1c-syntax/bsl-language-server#1214]
## Описание проблемы, ошибки, которую надо диагностировать
Имена объектов метаданных не должны превышать 80 символов.

Реализована проверка для объектов содержащих модули (#1128), необходимо реализовать для объектов, которые не содержат модули

Кроме проблем с использованием этих объектов возникают проблемы с выгрузкой конфигурации в файлы.

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы
https://its.1c.ru/db/v8std#content:474:hdoc:2.3

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)
* [x]  🐜 Ошибка
* [ ]  👮 Уязвимость
* [ ]  💂‍♂️ Потенциальная уязвимость
* [ ]  💩 Качество кода
* [ ]  :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)
* [ ]  💔 Блокирующая / Blocker
* [ ]  ❤️ Критическая / Critical
* [x]  💛 Важная / Major
* [ ]  💙 Незначительная / Minor
* [ ]  💚 Информационная / Info
* [ ]  💞 Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)
* [x]  `STANDARD` - "Нарушение стандартов 1С"
* [ ]  `LOCKINOS` - "Не будет работать в другой ОС"
* [ ]  `SQL` - "Проблема с запросом"
* [ ]  `PERFORMANCE` - "Проблема производительности"
* [ ]  `BRAINOVERLOAD` - "Непонятный код"
* [ ]  `BADPRACTICE` - "Плохая практика программирования"
* [ ]  `CLUMSY` - "Излишние действия"
* [ ]  `DESIGN` - "Ошибка в проектировании"
* [ ]  `SUSPICIOUS` - "Подозрительный код"
* [ ]  `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ]  `DEPRECATED` - "Устаревшая функциональность"
* [ ]  `ERROR` - "Ошибочная конструкция"
* [ ]  `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
10

## Дополнительная информация

**Comment by theshadowco** [comment]
дубль https://github.com/1c-syntax/bsl-language-server/issues/1128

**Comment by theshadowco** [comment]
читал невнимательно
