### ISSUE TITLE
[NEW] Неверное использование новых методов платформы 1С, которые не разрешены версией платформы для разрабатываемой системы или ее режимом совместимости

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1221]
## Описание проблемы, ошибки, которую надо диагностировать
Разработчики допускают ошибки, используя новые версии платформы и новые методы платформы, которые не разрешены режимом совместимости.
При этом могут возникнуть проблемы, если развернуть систему на более старой платформе. Будет ошибка выполнения.

Возможно, нужно анализировать не только режим совместимости, но и указывать версию платформы в файлах настройки анализа.
Также учесть приоритет - если версия в конфиге не задана, учитывать режим совместимости.

Настройка в конфиге актуальная для Конфигуратора, в ЕДТ версия платформы хранится сразу в исходниках
.

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [x] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

10 минут

**Comment by artbear** [comment]
Есть исключения:
использование методов СтрХХХ выдает синтакс-ошибку в Конфигураторе сразу же, если указан режим совместимости ниже 8.3.6
т.е для этих методов диагностика не будет особо полезна.

**Comment by asosnoviy** [comment]
Дубль #930
