### ISSUE TITLE
[NEW] У web- и http-сервиса неверно задан обработчик метода

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1222]
## Описание проблемы, ошибки, которую надо диагностировать
Разработчики иногда допускают ошибки при создании множества методов веб-сервисов, забывая указать метод-обработчик веб-сервиса.

Конфигуратор ругается только при включенном флаге "Проверка существования назначенных обработчиков"

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [x] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [x] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

10 минут

**Comment by zeegin** [comment]
Предлагаю повысить до `Блокирующий` и `Ошибка`

**Comment by artbear** [comment]
@theshadowco Уже можно реализовывать правило, т.к. поддержка метаданных реализована в связанном ишузе, верно?
тогда сними тег require/metadata

**Comment by theshadowco** [comment]
В операциях вебсервисов и хттп сервисов есть свойство handler

**Comment by artbear** [comment]
@nixel2007 Назначь на меня, я большую часть правил уже сделал.

**Comment by artbear** [comment]
@zeegin @nixel2007 Вопрос - Нужно ли в этом правиле проверять наличие хотя бы одного возврата в методе-обработчике?

правило на наличие Возвратов есть, но у него важность более низкая, и замечания по нему не являются ошибкой.
а для сервисов важно явно что-то вернуть вместо неявного возврата Неопределено, если нет возвратов.
