### ISSUE TITLE
[NEW] Неверное использование СтрШаблон

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1235]
## Описание проблемы, ошибки, которую надо диагностировать

можно довольно легко ошибиться при передаче значений для СтрШаблон

1. Количество переданных после шаблонной строки значений не равно (меньше или больше) максимальному номеру из строки вида %N внутри шаблонной строки
  - `СтрШаблон("Наименование (версия %1)'");` - как в варианте 2 ниже
  - `СтрШаблон("%1 (версия %2)'", Наименование);`

2. не передается вообще никаких значений, кроме форматированной строки
из-за большго число скобок внутри несложного выражения с НСтр и СтрШаблон
Пример:
- `СтрШаблон(НСтр("ru='Наименование (версия %1)'", Версия()));`
здесь ошибочно не закрыта скобка для НСтр 
в итоге выражение после вычисления НСтр становится пустым.

Выявить подобную ошибку чтением кода довольно сложно из-за наличия скобок.
И можно поймать только в рантайме (

Правильный вариант:
  - `СтрШаблон(НСтр("ru='Наименование (версия %1)'"), Версия());`

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

Связанные задачи:
- https://github.com/1c-syntax/bsl-language-server/issues/612
- https://github.com/1c-syntax/bsl-language-server/issues/365
### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [x] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [x] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

1 минута

**Comment by zeegin** [comment]
Будет гадание на кофейной гуще.
Конкретно в этом примере лучше выявлять ошибку типа : "в СтрШаблон передан только первый параметр" что гарантированно выявит проблему в этом примере.

Аналогично можно усложнить проверку по типу поиска значений %1 - %n и подсчета количества следующих параметров.

Проблемы с НСтр могут встречаться в разных комбинациях, но хардкодить конретные ожидаемые значения переменных даст очень много FP.

**Comment by artbear** [comment]
@zeegin согласен про СтрШаблон, проще отдельную диагностику сделать.
исправляю имя и тело ишуза

про много ФП не согласен, но переделка на диагностику в СтрШаблон это наше разногласие устранит )

**Comment by artbear** [comment]
@zeegin я переделал имя и тело ишуза.
