### ISSUE TITLE
[FP]Неверно определяет не достаточность постфикса КлиентСервер

### ISSUE THREAD

**Issue by qtLex** [1c-syntax/bsl-language-server#1243]
## Диагностика
CommonModuleNameClientServer

## Версия
v0.15.2

## Описание ложного срабатывания диагностики
Неверно определяет не достаточность постфикса КлиентСервер, если у модуля установлен признак "обычное приложение"

## Скриншоты
![изображение](https://user-images.githubusercontent.com/5488710/84037386-33af9900-a9a7-11ea-8cac-30114e2bdf2d.png)

![изображение](https://user-images.githubusercontent.com/5488710/84037219-f0552a80-a9a6-11ea-884f-7998bb9a87d6.png)

![изображение](https://user-images.githubusercontent.com/5488710/84037325-18448e00-a9a7-11ea-8453-ea9ecf02eab3.png)

Если конфигурация поддерживает работу в режиме обычного приложения думаю ругаться не должно. А если у ругаться, то указывать на лишнюю галку

**Comment by nixel2007** [comment]
> если у модуля установлен признак "обычное приложение"

у тебя на скрине вроде как раз нет галки

**Comment by qtLex** [comment]
У меня на скрине ее не видно. Так как основной режим запуска был "Управляемое приложение". Вот скрин с переключенным режимом.

![изображение](https://user-images.githubusercontent.com/5488710/84046525-e33e3880-a9b2-11ea-8bc4-fc030be19b66.png)

Суть проблемы в том, что клиент обычное приложение это и клиентский и северный контекст одновременно.

Сеть еще такой [пункт 1.4](https://its.1c.ru/db/v8std#content:467:hdoc) - "Для поддержки обратной совместимости ... конфигурация также должна поддерживать запуск в режимах обычного приложения ...". Так что все конфигурации, которые замахиваются на 1С совместимо скорее всего будут их проставлять.

**Comment by asosnoviy** [comment]
https://github.com/1c-syntax/bsl-language-server/commit/9a240ce633199c1b0cbdb98a5690bde61e2316a8
