### ISSUE TITLE
Применение определенных квик-фиксов для файла\файлов\каталогов при запуске в командной строке

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1251]
обсуждали в телеграме. начало https://t.me/bsl_language_server/45705

Хотелось бы, для каждого файла поочередно применить все заданные квик-фиксы.

Типовой кейс:
- чтобы не в VSC поочередно в файлах менять, а сразу поменять для большой группы файлов в исходниках конфигурации?

Примерный алгоритм:
- делаем спец. команду по примеру остальных
- как-то анализируем ключи ком.строки, выбираем нужные файлы
- команда должна учитывать json типовой структуры c настройкой квик-фиксов 
  - аналогично настройке диагностик 
  - или у каждой диагностики в файле есть доп.ключ включения\отключения квик-фикса
- выбираем нужные диагностики по json
- цикл по файлам, собираем их докКонтексты
- запускаем нужные квик-фиксы для докКонтекста

**Comment by nixel2007** [comment]
#245 и #596 

куда еще-то?
