### ISSUE TITLE
[MOD] UsingModalWindows добавить параметр принудительного включения

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#1256]
## Диагностика
UsingModalWindows

## Описание предлагаемых изменений
Добавить параметр который позволит принудительно включить диагностику независимо от режима использования модальности из корня

## Дополнительная информация
Для кейса когда мы приняли решение для старого проекта не вносить новые модальные окна.

**Comment by nixel2007** [comment]
Может глобальную настройку диагностик? Массив forceCompatibilityMode, а в нем перечисление ключей диагностик.

@Labotamy @otymko @TheShadoWCo?

**Comment by theshadowco** [comment]
а какие еще диагностики можно добавить? ну например синхронные вызовы... не любую диагностику то можно будет туда засунуть.

Я думаю, что стоит добавить режим force для конкретных диагностик, тогда это можно будет контролировать.

**Comment by nixel2007** [comment]
> а какие еще диагностики можно добавить?

все, в которых работает фильтрация по CompatibilityMode :)

**Comment by theshadowco** [comment]
упомянутая еще и смотрит на режим включенности модальности - если включена, то ругаться не будет

**Comment by otymko** [comment]
> Может глобальную настройку диагностик? Массив forceCompatibilityMode, а в нем перечисление ключей диагностик.
> 
> @asosnoviy @otymko @theshadowco?

Ты имеешь ввиду только версию совместимости или модальности? Просто надо понимать что глушить в фильтрах. Например отдельные свойства и в диагностиках подменять.

**Comment by asosnoviy** [comment]
я бы не заморачивался с конфигом и докинул параметр в конкретную диагностику

**Comment by nixel2007** [comment]
Модальность не торчит в DiagnosticMetadata, насколько я помню.

**Comment by nixel2007** [comment]
а, я понял, я ишуз не правильно прочел. речь изначально про модальность.
