### ISSUE TITLE
[FP] Функция в расширении не проходит проверку, так как нет вызова метода

### ISSUE THREAD

**Issue by Rtorosyan** [1c-syntax/bsl-language-server#1262]
## Диагностика
Неиспользуемый локальный метод

## Версия
1.6.0 для Sonar

## Описание ложного срабатывания диагностики
Функция в директивой Вместо не проходит проверку на использование метода в общем модуле

## Пример кода
&Вместо("ОпределитьВспомогательныеПараметрыПечати")
Функция ЗакПост_ОпределитьВспомогательныеПараметрыПечати(ОбъектПечати, Шаблон)
	
	ДополнительныеПараметры = Новый Структура;
	
----------------
----------------
----------------
КонецФункции

## Скриншоты
![image](https://user-images.githubusercontent.com/65313225/85117556-b9450b80-b227-11ea-8d89-d02620044cf9.png)

## Дополнительная информация
В расширение добавлен Общий модуль и переопределена логика работы одной функции с директивой Вместо

**Comment by asosnoviy** [comment]
@Rtorosyan Беда же не только с вместо? Перед и после будет аналогичные ФП?

**Comment by Rtorosyan** [comment]
@asosnoviy как то странно срабатывает. Вот ниже случай, когда и с директивой После, и Вместо сработала проверка и пишет ошибку
![image](https://user-images.githubusercontent.com/65313225/85208643-b8e96500-b33a-11ea-908f-9c3be3bc195e.png)

А вот, когда проверку прошла успешно с директивой Перед
![image](https://user-images.githubusercontent.com/65313225/85208661-ddddd800-b33a-11ea-85e8-5dc1e6b31109.png)

**Comment by asosnoviy** [comment]
Правило сейчас работает только в общих модулях.

**Comment by Rtorosyan** [comment]
@asosnoviy Единственная закономерность, что ошибку ловлю только с общими модулями. В одном случае это общий модуль МенеджераОбмена, в другом ШаблоныДокументов
