### ISSUE TITLE
[NEW] Проверка отсутствия установленного атрибута "Устанавливать права для новых объектов" в ролях

### ISSUE THREAD

**Issue by ivanmolodec** [1c-syntax/bsl-language-server#1280]
## Описание проблемы, ошибки, которую надо диагностировать
При добавлении новой роли может быть ошибочно установлен атрибут "Устанавливать права для новых объектов", что приведет к накоплению в этой роли прав на все добавленные после неё объекты и избыточные права у пользователей с этой ролью. 

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы
https://its.1c.ru/db/v8std/content/532/hdoc
Цитата: "Флажок «Устанавливать права для новых объектов» должен быть установлен только у роли ПолныеПрава"

## Параметры диагностики
Исключение - стандартная роль ПолныеПрава

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [x] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [x] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [x] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

**Comment by theshadowco** [comment]
@EvgSychev

**Comment by theshadowco** [comment]
хе-хе)
