### ISSUE TITLE
[FP] Инлайн описание переменной у которой используются аннотации

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#1292]
## Диагностика
Добавьте описание переменной (MissingVariableDescription)

## Версия
0.15.2

## Описание ложного срабатывания диагностики
При комментировании переменной в строке, ошибка будет продолжать высвечиваться пока не будут прокомментированы аннотации переменной.
По идее, диагностика должна пропускать аннотации.

## Пример кода
```bsl
&Идентификатор
&ГенерируемоеЗначение
&Колонка(Тип = "Целое")
Перем Идентификатор Экспорт; // Внутренний идентификатор объекта
```

## Скриншоты

![image](https://user-images.githubusercontent.com/32082417/88468369-c12e5480-cf25-11ea-8720-4b98eceb8bbd.png)

**Comment by nixel2007** [comment]
Насколько я могу судить после беглого просмотра кода, проблема в некорректном токене для поиска висячих комментариев:

https://github.com/1c-syntax/bsl-language-server/blob/develop/src/main/java/com/github/_1c_syntax/bsl/languageserver/context/computer/VariableSymbolComputer.java#L85

судя по коду передается ctx, а его первый токен является аннотацией. поэтому и комментарий ищется на этой строке, а не там же, где находится var_name
