### ISSUE TITLE
[NEW] [Запросы] Рекомендуется явно назначать псевдонимы полям

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#1295]
## Описание проблемы, ошибки, которую надо диагностировать

Рекомендуется указывать и необязательные конструкции запроса, прежде всего - явно назначать псевдонимы полям, в целях повышения наглядности текста запроса и "устойчивости" использующего его кода

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

https://its.1c.ru/db/v8std#content:437:hdoc  п.2

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [x] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

1 минута

**Comment by theshadowco** [comment]
при диагностике надо учесть, что в запросах с union в выборке надо диагностировать только в первом, т.к. в остальных тот же конструктор все алиасы уберет

**Comment by Stepa86** [comment]
> при диагностике надо учесть, что в запросах с union в выборке надо диагностировать только в первом, т.к. в остальных тот же конструктор все алиасы уберет

В типовых сейчас наоборот принято прописывать алиасы и в последующих запросах при объединении. Читается значительно лучше и позволяет находить баги, когда поля неправильно расставил. Но как они это пишут - я хз. Может конструктор в едт имеет другое поведение, а может всегда вручную они запросы улучшают.

**Comment by Chipazawra** [comment]
Заасайните меня пожалуйста.
