### ISSUE TITLE
Вложенный тернарный оператор

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#13]

**Comment by asosnoviy** [comment]
Да, не все диагностики основываются на стандартах 1с. Некоторые на здравом смысле и заботе о читаемости кода.

**Comment by nixel2007** [comment]
@asosnoviy к вопросу о конфигурационном файле...

**Comment by lChagelishvili** [comment]
Со здравым смыслом ясно, я просто пытаюсь решить это еще Info или уже Warning

**Comment by nixel2007** [comment]
Я за warning. :)
