### ISSUE TITLE
[NEW] [Запросы] Запрет условий в секции ГДЕ для виртуальных таблиц

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#1304]
## Описание проблемы, ошибки, которую надо диагностировать

При использовании виртуальных таблиц в запросах, следует передавать в параметры таблиц все условия, относящиеся к данной виртуальной таблице. Не рекомендуется обращаться к виртуальным таблицам при помощи условий в секции ГДЕ и т.п.

Такой запрос будет возвращать правильный (с точки зрения функциональности) результат, но СУБД будет намного сложнее выбрать оптимальный план для его выполнения. В некоторых случаях это может привести к ошибкам оптимизатора СУБД и значительному замедлению работы запроса. 

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

https://its.1c.ru/db/v8std#content:657:hdoc

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [x] `SQL` - "Проблема с запросом"
* [x] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

5 минут

**Comment by nixel2007** [comment]
кажется тут надо дописать, что ограничение касается отборов по измерениям. отбор по ресурсам в "где" как раз таки более правильное решение.

**Comment by Stepa86** [comment]
> кажется тут надо дописать, что ограничение касается отборов по измерениям. отбор по ресурсам в "где" как раз таки более правильное решение.

В стандарте про это не увидел и чот не знаю про общие практики. Отбор в ГДЕ по ресурсу каждый раз триггерит меня ощущением набыстрокодерства, но как делать правильнее - не знаю

**Comment by nixel2007** [comment]
Ну, от задачи же зависит. Отбор по ресурсу в параметрах вирт таблицы сначала вернёт тебе строки, удовлетворяющие отбору, а потом выполнит над ними операцию виртуальной таблицы. А в где наоборот - сначала построение виртуальной таблицы, а потом фильтрация по ресурсу.
Представь типовую задачку на получение документов определенного статуса (статус в регистре).

**Comment by artbear** [comment]
Реализовал простой вариант диагностики 
https://github.com/1c-syntax/bsl-language-server/pull/1556

проверяется наличие параметров у виртуальных таблиц

если параметры не заданы, выдается замечание.
