### ISSUE TITLE
[FP] CommonModuleNameCached

### ISSUE THREAD

**Issue by astrizhachuk** [1c-syntax/bsl-language-server#1315]
## Диагностика
CommonModuleNameCached

## Версия
1.21.1

## Описание ложного срабатывания диагностики
Язык = en
Сработало для модуля HTTPStatusCodesClientServerCached

## Пример кода
https://sonar.openbsl.ru/project/issues?id=HTTPStatusCodes&issues=AXOgGkfnAHY6OzvcjkQZ&open=AXOgGkfnAHY6OzvcjkQZ

## Скриншоты
![image](https://user-images.githubusercontent.com/25724999/88937516-eeb03080-d28c-11ea-8cb5-95063c9efaf9.png)

## Дополнительная информация
Предположение, что сработало так как кейс КлиентСерверПовтИсп в стандарте пропущен, указан только для сервера и для клиента отдельно.

**Comment by theshadowco** [comment]
сработал из-за опечатки - в правиле использовалась русская буква "С"

**Comment by asosnoviy** [comment]
Вторая опечатка там же. 
`ПовнорноеИспользование`
