### ISSUE TITLE
[FP] UnusedLocalMethod - Диагностика срабатывает для процедуры, вызов которой происходит через механизм расширений

### ISSUE THREAD

**Issue by korotovskih** [1c-syntax/bsl-language-server#1340]
## Диагностика
UnusedLocalMethod

## Версия
1.6.1 [1C (BSL) Community Plugin]

## Описание ложного срабатывания диагностики
Диагностика срабатывает для процедуры, вызов которой происходит через механизм расширений

## Пример кода
```bsl
#Область СлужебныеПроцедурыИФункции

&После("ФормаРегламентированнойОтчетности_ПриСозданииНаСервере")
Процедура _ФормаРегламентированнойОтчетности_ПриСозданииНаСервере(Форма)
	
КонецПроцедуры

#КонецОбласти

```

## Скриншоты
![image](https://user-images.githubusercontent.com/34188696/90512406-8cee3280-e177-11ea-8e5a-fdc4ef6ee9ae.png)

## Дополнительная информация

Вижу, что в деве поправлено, но ишуз закину

https://github.com/1c-syntax/bsl-language-server/blob/develop/src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/UnusedLocalMethodDiagnostic.java#L83

**Comment by asosnoviy** [comment]
Исправлено дааавно
