### ISSUE TITLE
Убрать информационный шум от codeLens / возможность отключить codeLens глобально

### ISSUE THREAD

**Issue by kuntashov** [1c-syntax/bsl-language-server#1348]
Сейчас даже на пустом методе вылезает подсказака о когнитивной и цикломатической сложности:

![Screenshot at 16-33-26](https://user-images.githubusercontent.com/1042299/92305369-affe4c00-ef97-11ea-861b-3a736deb6340.png)

Какая польза мне от информации?

И даже вот от этого никакой пользы нет, только шум:

![Screenshot at 16-32-58](https://user-images.githubusercontent.com/1042299/92305373-be4c6800-ef97-11ea-8135-787dc5826ebe.png)
(на скрине не показал, но там в методе цикл, один уровень вложенности).

Предложения/пожелания: 

  * не показывать метрики когнитивки и цикломатики, когда они обе менее определенного порога, если это возможно
  * сделать возможность отключить эти метрики глобально. Не хочу видеть этот шум во время разработки и не хочу при этом для каждого маленького скриптика делать .bsl-language-server.json

**Comment by asosnoviy** [comment]
1. На это есть диагностика по при
2. Это в принципе к глабальному конфигу  https://github.com/1c-syntax/vsc-language-1c-bsl/issues/185

**Comment by nixel2007** [comment]
@asosnoviy на пару с рефакторингом код лензов возможно стоит еще и порефакторить их конфиг. `@CodeLensMetadata` + `@CodeLensParameter` + выключение/конфигурирование код лензов а-ля diagnostic->parameters?
