### ISSUE TITLE
[NEW][Запросы]Использование подзапроса в секции ГДЕ

### ISSUE THREAD

**Issue by akabrr** [1c-syntax/bsl-language-server#1351]
## Описание проблемы, ошибки, которую надо диагностировать
Вместо внутреннего соединения используют подзапрос в секции ГДЕ.
Пример ошибочного текста запроса: 
```bsl
Выбрать 
  Контрагенты.Ссылка Как Контрагент
Из
  Справочник.Контрагенты Как Контрагенты
Где 
  Контрагенты.Ссылка В (Выбрать Т.Контрагент ИЗ КакаяТоВременнаяТаблица КАК Т)
```

СУБД MS SQL сначала прочитает все записи из таблицы Контрагенты, а меня там 30 миллионов. 

Как должно быть:
```bsl
Выбрать 
  Контрагенты.Ссылка Как Контрагент
Из
  Справочник.Контрагенты Как Контрагенты
  Внутреннее соединение КакаяТоВременнаяТаблица Как Т
  По Контрагенты.Ссылка = Т.Контрагент
```

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [X] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [X] `SQL` - "Проблема с запросом"
* [x] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
5 минут

**Comment by akabrr** [comment]
хочу взять в работу

**Comment by nixel2007** [comment]
Какой планируется алгоритм для поиска?

**Comment by akabrr** [comment]
Диагностика наследуется от AbstractSDBLVisitorDiagnostic.
Переопределяю visitWhereMember
Вызываю inlineSubquery
Если inlineSubquery вернул не null ругаюсь приличными словами.

**Comment by nixel2007** [comment]
ну, сам по себе inlineSubquery - это же не страшно. страшно, если внутри него mdo или джойны

**Comment by akabrr** [comment]
Я наверное не верно понял, что делает inlineSubquery. Я считал, что inlineSubquery возвращает подзапрос. Пойду дальше читать.

**Comment by nixel2007** [comment]
inlineSubquery возвращает подзапрос. но не каждый подзапрос страшен. если там идет выборка из временной таблицы с индексами, то это допустимо и часто применяется.

**Comment by akabrr** [comment]
внутреннее соединение не будет более эффективно?

**Comment by akabrr** [comment]
Я просто смотрел план запроса, того самого что указан в диагностике и было всё очень плохо.

**Comment by nixel2007** [comment]
> внутреннее соединение не будет более эффективно?

без плана сложно сказать :)

**Comment by nixel2007** [comment]
> Я просто смотрел план запроса, того самого что указан в диагностике и было всё очень плохо.

а можно пример? или там речь про то, что сначала идет скан всей таблицы контрагентов, а только потом фильтрация?

**Comment by akabrr** [comment]
да, скан всей таблицы

**Comment by akabrr** [comment]
ок, с возражениями согласен, но описывать дальше алгоритм сложнее :)

**Comment by akabrr** [comment]
Может быть вообще закрыть эту диагностику? Я погуглил, похоже только в моём случае были проблемы, возможно что то было не так со статистикой или мне просто не повезло.

**Comment by nixel2007** [comment]
@theshadowco что скажешь по этому поводу?

**Comment by theshadowco** [comment]
есть ситуации, при которых это плохо. Например может быть очень сложный подзвпрос. а не тот что в примере и тогда его не стоит применять. 
Еще - отсутствие индекса временной таблицы по полю, используемому в условии. но опять же, это зачастую связано с количеством строк в вт.

Я сам не взялся такую диагностику из-за слишком большого количества "если", так что в виде "нельзя использовать в где подзапрос" ее точно реализовывать нельзя.

**Comment by theshadowco** [comment]
кстати пример "хорошо" неправильный :) правильнее поменять таблицы местами
