### ISSUE TITLE
[BUG] Падает анализ при вкл. диагностике длинного наименования метеданных.

### ISSUE THREAD

**Issue by ZlobinDV** [1c-syntax/bsl-language-server#1366]
## Диагностика
Имена объектов метаданных не должны превышать допустимой длины наименования

## Версия
Плагин из маркетплейса сонаркуба 1.7.0, БСЛ вроде как 0.16.2.

## Описание ошибки диагностики
Если в профиле качества включено указанное правило, то анализ падает с ошибкой https://pastebin.com/jK1f7Zy2

## Пример кода
На чем падает не знаю, прикладываю исходники внешней обработки, которая была разобрана с помощью гитсинка (обычные формы).
[ДокументооборотСКонтролирующимиОрганами.zip](https://github.com/1c-syntax/bsl-language-server/files/5286432/default.zip)

## Скриншоты
![image](https://user-images.githubusercontent.com/52169208/94336832-1f93b400-fff7-11ea-9706-d41808fcb849.png)

## Дополнительная информация
Если правило из профиля качества деактивировать, то все работает в штатном режиме. Любые ответы вопросы, при необходимости предоставление исходников по запросу. Для оперативности можно обращаться в телеграмм.

**Comment by asosnoviy** [comment]
Замечание вешается на перенос строки, вот и падает.
