### ISSUE TITLE
[NEW] [Запросы] Избыточное использование ".Ссылка" в полях ссылочного типа. Прошу рассмотреть. 

### ISSUE THREAD

**Issue by ZlobinDV** [1c-syntax/bsl-language-server#1371]
## Описание проблемы, ошибки, которую надо диагностировать
Разработчики допускают ошибки, при написании запросов, а именно избыточно дописывают поля ".Ссылка" или ".Ссылка.Ссылка" уже к полям ссылочного типа. 

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы
Я не смог найти стандарт конкретно на эту проблему, на думаю самый близкий должен быть https://its.1c.ru/db/v8std/content/654/hdoc

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [x] `SQL` - "Проблема с запросом"
* [x] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
5 минут

## Дополнительная информация
Использование ".Ссылка" к полю ссылочного типа приведет к неявному левому соединению с таблицей-источником данного поля, при этом не несет никакой ценности, а только генерирует избыточную нагрузку на СУБД. 
При расследовании проблем производительности был вот такой  запрос
![image](https://user-images.githubusercontent.com/52169208/94546367-d3e34380-025e-11eb-9978-0a591bdc867f.png)
Данный запрос вызывался очень много-много раз, что в свою очередь приводило к избыточной нагрузке на CPU СУБД до 90-100%.

**Comment by artbear** [comment]
@ZlobinDV @EightM я бы еще добавил кейс использования .Ссылка внутри выражения.

В ПР от @EightM в тестах не увидел подобного теста.
Подскажите, ловится внутри выражения?

только что увидел на код-ревью в запросе `Контрагенты.Ссылка.ЮрФизЛицо`

```
		ТекстЗапроса = 
		"ВЫБРАТЬ
		|	Контрагенты.Ссылка КАК Контрагент,
		|	Контрагенты.Ссылка.ЮрФизЛицо = ЗНАЧЕНИЕ(Перечисление.ЮрФизЛицо.ИндивидуальныйПредприниматель) КАК ИндивидуальныйПредприниматель,
		|	Контрагенты.КПП КАК КПП
		|ИЗ
		|	Справочник.Контрагенты КАК Контрагенты
		|ГДЕ
		|	Контрагенты.ИНН = &ИНН";
```

**Comment by artbear** [comment]
@EightM и кстати, я в тестах твоего ПР не увидел отрицательный тест на простое  выражение (

```
ВЫБРАТЬ
		|	Контрагенты.Ссылка КАК Контрагент
```

такое простое выражение игнорится, да?

**Comment by nixel2007** [comment]
> Подскажите, ловится внутри выражения?

А посмотреть? :)

**Comment by artbear** [comment]
@nixel2007 у меня вроде бы последний VSC-плагин, и это правило не сработало на приведенный код (

потому и написал.

**Comment by EightM** [comment]
@artbear Контрагенты.Ссылка.ФизЛицо не будет ловиться, так как диагностика смотрит только на выражения с ". Ссылка" на конце.
