### ISSUE TITLE
[MOD] Перевесить comonModuleName с первого значещего токена на первый с ренджом

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#1374]
## Диагностика
comonModuleName*

## Описание предлагаемых изменений
Сменить позиционирование диагностики с первого значещего на первый любой символ

**Comment by nixel2007** [comment]
Это в дополнение к #1366 ?

**Comment by asosnoviy** [comment]
Ага, но по старым диагностикам. Кажется удобней, если диагностика зацепится за шапку модуля.
