### ISSUE TITLE
[MOD] CodeOutOfRegion не ругаться в unknown модуле

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#1386]
## Диагностика
CodeOutOfRegion не ругаться на unknown модуле

## Дополнительная информация

![image](https://user-images.githubusercontent.com/15638529/94957825-23dc3780-04f7-11eb-900b-d113c93827ec.png)

**Comment by nixel2007** [comment]
Вроде там есть какой-то небольшой список областей, которые имеет смысл применять везде, не?

**Comment by asosnoviy** [comment]
> Вроде там есть какой-то небольшой список областей, которые имеет смысл применять везде, не?

В просто открытом файле bsl, куда вставлен произвольный кусок кода, думаю не надо фонить
