### ISSUE TITLE
ограничение на букву ё

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#14]

**Comment by lChagelishvili** [comment]
А что проверяем?
Понятно, что в именах объектов, функций, процедур и в переменных буквы "ё" быть не должно.
А что делать с интерфейсными текстами?

**Comment by nixel2007** [comment]
есть стандарт на эту тему. надо следовать ему.

**Comment by lChagelishvili** [comment]
Я эти стандарты скоро наизусть смогу цитировать )
В целом, по стандарту нельзя, но иногда можно. Проверять соответствие текстов нормам русского языка - это перебор, на мой взгляд.
Я считаю, что или не проверять вообще или всегда запрещать.

**Comment by lChagelishvili** [comment]
В оригинале так:

> 1.1. В текстах модулях не допускается использовать букву "ё".
> Исключения составляют интерфейсные тексты, выводимые пользователю в сообщениях, формах и справке, где употребление буквы «ё» в ряде случаев допустимо.
> Буква «ё» употребляется только в тех случаях, когда возможно неправильное прочтение слова, когда надо указать правильное произношение редкого слова или предупредить речевую ошибку. Букву «ё» следует также писать в собственных именах. В остальных случаях следует писать букву «е».

Да, думаю, что в качестве допущения можно рассматривать все что лежит в строках как потенциальные сообщения пользователю и пропускать это.

Но, возможна и другая стратегия, анализируем все до чего можем дотянуться и выводим предупреждения, а пользователь пусть сам решает что с этим делать.

**Comment by asosnoviy** [comment]
Я бы тексты не трогал. Только методы/переменные/объекты(когда появятся)

**Comment by nixel2007** [comment]
Тогда разбор всех идентификаторов. Не обязательно даже от визитора наследоваться, можно по примеру line length check просто выбрать все токены и потом параллелстримом по ним пройтись
