### ISSUE TITLE
[NEW] ОбщийМодуль должен иметь программный интерфейс

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#1406]
## Описание проблемы, ошибки, которую надо диагностировать
ОМ без программного \ служебного программного интерфейса лишен смысла, нужно проверять что в общем модуле есть:
1. Хотя бы одна из областей:
    1. ПрограммныйИнтерфейс
    1. СлужебныйПрограммныйИнтерфейс
1. Хотя бы один экспортный метод

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы
Здравый смысл

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [x] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
5 минут

**Comment by asosnoviy** [comment]
Вроде есть диагностика на наличие стандартной области в модуле. Желаемого результата можно добиться оставив для общего модуля, только программные интерфейсы.  Но это так в качестве наброса

**Comment by sokolov-rv** [comment]
Можно взять в работу?

**Comment by nixel2007** [comment]
@sokolov-rv с радостью!
