### ISSUE TITLE
[Deprecated] The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0

### ISSUE THREAD

**Issue by igostv** [1c-syntax/bsl-language-server#1407]
**Версия**
Develop

**Описание ошибки**
Использование deprecated плагина Maven

**Дополнительная информация**

```bash
./gradlew test --warning-mode all
```

Configure project :
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the maven-publish plugin instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.6.1/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins

**Comment by nixel2007** [comment]
У нас используется и maven и maven-publish. Думаю, от maven можно безопасно избавиться.

**Comment by nixel2007** [comment]
Closed by e0dd4e75930a5301e8dd00c0fbab88e4c77eef81
