### ISSUE TITLE
[NEW] Поддержка  обычного приложения

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#1409]
## Описание проблемы, ошибки, которую надо диагностировать

1.4. Для поддержки обратной совместимости с различными собственными и сторонними решениями, внешними обработками и отчетами, разработанными на предыдущих версиях платформы 1С:Предприятие 8.0 и 8.1, конфигурация также должна поддерживать запуск в режимах обычного приложения (толстый клиент) и внешнего соединения для администраторов (пользователей с полными правами). Для этого рекомендуется 

* свойство конфигурации «Использовать управляемые формы в обычном приложении» установить в Истина, а свойство «Использовать обычные формы в управляемом режиме» – в Ложь.
* придерживаться общей схемы установки признаков общих модулей,
* а саму разработку в Конфигураторе вести в режиме редактирования для обоих режимов запуска – управляемое и обычное приложение (меню Сервис – Параметры – закладка Общие).

Проверять:
* свойство конфигурации «Использовать управляемые формы в обычном приложении» установить в Истина
* свойство «Использовать обычные формы в управляемом режиме» – в Ложь.
* В признаках общих модулей требовать устанавливать "Обычного клиента",

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

https://its.1c.ru/db/v8std#content:467:hdoc
### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [x] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

**Comment by nixel2007** [comment]
в чем суть?

**Comment by asosnoviy** [comment]
@nixel2007 
1. проверять 2 свойства и орать. 
2. Добавить в конфиг "МнеВсеРавноНаТолстыйКлиент" и не орать. На него же опираться в проверках на типы модулей.

**Comment by nixel2007** [comment]
Ага, спасибо
