### ISSUE TITLE
Общение по WebSocket

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#1427]
Добавить возможность общаться не только по stdin/stdout, но и по web socket. Заодно заложить место под обычный tcp

**Comment by artbear** [comment]
а сейчас есть возможность общаться с сервером только через stdin/stdout? или все-таки через tcp/udp/http можно общаться?

**Comment by nixel2007** [comment]
нет, только по stdin/stdout. под tcp был тестовый бранч, но заброшен.
в целом эта задача создавалась под monaco, а монако уже научился запускать LS с работой по stdin/stdout. так что возможно задача менее актуальна и приоритетна.
