### ISSUE TITLE
[FN] Перестала работать диагностика CodeOutOfRegion

### ISSUE THREAD

**Issue by Falra** [1c-syntax/bsl-language-server#1452]
## Диагностика
CodeOutOfRegion

## Версия
17.0-RC1

## Описание ложного НЕ срабатывания диагностики
В новой версии перестала работать диагностика CodeOutOfRegion

## Пример кода

```bsl

Процедура Тест()
	ПеремА = "Тест2";
	Сообщить("Перем " + ПеремА);
КонецПроцедуры


```

## Дополнительная информация
С 16.1 срабатывает

**Comment by nixel2007** [comment]
@asosnoviy это ж следствие https://github.com/1c-syntax/bsl-language-server/issues/1386 ?
кто прав, кто не прав в таком случае?

**Comment by Falra** [comment]
Не выводит phoenix/bslls-connector-for-edt
Похоже из-за того, что модуль передается как сингл документ.
Указание ConfigurationRoot на папку проекта EDT не помогло - или я просто не умею его готовить :)
@asosnoviy предложил подумать над явным указанием сингл/воркспейс в конфигах

**Comment by asosnoviy** [comment]
https://github.com/otymko/bslls-connector-for-edt/issues/16 - ЕДТ
А для фени может добавить настройку?

**Comment by otymko** [comment]
@Falra Самое "быстрое" решение - сделать параметр в диагностике учитывать все типы модулей. Но по-хорошему проблема стороне "поделий" для IDE.

Плагин для EDT:
* Сейчас плагин поддерживает анализ проекта с учетом метаданных. Нужно только правильно настроить конфигурационный файл BSL LS. После настройки, в модуле диагностика должна сработать. Промежуточную сборку можно скачать здесь из EDT: https://otymko.github.io/bslls-connector-for-edt/update/bslls-connector-for-edt/0.2.1/

PhoenixBSL для EDT:
* Тут все сложнее. Для определения типов модулей сейчас нужно: правильно определять путь к модулю при анализе и выгружать заранее метаданные. Надежды мало, что это появится в этом году.

@asosnoviy вводим параметр?

**Comment by Falra** [comment]
@otymko как-то все равно не взлетело :)
указал "configurationRoot": "D:/Путь_К_Репозиторию_EDT/src" и ничего не появилось, другие диагностики работают
В трейсе rootUri все равно указывает на воркспейс, хотя не уверен, что это связанные вещи

С параметром "все типы" будет смысл? тогда по сути FN будет, если задать область формы в модуле и наоборот?

**Comment by otymko** [comment]
@Falra попробуйте вот так указать:
```
"configurationRoot": "D:/Путь_К_Репозиторию_EDT/src/Configuration/Configuration.mdo"
```

**Comment by otymko** [comment]
@Falra с параметром вернется старое поведение нахождение кода вне области.

**Comment by Falra** [comment]
> @Falra попробуйте вот так указать:
> 
> ```
> "configurationRoot": "D:/Путь_К_Репозиторию_EDT/src/Configuration/Configuration.mdo"
> ```
На новой конфигурации с новым модулем заработало с ".../src"
Может EDT не хватает сил на большую конфу
Расположение репо с исходниками отдельно от воркспейса может влиять?

**Comment by otymko** [comment]
Возможно все проще - там баг с mdclasses. Его поправили только недавно.

**Comment by otymko** [comment]
@Falra и чтобы это получить в EDT, надо выпустить релиз. Этот issue остался последний =)

**Comment by Falra** [comment]
@otymko 

> Расположение репо с исходниками отдельно от воркспейса может влиять?

Все дело все-таки в этом

https://github.com/1c-syntax/bsl-language-server/blob/develop/src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfiguration.java#L148-L153

Перенес репо внутрь воркспейса EDT и заработало

**Comment by Falra** [comment]
@nixel2007 
От этого можно как-то уйти или нахождение src внутри root папки важно?
У меня воркспейс и репо лежали в отдельных папках, поэтому configurationRoot не ловился.
Ситуация вроде как вполне нормальная или что-то сломаем?)

https://github.com/1c-syntax/bsl-language-server/blob/develop/src/main/java/com/github/_1c_syntax/bsl/languageserver/configuration/LanguageServerConfiguration.java#L148-L153

**Comment by nixel2007** [comment]
Хм. А оно так было изначально запланировано:
https://github.com/1c-syntax/bsl-language-server/commit/71e2f02b26fe14b59e25dc61e126fc8744cfac1a#diff-f6f06b71e040c743aad2a42f45789dabe1a76327b16c8ed0b818d3c432985e0dR216

и в итоге реализовано:
https://github.com/1c-syntax/bsl-language-server/commit/c773f334dca43079d2edf2264b2ef03d7cf95e24

тут наверное больше вопрос к @otymko, помнит ли он, почему надо было убедиться в том, что конфигурация находится внутри воркспейса... С точки зрения ИДЕ возможно могут быть какие-то проблемы в этом месте, типа file doesn't belong to workspace. Но при этом VSC-плагин оперирует файлами вне воркспейса (в workspaceSymbolProvider, например) и VSCode это пережевывает без проблем. А вот сонар падает, но это "не наша" проблема.

Олег, помнишь что-нибудь на эту тему?
В целом можно просто попробовать убрать и потестить жарку.
