### ISSUE TITLE
[BUG] Ошибка разбора модуля расширения, в котором используется #Удаление - возможно, проблема в разрыве инструкций

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1473]
**Версия**
> Версия BSLLS либо плагина, который использует BSLLS

1.7.0

**Описание ошибки диагностики**
не разбирается модуль расширения, в котором используется #Удаление

возможно, проблема в разрыве инструкций. 

Если это так и поддержки при разрыве инструкций не планируется, сообщите и закрывайте ишуз.

**Пример кода**
```bsl
&ИзменениеИКонтроль("ПроверитьЗавершитьДоговорВАрхиве")
Функция ХФ164150_ПроверитьЗавершитьДоговорВАрхиве(ДоговорОбъект, ДопНастройки, ИмяРеквизитаДатаОкончания)
	ТекущаяДата   = НачалоДня(ТекущаяДатаСеанса());
	#Удаление
	Если СтароеУсловие
	#КонецУдаления
	#Вставка
	НовоеУсловие = Выражение;
	Если НовоеУсловие
	#КонецВставки
		И ЧастьСтарогоУсловия Тогда
		    Возврат Истина;
	КонецЕсли;
	Возврат Ложь;
КонецФункции
```

**Скриншоты**
> Скриншоты с подтверждением
![image](https://user-images.githubusercontent.com/2920817/100739230-d2adce80-33e7-11eb-85ca-4e1e61a09f67.png)

**Comment by asosnoviy** [comment]
ЕДТ что на это говорит?

**Comment by artbear** [comment]
пока без ЕДТ (

**Comment by asosnoviy** [comment]
Тогда, пока, придерживайтесь общего правила разрыва конструкций препроцессором =)

**Comment by nixel2007** [comment]
оффтопик.

кажется, надо еще и расцветочку на гитхабе обновить... асинхи всякие добавить заодно.
/cc @bambr1975

**Comment by theshadowco** [comment]
fixed https://github.com/1c-syntax/bsl-parser/pull/87

**Comment by nixel2007** [comment]
Нене, это не про строки, это разрыв внутри "если"

**Comment by theshadowco** [comment]
Вопрос-предложение:
Как смотрите на то, что лексером вырезать блок `#Удаление...#КонецУдаления`, отправляя содержимое в отдельный канал, а `#Вставка` и `#КонецВставки` просто в скрытый канал?

**Comment by theshadowco** [comment]
тогда код будет по сути - итоговым, как после компиляции

**Comment by nixel2007** [comment]
хм... хорошая идея. поможет подход Жени из висящего PR или надо будет что-то новое делать?

**Comment by theshadowco** [comment]
у меня проще вариант

**Comment by artbear** [comment]
Да, отличный вариант с вырезкой и получением результирующего кода.

**Comment by artbear** [comment]
Указанная проблема является довольно критичной, т.к. на  плагине 1.8.1 падает весь анализ, если встречается такой модуль (
ишуз выше

**Comment by nixel2007** [comment]
Все проблемы для кого-то являются критичными :)

**Comment by otymko** [comment]
@artbear в опенсоурсе можно и самому "допилить" =)

**Comment by asosnoviy** [comment]
Повтоюсь, если критично:
> Тогда, пока, придерживайтесь общего правила разрыва конструкций препроцессором =)

**Comment by theshadowco** [comment]
так сделали уже, в новом релизе будет

**Comment by theshadowco** [comment]
в парсере есть
