### ISSUE TITLE
RedundantAccessToObject

### ISSUE THREAD

**Issue by rusdaurov** [1c-syntax/bsl-language-server#1482]
## Диагностика
RedundantAccessToObject

## Версия
v0.17.0

## Описание ложного срабатывания диагностики
обращение к реквизитам формы через квадратные скобки

## Пример кода
ЭтотОбъект[ИмяРеквизита]

## Скриншоты

![image](https://user-images.githubusercontent.com/26689696/101983068-62296c00-3c89-11eb-9873-c65dcf2b5096.png)

**Comment by qtLex** [comment]
На меня повесьте, плз
