### ISSUE TITLE
[FP] Диагностика MissingTemporaryFileDeletion не учитывает вызов НачатьУдалениеФайлов

### ISSUE THREAD

**Issue by AlexanderNiMo** [1c-syntax/bsl-language-server#1484]
## Диагностика
**MissingTemporaryFileDeletion** 

## Версия
**v0.17.0**

## Описание ложного срабатывания диагностики
После получения имени временного файла вызов НачатьУдалениеФайлов не убирает проблему.

## Пример кода

```
Процедура ВыполнитьОбработку()
ВремФайл = ПолучитьИмяВременногоФайла(Файл.Расширение);
ОП = Новый ОписаниеОповещения("ПослеУдаленияФайлов", ЭтотОбъект);
НачатьУдалениеФайлов(ОП, ВремФайл);
КонецПроцедуры

Процедура ПослеУдаленияФайлов(ДополнительныеПараметры) Экспорт
    а =1;
КонецПроцедуры

```

## Скриншоты
![image](https://user-images.githubusercontent.com/13915652/102010658-88fea580-3d50-11eb-9686-e1cdfb726b75.png)

**Comment by nixel2007** [comment]
Спасибо за репорт, добавим в исключения по умолчанию в следующем релизе. Пока можете переопределить настройку searchDeleteFileMethod в своем локальном конфиге.
