### ISSUE TITLE
[FP] RedundantAccessToObject Обращение к переменной названной так же как и метаданное в модуле менеджера оного

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#1487]
## Диагностика
RedundantAccessToObject

## Версия
0.17.1

## Описание ложного срабатывания диагностики
При обращении в модуле менеджера к переменной которая названа так же как и метаданное

## Пример кода
```bsl
Для каждого Номенклатура Из НоменклатураИВидыНоменклатуры Цикл
	Результат.Вставить(
		Номенклатура.Ключ,
		НекотороеЗначение
	)
КонецЦикла;
```

## Скриншоты

![image](https://user-images.githubusercontent.com/32082417/102170455-24725080-3ee0-11eb-8113-8901940caba8.png)

**Comment by nixel2007** [comment]
А вот это вообще что-то странное...

**Comment by qtLex** [comment]
Не учел такой случай ((.
Уже смотрю. Повесьте на меня
