### ISSUE TITLE
Работа с Транзакциями

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#149]
https://its.1c.ru/db/v8std#content:783:hdoc

**Comment by asosnoviy** [comment]
Якорь: https://t.me/ssl1c/20973

**Comment by zeegin** [comment]
Можно список формальных правил из АПК взять. Их там штук 10-15.

**Comment by zeegin** [comment]
Вот формальные правила из АПК:

1. отсутствует вызов "НачатьТранзакцию()", хотя вызываются "ЗафиксироватьТранзакцию()"/"ОтменитьТранзакцию()" (325)
2. для вызова "НачатьТранзакцию()" отсутствует парный вызов "ЗафиксироватьТранзакцию()" (326)
3. для вызова "НачатьТранзакцию()" отсутствует парный вызов "ОтменитьТранзакцию()" (327)
4. не найден оператор "Попытка" после вызова "НачатьТранзакцию()" (328)
5. между "НачатьТранзакцию()" и "Попытка" есть исполняемый код (331)
6. вызов "ЗафиксироватьТранзакцию()" находится вне конструкции "Попытка... Исключение" (329)
7. отличаются условия "Если ... Тогда" у методов работы с транзакциями (415)
8. между "ЗафиксироватьТранзакцию()" и "Исключение" есть исполняемый код, который может вызвать исключение (330)
9. вызов "ОтменитьТранзакцию()" отсутствует в конструкции "Исключение... КонецПопытки" (332)
10. между "Исключение" и "ОтменитьТранзакцию()" есть исполняемый код (478)
11. преждевременный выход из блока "Попытка..Исключение" без завершения или отмены транзакции (521)
12. После инициализации блокировки отсутствует вызов "Заблокировать()" (1319)
13. Вызов "Заблокировать()" находится вне попытки (1320)
14. Конструкция "Попытка...Исключение...КонецПопытки" не содержит кода в исключении (280)

**Comment by theshadowco** [comment]
@nixel2007 
назначьте на меня, в рамках тестирования разработки попробую сделать

**Comment by theshadowco** [comment]
Оформил списком

 - [ ] отсутствует вызов "НачатьТранзакцию()", хотя вызываются "ЗафиксироватьТранзакцию()"/"ОтменитьТранзакцию()" (325)
 - [ ] для вызова "НачатьТранзакцию()" отсутствует парный вызов "ЗафиксироватьТранзакцию()" (326)
 - [ ] для вызова "НачатьТранзакцию()" отсутствует парный вызов "ОтменитьТранзакцию()" (327)
 - [ ] не найден оператор "Попытка" после вызова "НачатьТранзакцию()" (328)
 - [ ] между "НачатьТранзакцию()" и "Попытка" есть исполняемый код (331)
 - [ ] вызов "ЗафиксироватьТранзакцию()" находится вне конструкции "Попытка... Исключение" (329)
 - [ ] отличаются условия "Если ... Тогда" у методов работы с транзакциями (415)
 - [ ] между "ЗафиксироватьТранзакцию()" и "Исключение" есть исполняемый код, который может вызвать исключение (330)
 - [ ] вызов "ОтменитьТранзакцию()" отсутствует в конструкции "Исключение... КонецПопытки" (332)
 - [ ] между "Исключение" и "ОтменитьТранзакцию()" есть исполняемый код (478)
 - [ ] преждевременный выход из блока "Попытка..Исключение" без завершения или отмены транзакции (521)
 - [ ] После инициализации блокировки отсутствует вызов "Заблокировать()" (1319)
 - [ ] Вызов "Заблокировать()" находится вне попытки (1320)
 - [ ] Конструкция "Попытка...Исключение...КонецПопытки" не содержит кода в исключении (280)

**Comment by theshadowco** [comment]
Для всех примеров создал отдельные недостающие ишузы

@zeegin по этому 
> отличаются условия "Если ... Тогда" у методов работы с транзакциями

не нашел пояснения. Запость пож-ста
