### ISSUE TITLE
[MOD] Добавить возможность указывать костомный режим совместимости, или игнорировать его вовсе

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#1497]
## Диагностика
Все, опирающиеся на режим совместимости

## Описание предлагаемых изменений
Ввести параметр в котором можно указать требуемый режим совместимости для проверки, который будет иметь приоритет над режимом совместимость конфигурации. 
В этом же параметре значение "Не использовать" будет означать что нужно выполнять все диагностики в не зависимости от режима совместимости

## Дополнительная информация
Например для аудита решение перед поднятием режима совместимости, или полная проверка проекта для выявления всех замечания.

**Comment by nixel2007** [comment]
Кажется, дубликат #1459
