### ISSUE TITLE
Использование методов НайтиПоНаименованию и НайтиПоКоду

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#150]
## Описание
Диагностировать использование методов:
* НайтиПоНаименованию()
* НайтиПоКоду()

## Параметры
Scope: BSL
Type: CODE_SMELL
Severity: MAJOR

## Примеры
Неправильно
```bsl
Должность = Справочники.Должности.НайтиПоНаименованию("Ведущий бухгалтер");
Должность = Справочники.Должности.НайтиПоКоду("00-0000001");

Код = "123"
Спр1.НайтиПоКоду(Код);
```
Допустимо:
```bsl
Справочники.Валюты.НайтиПоКоду(ТекущиеДанные.КодВалютыЦифровой);
Справочники.КлассификаторБанков.НайтиПоКоду(СведенияОБанке.БИК);
```

**Comment by asosnoviy** [comment]
А Severity можно менять на лету?

**Comment by nixel2007** [comment]
> А Severity можно менять на лету?

нет.

**Comment by otymko** [comment]
> А Severity можно менять на лету?

хз) Хотел попробовать

**Comment by otymko** [comment]
Я на выходных попилю это

**Comment by otymko** [comment]
@asosnoviy @nixel2007 @lChagelishvili Такое наименование диагностики всех устраивает?

**UsingFindElementByString**
