### ISSUE TITLE
[FP] IdenticalExpressions `Результат = X / 60 / 60`

### ISSUE THREAD

**Issue by ovcharenko-di** [1c-syntax/bsl-language-server#1502]
## Диагностика
IdenticalExpressions

## Версия
0.17.1

## Описание ложного срабатывания диагностики
Ложное срабатывание в выражениях вида:
```bsl
Результат = X / 60 / 60;
```
## Скриншоты
![image](https://user-images.githubusercontent.com/24920942/103262532-4080f200-49b6-11eb-99f5-2e44f77d4bd1.png)

**Comment by nixel2007** [comment]
А что ложного? :) слева и справа от / находится одна и та же цифра

**Comment by ovcharenko-di** [comment]
Технически, конечно, верно. Может быть, диагностика не должна срабатывать, если слева и справа не переменные или выражения, а конкретные значения?

**Comment by EvilBeaver** [comment]
еще варианты:

`Пока 1=1 Цикл`

`БешаныеГигобайты = Файл.Размер() / 1024 /1024 /1024`

короче говоря, есть набор вселенских постоянных, на которые часто делят: 

* Время (цифра 60), 
* Размеры в байтах (цифра 1024)
* Старперский вариант `Пока Истина` для "семерочников": `Пока 1=1`

других пока не видел. Возможно имеет смысл такое отфильтровать. С другой стороны, это не FP, это точечная "неприменимость" и ее можно просто выключать комментарием...

**Comment by EvilBeaver** [comment]
AFAIK - это исправлено в #1725

**Comment by nixel2007** [comment]
@ovcharenko-di посмотришь на 0.19.0-rc.1?

**Comment by ovcharenko-di** [comment]
@nixel2007 @EvilBeaver проверил, все ок! закрываю
