### ISSUE TITLE
Не хватает списка Severity и Type в описаниях диагностик

### ISSUE THREAD

**Issue by DoublesunRUS** [1c-syntax/bsl-language-server#151]
На сайте https://1c-syntax.github.io/bsl-language-server/#diagnostics есть описание диагностик.
Внутри каждой диагностики хочется видеть, какой у неё severity и type.

**Comment by asosnoviy** [comment]
Кажется, Саша хотел на каждой странице

**Comment by theshadowco** [comment]
@DoublesunRUS ?

**Comment by DoublesunRUS** [comment]
Точно. Прямо в исходном сообщении об этом написано. Хочу зайти внутрь конкретной диагностики и увидеть её критичность.

**Comment by theshadowco** [comment]
Посмотри https://github.com/1c-syntax/bsl-language-server/issues/359#issuecomment-545293080
