### ISSUE TITLE
[FP] Избыточное обращение по имени к модулю с повторным использованием значений

### ISSUE THREAD

**Issue by Daabramov** [1c-syntax/bsl-language-server#1546]
## Диагностика
BSLLS:RedundantAccessToObject

## Версия
0.17.1

## Описание ложного срабатывания диагностики
Если в модуле с повторным использованием размещено несколько экспортных функций, которые вызывают друг друга, то для работы кеша необходимо указание полного имени модуля

## Пример кода

Пример модуля `ОбменДаннымиПовтИсп` из БСП

```
Функция АвтономнаяРаботаПоддерживается() Экспорт
 Возврат ...
КонецФункции

Функция ЭтоАвтономноеРабочееМесто() Экспорт
 Возврат ОбменДаннымиПовтИсп.АвтономнаяРаботаПоддерживается() И ...;
КонецФункции
```

## Скриншоты

![image](https://user-images.githubusercontent.com/31928832/108071539-e5df4a80-7076-11eb-83b5-217535a13b66.png)

## Дополнительная информация
Отсутствует

**Comment by zeegin** [comment]
Очень подозрительная хрень, а это где-то задокументировано или проверено на личном опыте? Может ли это быть ошибка платформы?

**Comment by nixel2007** [comment]
В доке по повтисп-модулям задокументированно, что внутренние вызовы не кэшируются. Пример ТС про использование кэша изнутри кэшируемого метода.

**Comment by zeegin** [comment]
Я не знал 0_о
Наверное потому что никогда не приходилось делать внутренних вызовов.

Надо добавить ссылку на документацию.
