### ISSUE TITLE
[NEW] Повторное добавление\вставка значений в коллекцию

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1551]
## Описание проблемы, ошибки, которую надо диагностировать

Диагностика находит проблемные места с дублированием кода вставки\добавления значений в различные коллекции.
Подобное часто возникает из-за копипаста.

Подозрительный код
```bsl
Коллекция = Новый Структура;
Коллекция.Вставить("Ключ1", 1);
Коллекция.Вставить("Ключ1", 2);

// выражения в одном блоке, но не подряд
Массив = Новый Массив;
Массив.Добавить(СтрокаТаблицы);
ДругойКод();
Массив.Добавить(СтрокаТаблицы);

Массив.Вставить(0, ДругаяСтрока);
Массив.Вставить(0, ДругаяСтрока);
```

Указанные дубли в большинстве случаев являются ошибкой, но иногда их наличие - это особенности алгоритма.
Например, вставка значений в начало массива или повторное добавление значения в массив не всегда является ошибкой..

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

Похожий ишуз
- https://github.com/1c-syntax/bsl-language-server/issues/1088
- 
### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [x] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

1

## Дополнительная информация

**Нужно учесть:**
- простые блоки кода, без переходов и условий, т.е. без Если, циклов, попыток и т.п.
- учесть, что строки могут идти не подряд друг за другом
- следующие методы объектов:
  - `Вставить` с 2мя параметрами, если в 2х строках совпадает 1й параметр
  - `Добавить` с 1м параметром, если в 2х строках совпадает 1й параметр
- можно учесть наличие объектов - Соответствие, Структура, Массив, ТаблицаЗначений, Список и т.п.
- а можно и не учитывать, а ориентироваться только по наименованию вызовов методов объектов Вставить и Добавить
  - подобное может дать больше полезных замечаний

**Comment by zeegin** [comment]
Кажется будет много FP.

**Comment by zeegin** [comment]
> простые блоки кода, без переходов и условий, т.е. без Если, циклов, попыток и т.п.

Это что именно будет?

**Comment by artbear** [comment]
@zeegin codeBlock в терминах парсера

Т.е. код в блоке учитывается в правиле
```
Коллекция = Новый Структура;
Коллекция.Вставить("Ключ1", 1);
Коллекция.Вставить("Ключ1", 2);
```
а так нет
```
Коллекция = Новый Структура;
Коллекция.Вставить("Ключ1", 1);
Если Условие Тогда
  Коллекция.Вставить("Ключ1", 2);
КонецЕсли;
```

**Comment by artbear** [comment]
Найденные интересные срабатывания из КА 2.5

- 1 
![image](https://user-images.githubusercontent.com/2920817/170663227-0b66221d-91b1-4a85-b96f-195d960f3131.png)

- 2 
![image](https://user-images.githubusercontent.com/2920817/170663362-253cbad3-deb2-41fa-a822-aeaff6cf7b97.png)

- 3 веселое 
  - 1 я на картинке красным текстом отметил - вычисляют дважды одно и то же
2 также дважды ставится КПП, но с разными значениями - ошибка!
  - ![image](https://user-images.githubusercontent.com/2920817/170663404-864f05e7-3ea2-40b7-9013-7fd7e84bb744.png)

- 4 авторы (или авторы) не могут определиться, какой же вариант дублирования вернее )

  - 
![image](https://user-images.githubusercontent.com/2920817/170663554-a67a75ea-0b8f-4bbf-ae79-634a7cddccab.png)

- 5 еще "замечательный" косяк с копипастом в типовом коде бух.отчетности (КА 2.5) - бедные глаза и руки автора кода )

  - 
![image](https://user-images.githubusercontent.com/2920817/170663609-b59a26ec-a2ab-417f-a2ee-ec351877b52e.png)

**Comment by EvilPunker** [comment]
> 5 еще "замечательный" косяк с копипастом в типовом коде бух.отчетности (КА 2.5) - бедные глаза и руки автора кода )
Вы там бухгалтерскую отчетность с налоговой не перепутали? Полный путь к модулю какой?

**Comment by artbear** [comment]
> > 5 еще "замечательный" косяк с копипастом в типовом коде бух.отчетности (КА 2.5) - бедные глаза и руки автора кода )
> 
> Вы там бухгалтерскую отчетность с налоговой не перепутали? Полный путь к модулю какой?

Спасибо за быструю реакцию )

2 похожие проблемы с именем НовИмяП009П1М110001 в КА 2.5 в одном отчете
- src\cf\Reports\РегламентированныйОтчетПрибыль\Ext\ObjectModule.bsl
- src\cf\Reports\РегламентированныйОтчетПрибыль\Forms\ФормаОтчета2019Кв4\Ext\Form\Module.bsl

ОтчетПрибыль - это налоговая или бух.отчетность? я уже не помню )

**Comment by EvilPunker** [comment]
> ОтчетПрибыль - это налоговая или бух.отчетность? я уже не помню )

Налоговая. Для удобства лучше использовать обобщающий термин "Регламентированная отчетность"

**Comment by artbear** [comment]
@EvilPunker вот еще пример ошибки из отчетности КА 2.5 - еще и отступы подозрительные
- src\cf\Reports\КнигаПокупок\Ext\ManagerModule.bsl
- 
![image](https://user-images.githubusercontent.com/2920817/170706299-db82720b-fa4c-492f-92d4-d7fe7cafbaa6.png)

хотя в этом же модуле в 2х или 3х местах есть правильный код - найдите отличия (с) 
- 
![image](https://user-images.githubusercontent.com/2920817/170706580-23ec7ba6-343a-4c5a-a718-dbd61b91fbb5.png)

**Comment by EvilPunker** [comment]
> вот еще пример ошибки из отчетности КА 2.5 - еще и отступы подозрительные

Отступы хорошие, сделаны переносы по стандарту https://its.1c.ru/db/v8std#content:444:hdoc

**Comment by artbear** [comment]
> > вот еще пример ошибки из отчетности КА 2.5 - еще и отступы подозрительные
> 
> Отступы хорошие, сделаны переносы по стандарту https://its.1c.ru/db/v8std#content:444:hdoc

я про отступы на строках, отмеченные красными стрелочками

**Comment by artbear** [comment]
И еще знаменитая ошибка "последней строки" 
![image](https://user-images.githubusercontent.com/2920817/170819791-80314196-bb97-4193-afc3-3e6fd071e9a0.png)
