### ISSUE TITLE
[MOD] Исключить из диагностики "Неиспользуемый локальный метод" методы с определенным текстом вначале названия

### ISSUE THREAD

**Issue by Iscarimet** [1c-syntax/bsl-language-server#1554]
## Диагностика
UnusedLocalMethod

## Описание предлагаемых изменений
Эта диагностика проверяет, что в модуле не должно быть неиспользуемых процедур и функций.
Насколько я помню, она игнорирует методы, если название начинается с "Подключаемый_".

Можно ли расширить это исключение на другие методы?
Например исключить методы, которые начинаются с "префиксПодключаемый_"?
Т.е. хотим в настройках диагностики добавить массив слов-исключений, и диагностика будет игнорировать методы, название которых начинается с этих слов.

## Дополнительная информация
Не нужно исключать методы, если слова исключения находятся внутри названия, а не вначале.

**Comment by zeegin** [comment]
Думаю можно просто писать
Подключаемый_ПрефиксИмяМетода

Так не хочется делать почему?
Я сходу не придумал.

**Comment by Iscarimet** [comment]
> Думаю можно просто писать
> Подключаемый_ПрефиксИмяМетода
> 
> Так не хочется делать почему?
> Я сходу не придумал.

Префикс нужен для быстрого поиска глазами методов, которые добавлены поверх типовых.
Если использовать вариант написания "Подключаемый_ПрефиксИмяМетода", то этот метод может затеряться среди типовых.
Это касается и сценариев обновления типовой конфы - с префиксом в начале названия сразу понятно, что этот метод нельзя трогать. Если префикс будет в середине - придётся в каждое название вчитываться.

Вот простое сравнение, что считывается легче в массе методов?
КоличествоВозможныхГоловныхКонтрагентов
Подключаемый_ОбновитьОтображениеИндексыСПАРК
ОбновитьОтображениеИндексыСПАРК
Подключаемый_лпДобавитьКнопку
Подключаемый_ВыполнитьКоманду1СПАРКРиски
ИсторияКПППослеЗакрытия
лпПодключаемый_ПроверитьКонтрагента
ИсторияНаименованийПослеЗакрытия

На мой взгляд, префикс вначале считывается легче, чем в середине. Для этого он и нужен.

Поэтому нам такой вариант не подошел и нужна такая доработка диагностики.

**Comment by artbear** [comment]
Да, хорошее предложение.

часто подобное требуется.

например, правило фонит на тестовых методах или реализации шагов из Ванесса-АДД

**Comment by zeegin** [comment]
Т.е. вопрос в порядке между префиксами ТвойПрефикс и Подключаемый_.
И наверное для разных задач важность и тот который хочется поставить на первое место будет разная.
Потому скорее стоит делать.
