### ISSUE TITLE
[NEW] Подозрительные многострочные строки

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1557]
## Описание проблемы, ошибки, которую надо диагностировать

Необходимо выдавать замечание на использование странных == сумасшедших многострочных литералов

Подобные строки считаю ошибкой + их наличие сильно усложняет чтение кода.
я за свою жизнь в 1С 8.Х ни разу не видел таких строк, но они возможны )

Необходимо приводить такие строки к  более привычным форматам строк.

### Примеры
1 простые строки
```
"" "Это" "все"

"" "одна" 

//И это тоже мультилайнстринг 
"строка по меркам 1С"
```

2 Также есть хороший пример ошибки в запросе https://github.com/1c-syntax/bsl-language-server/issues/738

Ниже указан пример запроса, на котором должно быть срабатывание диагностики. Запрос примечателен тем, что при его выполнении в выборку попадут только поля Номенклатура и НоменклатураНаименование. Поле НоменклатураКод будет исключено из-за проблемы с кавычками.
```bsl
Запрос = Новый Запрос;
Запрос.Текст = "ВЫБРАТЬ
|	ПриходныйОрдерНоменклатура.Номенклатура КАК Номенклатура,
|	ЕСТЬNULL(ПриходныйОрдерНоменклатура.Номенклатура.Код, "") КАК НоменклатураКод,
|	ЕСТЬNULL(ПриходныйОрдерНоменклатура.Номенклатура.Код, "") КАК НоменклатураНаименование
|ИЗ
|	Документ.ПриходныйОрдер.Номенклатура КАК ПриходныйОрдерНоменклатура
|ГДЕ
|	ПриходныйОрдерНоменклатура.Ссылка = &Ссылка";
```

из СП
```
В исходном тексте многострочные константы могут задаваться двумя способами:

1) Между фрагментами, представляющими отдельные строки многострочной строки, не должно встречаться никаких символов, за исключением пробелов, переводов строки и строк комментариев.
2) Каждая отдельная составляющая не замыкается кавычками, а на каждой последующей строке помещен символ переноса строки | (вертикальная черта). В этом варианте комментарии допускаются, если строка начинается с символа комментария //
```

- связанный ишуз в парсере https://github.com/1c-syntax/bsl-parser/issues/75

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [x] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [x] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

1 минута

**Comment by artbear** [comment]
Пример ошибки, возникающей из-за подобных сумасшедших строк
https://github.com/1c-syntax/bsl-language-server/issues/738

**Comment by zeegin** [comment]
С такими примерами критичность надо точно поднимать до Ошибка.

**Comment by artbear** [comment]
Да, исправил до Критичная и Ошибка
