### ISSUE TITLE
[NEW] [Запросы] Обращение к несуществующим метаданным в запросе

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1563]
## Описание проблемы, ошибки, которую надо диагностировать

При доработках конфигурации необходимо валидировать существующие запросы.

В запросах нужно обращаться к существующим метаданным, иначе при выполнении запроса будет выдано исключение.
Также важно обращение к правильным реквизитам метаданных.

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

- [Cтандарт - Работа с запросами](https://its.1c.ru/db/v8std#browse:13:-1:26:27)
- [Cтандарт - Оптимизация запросов](https://its.1c.ru/db/v8std#browse:13:-1:26:28)
- [Язык запросов - Методические рекомендации по конфигурированию](https://its.1c.ru/db/metod8dev#browse:13:-1:1989:2565:2567:2583)
- 
### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [x] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

10 минут

**Comment by zeegin** [comment]
Думаю это не 
DESIGN - "Ошибка в проектировании"
а
SUSPICIOUS - "Подозрительный код"

**Comment by artbear** [comment]
Да, исправил тег.

**Comment by artbear** [comment]
Дубль https://github.com/1c-syntax/bsl-language-server/issues/1822

странно, как я не нашел этот ишуз (

закрываю
