### ISSUE TITLE
[NEW] [ЗАПРОСЫ] Использование оператора ПОДОБНО в запросах

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1570]
## Описание проблемы, ошибки, которую надо диагностировать

1. При использовании в тексте запроса оператора `ПОДОБНО` допустимо использовать только 
- константные строковые литералы 
- или параметры запроса. 

Запрещается формировать строку шаблона при помощи вычислений, использовать конкатенацию строк средствами языка запросов.

Правильно:
```sql
Реквизит ПОДОБНО "123%"
```
Неверно:
```sql
Реквизит ПОДОБНО "123" + "%"
Реквизит ПОДОБНО Таблица.Шаблон
```

2. Запросы, в которых управляющие символы шаблона оператора `ПОДОБНО` находятся в полях запроса или в вычисляемых выражениях, по-разному интерпретируются на различных СУБД. 

Например, запрос, успешно выполняющийся при работе с файловой базой, может возвращать неверные результаты при работе в режиме клиент-сервера. 
Подобные выражения необходимо переформулировать.

Например, вместо:
```bsl
Запрос = Новый Запрос("
    |ВЫБРАТЬ
    |    Товары.Ссылка
    |ИЗ
    |    Справочник.Товары КАК Товары
    |ГДЕ
    |    Товары.СтранаПроисхождения.Наименование ПОДОБНО &ШаблонНазванияСтраны + "_"
    |");

Запрос.УстановитьПараметр("ШаблонНазванияСтраны", "ЧА");
```
Необходимо использовать:
```bsl
Запрос = Новый Запрос("
    |ВЫБРАТЬ
    |    Товары.Ссылка
    |ИЗ
    |    Справочник.Товары КАК Товары
    |ГДЕ
    |    Товары.СтранаПроисхождения.Наименование ПОДОБНО &ШаблонНазванияСтраны
    |");

Запрос.УстановитьПараметр("ШаблонНазванияСтраны", "ЧА_");
```

Данное требование продиктовано необходимостью переносимости прикладных решений на различные СУБД.

>**Область применения**: управляемое приложение, мобильное приложение, обычное приложение.

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

- [Особенности использования в запросах оператора ПОДОБНО](https://its.1c.ru/db/v8std#content:726:hdoc)
- [Оператор проверки строки на подобие шаблону - Руководство разработчика](https://its.1c.ru/db/v8318doc#bookmark:dev:TI000000506)
- 
### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [x] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [x] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [x] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

10 минут

**Comment by nixel2007** [comment]
Кажется пункт 2 - это прям bug, а не code smell

**Comment by artbear** [comment]
@nixel2007 1 п.2 - редкий случай, чтобы так явно передавали именно спец.символы

2 я бы всю диагностику к ошибке отнес, оба пункта!

но представляю реакцию код-ревьювера, решил оставить код-смелл )

**Comment by nixel2007** [comment]
Ну кстати да, почему бы и не целиком её сделать багом.
Может @zeegin подскажет?

**Comment by zeegin** [comment]
Да можно все сделать багом.
Еще, если мне не изменяет память, может быть ошибка если подобно берется от строки бесконечной длины.

**Comment by nixel2007** [comment]
ок, перевесил тип диагностики на баг.
