### ISSUE TITLE
[MOD] Typo. Сокращение количества замечаний

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#1586]
## Диагностика

Typo

## Описание предлагаемых изменений

Диагностика находит опечатки в модуле и, часто, приводит к лавинообразному увеличению количества замечаний, если опечатка присутствует в имени переменной или метода, который многократно используется

Предлагаю изменить логику работы следущим образом:
 - анализировать только имена переменных в блоках инициализации или объявления
 - анализировать имена методов в модуле объявления 
 - анализировать имена модулей, вешая замечание на первую строку модуля
 - анализировать имена параметров в объявлении метода

Кроме облегчения восприятия произойдет и снижение нагрузки от диагностики. После данной доработки можно подумать и о поиске замечаний в комментариях :)

**Comment by asosnoviy** [comment]
Очень хочется разделить на две:
1. Очепятки в именах переменных
2. Очепятки в стрингах, возможно видимых пользователю

**Comment by nixel2007** [comment]
Боюсь, что такая модификация будет давать тонну FN. Помимо явного присваивания в переменную слева от "равно", могут быть присваивания в свойства, вставки в какие-нибудь структуры/передача в конструкторы и проч.

на мой вкус лучше, чтобы оно орало всегда и на все токены, как сейчас. больше стимула поправить. если все же будет принято решение о переделке, заранее голосую за добавление флага для возвращения старого поведения.

**Comment by theshadowco** [comment]
вот счас не понял 
- присваивание в свойства - где здесь может опечатка не пойманная ранее?

ну и к дополнению предложения выше - провка на имена параметров метода, пропустил сразу

**Comment by nixel2007** [comment]
> присваивание в свойства - где здесь может опечатка не пойманная ранее?

смотря что такое "ранее". в общем случае структура может прийти откуда угодно, хоть из метаданных, хоть из json.
`МояСтруктура.Очепятка = 123;` такое тоже надо ловить, на мой взгляд. Впрочем, как ты наверное понял, я и использование `МояСтруктура.Очепятка` тоже хотел бы видеть и всегда орать.

**Comment by theshadowco** [comment]
в таком случае повлиять ты уже не сможешь: исправить при инициализации структуры - да, при создании объекта json - да, а вот в прикладном коде - нет. 
Сейчас мы имеем массу ошибок на исполнителе, который физически не может повлиять на исправление ошибки - он пользователь, исправлять надо в самом начале.

**Comment by nixel2007** [comment]
> Предлагаю на одинаковые опечатки вешать одно замечание - первое вхождение
и к нему привязывать ссылки на остальные опечатки

а вот это действительно неплохая идея. @theshadowco ?

**Comment by theshadowco** [comment]
согласен, что так лучше, чем сейчас, но не до конца :)

**Comment by EightM** [comment]
Вы уж либо крестик снимите, либо трусы наденьте. Диагностика гласит: "код должен быть написан без опечаток". Без исключений. 

Однако, вы говорите: "ну, это конечно, так, но что-то ошибок как-то слишком много (потому что у меня очень много опечаток) , поэтому давайте мы вот эти ошибки (важные лично для меня) будем считать ошибками, а остальное скроем или покажем как-нибудь по другому". 

Мне кажется куда более логичным, что если у вас Typo вывалила дофига ошибок, то вы либо wont fix бахните, либо исправляйте потихоньку, либо пишите таки код без ошибок.

**Comment by theshadowco** [comment]
Вот не согласен - сейчас имеем эффект шума. 
Пример 1:
Создан метод МояФункцияСОчепяткой, который используется в 100500 местах. Править не будем, почему - не имеет значения. Так вот я предлагаю фиксировать ошибкой имя этого метода, а не его использование, ибо при использовании выбора у разработчика нет, это не его ошибка

Пример 2: Объект метаданных назван с ошибкой. Аналогично примеру 1 исправлять его возможности нет, а фонить будет везде, где к нему обратятся и опять, это не ошибка разработчика, который использует этот объект.

**Comment by EightM** [comment]
> Так вот я предлагаю фиксировать ошибкой имя этого метода, а не его использование, ибо при использовании выбора у разработчика нет, это не его ошибка

И получаем кучу потенциальных проблем, когда разработчик изменил имя метода на правильное, но не исправил все использования. В таком случае получим крест в рантайме.

> это не ошибка разработчика, который использует этот объект
Согласен, это не ошибка разработчика. Это ошибки проекта. Неважно кто их допустил, но каждый раз используя имя с опечаткой, ты увеличиваешь тех. долг, так как ошибки будут множиться. Постоянное "жужжание" диагностики это напоминание о том, что твой код написан некорректно и что его следует поправить. Если мы будем заметать эти ошибки под ковер, рано или поздно они вылезут.

**Comment by theshadowco** [comment]
первый пример - это и без диагностики можно сломать :). Если разработчик такой - гнать его из профессии.
что по второму - ошибки на которые не можешь повлиять === шум, а среди него теряется полезная информация. 
Ошибка по факту одна - неверно названный метод, ее никто прятать не предлагает. все остальное - это не ошибки.

**Comment by EightM** [comment]
В данном случае, я рассматриваю код как "plain text", и твое предложение звучит как: "Давайте подсвечивать ошибки только в деепричастных оборотах и прямой речи".

Можно конечно сделать сложную параметрическую настройку где будет N чекбоксов, в которых пользователь будет отмечать какой скоуп объектов он хочет проверять, но пока это выглядит как недовольство тем, что сонар показывает плохие метрики из-за опечаток.

**Comment by nixel2007** [comment]
А ещё есть userWordsToIgnore...

**Comment by theshadowco** [comment]
> В данном случае, я рассматриваю код как "plain text", и твое предложение звучит как: "Давайте подсвечивать ошибки только в деепричастных оборотах и прямой речи".
> 
> Можно конечно сделать сложную параметрическую настройку где будет N чекбоксов, в которых пользователь будет отмечать какой скоуп объектов он хочет проверять, но пока это выглядит как недовольство тем, что сонар показывает плохие метрики из-за опечаток.

вот теперь я перестал вас понимать.
кратко
 - есть ошибка в имени объекта
 - сейчас показываются все места, где этот объект используется
 - я предложил показывать первое место появления ошибки

вопрос: какой плейн-текст, какие деепричастные обороты?

**Comment by theshadowco** [comment]
пример "на пальцах"
Привезли машину кривых кирпичей, из которых тебе надо построить. Приходит прораб и начинает орать за каждый кривой кирпич, а по факту решать проблему надо раньше - использовать нормальные кирпичи

**Comment by theshadowco** [comment]
> А ещё есть userWordsToIgnore...

Это экранирование слова, а его не надо экранировать - создали кривой справочник, ну чтож, живем, но имя не перестало быть ошибочным и в других местах, не связанных с использованием имени данного справочника будем громко шуметь

**Comment by zeegin** [comment]
Я бы хотел видеть все опечатки, и иметь возможность сгруппировать их по опечатке в конкретном слове. А при добавлении в словарь отметить исправленными сразу все замечания с этой опечаткой. Так делает АПК и это кажется очень правильным поведением.
