### ISSUE TITLE
Область первого уровня с таким именем уже существует в модуле

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#159]
Не знаю чем именно это плохо, но точно не хорошо.

**Comment by Stepa86** [comment]
Обычная практика иметь одинаковые области 2го уровня в разных областях первого уровня. Типа вот программный интерфейс для Файлов, вот служебный, а вот внутренние методы

**Comment by asosnoviy** [comment]
https://github.com/1c-syntax/bsl-language-server/pull/788
