### ISSUE TITLE
[NEW] [Запросы] Использование "ПЕРВЫЕ Х" без указания порядка сортировки или условий

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1591]
## Описание проблемы, ошибки, которую надо диагностировать

Использование конструкции `ПЕРВЫЕ Х` без указания порядка сортировки в `УПОРЯДОЧИТЬ ПО` или условий в секции `ГДЕ` чревато получением неожиданных результатов. Например, в разных СУБД порядок возвращаемых результатов будет отличаться, или этот порядок будет отличаться от порядка, который ожидает разработчик.
Еще могут быть проблемы с выборкой первых записей, если в запросе отсутствуют или неверно настроены фильтры.

Цитата из стандарта

>1.4. Отсутствие предложения `УПОРЯДОЧИТЬ ПО` оправдано только в тех случаях, когда

- алгоритм обработки результатов запроса не рассчитывает на определенный порядок записей
- результат обработки выполненного запроса не показывается пользователю
- результат запроса - заведомо одна запись

>В таких случаях рекомендуется не добавлять предложение `УПОРЯДОЧИТЬ ПО` в текст запроса, так как это приводит к дополнительным затратам времени при выполнении запроса.

Алгоритм
- пропускаем конструкцию `ПЕРВЫЕ 1`, если в запросе есть конструкции `УПОРЯДОЧИТЬ ПО` или `ГДЕ`
- если их нет, тогда выдается замечание на `ПЕРВЫЕ 1`
- Выдаем замечание на `ПЕРВЫЕ Х`, если нет конструкции `УПОРЯДОЧИТЬ ПО`
   
## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

- [Упорядочивание результатов запроса - Стандарт ИТС](https://its.1c.ru/db/v8std#content:412:hdoc)
  
### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [x] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

2 минуты

**Comment by zeegin** [comment]
Я думаю надо пропускать конструкцию `ПЕРВЫЕ 1` и `ПЕРВЫЕ 2`, часто используется для определения есть ли значение по умолчанию в справочнике, например когда разделение по организациям или складам отключено в ФО.
