### ISSUE TITLE
[NEW] Использование ПродолжитьВызов() в коде основной конфигурации

### ISSUE THREAD

**Issue by sokolov-rv** [1c-syntax/bsl-language-server#1593]
## Описание проблемы, ошибки, которую надо диагностировать

В тексте модулей конфигурации нельзя использовать функцию ПродолжитьВызов(). 
Сейчас даже встроенный синтаксический контроль модулей платформы (8.3.18.1289) в конфигураторе не ловит эту ошибку и в режиме предприятия на этом коде платформа выводит Exception.

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

Цитата из Синтакс-помощника:
Использовать функцию ПродолжитьВызов() можно только в расширениях и только в методах с аннотацией &Вместо.

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [x] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

1 минута (обычно эти строчки появляются при переносе копипастой расширений в основную конфигурацию и требуется гораздо больше времени понять, что должен был делать код и как это исправить)
## Дополнительная информация

Если можно - хотелось бы пройти самому путь контрибьютора на этой задаче. Это мой первый опыт. Надеюсь все правильно оформил.
Диагностику можно назвать WrongPlaceFunctionProceedWithCall или ProceedWithCallNotInExtension

**Comment by artbear** [comment]
@sokolov-rv я бы еще добавил тег Подозрительный код
