### ISSUE TITLE
В тексте модуля содержатся служебные комментарии (АПК:284)

### ISSUE THREAD

**Issue by zeegin** [1c-syntax/bsl-language-server#161]
//!!
//##
//@
//mrg
//todo
//debug
//отладка
//дляотладки
КОНСТРУКТОР_ЗАПРОСА_С_ОБРАБОТКОЙ_РЕЗУЛЬТАТА
КОНСТРУКТОР_ДВИЖЕНИЙ_РЕГИСТРОВ
КОНСТРУКТОР_ПЕЧАТИ
КОНСТРУКТОР_ВВОДА_НА_ОСНОВАНИИ

**Comment by otymko** [comment]
#117 было начато отслеживания подобного, но список тегов не полный

**Comment by nixel2007** [comment]
Там, кстати, список тегов параметром. Можно все эти теги перечислить и все будет ловиться. Но наверное стоит их добавить по дефолту.

**Comment by nixel2007** [comment]
@otymko дай угадаю, оно в обещанном невыпущенном релизе, да?)

**Comment by otymko** [comment]
@nixel2007 Тот самый релиз)
