### ISSUE TITLE
[MOD] Запрет на использование метода ТекущаяДата() - переформулировать описание проблемы и рекомендации

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1619]
## Диагностика

DeprecatedCurrentDate

## Описание предлагаемых изменений

Описание проблемы и предлагаемый способ решений очень неполные.

Предлагаемая рекомендация "заменять на ТекущаяДатаСеанса" некорректна в случае клиентских методов.

Нужно добавить текст аналогично шаблону https://its.1c.ru/db/v8std/content/643/hdoc или исходному ишузу #924

я удивлен, почему в ПР для правила так не сделали.

## Дополнительная информация

Исходная задача https://github.com/1c-syntax/bsl-language-server/issues/924

**Comment by APonkratov** [comment]
@nixel2007 заберу на себя, если не против

**Comment by nixel2007** [comment]
@APonkratov хватай
