### ISSUE TITLE
[FP] MissingReturnedValueDescription

### ISSUE THREAD

**Issue by zeegin** [1c-syntax/bsl-language-server#1641]
## Диагностика

MissingReturnedValueDescription

## Версия

v0.18.0

## Описание ложного срабатывания диагностики

https://github.com/zeegin/OpenSubsystemsLibrary/blob/e71d54a9fab7666574e368f89ccba6e47b796e6a/OpenSubsystemsLibrary/src/CommonModules/Json/Module.bsl#L14

## Пример кода

```bsl
// Specifies settings for reading values from JSON format
// 
// Returns:
//  Structure - contains:
// * ReadToMap - Boolean - default is True
// * PropertiesWithDateValuesNames - Array contains String - for every fields with date values
//                                 - String - if JSON has only one date field
// * ExpectedDateFormat - JSONDateFormat - default is ISO "YYYY-MM-DDTHH:MM:SSZ" example "2009-02-15T00:00:00Z"
// * Encoding - TextEncoding - default is UTF-8
//            - String - JSONReader.OpenStream encodings
// 
Function DeserializerSettings() Export
    
    Self = New Structure;
    Self.Insert("ReadToMap", True);
    Self.Insert("PropertiesWithDateValuesNames", New Array);
    Self.Insert("ExpectedDateFormat", JSONDateFormat.ISO);
    Self.Insert("Encoding", TextEncoding.UTF8);
    
    Return Self;
    
EndFunction
```

## Скриншоты

![image](https://user-images.githubusercontent.com/729213/116628503-f144d100-a957-11eb-8eb3-e1ac4f240745.png)

## Дополнительная информация

Опиание возвращаемого значения корректное

**Comment by zeegin** [comment]
Ругеатся на `Array contains String` если оставить `Array` то все ок

**Comment by zeegin** [comment]
https://github.com/1c-syntax/bsl-language-server/issues/1620

Видимо одна и та же ошибка парсера.

**Comment by huxuxuya** [comment]
Согласно докам https://its.1c.ru/db/v8std/content/453/hdoc п 5.2.2
правильно писать не "Array **contains** String" а "Array **of** String"

**Comment by zeegin** [comment]
Да, это было исправлено в одной из последних версий EDT синхронно со стандартом.
