### ISSUE TITLE
Вопросы по описанию диагностик в 0.18

### ISSUE THREAD

**Issue by EightM** [1c-syntax/bsl-language-server#1648]
- [ ] 1. CrazyMultilineString - нет ни примеров, ни источников. Скорее всего не соответствует "Major", так не нарушает бизнес логику

- [ ] 2. IncorrectUseLikeInQuery - описание написано в разделе примеры, примеры и источники отсутствуют. ~~Непонятно почему "Критичныый" статус.~~ (установлен major) "Запрещается формировать строку шаблона при помощи вычислений" - почему? "по-разному интерпретируются на различных СУБД." - где ссылки на подтверждения данной ситуации и примеры?

- [x] 3. ~~IncorrectUseOfStrTemplate - криво описан пример~~ скорректировано

- [ ] 4. LogicalOrInTheWhereSectionOfQuery - примеры занесены в секцию описание

- [ ] 5. MultilineStringInQuery - в примере нет никакого маркера, непонятно где ошибка

- [x] 7. ~~UsingLikeInQuery - Необъяснимое использование "критического" статуса~~ установлен major

- [x] 8. ~~VirtualTableCallWithoutParameters - Необъяснимое использование "критического" статуса~~ установлен major

- [ ] 9. WrongUseFunctionProceedWithCall - Слишком краткое описание. Непонятно что будет если использовать там где нельзя? Будет игнорирование кода, исключение, упадет база?

- [ ] 10. IncorrectLineBreak - Плохо описанный пример. Непонятно, приведен правильный или неправильный пример? Если неправильный, то не хватает правильного варианта

- [ ] 11. CommonModuleMissingAPI - Непонятно почему "Major". Непонятно, что будет если я не укажу область, что сломается, почему это плохо?

**Comment by zeegin** [comment]
@asosnoviy 
@nixel2007 
я бы поднял тему

**Comment by artbear** [comment]
> CrazyMultilineString - нет ни примеров, ни источников. Скорее всего не соответствует "Major", так не нарушает бизнес логику
- @theshadowco в ПР https://github.com/1c-syntax/bsl-language-server/pull/1597 почему-то не взял примеры из исходных тикетов (

>IncorrectUseLikeInQuery - описание написано в разделе примеры, примеры и источники отсутствуют. 
- и тут Валера почему-то не включил примеры из моего исходного тикета в свой ПР https://github.com/1c-syntax/bsl-language-server/pull/1596

**Comment by artbear** [comment]
>LogicalOrInTheWhereSectionOfQuery - примеры занесены в секцию описание

@EightM в данном случае пришлось так сделать, потому что объяснения, которых немало, в данном случае без примеров вообще не будут понятны (
ПР для связи https://github.com/1c-syntax/bsl-language-server/pull/1562

**Comment by artbear** [comment]
>IncorrectUseOfStrTemplate - криво описан пример

@EightM в описании 3 набора примеров. расшифруй замечание, т.к. непонятно, о каком именно примере ты написал.

**Comment by nixel2007** [comment]
актуализировал

**Comment by nixel2007** [comment]
> "по-разному интерпретируются на различных СУБД." - где ссылки на подтверждения данной ситуации и примеры?

а это вроде прям с ИТС цитата.

**Comment by artbear** [comment]
да, это точная цитата с итс. я оттуда часть описания брал

**Comment by EightM** [comment]
я понимаю, что это цитата с итс. Но bsl ls всё таки не портативный справочник its, и есть люди которые увидят такое "объяснение" и спросят "на основании чего сделано такое утверждение? Какие риски я несу если оставлю код без изменений?"

**Comment by EightM** [comment]
Стоит помнить несколько моментов:
1. Информация с ИТС может быть устаревшей;
2. Она может относиться к определенным версиям платформы;
3. Она может относиться только к конкретным видам СУБД / конкретным версиям СУБД.

**Comment by nixel2007** [comment]
>  Но bsl ls всё таки не портативный справочник its

но при этом много абзацев с ИТС де-факто выступают описанием диагностик. если говорить про подобно, но в стандарте нет четкого описания, почему и когда это может приводить к проблемам.  может быть что-то есть в разделе ТВКВ или на kb, можно попробовать там поискать. Но вполне вероятно это останется мифической рекомендацией от вендора, возведенной в стандарт.
