### ISSUE TITLE
[BUG] Ошибка при разборе JSON-файла, содержащего настройки диагностики CommentedCode

### ISSUE THREAD

**Issue by bapho-bush** [1c-syntax/bsl-language-server#1665]
## Диагностика

[CommentedCode](https://1c-syntax.github.io/bsl-language-server/diagnostics/CommentedCode/)

## Версия
Плагин версии 1.8.1

## Описание ошибки диагностики
```org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'diagnostics' defined in class path resource [com/github/_1c_syntax/bsl/languageserver/diagnostics/infrastructure/DiagnosticsConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.List]: Factory method 'diagnostics' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'diagnostic' defined in class path resource [com/github/_1c_syntax/bsl/languageserver/diagnostics/infrastructure/DiagnosticConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github._1c_syntax.bsl.languageserver.diagnostics.BSLDiagnostic]: Factory method 'diagnostic' threw exception; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commentedCodeDiagnostic' defined in URL [jar:file:/home/runner/.sonar/cache/7959bff7d2df378f7bed542287a4eb97/sonar-communitybsl-plugin.jar!/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommentedCodeDiagnostic.class]: Initialization of bean failed; nested exception is java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Float (java.lang.Integer and java.lang.Float are in module java.base of loader 'bootstrap')```

## Пример кода
До кода дело не доходит. Ошибка появляется на этапе разбора JSON-файла.

## Скриншоты
![изображение](https://user-images.githubusercontent.com/30332279/118482582-9a901300-b71d-11eb-9b6d-766999f71d69.png)

## Дополнительная информация
Пример JSON-файла, на котором поймал ошибку, - https://gist.github.com/bapho-bush/db96d4ca26ab94dae2387795d38e6a46

**Comment by asosnoviy** [comment]
```json
{  "$schema": "https://raw.githubusercontent.com/1c-syntax/bsl-language-server/master/src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/schema.json",  "language": "ru",  "diagnostics": {    "parameters": {      "LineLength": {        "maxLineLength": 150      },      "CognitiveComplexity": {        "complexityThreshold": 30,        "checkModuleBody": true      },      "CyclomaticComplexity": {        "complexityThreshold": 30      },      "MissingSpace": {        "allowMultipleCommas": true      },      "IfElseDuplicatedCodeBlock": false,      "IfElseIfEndsWithElse": false,      "NumberOfOptionalParams": {        "maxOptionalParamsCount": 5      },      "GetFormMethod": false,      "MissingSpace": false,      "CommonModuleInvalidType": false,      "CommentedCode": {         "threshold": 0.9         }    }  }}

**Comment by asosnoviy** [comment]
Параметр float и падает на касте =(
