### ISSUE TITLE
[FP] Неверное срабатывание правила IncorrectLineBreak на комментариях и длинных строках

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1683]
## Диагностика

IncorrectLineBreak

## Версия

0.18.1

## Описание ложного срабатывания диагностики

- Генерится замечание на строку в комментариях
1 ![image](https://user-images.githubusercontent.com/2920817/121511743-a6f04e80-c9f1-11eb-8309-25dc6edbf4bf.png)
- Генерится замечание на длинные строки
2 скриншот в комментарии https://github.com/1c-syntax/bsl-language-server/issues/1683#issuecomment-863735125

**Comment by asosnoviy** [comment]
@artbear сегодня одна релизная, завтра друга. Поле существует что бы писать туда конкретную циферу.

**Comment by artbear** [comment]
исправил на 0.18.1

**Comment by pzhgulev** [comment]
Не совсем комментарий, но на NStr тоже сработало ложно:
![telegram-cloud-photo-size-4-5929235230558893684-y](https://user-images.githubusercontent.com/47918264/122112955-7d408880-ce32-11eb-8de7-d8d0959fd83b.jpg)

**Comment by theshadowco** [comment]
![image](https://user-images.githubusercontent.com/9591731/122432557-193ad300-cf9e-11eb-885d-31e919b6f1b5.png)

**Comment by sfaqer** [comment]
Не комментарий, но тоже добавлю:

![image](https://user-images.githubusercontent.com/32082417/122503877-88670480-d03c-11eb-9193-f9270fd8783c.png)

**Comment by artbear** [comment]
@sfaqer Спасибо, дополнил описание
