### ISSUE TITLE
[MOD] Разрешить смешивание латинских и кириллических символов в одном идентификаторе, если символы другого языка есть только в конце строки

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1684]
## Диагностика

`LatinAndCyrillicSymbolInWord`

## Описание предлагаемых изменений

Добавить исключение - если символы другого языка встречаются только в конце строки
например, `ОписаниеСобытияХукаИзJson, ОписаниеСобытияJSON`
или даже `QRКод` - сначала английские, потом только русские

в Исполнителе подобные имена уже сделаны

это исключение либо по умолчанию, либо через параметр правила

**Comment by asosnoviy** [comment]
Плюсану. 
Правило сформировано из того, что: 
1. Не надо мучать разрабов постоянным переключением раскладки. 
2. Избежать ловушки с одинаковыми символами аля Сc Aа.

1. Автокомплит в помощь и проблемы с концевыми символами нет
2. Ошибки в раскладке, как правило в первых символах.

п.с. @artbear о каком исполнителе речь?

**Comment by artbear** [comment]
в продолжение исходного ишуза https://github.com/1c-syntax/bsl-language-server/issues/432

**Comment by artbear** [comment]
Исполнитель от 1С ) @asosnoviy 

там для многих встроенных идентификатор сначала русские символы, потом английские.

удобно, чтобы не переключать раскладку, контекстная подсказка помогает.

**Comment by asosnoviy** [comment]
Вообще не понял причем тут исполнитель...
