### ISSUE TITLE
[FP] UsageWriteLogEvent – срабатывает на использования менеджера ошибок 8.3.17 ОбработкаОшибок

### ISSUE THREAD

**Issue by pzhgulev** [1c-syntax/bsl-language-server#1691]
## Диагностика
UsageWriteLogEvent

## Версия
плагин 1.9.0 (0.18.1)

## Описание ложного срабатывания диагностики
Ложное срабатывание при использовании менеджера ошибок 8.3.17 ОбработкаОшибок.
При этом если поместить его внутрь WriteLogEvent(), то срабатывает диагностика на инициализацию вложенным методом.

## Пример кода
`Try
	Except
		
		DetailErrorDescriptionText = ErrorProcessing.DetailErrorDescription(ErrorInfo());
		
		WriteLogEvent(
			"CustomHandlersServer.CreateScheduledJob", 
			EventLogLevel.Error, 
			, 
			, 
			DetailErrorDescriptionText);
		
		Return False;
		
	EndTry;`

## Скриншоты
![image](https://user-images.githubusercontent.com/47918264/122056790-05a33700-cdfb-11eb-9673-b8c4263a3a75.png)

**Comment by artbear** [comment]
также ФП на это же правило https://github.com/1c-syntax/bsl-language-server/issues/1685

**Comment by artbear** [comment]
Также ФН на правило https://github.com/1c-syntax/bsl-language-server/issues/1714
