### ISSUE TITLE
[BUG] Typo - срабатывает на все NStr при использовании английского языка проекта

### ISSUE THREAD

**Issue by pzhgulev** [1c-syntax/bsl-language-server#1693]
## Диагностика
Typo 

## Версия
плагин 1.9.0 (0.18.1)

## Описание ошибки диагностики
Основной язык проекта - английский. В конфигурации есть локализация дополнительно на русский и арабский. После обновления плагина на 1.9.0 диагностика Typo сработала на все NStrы на русский и арабские языки (более 100к срабатываний). 
При этом, если переключить язык проекта на русский - ложных срабатываний на все NStrы нет, т.е. на английский и арабский языки не срабатывает в таком кейсе.

## Пример кода
`NStr("en = 'Departments'; ru = 'Подразделения'; ar = 'الأقسام'")`

## Скриншоты
![photo_2021-06-15 17 52 06](https://user-images.githubusercontent.com/47918264/122064845-8285df00-ce02-11eb-9c7f-063bd768f491.jpeg)
![image](https://user-images.githubusercontent.com/47918264/122072464-a5b38d00-ce08-11eb-9e1e-dfe948962d33.png)

## Дополнительная информация
В идеале хотелось бы иметь проверки на нужной комбинации языков (например en, ru), через параметры, но это другая история, как минимум хочется снова начать пользоваться диагностикой для основного языка.

**Comment by nixel2007** [comment]
Перестало? В 0.19 были изменения в механизме словаря

**Comment by pzhgulev** [comment]
Да) в change logе вроде есть пункт "Изменены диагностики: Typo - английский словарь больше не ругается на кириллицу и наоборот;". Я удивился еще что не привязали к релизу.
