### ISSUE TITLE
[FP] IncorrectUseOfStrTemplate - %%%1%% и %(1)%(2)

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#1700]
## Диагностика
IncorrectUseOfStrTemplate 

## Версия
0.18.1

## Описание ложного срабатывания диагностики
Некорректно обрабатываются шаблоны:
1.  %%%1%%
2. %(1)%(2)

## Скриншоты
![image](https://user-images.githubusercontent.com/15638529/123118745-90171680-d44b-11eb-9a30-ff7fcaa88446.png)

![image](https://user-images.githubusercontent.com/15638529/123118888-b472f300-d44b-11eb-8ea5-f41af9b20f34.png)

**Comment by theshadowco** [comment]
в диагностике надо поправить регексп и все...

**Comment by gosn1ck** [comment]
Привет

**Comment by artbear** [comment]
Исправлено мной в ПР https://github.com/1c-syntax/bsl-language-server/pull/1794
