### ISSUE TITLE
Подсвечивать параметры в текстах запросов

### ISSUE THREAD

**Issue by EvilBeaver** [1c-syntax/bsl-language-server#1705]
Было бы красиво видеть более богатую подсветку текстов запросов.
Например, параметры запросов просятся под выделение цветом.

![image](https://user-images.githubusercontent.com/2657561/123558018-ced70480-d79c-11eb-87f9-0ca2842e1a9a.png)

Так же можно было бы подсвечивать функции, такие как ЗНАЧЕНИЕ, НАЧАЛОПЕРИОДА и пр.

**Comment by nixel2007** [comment]
bsl ls на текущий момент вообще не занимается синтакс хайлайтом.
Хайлайт в всц и гитхабе подсвечивает параметры запросов.

Так что встречный вопрос - откуда этот скрин? :)

**Comment by EvilBeaver** [comment]
@nixel2007 скрин из VSС. Про хайлайт не знал, думал BSLLS тоже это делает.

**Comment by nixel2007** [comment]
Какая тема у тебя выбрана в редакторе?

**Comment by EvilBeaver** [comment]
Уточню. Но раз вы говорите, что оно уже красит, то скорее всего тема и виновата. Можно закрывать наверное

**Comment by nixel2007** [comment]
![image](https://user-images.githubusercontent.com/1132840/123650764-90405900-d833-11eb-85be-7a23298939e8.png)

one dark pro

![image](https://user-images.githubusercontent.com/1132840/123650895-b36b0880-d833-11eb-8cd8-ec7760f5ed48.png)

Светлая (Visual Studio)

![image](https://user-images.githubusercontent.com/1132840/123650946-bfef6100-d833-11eb-8c8d-0da56a884af2.png)

Светлая+ (По умолчанию)

**Comment by EvilBeaver** [comment]
А что насчет функций?

**Comment by nixel2007** [comment]
@EvilBeaver аналогично. но на Светлая+ она таким светлозолотым цветом выделяется, что ее почти и не видно.

Переходи на темную сторону, Люк!

**Comment by EvilBeaver** [comment]
Супер. Закрываю и меняю тему
