### ISSUE TITLE
Диагностика на блок кода перед методами

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#171]
type: bug
severity: ERROR
timeToFix: 5min
scope: ALL

Диагностика должна кидать сообщение на новый узел из https://github.com/1c-syntax/bsl-parser/issues/29

**Comment by asosnoviy** [comment]
Определения процедур и функций должны размещаться перед операторами тела модуля

**Comment by asosnoviy** [comment]
А дайте плз пример из тестера

**Comment by nixel2007** [comment]
Под рукой не осталось, но там что-то типа такого:

Метод();
Сообщить(""):

Процедура Метод()
...
КонецПроцедуры

**Comment by asosnoviy** [comment]
![image](https://user-images.githubusercontent.com/15638529/60085248-9c274b00-9741-11e9-9836-0f77f94146e6.png)

Угу, все так и есть.
