### ISSUE TITLE
[MOD] MissingTemporaryFileDeletion - добавить возможность исключения методов объектов, а не только глобальных методов

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1711]
## Диагностика

MissingTemporaryFileDeletion

## Описание предлагаемых изменений

Сейчас диагностики учитывает только глобальные методы вида УдалитьФайл

а во многих конфигурациях есть методы из общих модулей БСП (ОбщегоНазначения.УдалитьВременныйФайл) или аналогичные самописные методы в общих модулях или обработках-классах.

Нужно добавить 
- обработку подобных методов объектов в правиле
- возможность исключения подобных методов

Предлагаю добавить еще один вид исключения - Исключаемые методы, вызываемые через точку

## Дополнительная информация

Исходный ишуз https://github.com/1c-syntax/bsl-language-server/issues/435

**Comment by artbear** [comment]
Ранее сделанный, но закрытый ПР https://github.com/1c-syntax/bsl-language-server/pull/1447
его можно использовать как шаблон или взять из него тесты

**Comment by artbear** [comment]
@theshadowco @nixel2007 предлагаю поставить тег good first issue

**Comment by theshadowco** [comment]
> @theshadowco @nixel2007 предлагаю поставить тег good first issue

Не такой уж и good first
