### ISSUE TITLE
[BUG] Ошибка парсинга при использовании слова Wait как параметра метода

### ISSUE THREAD

**Issue by vkostyanetsky** [1c-syntax/bsl-language-server#1735]
**Версия**
Плагин 1.9.0 (0.18.1)

**Описание ошибки диагностики**
Если в качестве имени метода используется слово Wait, происходит ошибка разбора кода.

**Пример кода**
[sample.txt](https://github.com/1c-syntax/bsl-language-server/files/6860098/sample.txt)

**Скриншоты**
![error](https://user-images.githubusercontent.com/40140090/126592458-377ba9d5-3d20-4c70-9e96-9b86543ac1c2.png)

**Дополнительная информация**
Предположение: плагин распознает слово Wait как конструкцию Ждать/Await встроенного языка. 

Деталь: в индексе синтакс-помощника Конфигуратора тоже это слово фигурирует, хотя в самом тексте справки указан корректный синтаксис.

![3](https://user-images.githubusercontent.com/40140090/126593379-ce066ec2-894c-4ddc-9c51-8ad4ddab9d1d.png)

**Comment by nixel2007** [comment]
Спасибо за репорт.
Можно попросить тебя проверить эту ошибку на девелоп версии bsl ls? Недавно правили разбор await в выражении.

**Comment by vkostyanetsky** [comment]
> Можно попросить тебя проверить эту ошибку на девелоп версии bsl ls? Недавно правили разбор await в выражении.

У меня сейчас нет подходящего контура под рукой. В течении нескольких дней чекну!

**Comment by nixel2007** [comment]
Если что, я не про сонар плагин, а именно про бсл лс. Он собирается командной gradlew bootJar и просто поставляется в настройках vscode

**Comment by asosnoviy** [comment]
@nixel2007 Смотри какой сюрприз =) 
![image](https://user-images.githubusercontent.com/15638529/126679661-bbcfeaa4-f10c-4d4b-b60d-5d48c5efc086.png)

**Comment by asosnoviy** [comment]
Парсер поправили, но не зарелизили.  В девелопе ЛС торчит старый релиз. Пересобрался с мастера парсера, все стало нормально.

![image](https://user-images.githubusercontent.com/15638529/126743497-7ac6702a-d09e-4283-ab0b-4095085c26b8.png)

**Comment by nixel2007** [comment]
@asosnoviy супер! значит, надо релизнуть парсер и бампнуть зависимость тут.

**Comment by nixel2007** [comment]
@asosnoviy парсер вроде последний сейчас торчит. пофикшено, значит?

**Comment by asosnoviy** [comment]
@nixel2007 лучше перепроверить =(

**Comment by nixel2007** [comment]
ты вроде проверял уже на мастере, так что будем считать, что пофикшено.
