### ISSUE TITLE
Пожелание: Генерировать Json-настройки из GUI сайта

### ISSUE THREAD

**Issue by EvilBeaver** [1c-syntax/bsl-language-server#1738]
Было бы прикольно в UI сайта на страничке диагностик иметь UI, позволяющий видеть описание параметров диагностик и натыркивать мышкой целевой json с настройками.

Конкретные сценарии могут быть разными, но смысл такой, что если ты видишь неточную диагностику, то где-то прямо в контексте можешь прочитать - какие у нее есть настроечные рукоятки и подергать за них

**Comment by nixel2007** [comment]
А автодополнение в vscode при редактировании json-файла настроек не закрывает эту задачу?

**Comment by nixel2007** [comment]
Ну и кусочек json уже есть на сайте

https://1c-syntax.github.io/bsl-language-server/diagnostics/CognitiveComplexity/

**Comment by nixel2007** [comment]
Или под gui ты имеешь ввиду IDE и что-то типа code action?

**Comment by EightM** [comment]
Может проще десктоп приложение /плагин к VS code?

**Comment by nixel2007** [comment]
> что если ты видишь неточную диагностику, то где-то прямо в контексте можешь прочитать

Ещё отмечу, что если нажать на имя диагностики в vscode, то откроется сайт с документацией по диагностике

**Comment by asosnoviy** [comment]
Имхо автокомплит вполне справляется и врядли найдется кто то, кто напилит генератор в мкдоке.

**Comment by EvilBeaver** [comment]
автокомплит понимает параметры у диагностик и их описание? Видимо, я как-то не так настроил, у меня не показывал.

**Comment by nixel2007** [comment]
@EvilBeaver у тебя вероятно файл называется нестандартно, поэтому автокомплит в всц не понимает, что ему надо автоматом применить схему.

если файл называется стандартно, то автокомлит работает без доп настроек:
![image](https://user-images.githubusercontent.com/1132840/126956470-90bc91e8-72db-447d-adbc-7e69d77173a9.png)
Если нестандартно, то тебе надо добавить в json указание, где искать схему:
```json
{
  "$schema": "https://1c-syntax.github.io/bsl-language-server/configuration/schema.json",
  "diagnostics": {
    ...
  }
}
```

**Comment by EvilBeaver** [comment]
Ок, попробую еще раз
