### ISSUE TITLE
[BUG] изменилось формирование URI-пути в файле с пробелом в имени

### ISSUE THREAD

**Issue by EvilBeaver** [1c-syntax/bsl-language-server#1739]
**Версия**
develop ветка, коммит 77b82644013a

**Описание ошибки диагностики**
Изменилось формирование URI в файле, имя которого содержит пробел.

На коммите 26736970fae0 формировалось иначе

**Скриншоты**

*Было:*

![image](https://user-images.githubusercontent.com/2657561/126896081-55e82fec-00dc-4dcf-9abb-451270baf4af.png)

*Стало:*

![image](https://user-images.githubusercontent.com/2657561/126896090-466dbb9d-b3e4-4b29-bfd9-8ad8636376d2.png)

**Дополнительная информация**

Отличия только в relatedInformation диагностик. Возможно, поменялось API в develop и сломались невлитые в develop фича ветки?

Проявляется на ветке https://github.com/1c-syntax/bsl-language-server/pull/1725

**Comment by nixel2007** [comment]
@EvilBeaver попробуй, пожалуйста, пересобрать свой bsl ls с зависимостью `1c-syntax:utils:5bd46dd1b6761ef7aa990f97a62bc0a63394ec08`
