### ISSUE TITLE
[FN] ExecuteExternalCode не срабатывает в общих модулях

### ISSUE THREAD

**Issue by vkostyanetsky** [1c-syntax/bsl-language-server#1763]
## Диагностика
ExecuteExternalCode

## Версия
Плагин 1.9.0 (0.18.1)

## Описание ложного НЕ срабатывания диагностики
Диагностика ExecuteExternalCode не срабатывает, если оператор Выполнить применяется в общих модулях.

## Пример кода
```
SetSafeMode(True);
	
Execute Formats[Field.Format];
```

## Скриншоты
![firefox_xoW2yQsMBU](https://user-images.githubusercontent.com/40140090/129834264-d4595647-59a7-4c13-b58b-ff546d6ae17c.png)

## Дополнительная информация
Нет принципиальной разницы, в контексте чего выполнится потенциально опасный код — общего модуля или, например, формы документа. В обоих случаях программист может начать, например, копаться в файлах на сервере.

Возможно, я не до конца понимаю контекст проблемы.

**Comment by asosnoviy** [comment]
![image](https://user-images.githubusercontent.com/15638529/129842327-2b2cf376-1b10-48a9-8fae-cd0359921cd4.png)

**Comment by theshadowco** [comment]
https://1c-syntax.github.io/bsl-language-server/diagnostics/ExecuteExternalCodeInCommonModule/
https://1c-syntax.github.io/bsl-language-server/diagnostics/ExecuteExternalCode/

**Comment by nixel2007** [comment]
Разные типы проверок и разное время на исправление

**Comment by vkostyanetsky** [comment]
Ясно, спасибо!
