### ISSUE TITLE
[NEW] После вызова асинхронного метода есть строки кода

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1782]
## Описание проблемы, ошибки, которую надо диагностировать

При использовании асинхронных методов разработчики иногда ошибаются, написав код таким образом, что сразу после вызова асинхронного метода следуют строки кода. В этом случае указанные строки кода выполняются немедленно, без ожидания выполнения асинхронного метода.

Неверный код
```bsl
&НаКлиенте
Процедура Команда1(Команда)
    ДополнительныеПараметры = Новый Структура("Результат", 10);
    Оповещение = Новый ОписаниеОповещения("ПослеВводаКоличества", ЭтотОбъект);
    ПоказатьВводЧисла(Оповещение, 1, "Введите количество", ДополнительныеПараметры.Результат, 2);

    Сообщить("Введенное количество равно " + ДополнительныеПараметры.Результат); // неверно, т.к. всегда будет 10
КонецПроцедуры

&НаКлиенте
Процедура ПослеВводаКоличества(Число, ДополнительныеПараметры) Экспорт
    Если Число <> Неопределено Тогда
         ДополнительныеПараметры.Результат = Число;
    КонецЕсли;
КонецПроцедуры;
```

Правильное решение - вынести весь код, который должен быть выполнен после выполнения асинхронного действия, в экспортный метод и указать его имя в обработке оповещения, которая будет вызвана после завершения асинхронного действия.
Или использовать асинхронность через обещания, например, `Ждать ПредупреждениеАсинх(Текст);`

Правильный код
```bsl
&НаКлиенте
Процедура Команда1(Команда)
    ДополнительныеПараметры = Новый Структура("Результат", 10);
    Оповещение = Новый ОписаниеОповещения("ПослеВводаКоличества", ЭтотОбъект);
    ПоказатьВводЧисла(Оповещение, 1, "Введите количество", ДополнительныеПараметры.Результат, 2);

КонецПроцедуры

&НаКлиенте
Процедура ПослеВводаКоличества(Число, ДополнительныеПараметры) Экспорт
    Если Число <> Неопределено Тогда
        ДополнительныеПараметры.Результат = Число;
        Сообщить("Введенное количество равно " + ДополнительныеПараметры.Результат); // неверно, т.к. всегда будет 10
    КонецЕсли;
КонецПроцедуры;
```

В некоторых случаях выполнение кода сразу после вызова асинхронного метода вполне возможно, если не нужно ожидать результатов выполнения асинхронного действия.
Например
```bsl
&НаКлиенте
Процедура Команда1(Команда)
	ПоказатьПредупреждение(, "Предупреждаю", 10);
	Сообщить("начал работать код после ПоказатьПредупреждение");
    // ...
КонецПроцедуры
```

Также важно учесть, что асинхронный метод может вызываться в одной из веток кода и нужно анализировать последующий код до конца текущей процедуры\функции.
Пример:
```bsl
&НаКлиенте
Процедура Команда1(Команда)
    ДополнительныеПараметры = Новый Структура("Результат", 10);
    Если Условие Тогда
        Оповещение = Новый ОписаниеОповещения("ПослеВводаКоличества", ЭтотОбъект);
        ПоказатьВводЧисла(Оповещение, 1, "Введите количество", ДополнительныеПараметры.Результат, 2);
    Иначе
        // какой-то код
    КонецЕсли;
    // последующий код также может вызываться сразу после вызова асинхронного метода, что может быть неверно

    Сообщить("Введенное количество равно " + ДополнительныеПараметры.Результат); // неверно, т.к. всегда будет 10
КонецПроцедуры
```

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

- [Синхронные и асинхронные методы работы - Руководство разработчика Глава 4. Встроенный язык](https://its.1c.ru/db/v8319doc#bookmark:dev:TI000001505)
- [Длительные операции на клиенте - ИТС 1С](https://its.1c.ru/db/v8std#content:755:hdoc)
- [Длительные операции на сервере - ИТС 1С](https://its.1c.ru/db/v8std#content:642:hdoc)
  
### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [x] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

10 минут

## Дополнительная информация

Т.к. наличие кода сразу после вызова асинхронного метода не всегда является ошибкой, не ставлю признак ошибки у замечания.
Но из собственного опыта знаю, что наличие такого кода говорит о проблемах, особенно у начинающих разработчиков, поэтому предлагаю использовать критическую важность.

**Comment by artbear** [comment]
И реализация вроде бы простая 
- найти вызов любой предопределенного асинхронного метода
- и проверить, если после вызова этого метода хотя бы одна строка с каким-нибудь выражением.

good first - @theshadowco @nixel2007 ?

**Comment by artbear** [comment]
Список асинхронных методов можно взять из #46 и #336 и #337

**Comment by asosnoviy** [comment]
Плохая диагностика.

**Comment by asosnoviy** [comment]
@artbear если тебе такое надо и ты будешь реализовывать, не забудь выключить по умолчанию. В противном случае закрывай ишуз.

**Comment by artbear** [comment]
Поставьте тикет на меня, я сделаю.
правило будет выключено по умолчанию.
