### ISSUE TITLE
[FN] IncorrectUseOfStrTemplate

### ISSUE THREAD

**Issue by EightM** [1c-syntax/bsl-language-server#1787]
## Диагностика

IncorrectUseOfStrTemplate
## Версия

0.18.1
## Пример кода

```
Процедура Тест()
    СтрШаблон("%1, %2, %3, %4, %5, %6, %7, %8, %9, %10, %11", "ф", "ф", "ф", "ф", "ф", "ф", "ф", "ф", "Ф", "");
КонецПроцедуры
```

**Comment by nixel2007** [comment]
а в чем FN? десять параметров, девять значений, запятая подчеркнута...

**Comment by EightM** [comment]
Упс. Не знал, что будет автоматом передано неопределено

**Comment by EightM** [comment]
изменил кейс, на него точно должно ругаться

**Comment by artbear** [comment]
Значит, нужно выдавать замечание при наличии в шаблонной строке параметра %Число, где Число больше 10

**Comment by artbear** [comment]
Исправлено в ПР
