### ISSUE TITLE
Автоформатер / форматирование отступов знака "-"

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#179]
Изначальная строка:
```bsl
#Использовать xml-parser
```

После автоформатирования:
![image](https://user-images.githubusercontent.com/11651847/58792677-d7d96400-861e-11e9-84b5-da383a3017ec.png)

**Comment by asosnoviy** [comment]
Хе, а у нас парсер похоже не разбирает `#Использовать xml-parser`
