### ISSUE TITLE
[FP] Срабатывает IncorrectLineBreak в комментарии

### ISSUE THREAD

**Issue by vbondarevsky** [1c-syntax/bsl-language-server#1805]
## Диагностика
IncorrectLineBreak

## Описание ложного срабатывания диагностики
Срабатывает "Проверьте правильность переноса операндов, операторов и параметров" в комментарии (текст лицензии). И это даже не закомментированный код

## Пример кода
https://sonar.openbsl.ru/project/issues?id=connector&issues=AXopqazjlPnNfWNZd3zl&open=AXopqazjlPnNfWNZd3zl

## Скриншоты
![image](https://user-images.githubusercontent.com/11818792/132917210-4b7e7fee-9332-4fc0-aaa6-1a03505b6edf.png)

**Comment by nixel2007** [comment]
Исправлено в 0.19.0
