### ISSUE TITLE
[BUG] Сонар. Использование 'ПОДОБНО' в запросе

### ISSUE THREAD

**Issue by LazarenkoA** [1c-syntax/bsl-language-server#1815]
## Диагностика
Использование 'ПОДОБНО' в запросе

## Версия
1.9.0

## Описание ошибки диагностики
по факту в запросе написано так же как в описании к диагностике, но все равно диагностика считает, что это ошибка 

## Пример кода
<details><summary>Код</summary>
<pre>

Функция ПолучитьСотрудников(ИнформационнаяБаза, Абонент = Неопределено, АбонентВидСравнения = "=", 
							ЗаписьВРегистр = Ложь, СписокСотрудников = Неопределено) Экспорт
	
	Если ЗначениеЗаполнено(СписокСотрудников) Тогда
		Если НЕ ТипЗнч(СписокСотрудников) = Тип("Массив") Тогда
			ВызватьИсключение "Не верное значение параметра ""СписокСотрудников""";
		КонецЕсли;
		Запрос = Новый Запрос;
		Запрос.Текст = "ВЫБРАТЬ
		|	PTG_СоответствиеПользователейИСотрудников.ИдентификаторСотрудника КАК ИдентификаторСотрудника,
		|	МАКСИМУМ(PTG_СоответствиеПользователейИСотрудников.ФИО) КАК ФИО,
		|	PTG_СоответствиеПользователейИСотрудников.ОбластьДанных.Код КАК ОбластьДанных,
		|	PTG_СоответствиеПользователейИСотрудников.ОбластьДанных.Владелец КАК ИнформационнаяБаза
		|ИЗ
		|	РегистрСведений.PTG_СоответствиеПользователейИСотрудников КАК PTG_СоответствиеПользователейИСотрудников
		|ГДЕ
		|	PTG_СоответствиеПользователейИСотрудников.ИдентификаторСотрудника В(&ИдентификаторыСотрудников)
		|
		|СГРУППИРОВАТЬ ПО
		|	PTG_СоответствиеПользователейИСотрудников.ИдентификаторСотрудника,
		|	PTG_СоответствиеПользователейИСотрудников.ОбластьДанных.Код,
		|	PTG_СоответствиеПользователейИСотрудников.ОбластьДанных.Владелец
		|ИТОГИ ПО
		|	ИнформационнаяБаза,
		|	ОбластьДанных";
		Запрос.УстановитьПараметр("ИдентификаторыСотрудников", СписокСотрудников);
	Иначе
		Запрос = Новый Запрос;
		Запрос.Текст = 
		"ВЫБРАТЬ РАЗЛИЧНЫЕ 
		|	ОбластиДанных.Владелец КАК ИнформационнаяБаза,
		|	ОбластиДанных.Код КАК ОбластьДанных
		|ИЗ
		|	Справочник.ОбластиДанных КАК ОбластиДанных
		|ГДЕ 
		|	Состояние = Значение(Перечисление.СостоянияОбластейДанных.Используется)
		|	И ОбластиДанных.Владелец.ВерсияКонфигурации.Владелец.Имя ПОДОБНО ""ЗарплатаИКадры%""";
		
		Если ЗначениеЗаполнено(ИнформационнаяБаза) Тогда 
			
			Если ТипЗнч(ИнформационнаяБаза) <> Тип("СправочникСсылка.ИнформационныеБазы") Тогда
				ВызватьИсключение "Не верное значение параметра ""ИнформационнаяБаза""";
			КонецЕсли;	
			
			Запрос.Текст = Запрос.Текст + " И ОбластиДанных.Владелец = &ИнформационнаяБаза";
			Запрос.УстановитьПараметр("ИнформационнаяБаза", ИнформационнаяБаза);
		КонецЕсли;	
		Если ЗначениеЗаполнено(Абонент) Тогда 
			
			Если ТипЗнч(Абонент) <> Тип("СправочникСсылка.Абоненты")
				И ТипЗнч(Абонент) <> Тип("СписокЗначений") Тогда
				ВызватьИсключение "Не верное значение параметра ""Абонент""";
			КонецЕсли;	
			
			Запрос.Текст = Запрос.Текст + " И ОбластиДанных.Абонент " + АбонентВидСравнения + " (&Абонент)";
			Запрос.УстановитьПараметр("Абонент", Абонент);
		КонецЕсли;	
		Запрос.Текст = Запрос.Текст + " 
		|ИТОГИ ПО ИнформационнаяБаза";
		
	КонецЕсли;
	
	ТабРезультат = СоздатьТаблицуСотрудников();	
	ТабДанных = СоздатьТаблицуСотрудников();	
	
	УстановитьПривилегированныйРежим(Истина);
	Выборка = Запрос.Выполнить().Выбрать(ОбходРезультатаЗапроса.ПоГруппировкам);
	УстановитьПривилегированныйРежим(Ложь);
	МассивЗаданий = Новый Массив;
	МассивКлючейОбъектов = Новый Массив;
	ЧислоПараллельныхПотоков = 10;
	МассивОбластей = Новый Массив;
	ДанныеСотрудников = Новый Массив;
	Пока Выборка.Следующий() Цикл
		
		КлючОбъекта = Строка(Новый УникальныйИдентификатор()); 
		
		СтруктураПараметров = Новый Структура("dataareas, employees", "", "");
		Если ЗначениеЗаполнено(Абонент) ИЛИ ЗначениеЗаполнено(СписокСотрудников) Тогда
			ВыборкаОбласти = Выборка.Выбрать(ОбходРезультатаЗапроса.ПоГруппировкам);
			Пока ВыборкаОбласти.Следующий() Цикл
				СтруктураОбласть = Новый Структура("dataarea, data",Формат(ВыборкаОбласти.ОбластьДанных, "ЧГ="));
				СтруктураПараметров.dataareas = СтруктураПараметров.dataareas + "," + Формат(ВыборкаОбласти.ОбластьДанных, "ЧГ=");
				Если НЕ ЗначениеЗаполнено(СписокСотрудников) Тогда
					Продолжить;
				КонецЕсли;
				ВыборкаСотрудники = ВыборкаОбласти.Выбрать();
				Пока ВыборкаСотрудники.Следующий() Цикл
					 СтруктураПараметров.employees = СтруктураПараметров.employees + "," + 
							Формат(ВыборкаСотрудники.ИдентификаторСотрудника, "ЧГ=");
					СтруктураСотр = Новый Структура();
					СтруктураСотр.Вставить("id", Формат(ВыборкаСотрудники.ИдентификаторСотрудника, "ЧГ="));
					СтруктураСотр.Вставить("fio", ВыборкаСотрудники.ФИО);
					ДанныеСотрудников.Добавить(СтруктураСотр);
				КонецЦикла;
				СтруктураОбласть.data = ДанныеСотрудников;
				МассивОбластей.Добавить(СтруктураОбласть);
			КонецЦикла;
		КонецЕсли;
		СтруктураПараметров.employees = Прав(СтруктураПараметров.employees,СтрДлина(СтруктураПараметров.employees)-1);
		СтруктураПараметров.dataareas = Прав(СтруктураПараметров.dataareas,СтрДлина(СтруктураПараметров.dataareas)-1);

		ДанныеЗапоса = PTG_ExchangeСервер.ДанныеВ_JSON(МассивОбластей);
		МассивКлючейОбъектов.Добавить(КлючОбъекта);
		ПараметрыМетода = Новый Массив();
		ПараметрыМетода.Добавить(Выборка.ИнформационнаяБаза);
		ПараметрыМетода.Добавить(КлючОбъекта);
		ПараметрыМетода.Добавить(ЗаписьВРегистр);
		ПараметрыМетода.Добавить(ДанныеЗапоса);

		ИБСтрока = Строка(Выборка.ИнформационнаяБаза); 
		Задание = ФоновыеЗадания.Выполнить("PTG_РаботаСПользователямиИСотрудниками.ФоновоеПолучениеСотрудников", 
											ПараметрыМетода, ИБСтрока);
		
		МассивЗаданий.Добавить(Задание);
		
		Если МассивЗаданий.Количество() >= ЧислоПараллельныхПотоков Тогда
			PTG_ExchangeСервер.ОбработатьМассивФоновыхЗаданий(МассивЗаданий, Истина);
		КонецЕсли;

	КонецЦикла;	
	
	Пока МассивЗаданий.Количество() > 0 Цикл
		PTG_ExchangeСервер.ОбработатьМассивФоновыхЗаданий(МассивЗаданий, Истина);
	КонецЦикла;
	
	Если ЗаписьВРегистр Тогда
		Возврат Неопределено;
	КонецЕсли;
	
	УстановитьПривилегированныйРежим(Истина);
	ВыборкаНастройки = ХранилищеОбщихНастроек.Выбрать(Новый Структура("КлючНастроек", 
														"РезультатФоновогоЗаданияДанныеСотрудников"));
	УстановитьПривилегированныйРежим(Ложь);	
	
	Пока ВыборкаНастройки.Следующий() Цикл
		
		Если МассивКлючейОбъектов.Найти(ВыборкаНастройки.КлючОбъекта) = Неопределено Тогда
			Продолжить;
		КонецЕсли;
				
		ТабРезультат = ДобавитьСтрокиВТаблицу(ТабРезультат, ВыборкаНастройки.Настройки.СписокСотрудников);
		ТабДанных = ДобавитьСтрокиВТаблицу(ТабДанных, ВыборкаНастройки.Настройки.ДанныеСотрудников);
		
	КонецЦикла;	
	
	УдалитьДанныеИзХранилица("РезультатФоновогоЗаданияДанныеСотрудников",МассивКлючейОбъектов);
	Возврат Новый Структура("ТаблицаСотрудников, ДанныеСотрудников", ТабРезультат, ТабДанных);
	
КонецФункции

</pre>
</details>

## Скриншоты
![image](https://user-images.githubusercontent.com/15386101/133270985-03846bfa-7782-405b-88d7-7cc21ffd6cb9.png)

**Comment by artbear** [comment]
@LazarenkoA Есть 2 диагностики.
- UsingLikeInQueryDiagnostic - использование ПОДОБНО
- IncorrectUseLikeInQueryDiagnostic - неправильное использование ПОДОБНО

ПР https://github.com/1c-syntax/bsl-language-server/pull/1596

первая диагностика выдает замечания на ЛЮБОЕ использование подобно в запросе.
у тебя сработало именно это правило.

фактически это правило для доп.контроля написания ПОДОБНО и может выдавать ложные срабатывания.

можешь его отключить и использовать только второе.

ишуз предлагаю закрыть как неточный.

**Comment by nixel2007** [comment]
Да, действительно. Причём эта диагностика по умолчанию выключена, то есть ты её явно включил.
Закрываю тогда.
