### ISSUE TITLE
Неразрывный пробел в строке

### ISSUE THREAD

**Issue by Iscarimet** [1c-syntax/bsl-language-server#186]
Регистрировать наличие неразрывного пробела в строке как ошибку.
Расширенная проверка EDT не может корректно обработать такую строку, и выдаёт кучу не связанных ошибок на все элементы строки.

**Comment by nixel2007** [comment]
https://t.me/edt1c/10518

**Comment by theshadowco** [comment]
Подразумевается просто наличие в модуле символа НПП или где-то конкретно?

**Comment by Iscarimet** [comment]
Просто наличие в модуле неразрывного пробела ломает все диагностики модуля начиная с этой строки.
Вот краткое обсуждение в чате EDT:
![image](https://user-images.githubusercontent.com/38294225/67639005-9ec2c880-f90c-11e9-92db-ff021e47dd4f.png)

**Comment by theshadowco** [comment]
прикольно, не сталкивался.

**Comment by nixel2007** [comment]
Вообще это хорошо бы на партнерку зарепортить...
