### ISSUE TITLE
[MOD] SeveralCompilerDirectives

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#1863]
## Диагностика

SeveralCompilerDirectives
## Описание предлагаемых изменений

В продолжение https://github.com/1c-syntax/bsl-language-server/issues/1115
Нужно исправить код правила, чтобы использовать информацию о директиве компиляции в MethodSymbol вместо поиска ноды директивы компиляции 
- индекс BSLParser.RULE_compilerDirective

**Comment by theshadowco** [comment]
@artbear 
Там сейчас как раз корректно - используется проверка на директиву в символе метода и по дереву смотрится, что их несколько. в символе - только одна.

**Comment by asosnoviy** [comment]
@nixel2007 выдай вердикт плз.

**Comment by nixel2007** [comment]
@asosnoviy а в аннотации оставшиеся директивы не сваливаются? Если нет, то думаю, можно закрыть.
