### ISSUE TITLE
Выполнить в безопасном режиме

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#188]
https://its.1c.ru/db/v8std/content/770/hdoc

**Comment by qtLex** [comment]
Покрывается диагностиками [Выполнение произвольного кода на сервере](https://1c-syntax.github.io/bsl-language-server/diagnostics/ExecuteExternalCode) и [Выполнение произвольного кода в общем модуле на сервере](https://1c-syntax.github.io/bsl-language-server/diagnostics/ExecuteExternalCodeInCommonModule). Можно закрыть.
