### ISSUE TITLE
[FP] MissingParameterDescription при экранировании проверки EDT

### ISSUE THREAD

**Issue by Daabramov** [1c-syntax/bsl-language-server#1912]
## Диагностика
`MissingParameterDescription `

## Версия
1.10.0 (sonar bsl plugin)

## Описание ложного срабатывания диагностики
При экранировании проверки EDT спец комментарием `@skip-check {КодДиагностики}` проверка думает, что я написал комментарий описания функции или процедуры, поэтому выполняет проверку `MissingParameterDescription `, хотя по сути не должна

## Пример кода

В данном случае элемент, к которому привязан этот обработчик добавлен программно, для экранировании ошибки неиспользуемого метода добавлен служебный комментарий.

```
// @skip-check module-unused-method
&НаКлиенте
Процедура бф_СуммаВалютнаяПриИзменении(Элемент)
	Если Не ЗначениеЗаполнено(Объект.бф_ВалютаВзаиморасчетов) Или Не ЗначениеЗаполнено(Объект.бф_ДатаРасчета) Тогда
		Возврат;
	КонецЕсли;
	бф_ПересчетРублевойСуммы();
КонецПроцедуры
```

## Скриншоты
![image](https://user-images.githubusercontent.com/31928832/142741153-3f656e0b-6b16-4596-afb3-4e3d645e112f.png)

## Дополнительная информация
-

**Comment by theshadowco** [comment]
Это не FP. Комментирующие теги от сторонних анализаторов никак не поддерживаются. 
Если есть желание поддерживать - то нужна отдельная ишуза по добавлению возможности в ядро. Эту закрываю
