### ISSUE TITLE
[MOD] UnknownPreprocessorSymbol: МобильныйАвтономныйСервер не ошибка 

### ISSUE THREAD

**Issue by Kyrales** [1c-syntax/bsl-language-server#1913]
## Диагностика
UnknownPreprocessorSymbol

## Описание предлагаемых изменений

МобильныйАвтономныйСервер  это не ошибка, а реально существующий операнд.

![image](https://user-images.githubusercontent.com/79920318/142758056-0a056c74-cf03-4b42-b872-5ebf7981969f.png)

**Comment by nixel2007** [comment]
Эта директива была недавно добавлена в бсл парсер. При его обновлении поправится и здесь.
Спасибо за репорт!
