### ISSUE TITLE
[FP] CommentedCode Ложное срабатывание на исправленный код в типовом блоке кода

### ISSUE THREAD

**Issue by Kyrales** [1c-syntax/bsl-language-server#1920]
## Диагностика
CommentedCode

## Версия
0.19.1

## Описание ложного срабатывания диагностики
Разработчик закомментировал типовой код и внес изменения своим кодом. Как быть с такими случаями? Или эта проверка для изменяемого типового не подходит?

## Пример кода
![image](https://user-images.githubusercontent.com/79920318/143377109-227f8383-e7e2-4d58-a8ab-8353ef86c550.png)

**Comment by nixel2007** [comment]
Не комментировать типовой код, а использовать инструменты трехстороннего сравнения в конфигураторе (типа kdiff3) и/или git :)

**Comment by theshadowco** [comment]
А где ложное срабатывание то? Код закомментирован, так делать нельзя - диагностика ругается.

**Comment by Kyrales** [comment]
В типовых конфигурациях которые изменяем, обычно комментируем старый код 1С и ставим свой новый код.

**Comment by theshadowco** [comment]
а так - поддержку Никиту: не оставляйте закомментированный код

**Comment by Kyrales** [comment]
@nixel2007 @theshadowco  Коллеги, правильно я понимаю что вы в своих решениях при изменении типового кода никаких комментариев не оставляете?

**Comment by theshadowco** [comment]
да

**Comment by theshadowco** [comment]
при разработке с использованием систем контроля версий отсутсвует необходимость в данном рудименте

**Comment by Kyrales** [comment]
@theshadowco при обновлении типовых на новые редакции вы не используете стандартный инструмент обновления в 1С?

**Comment by nixel2007** [comment]
@Kyrales его можно продолжать использовать. просто нет необходимости иметь старый закомментированный код, если сравнивать модули в режиме трех-стороннего сравнения через "внешнюю утилиту сравнения" (настраивается в конфигураторе). тогда и так видно, где старый код поставщика, где новый код поставщика, а где измененный код из основной конфигурации.

**Comment by asosnoviy** [comment]
имхо достаточно в швлон комментирования добавить подавляющий срабатывание тег. Тогда вам не придется отказываться от привычного процесса и не ловить ложные, с вашей точки зрения замечания

**Comment by EightM** [comment]
С точки зрения 1С совместимо это тоже ложные срабатывания)
