### ISSUE TITLE
[FP] Игнорировать ошибку на вложенность НСтр(). Например: СтрШаблон(Нстр(...), ...)

### ISSUE THREAD

**Issue by Kyrales** [1c-syntax/bsl-language-server#1923]
## Диагностика
NestedFunctionInParameters

## Версия
Актуальная на 28.11.2021

## Описание ложного срабатывания диагностики

Игнорировать вложенность НСтр(). Например: СтрШаблон(НСтр(...), ...)

## Пример кода
СтрШаблон(НСтр(...), ...)

НСтр не имеет смысла разделять. Популярная конструкция.

**Comment by theshadowco** [comment]
А на каком примере сработало?

**Comment by Kyrales** [comment]
Пример подобного : 
![image](https://user-images.githubusercontent.com/79920318/144069827-81b8a7da-4bbc-4f59-bfc7-9eef35ced4f8.png)

**Comment by Kyrales** [comment]
В БСП:
![MicrosoftTeams-image (23)](https://user-images.githubusercontent.com/79920318/144400644-67f33a19-993b-4bb3-a786-8d6006febf17.png)

**Comment by Kyrales** [comment]
Как вариант можно дополнить параметром, в котором задавать исключения вложенных функций. Например для данного примера задал бы "НСтр" как исключение, которое не нужно проверять на вложенность.

**Comment by asosnoviy** [comment]
Своего мнения не имею т.к. не занимаюсь локализацией вообще.
Смотрю стандарт п.7 https://its.1c.ru/db/v8std/content/761/hdoc 
там есть пример подобного такого кейса:
```bsl
ТекстСообщения = НСтр("ru = 'Не удалось сохранить файл документа по причине:'")
  + Символы.ПС + ИнформацияОбОшибке
```

п.с. добавление исключений может оказаться нетривиальной задачей
