### ISSUE TITLE
[FP] Отсутствует описание возвращаемого значения функции не полностью отрабатывается проверка

### ISSUE THREAD

**Issue by Kyrales** [1c-syntax/bsl-language-server#1927]
## Диагностика
MissingReturnedValueDescription

## Версия
v0.20.0-ra.2

## Описание ложного срабатывания диагностики

Если у возвращаемого значения нет описания, а только указан тип, то будет ложное срабатывание.
По стандарту выделенные варианты не должны быть ошибкой:
![image](https://user-images.githubusercontent.com/79920318/144746508-af363665-9308-4c8c-aefe-a313d2669cfc.png)

## Скриншоты
![image](https://user-images.githubusercontent.com/79920318/144746476-bfa4de79-2bf5-45e4-af15-961cff06800c.png)

**Comment by theshadowco** [comment]
В принципе можно добавить параметр либо по умолчанию разрешить данное написание

**Comment by Kyrales** [comment]
@theshadowco лучше по умолчанию разрешить данное написание, как в трактовке стандарта.

**Comment by nixel2007** [comment]
Параметр все равно соиит добавить.

**Comment by aleksandr-ermakov** [comment]
Кстати, возникает вопрос:
У этой диагностики важность = Важный, что означает, кхм, 
> Неправильно работающая ключевая бизнес-логика, дыры в системе безопасности, проблемы, приводящие к временной неработоспособности приложения или его компонент.

Так у всех по умолчанию?

**Comment by nixel2007** [comment]
Хм, а откуда этот текст?

https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity/

Здесь другая формулировка

**Comment by aleksandr-ermakov** [comment]
Пардон, не с того абзаца содрал.
Вот правильная формулировка:
> Часть основной бизнес-логики работает некорректно, но есть обходные пути либо низкокачественный код, приводящий к проблемам производительности, эффективности, плавающим ошибкам. Используется только для Ошибок и Дефектов кода.

Всё ещё плохо стыкуется с любой диагностикой комментария к процедуре.
