### ISSUE TITLE
Использование ПредопределнноеЗначение() на сервере

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#221]
Где то когда то натыкался (толи в недрах ИТС толи в АПК) на запрет использования ПредопределнноеЗначение() на сервере. Пруфа найти не могу. Сам обжигался на багах платформы когда иногда

```BSL
ПредопределенноеЗначение(Перечисление.КакоетоПеречисление.Значение) <> Перечисление.КакоетоПеречисление.Значение`

**Comment by asosnoviy** [comment]
Использована функция ПредопределенноеЗначение() в условиях, когда доступны менеджеры прикладных объектов.  Обязательно к исполнению.

 2.5.12. Функция глобального контекста ПредопределенноеЗначение() не должна применяться  2.5.12. Функция глобального контекста ПредопределенноеЗначение() не должна применяться в тех условиях, когда доступны менеджеры прикладных объектов, вне кода тонкого или Web-клиента, т.е. в модулях объектов, наборов записей, общих модулях, для которых не установлен флаг компиляции на тонком клиенте, серверных процедурах и функциях модулей форм и т.д. Для указанных выше модулей обращение к предопределенным значениям должно выполняться через менеджер соответствующего объекта.

**Comment by asosnoviy** [comment]
https://t.me/bsl_language_server/7912

**Comment by yukon39** [comment]
Есть древняя (2012) тема на [партнерке](https://partners.v8.1c.ru/forum/topic/1058755) где:
1. Требование чисто стилистическое
2. Обещали (угу, 7 лет назад) пересмотреть требование.

**Comment by asosnoviy** [comment]
Оно в АПК в разделе прежние. Похоже отменили.
