### ISSUE TITLE
Работа в разных часовых поясах

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#222]
http://its.1c.ru/db/translate/?db=v8std&path=src/d810/i8100643.htm

ИЗ АПК
1.Проверить серверные процедуры и функции на использование функции ТекущаяДата(), вместо нее должна использоваться функция ТекущаяДатаСеанса()
2.Проверить клиентский код на использование функции ТекущаяДата(). Функция должна использоваться при передаче с сервера на клиент время и даты, приведенных к часовому поясу пользовательского сеанса. При работе с документами на клиенте, использовать дату документа.

**Comment by Stepa86** [comment]
Если в кратце, то нельзя использовать теперь ТекущаяДата(). Сам напоролся на подобную ошибку. Было больно.

**Comment by asosnoviy** [comment]
С серверными понятно, с клиентскими не совсем. Ну и все та же проблема определения типа модуля

**Comment by zeegin** [comment]
@asosnoviy Так в общем случае все просто, не использовать `ТекущаяДата` вообще никогда.
Использовать `ТекущаяДатаСеанса` на сервере или `ОбщегоНазначенияКлиент.ДатаСеанса` на клиенте.

Кстати, а проверку наличия БСП для таких методов вообще как-то делается? Если БСП нет как проверять?
