### ISSUE TITLE
[FP] NestedConstructorsInStructureDeclaration

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#224]
```BSL
Новый Структура("Константы,Объекты,НаборыЗаписей", Новый Массив(), Новый Массив(), Новый Массив());
```

**Comment by asosnoviy** [comment]
Тут не уверен надо пообсуждать.
```
Новый Структура(Новый ФиксированнаяСтруктура(ПараметрыПланирования));
```
```
Новый ФиксированнаяСтруктура(Новый Структура("Источник, Данные"));
```
Имхо вполне валидные конструкторы

**Comment by lChagelishvili** [comment]
А это вообще нормальная ситуация, что callParam() возвращает не пустой массив для Новый Массив()?

**Comment by asosnoviy** [comment]
Оказалось там  () лежат =(

**Comment by asosnoviy** [comment]
а вообще странно `doCall           : LPAREN callParamList RPAREN;`

**Comment by asosnoviy** [comment]
А не. Наверно это странно и можно подумать.

doCall : LPAREN callParamList RPAREN;
callParamList    : callParam (COMMA callParam)*;
callParam        : expression?;
expression       : member (preprocessor* operation preprocessor* member)*;

и похоже мачится мембер 
member           : unaryModifier? (constValue | complexIdentifier | ( LPAREN expression RPAREN ));

**Comment by asosnoviy** [comment]
Коллекция FP
`Новый Структура(Новый ФиксированнаяСтруктура(Мок_ПараметрыПроцедуры));`

**Comment by qtLex** [comment]
Забрал. Если никто не против
