### ISSUE TITLE
[FP] UnusedLocalVariable Срабатывает на любую переменную которая содержит заполняемый элемент коллекции

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#2287]
## Диагностика
UnusedLocalVariable

## Версия
v0.20.0-rc.1

## Описание ложного срабатывания диагностики
Срабатывает на любую переменную которая содержит заполняемый элемент коллекции (СтрокаТабличнойЧасти, СтрокаТаблицыЗначений, ЭлементБлокировки и т.д и т.п)

## Пример кода
```bsl
	НоваяСтрока                = ГруппаДоступа.ВидыДоступа.Добавить();
	НоваяСтрока.ВидДоступа     = СтрокаВидаДоступа.ВидДоступа;
	НоваяСтрока.ДоступРазрешен = СтрокаВидаДоступа.ДоступРазрешен;
```

## Скриншоты
![image](https://user-images.githubusercontent.com/32082417/148000180-76e8f95d-45b7-468f-af42-a26c05c75dbf.png)

**Comment by qtLex** [comment]
Начал смотреть
