### ISSUE TITLE
Уточнение позиционирования ParseError

### ISSUE THREAD

**Issue by aleksandr-ermakov** [1c-syntax/bsl-language-server#242]
- Неверная отработка Функция ... Возврат ... КонецФункции
- Неверная обработка Для каждого ... Из ... Цикл

<a href="http://joxi.ru/vAWz3k9TgDYkL2" target="_blank"><img src="http://dl4.joxi.net/drive/2019/06/24/0027/1778/1808114/14/96d5810d0c.png"></a>

Версия BSL: 1.15.0
VSC Version: 1.35.1 (system setup)

Сам код:
```1c-enterprise
Функция ИмяФункции(Знач КакаятоСтруктура)

	ВозвратноеЗначение = Новый ТаблицаЗначений;

	КакойтоМассив = Новый Массив;

	Для ЭлементСтруктуры Из КакаятоСтруктура Цикл
		Если КакойтоМассив.Найти(ЭлементСтруктуры.Значение) = Неопределено Тогда
			КакойтоМассив.Добавить(ЭлементСтруктуры.Значение);
		КонецЕсли;
	КонецЦикла;

	Возврат ВозвратноеЗначение;

КонецФункции // ИмяФункции()
```

**Comment by nixel2007** [comment]
let's move it to another place!
:shipit:

**Comment by nixel2007** [comment]
@aleksandr-ermakov точность диагностики постараемся поправить.

А так - добавьте себе пропущенное ключевое слово и ошибка пропадет :)

**Comment by aleksandr-ermakov** [comment]
@nixel2007 Пропущенное слово - само-собой, но результат проверки всё равно выглядит забавно.

**Comment by Stepa86** [comment]
Бывает 2 типа циклов Для
`Для каждого <Имя переменной 1> Из <Имя переменной 2> Цикл`
и
`Для <Имя переменной> = <Выражение 1> По <Выражение 2> Цикл`

Ругаемся на отсутствие `каждого`, если есть `из`, и ругаемся на отсутствие `=` при наличии `По`

**Comment by asosnoviy** [comment]
Там как бы не мы ругаемся, ругается парсер. Мы только пытаемся показать это внятно.

**Comment by Stepa86** [comment]
Передайте парсеру, что если после `Для` нет `каждого`, то должно быть `По` и можно ругаться на `По`, а не на конец функции

**Comment by nixel2007** [comment]
Пш-пшшш, парсер, ответьте, пшшшш, как слышно? пшшшшшшшшшшшшшшшшш

**Comment by asosnoviy** [comment]
Информации стало больше 
![image](https://user-images.githubusercontent.com/15638529/79437279-a40af100-7fda-11ea-9a5a-954b8833a6e5.png)

@aleksandr-ermakov так лучше?

**Comment by aleksandr-ermakov** [comment]
@asosnoviy , значительно понятнее.
