### ISSUE TITLE
FP EmptyStatements при ошибке разбора

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#243]
```BSL
Для Каждого ЭлементСтруктуры Из КакаятоСтруктура Цикл
	КонецЕсли;
КонецЦикла;

```

![image](https://user-images.githubusercontent.com/15638529/60000852-b4c63100-966d-11e9-8516-9ecc451c3a7e.png)

**Comment by theshadowco** [comment]
Ошибка еще повторяется?

**Comment by theshadowco** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5c3ed2ac92682f000f20d6a6/attachments/5da6cb89401a08000f7cf1be)

**Comment by theshadowco** [comment]
у меня нормально, без fp

**Comment by theshadowco** [comment]
Отбой, повторил

**Comment by theshadowco** [comment]
Нашел логическую ошибку в trees
