### ISSUE TITLE
Пропущенные пробелы

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#244]
```bsl
Метод(Параметр,Параметр2);
А=А+1;
```

**Comment by YanSergey** [comment]
Возьму себе в разработку

**Comment by YanSergey** [comment]
Вроде норм так
```bsl
// Комментарий,комментарий		// 0

Процедура Метод1(Парам1, Парам2)	// 0
	Перем А1,Б1;А1=Б1+ 1;		// 4

	// Рез1=Парам1+Парам2;		// 0
	Рез1=Парам1+Парам2;		// 2
	Рез1=Парам1- Парам2;		// 2
	Рез1=Парам1 + Парам2;		// 1
	Рез1 =Парам1* Парам2;		// 2
	Рез1 =Парам1 /Парам2;		// 2
	Рез1 = Парам1 + Парам2;		// 0
	Рез1= Парам1% Парам2;		// 2

КонецПроцедуры

Процедура Метод2(А,Б, В)		// 1
	Рез = А> Б;			// 1
	Рез = А <Б;			// 1
	Рез = А > Б;			// 0
	
	Рез = А>= Б;			// 1
	Рез = А <=Б;			// 1
	Рез = А <> Б;			// 0
	Рез = А<>Б;			// 1
КонецПроцедуры

Метод1(60,24);Метод2(24, 60,60);	// 3

Метод2(60, 60, 60);			// 0
Метод2(24,				// 0
       60,
       60);
```

**Comment by nixel2007** [comment]
Перем А1,Б1;А1=Б1+ 1;  // 4

Я вот здесь 5 насчитал вроде.

**Comment by YanSergey** [comment]
![image](https://user-images.githubusercontent.com/24665801/64565257-0bcdcf00-d35c-11e9-9dc0-b9f36f65a5eb.png)
Я рассчитывал считать не количество пропущенных пробелов, а количество срабатываний.
Варианты:
 "А1=Б1"
 "А1 =Б1"
 "А1= Б1"
у всех по одному срабатыванию.
Т.е закладываю логику, что операторы: +-*/=%<> требуют пробелы с обоих сторон. Если нет одного или обоих - срабатывание одно.
К ним добавляются   >=   <=   <>
Символы , (запятая) и ; (точка с запятой) требуют пробел только справа.
Как то так.

**Comment by nixel2007** [comment]
Не забудь унарные минус и плюс.

**Comment by nixel2007** [comment]
Про количество срабатываний - да, хорошая логика. А сможешь в сообщение выводить чего именно не хватает? Справа, слева или с обеих сторон?

**Comment by YanSergey** [comment]
Итого, список параметров, со значениями по-умолчанию выглядит следующим:
```bsl
listForCheckLeft          = "";      // символы, требующие пробелы только слева
listForCheckRight         = ", ;";   // ... только справа
listForCheckLeftAndRight  = "+ - * / = % < > <> <= >="; // ... с обоих сторон

checkSpaceToRightOfUnary  = false;   // Проверять пробел справа от унарного знака
allowMultipleCommas       = false;   // Разрешить несколько запятых подряд
```
В listForCheckLeft можно вписать например ")"
А в listForCheckRight добавить "("
