### ISSUE TITLE
CodeAction на открытие документации по диагностике

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#247]
Ссылки на 1c-syntax.github.io/bsl-language-server должно хватить.

Что думаешь, @asosnoviy ?

Видел такую фичу у сонарлинта и tslint

**Comment by asosnoviy** [comment]
Сюда?
![image](https://user-images.githubusercontent.com/15638529/60082570-aabf3380-973c-11e9-8c20-89c26bb1ada6.png)
Или сюда
![image](https://user-images.githubusercontent.com/15638529/60082588-b7dc2280-973c-11e9-9ef8-fd9e38deff77.png)

Или это одно и тоже =)?

**Comment by nixel2007** [comment]
во всплывашку по нажатию на "quick fix..."

**Comment by nixel2007** [comment]
среди "лампочек"

**Comment by asosnoviy** [comment]
![image](https://user-images.githubusercontent.com/15638529/60084982-2de28880-9741-11e9-8e5b-fbf07a0ebf93.png)
Оно?

**Comment by nixel2007** [comment]
Да. вот туда еще команду "открыть документацию по диагностике "Каноническое написание слов"" или что-то такое

**Comment by nixel2007** [comment]
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentLink
