### ISSUE TITLE
Шильдик на скачавания

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#25]
[![Github All Releases](https://img.shields.io/github/downloads/1c-syntax/bsl-language-server/total.svg)]() 
[![Github Releases](https://img.shields.io/github/downloads/1c-syntax/bsl-language-server/latest/total.svg)]()

**Comment by nixel2007** [comment]
а откуда счетчик делать? jitpack отдает только скачку через системы сборки, по зависимостям. bintray? что-то свое?

**Comment by asosnoviy** [comment]
Тогда наверно шильдики надо не в этот реп, а в конечные репы. Конкретно этот считает с релизов гитхаба.

**Comment by asosnoviy** [comment]
https://shields.io еще там много вкусного =)

**Comment by nixel2007** [comment]
даааа? не знал, что гитхаб отдает статистику по скачивания. тогда можно и
эти использовать!

вт, 29 янв. 2019 г. в 14:22, Alexey Sosnoviy <notifications@github.com>:

**Comment by asosnoviy** [comment]
После выхода в маркет не сильно актуально...
