### ISSUE TITLE
Не ругаться на EmptyCodeBlock, если внутри есть комментарий

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#255]
- Код в блоке может быть пустым ошибочно, т.к. не заполнили - в нем нет комментариев или там служебные, типа `//ToDo` или `// Вставить содержимое обработчика`, на которые должна ругаться другая проверка
- Код в блоке может быть пустым из-за закомментирования кода. В АПК это определяется как комментарий, где после черт нет пробела. `//Сообщить("Привет")` это закомментированный код, а `// Сообщить("Привет")` это комментарий. На закомментированный код должна быть отдельная проверка.
- Код в блоке может быть специально пустым и внутри блока написана причина.

То есть во всех случаях получаем FP - или тут другая ошибка, или ошибки нет.

**Comment by asosnoviy** [comment]
А спец коммент подойдёт сюда?

**Comment by nixel2007** [comment]
Да вроде обычного достаточно

**Comment by asosnoviy** [comment]
Проверка на законченный код с пробелом смущает... И второй вопрос, а как достать коммент из Скипа?)

**Comment by nixel2007** [comment]
1. На это можно отдельную диагностику сделать
2. Комменты не в скипе, они в другом канале. Их можно достать из документ контекста через getCommenta

**Comment by theshadowco** [comment]
Правильно ли я понял, что в принципе сошлись на том, что пустой блок с комментарием не есть пустой блок и надо так доработать диагностику?

**Comment by theshadowco** [comment]
Ну и добавить параметр - учитывать комментарий в пустом блоке или нет

**Comment by asosnoviy** [comment]
Ага

**Comment by nixel2007** [comment]
@TheShadoWCo прям а 0.11.0? Шустрый какой...

**Comment by theshadowco** [comment]
@nixel2007 а что? пусть идет в релиз ))
