### ISSUE TITLE
Закомментированный код

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#256]
Стандарт: https://its.1c.ru/db/v8std/content/456/hdoc

type: CODE_SMELL
severity: MINOR
timeToFix: 5min

АПК ругается так "Закомментированный код или отсутствие пробела в комментарии после знака "//"."

**Comment by asosnoviy** [comment]
@nixel2007 первую реализацию сделаем тупую?

**Comment by asosnoviy** [comment]
#255

**Comment by nixel2007** [comment]
Насколько тупую?)

**Comment by asosnoviy** [comment]
Есть пробел после // - коммент. Нет пробела - код.

**Comment by nixel2007** [comment]
А может поумнее? взять текст коммента, прогнать его через токенайзер, оценить типы токенов... не?

**Comment by asosnoviy** [comment]
Тады это не тянет на goodfirst =)

**Comment by qtLex** [comment]
@nixel2007 кажется закрыли не тот issue. #206 на другую тему.

**Comment by nixel2007** [comment]
Упс. пардоньте. Спасибо!
