### ISSUE TITLE
Ошбика парсинга acc-json

### ISSUE THREAD

**Issue by KrapivinAndrey** [1c-syntax/bsl-language-server#257]
Собрал маленькую конфигурацию выполнил проверку через АПК и пытаюсь загрузить данные в SQ.
Ловлю ошибку.
java.lang.IllegalArgumentException: Start pointer [line=3313, lineOffset=0] should be before end pointer [line=3313, lineOffset=0]

Выглядит так, как будто не удается корректно посчитать смещение.

Самое интересное - удаляю место с ошибкой(большой блок) и снова ошибка в этом же месте

**Comment by KrapivinAndrey** [comment]
Чуть позже будет лог

**Comment by Stepa86** [comment]
Ааааа, ошибка парсинга из АПК... Эт не сюда, эт в https://github.com/otymko/acc-export  ))))

@otymko у меня ведь такие ошибки тож валились, но я не стал разбираться и в той моей последней обработке тупо выпилен расчет диапазона - только строка. Можт так и оставить?

**Comment by Stepa86** [comment]
@KrapivinAndrey Попробуй вот эту обработку для импорта https://yadi.sk/d/FR7xcflOVOQ-3w

**Comment by KrapivinAndrey** [comment]
@Stepa86 Кажется ты прислал ту же версию. Точно так же range рассчитывается. и ошибка ровно та же

**Comment by asosnoviy** [comment]
А если не делать импорт, а только встроенный анализ, то все ок?

**Comment by KrapivinAndrey** [comment]
все ok

**Comment by nixel2007** [comment]
Если вы не против, я тогда закрою ишуз тут, чтобы не распылять внимание :)
