### ISSUE TITLE
[FP] UnusedLocalVariable 

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#2578]
## Диагностика
UnusedLocalVariable

## Версия
sonar-communitybsl-plugin-1.11.0-rc.1

## Описание ложного срабатывания диагностики
На примере видно что выдаёт FP на переменной `Запрос` которая далее отправляется в метод `ВыполнитьЗапрос`

## Пример кода
```bsl
Функция ЗаписатьОбъекты(Прокси, Объекты) Экспорт
	
	Запрос = СоздатьОбъект(Прокси, "DMUpdateRequest");

	Для Каждого Объект Из Объекты Цикл
		Запрос.objects.Добавить(Объект);
	КонецЦикла;
	
	Ответ = ВыполнитьЗапрос(Прокси, Запрос);
	ПроверитьВозвратВебСервиса(Прокси, Ответ);
	Возврат Ответ;
	
КонецФункции
```

## Скриншоты
![image](https://user-images.githubusercontent.com/32082417/158711129-71c8e7f8-61dc-4251-898c-2203f02bf937.png)

**Comment by nixel2007** [comment]
Да тут и в цикле использование не поймалось.

**Comment by qtLex** [comment]
По весьте на меня гляну на выходных

**Comment by qtLex** [comment]
Тут у меня не получается поймать проблему. На develop и на sonar-communitybsl-plugin-1.11.0-rc.1 все хорошо.
Нашел пару других FP. Нужно еще понаблюдать и подумать.

**Comment by asosnoviy** [comment]
@nixel2007 а это не пофиксилось вместе с comparable?

**Comment by sfaqer** [comment]
> @nixel2007 а это не пофиксилось вместе с comparable?

Да это и есть ишью про референс индекс.)
