### ISSUE TITLE
VSC на ховере показывает Unsupported Markup Content

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#26]
Проверить корректность реализации протокола:
![image](https://user-images.githubusercontent.com/1132840/51933072-8f602e80-2411-11e9-8bd6-8915ca9b37a1.png)

**Comment by asosnoviy** [comment]
@nixel2007 Полечилось же?

**Comment by nixel2007** [comment]
Я ховер просто выключил. Пока можно закрыть, думаю.
