### ISSUE TITLE
Автоисправление пробелов после запятых в аргументах методов и вызовов

### ISSUE THREAD

**Issue by zeegin** [1c-syntax/bsl-language-server#260]
**Плохо**
```bsl
Процедура Фу(П1,П2  ,  П3, П4)
КонецПроцедуры

Фу(П1,  П2  , П3,П4)
```
**Хорошо**
```bsl
Процедура Фу(П1, П2, П3, П4)
КонецПроцедуры

Фу(П1, П2, П3, П4)
```

**Comment by nixel2007** [comment]
вроде форматтер это уже должен делать и так, разве нет?

**Comment by zeegin** [comment]
@nixel2007 я сейчас взял версию в vscode из маркета, может это в деве сделано и пока не выпущено?

**Comment by nixel2007** [comment]
![format](https://user-images.githubusercontent.com/1132840/60956418-72f2e700-a30b-11e9-8c66-a033e6aa9262.gif)

**Comment by nixel2007** [comment]
форматтер после выпуска последней версии плагина не трогался.
У тебя точно форматтер от бсл лс срабатывает, а не legacy из плагина?

**Comment by nixel2007** [comment]
Обсудили, отрабатывал легаси форматтер.

**Comment by zeegin** [comment]
Все хорошо, работает.
