### ISSUE TITLE
FP Итератор не используется в теле цикла.

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#263]
![image](https://user-images.githubusercontent.com/15638529/61080276-5ea70b00-a42d-11e9-9cb1-b113b6afe0c9.png)

**Comment by asosnoviy** [comment]
Подобная конструкция используется для получения первого элемента соответствия.

**Comment by nixel2007** [comment]
Кажется, что это какая-то херня. Триггер ЧБ срабатывает, а значит, надо рефакторить.

Я бы закрыл ишуз.

**Comment by Stepa86** [comment]
Мне кто-то говорил, что такие вещи нужно вынести в отдельный модуль и обмазать скипворнингами, а не править анализатор

**Comment by asosnoviy** [comment]
@zeegin третьим будешь?

**Comment by zeegin** [comment]
А сделать просто `Ошибка[0]` не проще?  И проверить на `Количество() > 0` если нужно.
Я думаю это не FP, так лучше не писать: не очевидная конструкция,  не стандартная для стандартной задачи, нет понимания что будет если соответствие пустое,  предполагает обращение к итератору вне цикла что не очень хорошо, хорошо когда области видимости соблюдаются.
