### ISSUE TITLE
Код после возврата (Недостижимый код)

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#265]
```bsl

Возврат СтруктураПараметров;

Возврат ПрочитатьКоллекциюИзJSONФайла(ИмяФайла);

```

**Comment by asosnoviy** [comment]
Наивная реализация без флоу. Если на одном уровне с возвратом есть код. Вопрос на что кидать?

**Comment by nixel2007** [comment]
На первый стейтмент

**Comment by nixel2007** [comment]
А я бы и с флоу сделал. Кажется, это без особых проблем делает я на стеке

**Comment by DanilaSpevak** [comment]
примечание: недостижимый код может быть еще и после ВызватьИсключение

**Comment by Stepa86** [comment]
Ну если уж на то пошло, то и после Продолжить и Прервать в цикле.

**Comment by zeegin** [comment]
И Перейти.
