### ISSUE TITLE
[MOD] Не учитывать в диагностике за областью ВызватьИсключение НСтр("ru = 'Недопустимый вызов объекта на клиенте.'");

### ISSUE THREAD

**Issue by Kyrales** [1c-syntax/bsl-language-server#2749]
## Диагностика
CodeOutOfRegion

## Описание предлагаемых изменений
Не учитывать в диагностике за областью код ниже. Т.к. это рекомендуемый подход использования в модуле объекта вставки вида:
#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда

ТУТ ОБЛАСТИ

#Иначе
**ВызватьИсключение НСтр("ru = 'Недопустимый вызов объекта на клиенте.'");**
#КонецЕсли

![image](https://user-images.githubusercontent.com/79920318/167059583-4b3d24a6-fbb6-4520-94cb-c29c394d5303.png)

**Comment by nixel2007** [comment]
Не вижу в стандарте ничего про области. Можно пример такой расстановки кода?

**Comment by asosnoviy** [comment]
> Не вижу в стандарте ничего про области. Можно пример такой расстановки кода?
https://its.1c.ru/db/v8std/content/680/hdoc

```

**Comment by EightM** [comment]
Я бы даже сказал, что данный код должен быть в области "Инциализация", так как он выполняется исключительно при начале выполнения модуля и моментально её прерывает

**Comment by asosnoviy** [comment]
> Не, этот кусок кода я вижу. я не вижу требований включить область внутрь инструкции, а не снаружи

ну фигня же выйдет =(

**Comment by nixel2007** [comment]
Может быть :)

Но в целом я даже согласен с Витей по поводу инициализации.

**Comment by asosnoviy** [comment]
> Может быть :)
> 
> Но в целом я даже согласен с Витей по поводу инициализации.

Позырил в утху типовую.... ни одной области вокруг исключения не обнаружено +)

**Comment by EightM** [comment]
> > Может быть :)
> > 
> > Но в целом я даже согласен с Витей по поводу инициализации.
> 
> Позырил в утху типовую.... ни одной области вокруг исключения не обнаружено +)

Им просто пофиг на такие мелочи
