### ISSUE TITLE
[FP] Исправьте обращение к несуществующему метаданному в запросе

### ISSUE THREAD

**Issue by agibalovsa** [1c-syntax/bsl-language-server#2760]
## Диагностика
Исправьте обращение к несуществующему метаданному "Справочник.Организации" в запросе

## Версия
1.11.0-RC.2+17.dev

## Описание ложного срабатывания диагностики
Запрос открывается в расширение, но BSL все равно выдает ошибку

## Пример кода
[уит_ОбменДанными.zip](https://github.com/1c-syntax/bsl-language-server/files/8727651/_.zip)

## Скриншоты
![image](https://user-images.githubusercontent.com/14235747/169256510-7180317a-d3fd-4cd5-b876-1e96a52aaf65.png)

## Дополнительная информация
Для расширения нужны некоторые метаданные в ЕРП (2.5.6.171), но я думаю, это не помешает.
П.С. Часть кода не наша, прошу строго не относиться к некоторым формам написания :)

**Comment by agibalovsa** [comment]
Да, я проверял. Запрос в расширение открывается без ошибок.

**Comment by agibalovsa** [comment]
> Справочник заимствован в расширение?

Да, я проверял. Запрос в расширение открывается без ошибок.

**Comment by nixel2007** [comment]
В репозитории один корень конфигурации/расширения или несколько? Если несколько, как задан параметр sonar.sources?

**Comment by agibalovsa** [comment]
> В репозитории один корень конфигурации/расширения или несколько? Если несколько, как задан параметр sonar.sources?
![image](https://user-images.githubusercontent.com/14235747/169275312-eded11cb-069f-4bfd-ac1f-628773d7f17b.png)
![image](https://user-images.githubusercontent.com/14235747/169275410-a74ef114-d0b3-4af5-a7a3-9f06d9160226.png)

**Comment by asosnoviy** [comment]
А кто такой реп?

**Comment by agibalovsa** [comment]
реп - это папка с обработками. В общем помогло решение из issues 2762.
