### ISSUE TITLE
[FP] Удалите не используемую переменную

### ISSUE THREAD

**Issue by agibalovsa** [1c-syntax/bsl-language-server#2762]
## Диагностика
Удалите не используемую переменную Наименование

## Версия
1.11.0-RC.2+17.dev

## Описание ложного срабатывания диагностики
В расширение в модуле объекта задается наименование. Срабатывает проверка на неиспользуемую переменную.

## Пример кода
[уит_НСИ.zip](https://github.com/1c-syntax/bsl-language-server/files/8728282/_.zip)

## Скриншоты
![image](https://user-images.githubusercontent.com/14235747/169272844-0502cb85-92f0-45c2-aa34-12ece2caec20.png)

## Дополнительная информация
Модуль объекта справочника "уит_АдресаДоставкиПартнеров"

**Comment by nixel2007** [comment]
Аналогичный вопрос про корни и sonar.sources

**Comment by agibalovsa** [comment]
> Аналогичный вопрос про корни и sonar.sources

![image](https://user-images.githubusercontent.com/14235747/169275312-eded11cb-069f-4bfd-ac1f-628773d7f17b.png)
![image](https://user-images.githubusercontent.com/14235747/169275410-a74ef114-d0b3-4af5-a7a3-9f06d9160226.png)

**Comment by nixel2007** [comment]
В cfe одно расширение или несколько?

**Comment by agibalovsa** [comment]
> В cfe одно расширение или несколько?

Извиняюсь, да, несколько расширений, конечно.
![image](https://user-images.githubusercontent.com/14235747/169281763-1afabe07-5efd-49e0-911c-5ad3ee38d419.png)

**Comment by nixel2007** [comment]
Боюсь, у меня плохие новости. В теущей реализации плагина каждое расширение нужно прописывать отдельно в src. Иначе могут врать проверки на метаданные.

**Comment by agibalovsa** [comment]
Не совсем понял. Это как?

**Comment by agibalovsa** [comment]
Нууууу, хотя бы так. Спасибо! )) А для обработок тоже же важны метаданные. Там тоже нужно каждую так прописывать?

**Comment by nixel2007** [comment]
С обработками... Не подскажу. Скорее всего будут баги :)

**Comment by agibalovsa** [comment]
В общем помогло. Спасибо большое. Для расширений, это терпимо, обработки не проверял, но для них каждый раз править sonar.properties - жесть )
