### ISSUE TITLE
[NEW] Вложенные блоки Если внутри Если

### ISSUE THREAD

**Issue by agibalovsa** [1c-syntax/bsl-language-server#2793]
## Описание проблемы, ошибки, которую надо диагностировать
Очень часто неопытные программисты используют следующие конструкции
```
Если Тогда
   Если Тогда
      Если Тогда
      КонецЕсли
   КонецЕсли
Иначе
   Если Тогда
      Если Тогда
      КонецЕсли
   КонецЕсли
КонецЕсли;
```
Эти убийственные конструкции не всегда отлавливаются проверкой когнитивной и цикломатической сложности. Тем не менее, если их привести к конструкции
```
Если Тогда
ИначеЕсли Тогда
Иначе
КонецЕсли;
```
Тогда оказывается, что условие на столько простое. что часть переменных не нужно, и весь код сокращается раза в 3. Очень часто такие конструкции возникают, когда в один и тот же код заходя разные программисты, и им лень разбираться в исходной логике.

Я считаю, что это отдельный случай неопытности и неопрятности, который нужно отлавливать.

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы
...

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)
* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)
* [ ] :broken_heart: Блокирующая / Blocker
* [x] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)
* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [x] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
10

## Дополнительная информация
...

**Comment by artbear** [comment]
ИМХО Про вложенные Если уже есть ишуз

**Comment by artbear** [comment]
Уже есть https://github.com/1c-syntax/bsl-language-server/issues/959

текущий тикет-дубль предлагаю закрыть.
