### ISSUE TITLE
[FP] При выборе из критерия отбора срабатывает "Не следует использовать виртуальные таблицы без параметров"

### ISSUE THREAD

**Issue by antonsm2011** [1c-syntax/bsl-language-server#2799]
## Диагностика
VirtualTableCallWithoutParameters

## Версия
v0.20.0

## Описание ложного срабатывания диагностики
Есть выбор из таблицы КритерийОтбора.СтруктураПодчиненности с указанием одного параметра.
Больше параметров у этой таблицы нет.
Еще есть условие в секции ГДЕ.

## Пример кода
Код в УНФ 1.6.26.185, но код нетиповой.
Запрос.Текст = 
"ВЫБРАТЬ
|	ЗаказПоставщику.Ссылка КАК Ссылка,
|	ЗаказПоставщику.ПоложениеЗаказаПокупателя КАК ПоложениеЗаказаПокупателя,
|	ЗаказПоставщику.ПометкаУдаления КАК ПометкаУдаления,
|	ЗаказПоставщику.Проведен КАК Проведен
|ПОМЕСТИТЬ втЗаказПоставщику
|ИЗ
|	КритерийОтбора.СтруктураПодчиненности(&ЗаказПокупателя) КАК СтруктураПодчиненности
|		ВНУТРЕННЕЕ СОЕДИНЕНИЕ Документ.ЗаказПоставщику КАК ЗаказПоставщику
|		ПО СтруктураПодчиненности.Ссылка = ЗаказПоставщику.Ссылка
|ГДЕ
|	СтруктураПодчиненности.Ссылка ССЫЛКА Документ.ЗаказПоставщику"

## Скриншоты
![2022-06-08_21-44-13](https://user-images.githubusercontent.com/12731230/172695019-f30f20c1-fbba-450b-a9e7-cb800c65c28d.png)

**Comment by artbear** [comment]
Дубль уже существующего https://github.com/1c-syntax/bsl-language-server/issues/1616
