### ISSUE TITLE
Одинаковые выражения слева и справа от оператора

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#283]
Явно косяк, если выражение слева и справо от операторов `+`, `-`, `/`, `И`, `ИЛИ` и `=` совпадает

```bsl
Перем1 = Перем1;

Если Перем1=Перем1 Тогда
    ...
КонецЕсли;

Перем2 = Перем1 + Перем1;  // С 2*Перем1 понятнее
Перем3 = Перем1/Перем1; 

Если (Перем1+Перем2+Перем3) = (Перем1+Перем2+Перем3) Тогда
    ...
КонецЕсли;

Если УсловиеВыполняется() ИЛИ УсловиеВыполняется() Тогда
    ...
КонецЕсли;

Если (Перем1 = 0) И (Перем1 = 0) Тогда
    ...
КонецЕсли;

Если Перем1=Перем1 Тогда
    ...
КонецЕсли;

Возврат Перем1 - Перем1;
```

**Comment by Stepa86** [comment]
Еще `>` `<` сюда же

**Comment by qtLex** [comment]
А подразумевается сравнение выражения только вокруг одного оператора или конструкции вида ```Перем1 И Перем2 И Перем1``` определяться как ошибка?

**Comment by nixel2007** [comment]
@qtLex давай начнем с "вокруг одного оператора". 

Для `Перем1 И Перем2 И Перем1` по-хорошему надо писать какой-то простенький движок с пред-вычислениями, а наколеночно делать не хочется :(

**Comment by lChagelishvili** [comment]
```bsl
Перем1 = Перем1;
```
Не сюда, наверное. Это присваивание и для него уже есть диагностика.
