### ISSUE TITLE
[MOD] IfElseIfEndsWithElse - присвоение одной переменной не считать ошибкой

### ISSUE THREAD

**Issue by Kyrales** [1c-syntax/bsl-language-server#2840]
## Диагностика
IfElseIfEndsWithElse

## Описание предлагаемых изменений
Стоит изменить диагностику, чтобы присвоение значения одной переменной не считалось ошибкой.
Чтобы не строить "монструозные" конструкции "Если" в одном действии.

Например
```
Если ПервоеСложноеУсловие Тогда
   **ФлагДействия = Истина;**
ИначеЕсли ВтороеСложноеУсловие Тогда
    **ФлагДействия = Истина;**
Иначе
    ФлагДействия = Ложь;
КонецЕсли;

Если ФлагДействия Тогда
     ...
КонецЕсли;
```

**Comment by asosnoviy** [comment]
я не понял предложения =(

**Comment by nixel2007** [comment]
Я не совсем понимаю, как диагностика IfElseIfEndsWithElse связана с предлагаемым изменением. Она ругается на отсутствие ветки else, а не на присваивание переменных
