### ISSUE TITLE
Параметр функции не должен возвращать значение.

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#289]
Весь вывод должен быть в возвращаемом значении. Если нужно возвращать несколько значений следует использовать такие типы как Структура, Массив и т.д.
```bsl
// Плохо:
URLСервиса = "";
ИмяПользователя = "";
ПарольПользователя = "";

ЗаполнитьПараметрыПодключения(URLСервиса, ИмяПользователя, Пароль);

// Хорошо:
ПараметрыПодключения = ПолучитьПараметрыПодключения();
// Возвращаемое значение - структура:
//     URLСервиса         - Строка
//     ИмяПользователя    - Строка
//     ПарольПользователя - Строка
```

**Comment by nixel2007** [comment]
Кажется, мы уже холиварили на эту тему, но пускай повис и

**Comment by sfaqer** [comment]
Ну, можно в варианте "холиварная диагностика" т.е. по умолчанию выключена, а дальше на усмотрение потребителя.)

**Comment by Stepa86** [comment]
Т.к. в 1С все плохо с ООП, то проверка может слишком много боли принести без ощутимого профита

![image](https://user-images.githubusercontent.com/25096392/62271533-8c3a0f80-b441-11e9-8408-4df50e0cd726.png)

**Comment by sfaqer** [comment]
@stepa86 да, это боль... Но диагностика для небольших нетленок будет к месту, на ерп её конечно не натравить...

**Comment by sfaqer** [comment]
Опять же для небольших библиотек onescript тоже зайдет

**Comment by asosnoviy** [comment]
@nixel2007 Кстати, а область действия мы как нить можем переопределить в веб интерфейсе?

**Comment by Stepa86** [comment]
Еще надо учитывать, что Отказ и СтандартнаяОбработка гуляют почти всегда через параметр

**Comment by nixel2007** [comment]
> @nixel2007 Кстати, а область действия мы как нить можем переопределить в веб интерфейсе?

@asosnoviy нет, не можем. и через конфиг тоже.

**Comment by asosnoviy** [comment]
Я имел ввиду гипотетически, а не прям сейчас

**Comment by zeegin** [comment]
Случай 1:
Мы делаем свою подписку на событие в переопределяемом модуле и описываем ее реализацию:
```bsl
Процедура ПриДобавленииПодсистем(Подсистемы) Экспорт
    Посистемы.Добавить("МояСуперПуперПодсистема");
КонецПроцедуры
```
 и 
Случай 2:
Мы делаем рекурсию в которой параметры передаются по стеку вызова и не используем `Знач`. Забыли? А надо ли обрабатывать? Хз.

```bsl
Функция Рекурсия(Итератор = 0)
    Итератор = Итератор + 1;    
    Если Итератор > 5 Тогда
        Возврат Новый Структура("ВсеЧетка", Истина);
    КонецЕсли;
    Рекурсия(Итератор);
КонецФункции
```

**Comment by asosnoviy** [comment]
Случай 1, это не функция.
Случай 2 в простом случае ловятся.
