### ISSUE TITLE
[BUG] BSL не стартует в новой macOS 13.0 Ventura

### ISSUE THREAD

**Issue by mothlike** [1c-syntax/bsl-language-server#2919]
**Версия**
Language 1C (BSL) v1.26.0

**Описание ошибки диагностики**
При старте VSCode возникает ошибка запуска BSL Language Server и вечно висит надпись Initializing BSL Language Server. Если переместить в корзину то дальше возникает ошибка file not found при запуске этого бинарника.

**Пример кода**
`[Info  - 2:31:15 PM] Connection to server got closed. Server will restart.
[Info  - 2:31:16 PM] Connection to server got closed. Server will restart.
[Info  - 2:31:17 PM] Connection to server got closed. Server will restart.
[Info  - 2:31:18 PM] Connection to server got closed. Server will restart.
[Error - 2:31:19 PM] The BSL Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
`

**Скриншоты**
<img width="416" alt="image" src="https://user-images.githubusercontent.com/2392281/198015717-4c30aed4-700e-49b1-ace0-d99f54494a43.png">
<img width="475" alt="image" src="https://user-images.githubusercontent.com/2392281/198015850-12c2702d-e821-41b2-a907-1240d06ec6f8.png">

**Дополнительная информация**
`java -version
openjdk version "11.0.15" 2022-04-19 LTS
OpenJDK Runtime Environment (build 11.0.15+10-LTS)
OpenJDK 64-Bit Server VM (build 11.0.15+10-LTS, mixed mode)

/usr/libexec/java_home -V
Matching Java Virtual Machines (1):
    11.0.15+10-LTS (x86_64) "BellSoft" - "BellSoft Liberica JDK 11.0.15+10" /Library/Java/JavaVirtualMachines/liberica-jdk-11-full.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/liberica-jdk-11-full.jdk/Contents/Home`

**Comment by mothlike** [comment]
Примечание, Liberica JDK стоит для x86-64, хотя компьютер M1 (для работы EDT). В предыдущей версии ОС все работало без проблем.

**Comment by mothlike** [comment]
Ручной запуск приводит к тому же самому:
<img width="784" alt="image" src="https://user-images.githubusercontent.com/2392281/198022506-1b77c4a3-21be-49ca-bf51-26619b6e222b.png">

**Comment by asosnoviy** [comment]
@otymko есть где погонять?

**Comment by otymko** [comment]
> @otymko есть где погонять?

Ага, сегодня посмотрю

**Comment by otymko** [comment]
Сейчас обновлю macOS и проверим как у меня будет работать.

**Comment by otymko** [comment]
@mothlike, есть пока возможность проверить запуск из jar?

**Comment by mothlike** [comment]
Напишите просто в телегу - ник такой же как тут. Будет быстрее передавать диагностику.

**Comment by mothlike** [comment]
Если я правильно понял то jar работает:
`java -jar ./bsl-language-server-0.21.0-ra.2-exec.jar --help
BSL language server
Usage: bsl-language-server [-h] [-c=<path>] [COMMAND [ARGS]]
  -c, --configuration=<path>
               Path to language server configuration file
  -h, --help   Show this help message and exit
Commands:
  analyze, -a, --analyze  Run analysis and get diagnostic info
  format, -f, --format    Format files in source directory
  version, -v, --version  Print version
  lsp, --lsp              LSP server mode (default)
Copyright(c) 2018-2020
`

**Comment by mothlike** [comment]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/2392281/198077483-94c45f02-07db-4528-93ad-ff4b6b25bd94.png">
И чтобы окончательно решить - если в плагине указать внешний jar, то все работает.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/2392281/198077594-17aad586-4dfc-4b5b-9ab6-3b285822150e.png">

**Comment by otymko** [comment]
@nixel2007 очень похоже на траблу https://bugs.openjdk.org/browse/JDK-8276150. Обновление конечно же не помогло. Что думаешь?

**Comment by otymko** [comment]
Собирается с нормальной подписью только на java-20-ea (https://github.com/openjdk/jdk/commit/1e222bccd3807c1be0d1d824e0ff9745751d8375)
