### ISSUE TITLE
[NEW] Не установлен флаг "Запрет незаполненных значений" для измерений регистра

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#2975]
## Описание проблемы, ошибки, которую надо диагностировать

Довольно часто при проектировании структуры метаданных соблюдается правило - измерения регистра всегда должны быть заполнены конкретными значениями и не должны быть пустыми.
Выполнение этого правила подразумевает, что записи регистра с незаполненным измерением не имеют смысла в информационной базе, каким бы образом они в нее ни попали: в результате интерактивного ввода или в результате выполнения программного кода.

Проверку на заполненность измерений удобно выполнять встроенными средствами платформы 1С, установив флаг "Запрет незаполненных значений" для измерения регистра. В этом случае платформа самостоятельно будет проверять заполненность измерений и при программной обработке регистров, и при интерактивной обработке. 

Без установки указанного флага могут возникать различные ситуации, которые приводят к проблемам или усложняют сопровождение систем 1С. Например,
- пользователи смогут интерактивно указать пустые значения 
- или разработчики могут при разработке ошибаться, не указывая значения измерения при подготовке записей регистра. 

Текущее правило может выдавать ложные срабатывания для измерений, которые могут быть не заполнены.

Правило применяется для следующих регистров:
- сведений
- накопления
- бухгалтерских
- расчетных

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

- [Книга "Разработка интерфейса прикладных решений на платформе "1С:Предприятие 8" - глава "Проверка заполнения и проверка при записи"](https://its.1c.ru/db/pubv8devui#content:225:1)
- [Документация разработчика 1С 8.3 - Свойства измерения (ресурса, реквизита) регистра сведений](https://its.1c.ru/db/v8323doc#bookmark:dev:TI000000349)
- [Документация разработчика 1С 8.3 - Свойства измерения (ресурса, реквизита) регистра накопления](https://its.1c.ru/db/v8323doc#bookmark:dev:TI000000363)

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

**Правило по умолчанию выключено**

### Время на исправление (минут)

1 минута

**Comment by otymko** [comment]
@artbear, я примерно понял правило. Но из описания не понятно - почему нельзя. В например только действия, а не последствия.

**Comment by otymko** [comment]
@artbear, допиши, плиз, последствия в описание. На мой взгляд, правильно, должно быть по умолчанию выключено, слишком индивидуально. Возможно я не прав, нужны "последствия" узнать.

**Comment by artbear** [comment]
> @artbear, допиши, плиз, последствия в описание. На мой взгляд, правильно, должно быть по умолчанию выключено, слишком индивидуально.

я поправил, теперь **Правило по умолчанию выключено**
