### ISSUE TITLE
Правило: "отсутствует вызов "НачатьТранзакцию()", хотя вызываются "ЗафиксироватьТранзакцию()"/"ОтменитьТранзакцию()" (325)"

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#298]
#149 Реализация п. 1

**Comment by theshadowco** [comment]
Предлагаю обсудить реализацию:

 - метод начинается с Зафиксировать / Отменить транзацию - вешаем ошибку на обнаруженный вызов и проверку метода завершаем
 - метод начинается с Начать транзацию - считаем нормальным

**Comment by theshadowco** [comment]
@nixel2007 @asosnoviy

**Comment by nixel2007** [comment]
Я думаю, тут стоит считать "парность" вызовов.

Например,

```bsl
НачатьТранзакцию();
ЗафиксироватьТранзакцию();
ЗафиксироватьТранзакцию();
```

должен ругнуться на второй`ЗафиксироватьТранзакцию()`, так как нет парного `НачатьТранзакцию()`

**Comment by theshadowco** [comment]
Парность - это другое правило

**Comment by theshadowco** [comment]
Либо само по себе правило отсутствие начала выкинуть, а сделать парность как надмножество

**Comment by nixel2007** [comment]
в списке из исходного ишуза парность палится по "начатьтранзакцию". что у них должен быть парный завершить/отменить. а тут наоборот, на завершить/отменить должен быть парный "начать"

**Comment by theshadowco** [comment]
В итоге, покрывается правилом парности. Если что, может быть в другой раз сделаю отдельно
