### ISSUE TITLE
Запрет хардкода конфиденциальной информации

### ISSUE THREAD

**Issue by zeegin** [1c-syntax/bsl-language-server#303]
CERT, MSC03-J. - Never hard code sensitive information

https://wiki.sei.cmu.edu/confluence/display/java/MSC03-J.+Never+hard+code+sensitive+information

https://rules.sonarsource.com/java/RSPEC-1313
https://rules.sonarsource.com/java/RSPEC-2068

* Логины
* Пароли
* IP адреса
* может быть что-нибудь еще

**Comment by otymko** [comment]
Поиск IP и хардкодных путей к каталогам и папкам было бы кстати!

**Comment by theshadowco** [comment]
Простые поймать не сложно, но вот хитрые...

**Comment by otymko** [comment]
Беру на себя диагностики

**Comment by otymko** [comment]
Вторая диагностика не доделана и не передана в develop

**Comment by nixel2007** [comment]
Хорошо бы на будущее делать по ишузу на диагностику :)
