### ISSUE TITLE
[MOD] Двойная запись в ЖР в диагностике UsageWriteLogEvent

### ISSUE THREAD

**Issue by kuzyara** [1c-syntax/bsl-language-server#3042]
## Диагностика
https://1c-syntax.github.io/bsl-language-server/diagnostics/UsageWriteLogEvent/

## Описание предлагаемых изменений
необходимо добавить примеров в описание диагностики

## Дополнительная информация
В диагностике написано что надо делать так:
```bsl
    Исключение
      ЗаписьЖурналаРегистрации(НСтр("ru = 'Выполнение операции'"), УровеньЖурналаРегистрации.Ошибка, , ,
         ТекстОшибки); // <- только если выше по стеку произойдёт подавление ошибки без записи в ЖР
      ВызватьИсключение;
    КонецПопытки;
```
Но не написано, что так надо делать только если ошибка подавляется.
В случае если ошибка вызванная методом `ВызватьИсключение;` не подавляется, вызов метода ЗаписьЖурналаРегистрации() не нужен. (это сделает платформа)

Иначе это приведёт к двойной записи ошибки в ЖР.

Ситуация похожа на работу с вложенными транзакциями.

Неправильно:
```bsl
    Исключение
      ОтменитьТранзакцию();
      ЗаписьЖурналаРегистрации(НСтр("ru = 'Выполнение операции'"), УровеньЖурналаРегистрации.Ошибка, , ,
         ТекстОшибки); // <- зачем?
      ВызватьИсключение;
    КонецПопытки;
```
Если во внешней попытке делается запись в ЖР, во внутренней делать её уже не нужно:
```bsl
// регламентное задание
Процедура ЗагрузитьДанные() Экспорт
    Попытка
        ВыполнитьЗаписьДанных();
    Исключение
        ЗаписьЖурналаРегистрации(); // <- исключение подавляется с записью в ЖР
    КонецПопытки;
КонецПроцедуры

Процедура ВыполнитьЗаписьДанных()
    НачатьТранзакцию();
    Попытка
        // ...
        ЗафиксироватьТранзакцию();
    Исключение
        ОтменитьТранзакцию();
        ВызватьИсключение; // <- вложенная попытка, запись в ЖР не требуется
    КонецПопытки;
КонецПроцедуры
```
Правильно:
```bsl
//Например, вернуть счетчик транзакций в начальное значение (до нашего вызова):
Исключение
    ОтменитьТранзакцию();
    ВызватьИсключение; // <- если это вложенная попытка (транзакция)
КонецПопытки;

//Например,освободить файл:
Исключение
    ЧтениеДанныхАрхива.Закрыть();
    ВызватьИсключение;
КонецПопытки;

//Например, отключить монопольный режим:
Исключение
    УстановитьМонопольныйРежим(Ложь);
    ВызватьИсключение;
КонецПопытки;

//Например, закрыть форму:
Исключение
    ДлительныеОперацииКлиент.ЗакрытьФормуДлительнойОперации(ФормаДлительнойОперации);
    ВызватьИсключение;
КонецПопытки;
```

**Comment by kuzyara** [comment]
То есть при правильной работе с попытками `ЗаписьЖурналаРегистрации()` перед `ВызватьИсключение;` делать не надо.

А надо, если кругом враги и говного, и нужно чтобы уж наверняка, и пофиг ошибка дублироваться.

**Comment by kuzyara** [comment]
То есть если следовать правилу в диагностике, на каждую вложенную попытку будет создаваться запись в ЖР.

Две вложенные попытки - две записи. Три вложенные попытки - три одинаковых записи в ЖР.

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/233283905-c5567186-eec9-44dc-9c41-f89522333e6f.png)

![image](https://user-images.githubusercontent.com/2604430/233284110-f92eeb3c-4d42-4618-8984-3ce2ce2e256a.png)

ссылка на схему
https://miro.com/welcomeonboard/eTNUcndTYWVQN05tWXkwaHhoV2VmSDdVeVNLWlQ3YWdLbFE4MWM3ZUM2Q2tkVDhCOVhLR2lZU3BBSGxWbFI4T3wzMDc0NDU3MzQ3MDE1OTEwMTc2fDI=?share_link_id=406501673069

**Comment by Ndochp** [comment]
Запись в ЖР в этом случае не помешает, только там должен быть не текстОшибки, а НевидимыйВышеКонтекст. Типа значений параметров

**Comment by kuzyara** [comment]
![image](https://user-images.githubusercontent.com/2604430/233332399-0443ff89-52b3-4499-b2f0-b3e51f8eec2b.png)
