### ISSUE TITLE
Важность "Работа с параметром отказ"

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#308]
Имхо это Критикал.

![image](https://user-images.githubusercontent.com/15638529/62698455-da24b980-b9e5-11e9-8189-1af89d825942.png)

**Comment by asosnoviy** [comment]
Заодно в описании "ИЛИ" неканонично.

**Comment by theshadowco** [comment]
Майор

**Comment by asosnoviy** [comment]
@zeegin конечно критикал. все что может привести к развалу в режиме предприятия - критикал

**Comment by nixel2007** [comment]
я вообще за майора, но что там по нашему новому гайду? майора хватит или все же на критикал попадает?

**Comment by theshadowco** [comment]
https://github.com/1c-syntax/bsl-language-server/blob/develop/docs/contributing/DiagnosticTypeAndSeverity.md
