### ISSUE TITLE
[MOD] UnusedLocalMethod - "Неиспользуемый локальный метод" - поддержка модулей объектов через параметр правила

### ISSUE THREAD

**Issue by artbear** [1c-syntax/bsl-language-server#3111]
## Диагностика

UnusedLocalMethod - Неиспользуемый локальный метод

## Описание предлагаемых изменений

Предлагаю добавить поддержку модулей объектов через булевый параметр правила
считаю, что для этих модулей правило будет полезно и ложных срабатываний не будет много, поэтому с ними можно мириться
а также полезно для внешних файлов

по умолчанию параметр выключен и проверки модулей объектов не производится
при включении параметра правило начинает работать в модулях объектов

**Comment by nixel2007** [comment]
Не совсем понимаю тезис про "не будет фонить". Оно фонит именно на модулях объектов из-за стандартных обработчиков объектов, которые в явном виде из кода не вызываются

**Comment by artbear** [comment]
> Не совсем понимаю тезис про "не будет фонить". Оно фонит именно на модулях объектов из-за стандартных обработчиков объектов, которые в явном виде из кода не вызываются

типовые, часто встречаемые имена, ПередЗаписью, ПриЗаписи и т.п. можно добавить в исключения
а остальные методы считать ошибкой.

в этом случае ФП будет немного.

и напомню, что такое поведение по умолчанию выключено.
кому нужно, тот настроит.

нам, в Инфостарте, нужно!
