### ISSUE TITLE
[DOCS] Исправление ошибки в документации

### ISSUE THREAD

**Issue by alei1180** [1c-syntax/bsl-language-server#3200]
Ошибка живет в файле [docs/index.md ](https://github.com/1c-syntax/bsl-language-server/tree/develop/docs/index.md ) и имеет синтаксический характер в предложении:
"Для формирования отчета об анализе требуется указать один **или** "репортеров"".
Вроде мелочь, а в глаза бросилась при четнии документации.

**Comment by nixel2007** [comment]
Такие вещи можно сразу пулл реквестом :)
