### ISSUE TITLE
Вставляется лишний пробел при экранировании кавычек в тексте запроса

### ISSUE THREAD

**Issue by kodemi** [1c-syntax/bsl-language-server#329]
Если в тексте запроса есть экранирование кавычек:
```bsl
...
|ГДЕ
|     Справочник.Реквизит1 = """" И Справочник.Реквизит2 = """"
...
```
то при срабатывании форматирования файла в крайнюю последовательность кавычек вставляется пробел, что ломает текст запроса:
```bsl
...
|ГДЕ
|     Справочник.Реквизит1 = """" И Справочник.Реквизит2 = """ "
...
```

Еще пример.
Должно быть:
```bsl
...
|ГДЕ
|     Справочник.Реквизит1 = """"
...
```
Форматируется:
```bsl
...
|ГДЕ
|     Справочник.Реквизит1 = """ "
...
```
Версия плагина: 1.16.0

**Comment by nixel2007** [comment]
Поправится автоматом после исправления https://github.com/1c-syntax/bsl-parser/issues/41

**Comment by kodemi** [comment]
> Спасибо за репорт!
> 
> Подскажите, вы пользуетесь форматером от BSL Language Server (по умолчанию) или legacy-вариантом? Свойство "Language Server Enabled"
> ![image](https://user-images.githubusercontent.com/1132840/63264493-e0435180-c293-11e9-8474-651b40415faa.png)

Да, флажок стоит напротив "Language Server Enabled".
