### ISSUE TITLE
[BUG] Лексема "По" для цикла в EN варианте должно быть "To", а не "For"

### ISSUE THREAD

**Issue by Bayselonarrend** [1c-syntax/bsl-language-server#3293]
## Диагностика
CanonicalSpellingKeywords

## Описание ошибки диагностики
"По" для цикла в EN варианте должно быть "To", а не "For"

## Скриншоты

![изображение](https://github.com/1c-syntax/bsl-language-server/assets/105596284/0dba6bc5-b74c-4b24-9a39-78c16dc65d33)
![изображение](https://github.com/1c-syntax/bsl-language-server/assets/105596284/948abf6d-058a-4374-a939-fd2c88a59984)
![изображение](https://github.com/1c-syntax/bsl-language-server/assets/105596284/c9ac7f40-1a56-41cf-a7bb-04b9b53d27bd)

## Дополнительная информация
Может есть еще какое-то "По"?

**Comment by nixel2007** [comment]
Кажется, это ошибка документации. Спасибо! Не желаете ли прислать исправление? :)

**Comment by Bayselonarrend** [comment]
>Кажется, это ошибка документации. Спасибо! Не желаете ли прислать исправление? :)

Это ошибка только в этом мдшнике?

**Comment by nixel2007** [comment]
Да, я проверил код, в самой диагностике используются корректные токены.
