### ISSUE TITLE
Using "goto" ruleName not localized

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#331]

**Comment by nixel2007** [comment]
@asosnoviy пофикшено же? https://github.com/1c-syntax/bsl-language-server/commit/b87b5d3342039fde423734530ca4aeee358dfb2c

**Comment by asosnoviy** [comment]
Ага, это я в сборке сонар угледел. А там сборка оказывается не от 10.1, а от какого то коммита.
