### ISSUE TITLE
[BUG] форматер некорректно исправляет Или Не на ИЛИ НЕ

### ISSUE THREAD

**Issue by tropin-ak** [1c-syntax/bsl-language-server#3326]
**Версия**
0.23.1

**Описание ошибки диагностики**
форматер некорректно исправляет Или Не на ИЛИ НЕ

**Пример кода**
```sh
java -jar "bsl-language-server-0.23.1-exec.jar" --format --src ./ -c ".bsl-language-server.json"
```

**Скриншоты**

**Дополнительная информация**
пробовал разные настройки, 
**настройка 1**
```json
"formatting": {
		"useUpperCaseForOrNotKeywords": true,
		"useKeywordsFormatting": true
	}
```

```bsl
"Если Не Записать() Или Отказ Тогда" меняет на "Если НЕ Записать() ИЛИ Отказ Тогда"
```

**настройка 2**
```json
  "formatting": {
                "useUpperCaseForOrNotKeywords": false,
                "useKeywordsFormatting": true
        }
```

```bsl
"Если Не Записать() Или Отказ Тогда" меняет на "Если НЕ Записать() ИЛИ Отказ Тогда"
```

**настройка 3**

```json
  "formatting": {
                "useUpperCaseForOrNotKeywords": false,
                "useKeywordsFormatting": false
        }
```

useKeywordsFormatting отключен, поэтому ничего не меняется

**Comment by nixel2007** [comment]
Кажется, в документации ошибка. Свойство называется `useUpperCaseForOrNotAndKeywords`

**Comment by nixel2007** [comment]
Проверьте с ним, пожалуйста

**Comment by tropin-ak** [comment]
да, подошла настройка
"formatting": {
                "useUpperCaseForOrNotAndKeywords": false,
                "useKeywordsFormatting": true
        }
Предлагаю сделать её настройкой по умолчанию

**Comment by nixel2007** [comment]
Умолчание будет с апперкейсом, так как это каноническое написание, а вот имя настройки я конечно же поправлю.
