### ISSUE TITLE
Позиционирование Несколько директив компиляции

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#340]
![image](https://user-images.githubusercontent.com/15638529/64451732-7cbb7f80-d0ed-11e9-992c-80499b8646d3.png)

**Comment by theshadowco** [comment]
надо на имя спозионировать?

**Comment by asosnoviy** [comment]
> надо на имя спозионировать?

Или на `Процедура`. Можно еще с secondaryLoc поупражняться.

**Comment by asosnoviy** [comment]
Короче куда там проще по грамматике, туда и повесить.

**Comment by theshadowco** [comment]
окай

**Comment by nixel2007** [comment]
Я бы на директивы или имя метода повесил. И все директивы в secondary loc.

**Comment by theshadowco** [comment]
на имя метода повешу

**Comment by nixel2007** [comment]
Напоминаю, что subNameRange есть теперь в MethodSymbol

**Comment by theshadowco** [comment]
да, нашел.

**Comment by theshadowco** [comment]
теперь надо и для глобальных переменных модуля формы

**Comment by theshadowco** [comment]
Готово
