### ISSUE TITLE
Массовое форматирование через cli

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#346]
`java -jar bsl-language-server.jar format path`

Путь? Шаблон? --srcDir?

**Comment by theshadowco** [comment]
мож распишешь? чего надо то

**Comment by nixel2007** [comment]
Новую команду в entrypoint. Там уже есть analyze и обычный запуск в режиме сервера. Хочу добавить третий режим, для запуска форматтера. Получить каталог, зачитать из него все os/bsl файлы (как это делает analyze), прогнать через FormatProvider, полученные тексты записать обратно в файлы.
