### ISSUE TITLE
Тэги диагностикам

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#357]
Необходимо реализовать возможность указания тэгов для диагностик (можно указать несколько). 
Пример тэгов
 - OnlyLinux - для диагностик актуальных для linux
 - Standart - диагностики относящиеся к стандарту разработки 1С
 - SQL - отнится к запросам
 - Metadata - к метаданным 
 - NoEDT - не актуальна для EDT, есть своя реализация
и т.д.

Кроме указания диагностик необходимо доработать 
 - репортеры (в частности junit)
 - конфиги - для возможности отключения / включения диагностик по тэгу
 - плагин для сонара - подгружать в тэги правил
 - плагин для EDT - отключать диагностики по тэгу без необходимости хардкодить

**Comment by theshadowco** [comment]
Собираю список тэгов, который сразу добавим (в т.ч. в доку)

- [x] ONLYLINUX - Только для Linux
- [x] STANDARD - Стандарт разработки 1С
- [x] SQL - Запросы
- [x] PERFORMANCE - Производительность

**Comment by theshadowco** [comment]
Варианты

- [ ]  БСП - Использование возможностей БСП
- [ ] DepecatedCode - Устаревший метод ... 
- [ ] **Depecated - Устаревшее правило**

**Comment by nixel2007** [comment]
> Depecated - Устаревшая диагностика

кажется, это лучше отдельной аннотацией. и как-нибудь по особому обрабатывать и в диагностик-провайдере и в сонаре

**Comment by theshadowco** [comment]
ага
