### ISSUE TITLE
Шаблон диагностики

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#359]
Придумать шаблон диагностики для возможности его автоматического наполнения и обновления. 

Например

```
#<Description> - заполняется автоматически из соответствующего ресурса

<Описание заполняется вручную>

## <EXCLUDE> <OPTIONAL> - заполняется из класса автоматически при наличии

## Примеры

<Заполняется вручную>

## Источники
<Заполняется вручную>

## Параметры

<Заполняется> автоматически из класса

```

**Comment by theshadowco** [comment]
Примеры 

До

![image](https://user-images.githubusercontent.com/9591731/67364875-1abdb900-f579-11e9-87f5-1f1ce5839782.png)

После 

![image](https://user-images.githubusercontent.com/9591731/67364906-2b6e2f00-f579-11e9-9bd8-951ff206410f.png)

**Comment by theshadowco** [comment]
Для понимания, блок с первой строки до "##Описание" генерируется автоматически и перезатирается

**Comment by asosnoviy** [comment]
@DoublesunRUS старый ишуз #151 закрыли. Этот должен удовлетворить твое желание.

**Comment by nixel2007** [comment]
Верхнюю табличку бы сделать плоской. 5 колонок 2 строки

**Comment by nixel2007** [comment]
Параметры под описание

**Comment by theshadowco** [comment]
1. ![image](https://user-images.githubusercontent.com/9591731/67373627-a4c14e00-f588-11e9-899a-b6f57618a2e6.png)

2. ![image](https://user-images.githubusercontent.com/9591731/67373671-b30f6a00-f588-11e9-8e5c-ebe2931ecd01.png)

3. ![image](https://user-images.githubusercontent.com/9591731/67373710-bf93c280-f588-11e9-95db-0c5824833682.png)

**Comment by theshadowco** [comment]
полосочки справа - это у меня курсор стоит
