### ISSUE TITLE
Настройки диагностик

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#36]
Какие диагностики применять/исключать при анализе.
* Конкретный список
* По важности
* По области действия

Индивидуальные настройки, у каждой диагностики свои параметры
* Максимальная длинна строки
* Разрешить однотипные присваивания в одной строке
* и т.д.

**Comment by nixel2007** [comment]
туда же: язык диагностик (параметр --diagnosticLanguage).
