### ISSUE TITLE
Совместное использование НСтр() и СтрШаблон()

### ISSUE THREAD

**Issue by qtLex** [1c-syntax/bsl-language-server#365]
#### Из АПК:
Требование - Ограничение на использование метода "СтрШаблон()" в коде модулей
Правило - Поиск метода "СтрШаблон()"
Ошибка - Использование метода "СтрШаблон()" (456)

#### Описание
Например, имеем следущий код в модулях конфигурации:
```
ШаблонТекста = НСтр("ru='Первый параметр %1, второй параметр %2'");
Текст = СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(ШаблонТекста, 1, 2);
```

Избавимся от прослойки вызовов и лишних методов с помощью метода СтрШаблон():

```
ШаблонТекста = НСтр("ru='Первый параметр %1, второй параметр %2'");
Текст = СтрШаблон(ШаблонТекста, 1, 2);
```
Конфигурация не всегда сразу полностью переводится на другой язык. И, если в системе будет работать пользователь, у которого будет установлен язык не RU, то первый код отработает корректно, а второй выдаст ошибку исполнения.

Во втором случае локализованной строки нет, следовательно, параметров в строке нет,  следовательно, возникает ошибка исполнения.

*В связи с этим, в модулях конфигураций принято решение не использовать СтрШаблон() до исправления ошибки платформы.*

#### Предлагаемая критичность:
ERROR
MAJOR
1 min

**Comment by nixel2007** [comment]
Я что-то смысла диагностики не понимаю. Не вызывать СтрШаблон поверх НСтр? Если да, то это не КодСмелл, это потенциальный баг и эксепшен в рантайме

**Comment by qtLex** [comment]
> Не вызывать СтрШаблон поверх НСтр? Если да, то это не КодСмелл, это потенциальный баг и эксепшен в рантайме

Согласен. Внес изменения в первоначальный текст.

Тут правда не понятно насколько жестким быть.

Ругаться только на явно вложенные вызовы или вообще на использование СтрШаблон().

Формирование строки шаблона и ее использование в СтрШаблон() может быть в разных местах. Из-за этого не всегда удастся отследить связь.
В АПК предлагают радикальное рещение - не использовать никогда функцию , а всегда использовать метод БСП. Ссылки на стандарт нет

**Comment by qtLex** [comment]
Думаю, начну с мест где взаимосвязь очевидна. А там разовью мысль.
Можно за мной задачу закрепить?

**Comment by nixel2007** [comment]
> не использовать никогда функцию , а всегда использовать метод БСП

Не, ну это перебор имхо О_о

@zeegin ?

**Comment by nixel2007** [comment]
@qtLex давай действительно начнем с НСтр вложенного в СтрШаблон. посмотрим на срабатывания

**Comment by zeegin** [comment]
>  не использовать никогда функцию , а всегда использовать метод БСП
@nixel2007 

Суть проблемы:
`NStr` в мультиязычной конфигурации имеет разные фрагменты для разных языков.
Если запустить сеанс под кодом языка, которого нет в строке передаваемой в `NStr` то она вернет пустую строку.
Обычно конфигурации переводят не сразу, а поэтапно. Потому получается, что могут возникнуть случаи, когда `NStr` возвращает пустую строку. При этом в общем случае это к проблемам не приводит - просто будет дерьмовый интерфейс без текста.
Но если в `StrTemplate` передать первым параметром пустую строку, то будет исключение. Потому в не полностью переведенных конфигурациях критично чтобы хотябы те `NStr` которые используются первым параметров в `StrTemplate` всегда имели перевод для каждого объявленного в конфигурации языка.

Такая проблема в общем то не только для `StrTemplate` свойственна, но еще и тут https://its.1c.ru/db/v8std/content/763/hdoc

Правильно правило проверки будет выглядеть так:
- Для каждой `NStr` должен быть задан перевод для каждого кода языка в информационной базе. ERROR MINOR
- Для `NStr` используемой в `StrTemplate` всегда должен быть задан перевод для каждого языка ИБ. ERROR MAJOR.

Особенность метода БСП в том, что оно не бросает исключения и просто не выводит строку, если шаблон ей передать пустой. Потому при использовании метода БСП это MINOR.

**Comment by nixel2007** [comment]
Тэкс. тут нам тогда нужны данные конфигурации, а конкретно о языках. @otymko ?

**Comment by qtLex** [comment]
А можем ли мы получить вообще перечень языков?

Конечный потребитель не всегда под контролем. Если пользователь запуститься на не поддерживаемом языке у него исключения вылетать не должны. Кривой интерфейс конечно не хорошо, но исключения совсем плохо.

@nixel2007 может тогда тут несколько диагностик?:
1. Для каждой NStr должен быть задан перевод для каждого кода языка в информационной базе. ERROR MINOR
2. Для NStr используемой в StrTemplate всегда должен быть задан перевод для каждого языка ИБ. ERROR MAJOR.
3. Замените СтрШаблон() на метод из БСП. ERROR MAJOR.

**Comment by zeegin** [comment]
> Замените СтрШаблон() на метод из БСП. ERROR MAJOR.

Я бы такое не делал.
АПК сделали такое правило, потому что не смогли нормально реализовать первые два.

**Comment by qtLex** [comment]
> Замените СтрШаблон() на метод из БСП. ERROR MAJOR.
Тоже не горю желанием запрещать использовать метод платформы.

**Comment by nixel2007** [comment]
Да, тоже хотел разделить на 2 правила. запрет делать не стоит.

но за списком языков надо подождать метаданных, иначе будет FP

**Comment by nixel2007** [comment]
@qtLex - вроде обе диагностики готовы, да? Закрываем?

**Comment by qtLex** [comment]
@nixel2007 Да. Можно закрывать.
Я вроде в шапке pr номер указал. Или нужно именно close #<номен>?

**Comment by nixel2007** [comment]
Да, нужно ключевое слово. Fix, fixes, close или closes.
