### ISSUE TITLE
Рандомное падение прогресс-бара в некоторых терминалах

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#369]
org.github._1c_syntax.bsl.languageserver.BSLLSPLauncherTest > testAnalyze() FAILED
    java.lang.AssertionError at BSLLSPLauncherTest.java:105

https://github.com/1c-syntax/bsl-language-server/commit/85bac23c7fa01d4a20282f38a66db438beb901cc/checks

**Comment by ovcharenko-di** [comment]
@nixel2007, я правильно понимаю, что это скорее всего из-за асинхронности тест не успевает прочитать вывод команды?

**Comment by nixel2007** [comment]
@ovcharenko-di затрудняюсь сказать. я вчера пытался отладить, в cli падает, в идее - нормально. под 8 и под 11, не важно. на трависе в cli вон работает, на GA - падает.

Я ловил сам эксепшен - там NPE. но оно вообще без контекста и стэка. Причем самое странное, что если убрать аннотацию на отлов вызова `System.exit` и `try`, оно все равно падает с NPE, позиционируясь на вызов BSLLauncher.main(args), хотя в этой строке точно не может быть NPE, т.к. это статик метод

**Comment by nixel2007** [comment]
@theshadowco смотри, что поймал через gradlew test --stacktrace

![image](https://user-images.githubusercontent.com/1132840/66055096-b0979280-e53d-11e9-9dc9-a9e3d5765d7f.png)

**Comment by qtLex** [comment]
@nixel2007 ты в cmder запускаешь? Я только на нем такое поймать смог.

**Comment by nixel2007** [comment]
@qtLex да. Но у @TheShadoWCo такая же проблема была в терминале IDEA

**Comment by nixel2007** [comment]
Вроде после фикса не воспроизводится. Считаем, что исправлено.
