### ISSUE TITLE
Вставка в коллекцию ссылки на саму себя

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#372]
Утечка памяти.

Массив = Новый массив;
Массив.Добавить(Массив);

https://its.1c.ru/db/metod8dev#content:5859:hdoc

**Comment by otymko** [comment]
Словил такое недавно?

**Comment by asosnoviy** [comment]
Не я, но говорят в УХе есть.

**Comment by asosnoviy** [comment]
@qtLex Забрал
