### ISSUE TITLE
Ложное срабатывание правила "Нарушение парности использования методов "НачатьТранзакцию()" и "ЗафиксироватьТранзакцию()" / "ОтменитьТранзакцию()""

### ISSUE THREAD

**Issue by AlexPCRus** [1c-syntax/bsl-language-server#384]
Полностью код привести не могу, структура процедуры следующая:

Процедура Процедура1()

	// {{ ++
	НачатьТранзакцию();
	// }} --
	Попытка
		
		// {{ ++
		// НачатьТранзакцию();
		// }} --
		
		<код>
		
		ЗафиксироватьТранзакцию();
		
	Исключение

	    ОписаниеОшибки = ОписаниеОшибки();
		// Откатим транзакцию
		ОтменитьТранзакцию();
	КонецПопытки;		

КонецПроцедуры

как видно из кода, я специально вынес начатьтранзакцию() вне блока попытка - исключение - конецпопытки, но проверку этот код все равно не проходит.

**Comment by AlexPCRus** [comment]
Где Вы видите что транзакция начинается дважды?

**Comment by AlexPCRus** [comment]
Методом проб я понял что проблема в том, что в теле условного оператора, который я цитировал выше содержится оператор ОтменитьТранзакцию(). Похоже что правило считает общее количество операторов в процедуре и не в силах понять, что у процедуры несколько точек возврата.

**Comment by theshadowco** [comment]
В соответствии со стандартом - это является нарушением, необходимо скорректировать код.

**Comment by nixel2007** [comment]
@AlexPCRus первая и третья значимая строка в первом сообщении в ишузе. Два раза НачатьТранзакцию

**Comment by AlexPCRus** [comment]
Третья строка кода закомментирована и не оказывает влияния на проверку.

**Comment by AlexPCRus** [comment]
theshadowco, виноват, никак не справлюсь с цитированием, то есть Вы хотите сказать что по стандарту не должно быть больше одной отмены транзакции на каждое ее начало? И в теле процедуры необходимо все ветвления с последующей отменой транзакции свести к одной?

**Comment by nixel2007** [comment]
@AlexPCRus Оу, слона-то я и не заметил. Извиняюсь.

**Comment by zeegin** [comment]
@AlexPCRus 
>И в теле процедуры необходимо все ветвления с последующей отменой транзакции свести к одной?
Да, замени 
```
Если ЗначениеЗаполнено(ТекстОшибки) Тогда
	ЗаписатьСтрокуЛога("Ошибка Веб-сервиса: "+ТекстОшибки, , "err");
	ОтменитьТранзакцию();
	Возврат;
КонецЕсли;
```
На
```
Если ЗначениеЗаполнено(ТекстОшибки) Тогда
	ВызватьИсключение СтрШаблон(НСтр("ru = 'Ошибка Веб-сервиса: %1'"), ТекстОшибки);
КонецЕсли;
```

**Comment by AlexPCRus** [comment]
Я понял. Ну я вообще вынес код за пределы транзакции, так как по логике в случае ошибки получения данных из сервиса смысла стартовать транзакцию нет. А совет по использованию "ВызватьИсключение" приму к сведению.

**Comment by phsin** [comment]
в стандартной конфигурации 1С Торговля такой код: 
и правило использования методов "НачатьТранзакцию()" и "ЗафиксироватьТранзакцию()" / "ОтменитьТранзакцию()" соблюдается ...

`
Процедура ПриЗаписи()
        ...
	НачатьТранзакцию();

	Попытка
		Записать();

	Исключение
		ОтменитьТранзакцию();
		Сообщить("Запись контрагента: " + ОписаниеОшибки(), "!");
		Возврат;

	КонецПопытки;

	Попытка
		Если ЗаписьЮрФизЛица() = 0 Тогда
			ОтменитьТранзакцию();
			Возврат;
		КонецЕсли;

	Исключение
		ОтменитьТранзакцию();
		Сообщить("Запись юр.(физ.) лица: " + ОписаниеОшибки(), "!");
		Возврат;

	КонецПопытки;

	Попытка
		Если ЗаписьОснДоговора() = 0 Тогда
			ОтменитьТранзакцию();
			Возврат;
		КонецЕсли;

	Исключение
		ОтменитьТранзакцию();
		Сообщить("Запись основного договора: " + ОписаниеОшибки(), "!");
		Возврат;

	КонецПопытки;

	Попытка
		Если ЗаписьОснСчета() = 0 Тогда
			ОтменитьТранзакцию();
			Возврат;
		КонецЕсли;

	Исключение
		ОтменитьТранзакцию();
		Сообщить("Запись основного счета: " + ОписаниеОшибки(), "!");
		Возврат;

	КонецПопытки;

	Попытка
		Если ЗаписьОснСвойства() = 0 Тогда
			ОтменитьТранзакцию();
			Возврат;
		КонецЕсли;

		СохранитьЗначение("ОсновноеСвойствоКонтрагентов", Свойство);
		ЗафиксироватьТранзакцию();
		СтатусВозврата(1);

	Исключение
		ОтменитьТранзакцию();
		Сообщить("Запись основного свойства: " + ОписаниеОшибки(), "!");

	КонецПопытки;

КонецПроцедуры // ПриЗаписи()
`

**Comment by nixel2007** [comment]
Ну оно же все непарное :)

**Comment by phsin** [comment]
парный вызов кода, а не парное написание кода ;)

**Comment by phsin** [comment]
если ошибка происходит в одной из процедур - отменяется вся транзакция, разве нет?

**Comment by zeegin** [comment]
Нет.
если ошибка происходит в одной из процедур - транзакция помечается как транзакция с ошибкой. Реально транзакция отмениться тогда, когда будет вызван метод `ЗафиксироватьТранзакцию` или `ОтменитьТранзакцию`.

См. https://its.1c.ru/db/v8std#content:783:hdoc пункт 1.1

**Comment by phsin** [comment]
> Нет.
> если ошибка происходит в одной из процедур - транзакция помечается как транзакция с ошибкой. Реально транзакция отмениться тогда, когда будет вызван метод `ЗафиксироватьТранзакцию` или `ОтменитьТранзакцию`.
> 
> См. https://its.1c.ru/db/v8std#content:783:hdoc пункт 1.1

это и показано в примере - ОтменитьТранзакцию может вызываться несколько раз

**Comment by zeegin** [comment]
@phsin Давай будем честны. Этот код будет работать. Он будет работать без ошибок в транзакциях. Но это дерьмовый стиль написания кода.

Можно писать компактнее, понятнее, и добиваться более простой поддержки, например:

```
 Процедура ПриЗаписи()
        
	НачатьТранзакцию();
	Попытка
                // А тут еще надо ставить блокировки!
      
		Записать();
		ЗаписьЮрФизЛица();
                ЗаписьОснДоговора();
                ЗаписьОснСчета();
                ЗаписьОснСвойства();
                
                ЗафиксироватьТранзакцию();
	Исключение
		ОтменитьТранзакцию();
                ЗаписьЖурналаРегистрации("Область", УровеньЖурналаРегистрации.Ошибка,,, ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));
	КонецПопытки;

КонецПроцедуры
```

**Comment by phsin** [comment]
@zeegin  да согласен, так намного красивее и понятнее. Спасибо!

**Comment by asosnoviy** [comment]
Со всем изложенным согласен, но там формировались сообщения, думаю из-за них такой стиль и вышел.

**Comment by zeegin** [comment]
Нефиг формировать сообщения в бизнес-логике.
Исключение само по себе отличное сообщение которое корректно будет отработано платформой.
Если нужно что-то дополнительно сообщать - о том как это делать должен решать тот кто будет делать фронтенд а не тот кто пишет бизнес-логику.

Я бы вообще с удовольствием запретил использовать Новый СообщениеПользователю как таковое везде кроме модулей форм. Код был бы чище.
