### ISSUE TITLE
Заменить баджик с трависа на GA

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#387]
На странице проекта изменить баджик сборки

`[![Actions Status](https://github.com/1c-syntax/bsl-language-server/workflows/Java%20CI/badge.svg)](https://github.com/1c-syntax/bsl-language-server/actions)`

[![Actions Status](https://github.com/1c-syntax/bsl-language-server/workflows/Java%20CI/badge.svg)](https://github.com/1c-syntax/bsl-language-server/actions)

Подумать над названием workflow

**Comment by asosnoviy** [comment]
Не понял как оно работает, как будто по последнему запуску. Как повесить на конкретную верку пока не осознал

**Comment by theshadowco** [comment]
@asosnoviy  

https://github.com/CultureHQ/github-actions-badge

https://xxx.execute-api.us-west-2.amazonaws.com/production/badge/{owner}/{repo}?branch={branch}

**Comment by theshadowco** [comment]
насколько я понимаю, на ветку никак не прикрутить https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

только создавать разный worflow

**Comment by theshadowco** [comment]
> Status badges show whether a workflow is currently failing or passing. A common place to add a status badge is in the README.md file of your repository, but you can add it to any web page you'd like. Badges display the status of your default branch (usually master).

**Comment by nixel2007** [comment]
> Badges display the status of your default branch (usually master).

У нас дефолтный бранч - это девелоп. Разве это не то, что нам нужно?

**Comment by asosnoviy** [comment]
> > Badges display the status of your default branch (usually master).
> 
> У нас дефолтный бранч - это девелоп. Разве это не то, что нам нужно?

Он показывает не дефолтный, а "верхний" из workflow

**Comment by theshadowco** [comment]
> > > Badges display the status of your default branch (usually master).
> > 
> > 
> > У нас дефолтный бранч - это девелоп. Разве это не то, что нам нужно?
> 
> Он показывает не дефолтный, а "верхний" из workflow

Постим баг гитхабавцам?
