### ISSUE TITLE
Хелперы в Trees

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#389]
- [ ] найти соседей
- [ ] найти соседей справа
- [x] найти соседа справа
- [ ] найти соседей слева
- [x] найти соседа слева
- [x] Найти предка по типу

**Comment by otymko** [comment]
* Найти предка по типу

**Comment by theshadowco** [comment]
В trees уже есть отмеченные

**Comment by theshadowco** [comment]
эту закрываю. 
Остальные хэлперы https://github.com/1c-syntax/bsl-language-server/issues/979
