### ISSUE TITLE
У процедуры (функции) в модуле формы/модуле команды отсутствует директива компиляции

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#395]
Платформа позволяет в модулях форм реализовывать процедуры без директив компиляции (&НаСервере и т.п.). Такие процедуры не работают в веб-клиенте и приводят к лишнему серверному вызову. (из описания в АПК)

**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**
В АПК указан этот стандарт https://its.1c.ru/db/v8std#content:467:hdoc
Еще есть https://its.1c.ru/db/v8std#content:439:hdoc

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [x] Ошибка
* [ ] Уязвимость
* [ ] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [x] Критическая / Critical
* [ ] Важная / Major
* [ ] Незначительная / Minor
* [ ] Информационная / Info
* [ ] Другое

**Comment by asosnoviy** [comment]
Действительно веб клиент не работает если не указана директива компиляции?
