### ISSUE TITLE
Кейсы и прочие свичи должны содержать Иначе

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#40]
```BSL
Если x % 15 = 0 Тогда
	Результат = "FizzBuzz";
ИначеЕсли x % 3 = 0 Тогда
	Результат = "Fizz";
ИначеЕсли x % 5 = 0 Тогда
	Результат = "Buzz";
КонецЕсли;
```

**Comment by lChagelishvili** [comment]
Для запроса будет отдельная проверка?

**Comment by nixel2007** [comment]
скорее всего да. у запросов будет отдельные узлы AST. да и вообще было бы хорошо сразу разделять диагностики языка 1с и языка запросов

**Comment by asosnoviy** [comment]
А придумайте кейс с валидным:
```bsl
Если Тогда

ИначеЕсли

КонецЕсли;

```

Пока кажется что такой кейс должен заменятся на

```bsl
Если Тогда

Иначе

КонецЕсли;
```

Или проще прогнать на коде и половить ФП?

**Comment by nixel2007** [comment]
@asosnoviy свитч на расчёт значения переменной с дефолтной инициализацией этой переменной до начала свитча

**Comment by asosnoviy** [comment]
> @asosnoviy свитч на расчёт значения переменной с дефолтной инициализацией этой переменной до начала свитча

Так диагностика вроде про это "Дефотное значение и должно быть в секции Иначе"

Тут наверно вопрос:
Сколько ИначеЕсли считать свичем?

**Comment by nixel2007** [comment]
1 и больше? :)

**Comment by lChagelishvili** [comment]
> Пока кажется, что такой кейс должен заменятся на
> 
> ```bsl
> Если Тогда
> 
> Иначе
> 
> КонецЕсли;
> ```

Я исходил из этих же соображений, поэтому интерпретирую вхождение хотя бы одного ИначеЕсли как свич.
