### ISSUE TITLE
Одинаковые выражения слева и справа от "foo" оператора работает только с простыми выражениями

### ISSUE THREAD

**Issue by qtLex** [1c-syntax/bsl-language-server#403]
**Диагностика**
> Одинаковые выражения слева и справа от "foo" оператора

**Версия**
> 0,10,2

**Описание**
> Диагностика не анализирует сложный выражения.

**Пример кода**
> А И Б ИЛИ А И Б

**Скриншоты**
![Снимок](https://user-images.githubusercontent.com/5488710/66255078-170ff100-e788-11e9-8323-e78b7dd1fb35.PNG)

**Comment by nixel2007** [comment]
Успеешь в 0.11 или перенесём на 0.12?

**Comment by qtLex** [comment]
Давай перенесем в 0,12.

**Comment by theshadowco** [comment]
Может эту диагностику пометим выключенной в 0.11?

**Comment by nixel2007** [comment]
Зачем? 
1. Это FN, а не FP
2. Её уже релизнули, в 0.10 :)

**Comment by theshadowco** [comment]
упс ))

**Comment by theshadowco** [comment]
```
С этой дигностикой все гораздо сложнее - она отлавливает совсем простые совпадения. ниже примеры, когда не работает

    Б = 0;
    С = (А = 1) И (Б = 1) ИЛИ (А = 1) И (Б = 1);
    Если А = 1 ИЛИ А = 1 Тогда
        Б = 1;
    ИначеЕсли 1 = А ИЛИ А = 1 Тогда
        Б = 11;
    ИначеЕсли А = 1 ИЛИ (А = 1) Тогда
        Б = 12;
    ИначеЕсли (А = 1) И (Б = 1) ИЛИ ((А = 1) И (Б = 1) )Тогда
        Б = 13;
    ИначеЕсли (1 = А) ИЛИ (А = 1) Тогда
        Б = 14;
    ИначеЕсли ((1 < А < 2))ИЛИ (1 < А < 2) Тогда
        Б = 15;
    ИначеЕсли (2 > А > 1) ИЛИ (1 < А < 2) Тогда
        Б = 14;
    КонецЕсли;
```

**Comment by theshadowco** [comment]
я так понимаю, нужен отдельный парсер выражений, для выстраивания приоритетов и последовательностей.

**Comment by qtLex** [comment]
> я так понимаю, нужен отдельный парсер выражений, для выстраивания приоритетов и последовательностей.

В первую версию диагностики был внесен ряд упрощений для того, что бы не писать "парсер", который построит дерево с учетом приоритетов операций. Так как это не самая простая задача оказалась.

Сейчас пришло время развить диагностику.
