### ISSUE TITLE
Тест: проверка bsl тестовых файлов всеми диагностиками

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#404]
Случаются ситуации, когда диагностики могут поломать другие диагностики. Тесты диагностик проходят, но если проверять кейсы всеми диагностиками сразу - анализ не проходит.

**Comment by nixel2007** [comment]
Можно сделать на базе текущего теста для команды аналайз, например

**Comment by nixel2007** [comment]
Или теста BSLLSPLauncher (или как он там))

**Comment by theshadowco** [comment]
Вопрос: как понимать, что все хорошо? 
Надо придумать формат пометок мест, где ожидаем срабатывание диагностик (родной и остальных), чтобы при написании своей диагностики не приходилось править тесты во всех ранее созданных.

**Comment by asosnoviy** [comment]
Срабатывания не надо ловить. Надо чтобы не падало.

**Comment by theshadowco** [comment]
Просто на NPE проверять?

**Comment by otymko** [comment]
Типо того. Прошел тест всех кейсом разом или нет.

**Comment by theshadowco** [comment]
Ок, можно и запилить

**Comment by nixel2007** [comment]
@theshadowco у нас есть ~component/dev. точно нужна отдельная метка для тестов?

**Comment by theshadowco** [comment]
счас, не увидел :( слеповат
