### ISSUE TITLE
Отсутствует описание у экспортной переменной

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#415]
**Описание проблемы, ошибки, которую надо диагностировать**
>  2.5.5. Все переменные модуля обычного приложения, модуля управляемого приложения, модуля сеанса, модуля внешнего соединения, а также все экспортируемые переменные должны иметь комментарии. Комментарии должны быть достаточно подробными, чтобы пояснять назначение переменных. Комментарии ставятся в той же строке после переменной. 
Пример:
```
Перем ДиалогРаботыСКаталогом; // Диалог работы с каталогом
```
(ц) АПК
**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**
https://its.1c.ru/db/v8std#content:455:hdoc  п. 2.2 Все переменные модуля должны быть снабжены комментарием, достаточным для понимания их назначения. Комментарий рекомендуется размещать в той же строке, где объявляется переменная.

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [ ] Ошибка
* [ ] Уязвимость
* [x] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [ ] Критическая / Critical
* [ ] Важная / Major
* [x] Незначительная / Minor
* [ ] Информационная / Info
* [ ] Другое

**Comment by zeegin** [comment]
Почему не `Качество кода`?

**Comment by theshadowco** [comment]
а кто сможет реализовать диагностику на "Комментарии должны быть достаточно подробными, чтобы пояснять назначение переменных"?

**Comment by nixel2007** [comment]
СтрДлина(Комментарий) < 20? :)

**Comment by theshadowco** [comment]
// Э т о         д л и н н о е        о п и с а н и е     п е р е м е н н о й

**Comment by zeegin** [comment]
Расстояние Дамирау-Левенштейна > 20.
:)
А если серьезно, кажется достаточно просто проверить что он вообще есть.
