### ISSUE TITLE
Запрет на использование директив компиляции НЕ в модуле формы/команды

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#418]
**Описание проблемы, ошибки, которую надо диагностировать**

> Директивы компиляции:
> 
> `&НаКлиенте (&AtClient)`
> `&НаСервере (&AtServer)`
> `&НаСервереБезКонтекста (&AtServerNoContext)`
> 
> следует применять **только** в коде модулей управляемых форм и в коде модулей команд. В остальных модулях рекомендуется применять инструкции препроцессору.

**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**

https://its.1c.ru/db/v8std#content:439:hdoc

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [x] Ошибка
* [ ] Уязвимость
* [ ] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [x] Критическая / Critical
* [ ] Важная / Major
* [ ] Незначительная / Minor
* [ ] Информационная / Info
* [ ] Другое

**Comment by zeegin** [comment]
Почему директивы компиляции НЕ использовать запрещено?
Их не запрещено использовать. А даже если запретить - всегда можно сделать секцию `Иначе`.

Проблема в другом - нельзя контекст исполнения определить достоверно в клиент-серверных модулях при работе в толстом клиенте управляемом приложении.

Надо запрещать в клиент-серверных модулях использовать директивы: 
- "Сервер" (англ. "Server")
- "Клиент" (англ. Client)

Допустимые конструкции:
```bsl
#Если [Не] ВебКлиент [[И/ Или] [Не] МобильныйКлиент]
#Если [Не] ТонкийКлиент [[И/ Или] [Не] МобильныйКлиент]
#Если [Не] ТолстыйКлиентОбычноеПриложение Тогда
#Если [Не] ВнешнееСоединение Тогда
```
т.к. они пропускают не весь клиентский код, а только какой-то один из видов клиентов.

**Comment by Stepa86** [comment]
@zeegin директивы компиляции запрещено использовать в модулях, которые не являются модулем формы и модулем команды. И вообще это копипаст стандарта. И речь про директивы компиляции, а не инструкции препроцессора. Про инструкции препроцессора это другую диагностику надо
