### ISSUE TITLE
Не допустимые символы в коде

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#419]
**Описание проблемы, ошибки, которую надо диагностировать**

> В текстах модулей не допускается использовать неразрывные пробелы и знак минус "-" в других кодировках (короткое, длинное тире и т.п.).
> 
> Такие символы часто оказываются в тексте модулей при копировании из офисных документов и приводят к ряду сложностей при разработке. Например, не работает поиск фрагментов текста, включающих «неправильные» минусы и пробелы; некорректно выводятся подсказки типов параметров процедур и функций в конфигураторе и расширенная проверка в 1С:EDT; указание «неправильного» минуса в выражениях приведет к синтаксической ошибке.

**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**
https://its.1c.ru/db/v8std#content:456:hdoc п.1.2

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [x] Ошибка
* [ ] Уязвимость
* [ ] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [x] Блокирующая / Blocker
* [ ] Критическая / Critical
* [ ] Важная / Major
* [ ] Незначительная / Minor
* [ ] Информационная / Info
* [ ] Другое

**Дополнительная информация**
Запрещенные символы из диагностики в АПК:

```
Символ(173)
Символ(8210)
Символ(8211)
Символ(8212)
Символ(8213)
Символ(8722)
Символ(160)
```

**Comment by nixel2007** [comment]
Сомневаюсь про баг и блокер

**Comment by Stepa86** [comment]
> Сомневаюсь про баг и блокер

Из-за этой ошибки могут отвалится в том числе и сонар/АПК и гит итп. На само выполнение это конечно не влияет, наверное, но вот на весь инструментарий очень даже.

**Comment by theshadowco** [comment]
с НПП ничего не скажу, но символ вертикального таба мне много крови попортил
