### ISSUE TITLE
Неправильный перенос выражения

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#420]
**Описание проблемы, ошибки, которую надо диагностировать**
2. Длинные арифметические выражения переносятся следующим образом: 

в одной строке может находиться более одного операнда; 
при переносе знаки операции пишутся в начале строки (а не в конце предыдущей строки); 
операнды на новой строке предваряются стандартным отступом, либо выравниваются по началу первого операнда без учета знаков операций.

Пример:

```bsl
СуммаДокумента = СуммаБезСкидки
                 + СуммаРучнойСкидки
                 + СуммаАвтоматическойСкидки;
```

или

```bsl
СуммаДокумента = СуммаБезСкидки
    + СуммаРучнойСкидки
    + СуммаАвтоматическойСкидки;
```
3.2. В общем случае при конкатенации строк знак "+" рекомендуется писать в начале строки, так же как и при переносе арифметических выражений (см. п.2), например:

```bsl
ПоляОтбора = "Номенклатура,Характеристика,Склад"
   + ДополнительныеПоляОтбора;
```
3.3. При конкатенации длинных строк знак "+" можно писать в конце строки, чтобы не ломать общее форматирование текста. Например,

```bsl
ТекстЗапроса = ТекстЗапроса +
"ВЫБРАТЬ
| Номенклатура.Ссылка КАК Ссылка
|ИЗ
| Справочник. Номенклатура КАК Номенклатура";
```
4. При необходимости параметры процедур, функций и методов следует переносить следующим образом: 

- параметры выравниваются по началу первого параметра, либо предваряются стандартным отступом; 
- закрывающая скобка и разделитель операторов ";" пишутся в той же строке, что и последний параметр;
- также допустим и способ форматирования, который предлагает функция автоформатирования в конфигураторе (см. п. 5).

Пример:

```bsl
ИменаДокументов = Новый СписокЗначений;
ИменаДокументов.Добавить(Метаданные.Документы.СтрокаВыпискиРасход.Имя, 
                         Метаданные.Документы.СтрокаВыпискиРасход.Синоним);
ИменаДокументов.Добавить(Метаданные.Документы.РасходныйКассовыйОрдер.Имя, 
                         Метаданные.Документы.РасходныйКассовыйОрдер.Синоним);
```

или

```bsl
ИменаДокументов = Новый СписокЗначений;
ИменаДокументов.Добавить(Метаданные.Документы.СтрокаВыпискиРасход.Имя, 
    Метаданные.Документы.СтрокаВыпискиРасход.Синоним);
ИменаДокументов.Добавить(Метаданные.Документы.РасходныйКассовыйОрдер.Имя, 
    Метаданные.Документы.РасходныйКассовыйОрдер.Синоним);
```

5. Сложные логические условия в Если…ИначеЕсли…КонецЕсли следует переносить следующим образом: 

- каждое элементарное условие нужно начинать с новой строки, если длина строки превышает ограничение в 120 символов; 
- логические операторы И, ИЛИ ставятся в начале строки, а не в конце предыдущей строки; 
- все условия предваряются стандартным отступом, либо выравниваются по началу первого условия, без учета логического оператора (для выравнивания выражений относительно первой строки рекомендуется использовать пробелы).

Примеры:

```bsl
Если (ВидОперации = Перечисления.ВидыОперацийПоступлениеМПЗ.ПоступлениеРозница)
  ИЛИ (ВидОперации = Перечисления.ВидыОперацийПоступлениеМПЗ.ПоступлениеРозницаКомиссия) Тогда
  Возврат Истина;
КонецЕсли;
```

```bsl
Если ((СтруктураМодуля[Индекс].Блок = Перечисления.ТипыБлоковМодулей.ЗаголовокПроцедуры)
  ИЛИ(СтруктураМодуля[Индекс].Блок = Перечисления.ТипыБлоковМодулей.ЗаголовокФункции))
  И(Найти(ВРЕГ(СтруктураМодуля[Индекс].Текст), КлючБлока)> 0) Тогда
```

**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**

https://its.1c.ru/db/v8std#content:444:hdoc

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [ ] Ошибка
* [ ] Уязвимость
* [x] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [ ] Критическая / Critical
* [ ] Важная / Major
* [ ] Незначительная / Minor
* [x] Информационная / Info
* [ ] Другое

**Дополнительная информация**
В АПК реализовано так:
Строка не может начинаться с ")", ";", ");" и не может заканчиваться на "+", "-", "*", "/", "И", "ИЛИ", "OR", "AND".

**Comment by theshadowco** [comment]
Охтыж ептить!

Штука клевая, особенно если к ней будут квикфиксы ))

**Comment by zeegin** [comment]
Я люблю писать
```bsl
ВызовМетода(
    Параметр1,
    Параметр2
);
```
Прошу сделать возможность отключения проверки такого варианта переноса.

**Comment by Stepa86** [comment]
Стандарт суров, но он стандарт

**Comment by nixel2007** [comment]
@zeegin тоже так пишу и другим советую. В команде про стандарт знают, но осознанно его нарушают по общему соглашению.

**Comment by theshadowco** [comment]
я так пишу для длинных вызовов, точнее для длинных параметров

**Comment by theshadowco** [comment]
и кстати, стандарт стандартом, но никто не мешает реализовать поддержку "своего стандарта", если большая часть участников проекта так делает

**Comment by Stepa86** [comment]
Поддержка единого код-стайла на проекте это космос. Для него нужно тогда еще:
1. Указание настроек - как правильно, а как нет
1.1 Пробелы
1.2 Переносы выражений
1.3 Правила именований
1.4 ...
2. Ругаться на неправильно
3. Квик-фиксы на неправильно
4. Форматтер должен делать все сразу правильно

Я вот после этого видосика https://www.youtube.com/watch?v=lJmQL5pbCPs&t=3740s активно хочу единого код-стайла на проекте

**Comment by huxuxuya** [comment]
Хочу взять задачу в работу.

**Comment by theshadowco** [comment]
@huxuxuya назначил
