### ISSUE TITLE
Запрет на использование ДанныеФормыВЗначение

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#421]
**Описание проблемы, ошибки, которую надо диагностировать**

> В большинстве случаев, в модулях форм следует использовать метод формы РеквизитФормыВЗначение вместо метода ДанныеФормыВЗначение. 
> 
> Рекомендация обусловлена соображениями унификации прикладного кода и тем, что синтаксис метода РеквизитФормыВЗначение проще, чем у ДанныеФормыВЗначение (а следовательно, меньше вероятность ошибки).
> В ДанныеФормыВЗначение необходимо дополнительно передавать тип значения:
> 
> `ТаблицаПодписей = ДанныеФормыВЗначение(ТаблицаПодписей, Тип("ТаблицаЗначений"));`
> 
> а для РеквизитФормыВЗначение это не обязательно, а в практическом плане - избыточно:
> 
> `ТаблицаПодписей = РеквизитФормыВЗначение("ТаблицаПодписей");`
> 
> Наличие в платформе 1С:Предприятие метода формы РеквизитФормыВЗначение (наряду с методом глобального контекста ДанныеФормыВЗначение) объясняется только удобством его применения. С точки зрения эффективности и результата методы работают одинаково.
> 

**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**
https://its.1c.ru/db/v8std#content:409:hdoc

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [ ] Ошибка
* [ ] Уязвимость
* [x] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [ ] Критическая / Critical
* [ ] Важная / Major
* [ ] Незначительная / Minor
* [x] Информационная / Info
* [ ] Другое

**Comment by asosnoviy** [comment]
В модулях форм. Нужны метаданные.

**Comment by Stepa86** [comment]
> В модулях форм. Нужны метаданные.

Везде нельзя, т.к. применимо только к формам, а юзать можно и в общем модуле, типа Форма.ДанныеФормыВЗначение. Можно ж без метаданных

**Comment by asosnoviy** [comment]
Один метод Формы, второй глобального контекста. Точнее, не помню, надо пробовать.

**Comment by Stepa86** [comment]
> Один метод Формы, второй глобального контекста. Точнее, не помню, надо пробовать.

Во-во, постоянно надо помнить. Лучше запретить кхерамвезде и пусть машина думает
