### ISSUE TITLE
Запрет на использование РольДоступна()

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#425]
**Описание проблемы, ошибки, которую надо диагностировать**

> 3. Для проверки прав доступа в коде следует использовать метод ПравоДоступа.
> Например, неправильно:
> 
> `Если РольДоступна("ДобавлениеИзменениеСтранМира") Тогда ...`
> `Если РольДоступна("ПросмотрОтчетаПопулярныеСтраны") Тогда ...`
> 
> правильно:
> 
> `Если ПравоДоступа("Редактирование", Метаданные.Справочники.СтраныМира) Тогда ...`
> `Если ПравоДоступа("Просмотр", Метаданные.Отчеты.ПопулярныеСтраны) Тогда ...`
> 
> Такой подход позволяет повысить устойчивость кода к пересмотру состава ролей в конфигурации.

**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**
https://its.1c.ru/db/v8std#content:737:hdoc

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [x] Ошибка
* [ ] Уязвимость
* [ ] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [ ] Критическая / Critical
* [x] Важная / Major
* [ ] Незначительная / Minor
* [ ] Информационная / Info
* [ ] Другое

**Дополнительно**

При этом дальше в стандарте написано

> 4. В тех случаях, где роль не дает никаких прав на объекты метаданных, а служит только для определения того или иного дополнительного права, следует использовать метод РольДоступна. При использовании в конфигурации Библиотеки стандартных подсистем (БСП) следует использовать функцию РолиДоступны общего модуля Пользователи:
> Например, без использования БСП:
> 
> `Если РольДоступна(...) Или <ЭтоПолноправныйПользователь> Или ПривилегированныйРежим() Тогда ...`
> 
> Либо аналогичная проверка с использованием БСП:
> 
> `Если Пользователи.РолиДоступны(...) Тогда ...`

**Comment by asosnoviy** [comment]
Если развивать, то еще РольДоступна не должна быть одна, без проверки привилегерованного режима и полноправного пользователя.
