### ISSUE TITLE
Неэкспортные методы в областях ПрограммныйИнтерфейс и СлужебныйПрограммныйИнтерфейс

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#426]
**Описание проблемы, ошибки, которую надо диагностировать**

> - Раздел «Программный интерфейс» **содержит экспортные процедуры и функции**, предназначенные для использования другими объектами конфигурации или другими программами (например, через внешнее соединение).
> - Раздел «Служебный программный интерфейс»  предназначен для модулей, которые являются частью некоторой функциональной подсистемы. В нем д**олжны быть размещены экспортные процедуры и функции**, которые допустимо вызывать только из других функциональных подсистем этой же библиотеки.

**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**
https://its.1c.ru/db/v8std#content:455:hdoc

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [ ] Ошибка
* [ ] Уязвимость
* [x] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [ ] Критическая / Critical
* [x] Важная / Major
* [ ] Незначительная / Minor
* [ ] Информационная / Info
* [ ] Другое

**Comment by zeegin** [comment]
Не экспортные - это не ошибка. Это качество кода. Т.к. оно к проблемам не приведет, но будут неправильно работать анализаторы рассчитывающие на области видимости.

**Comment by theshadowco** [comment]
смержили, поэтому поменял майлстоун
