### ISSUE TITLE
Запрет на Параметры.Свойство("АвтоТест")

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#427]
**Описание проблемы, ошибки, которую надо диагностировать**

> 3. Программные модули не должны иметь закомментированных фрагментов кода, а также фрагментов, которые каким-либо образом связаны с процессом разработки (отладочный код, служебные отметки, например, TODO, MRG и т.п.) и с конкретными разработчиками этого кода.
> 
> Стандарт 772 "Взаимодействие со средствами автоматизированного тестирования" был отменен.
> В связи с этим, больше не нужна проверка параметра "АвтоТест" в коде форм:
> 
> ```bsl
> Если Параметры.Свойство("АвтоТест") Тогда
> Возврат;
> КонецЕсли;
> ```
> 
> и обработчике ОбработкаЗаполнения модуля объекта (набора записей):
> 
> ```bsl
> // Пропускаем обработку, чтобы гарантировать получение формы при передаче параметра "АвтоТест".
> Если ДанныеЗаполнения = "АвтоТест" Тогда
> Возврат;
> КонецЕсли;
> ```
(ц) АПК
**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**
На ИТСе ссылок нет =(

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [ ] Ошибка
* [ ] Уязвимость
* [x] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [ ] Критическая / Critical
* [ ] Важная / Major
* [x] Незначительная / Minor
* [ ] Информационная / Info
* [ ] Другое

**Comment by theshadowco** [comment]
у нас же уже есть диагностики на тэги и закомментированный код

**Comment by nixel2007** [comment]
Это вроде ни то ни другое, @TheShadoWCo?

**Comment by theshadowco** [comment]
Ну если рассматривать только свойство автотест - да, просто в тексте остальное тож помаинается
