### ISSUE TITLE
Шильдик на телеграмм 

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#43]
https://t.me/bsl_language_server

**Comment by asosnoviy** [comment]
[![telegramm](https://img.shields.io/badge/telegramm-chat-green.svg)](https://t.me/bsl_language_server)

**Comment by nixel2007** [comment]
Может flat?

**Comment by asosnoviy** [comment]
А кто такой flat? +)

**Comment by nixel2007** [comment]
Это стиль шильдиков такой) плоский, квадратный. На shild.io есть переключалка внизу

**Comment by asosnoviy** [comment]
Ну ты эстет=))
