### ISSUE TITLE
Смешивание латинских и кириллических символов в одном идентификаторе

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#432]
**Описание проблемы, ошибки, которую надо диагностировать**
В АПК это правило "Слово содержит кириллицу и латиницу (216)"
Бывает смешивание русской с и латинской c.
Или заставляет переключать расскладку при работе с одной переменной

**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**
На ИТС не нашел

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [ ] Ошибка
* [ ] Уязвимость
* [x] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [ ] Критическая / Critical
* [ ] Важная / Major
* [ ] Незначительная / Minor
* [x] Информационная / Info
* [ ] Другое

**Дополнительная информация**
Холиварненько

**Comment by theshadowco** [comment]
При ловле замечаний надо следующее учесть:
 - ловить в именах локальных методов и переменных
 - ловить имена модулей / объектов, а не их вызовы
 - подготовить список для исключений, типа ФабрикаXDTO или ComОбъект

**Comment by EightM** [comment]
Данная диагностика не покрывается очепятко детектором? #254 В случае смешения символов, слово с высокой долей вероятности будет помечено как ошибочное.

**Comment by DitriXNew** [comment]
> Данная диагностика не покрывается очепятко детектором? #254 В случае смешения символов, слово с высокой долей вероятности будет помечено как ошибочное.

Все верно, но вот висит ошибка в слове Check, тайпо тебе говорит - проблема!
И в чем тут проблема? А гугл и подобные - исправляют ошибку автоматом. Приходится при  подозрении идти на ресурсы другие и там проверять.

**Comment by artbear** [comment]
@theshadowco Еще в результате обсуждения с @tormozit
появилось вот такое дополнение (или новое правило)
- использование 3 (цифры три) и З (большая русская буква Зэ)

правда, как стат.анализ должен отличить вот этот вариант, непонятно )
чем Переменная3 (цифра) отличается от ПеременнаяЗ (буква) ? )

если только такое ловить - переменная3ашибись (цифра) или переменнаяЗашибись (буква)

когда внутри имени "внезапно и по середине" встречается 3, и больше других цифр в имени нет ?

**Comment by theshadowco** [comment]
@artbear 
Лучше отдельно офрмить пообмусолить )
