### ISSUE TITLE
Не удален файл после использования

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#435]
**Описание проблемы, ошибки, которую надо диагностировать**

> 4. После окончания работы с временным файлом или каталогом, его необходимо удалить самостоятельно. Нельзя рассчитывать на автоматическое удаление файлов и каталогов при следующем запуске платформы, это может привести к исчерпанию свободного места в каталоге временных файлов.
> 
> ```bsl
> ИмяПромежуточногоФайла = ПолучитьИмяВременногоФайла("xml");
> Данные.Записать(ИмяПромежуточногоФайла);
> 
> // Работа с файлом
> ...
> 
> // Удаляем временный файл
> Попытка
>    УдалитьФайлы(ИмяПромежуточногоФайла);
> Исключение
>    ЗаписьЖурналаРегистрации(НСтр("ru = 'Мой механизм.Действие'"), УровеньЖурналаРегистрации.Ошибка, , , ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));
> КонецПопытки;
> ```

**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**
https://its.1c.ru/db/v8std#content:542:hdoc

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [x] Ошибка
* [ ] Уязвимость
* [ ] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [ ] Критическая / Critical
* [x] Важная / Major
* [ ] Незначительная / Minor
* [ ] Информационная / Info
* [ ] Другое

**Comment by otymko** [comment]
кидаю себе на реализацию
