### ISSUE TITLE
[FP] недостижимый код и препроцессор

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#437]
**Диагностика**
UnreachableCode

**Версия**
Develop

**Описание ошибки диагностики**
Не учитывает область действия препроцессора

**Пример кода**
```
#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда

        Возврат ИнтернетПоддержкаПользователей.ДоступноПодключениеИнтернетПоддержки();
 #Иначе
  ПараметрыРаботыКлиента = СтандартныеПодсистемыКлиент.ПараметрыРаботыКлиента().ИнтернетПоддержкаПользователей;
   Возврат ПараметрыРаботыКлиента.ДоступноПодключениеИнтернетПоддержки;
#КонецЕсли

```

**Скриншоты**

![image](https://user-images.githubusercontent.com/15638529/66429205-450f6280-ea20-11e9-9315-41b9a8f62450.png)

**Дополнительная информация**

**Comment by theshadowco** [comment]
це ж говнокод

**Comment by nixel2007** [comment]
Плюсую за говнокод и предлагаю не исправлять.

**Comment by asosnoviy** [comment]
Может побырику ресетить об препроцессор?

**Comment by theshadowco** [comment]
Много FP?

**Comment by theshadowco** [comment]
прикольно, тогда берем в работу

**Comment by zeegin** [comment]
> У меня где-то 70% fp. По большей части, это код из бсп следующего вида

БПО

**Comment by zeegin** [comment]
```bsl
#Если Сервер Или ТолстыйКлиентОбычноеПриложение Или ВнешнееСоединение Тогда

        Возврат ИнтернетПоддержкаПользователей.ДоступноПодключениеИнтернетПоддержки();
 #Иначе
  ПараметрыРаботыКлиента = СтандартныеПодсистемыКлиент.ПараметрыРаботыКлиента().ИнтернетПоддержкаПользователей;
   Возврат ПараметрыРаботыКлиента.ДоступноПодключениеИнтернетПоддержки;
#КонецЕсли
```

А модуль какой? Если серверный - то надо ругаться. Если клиент-серверный - не надо.

**Comment by qtLex** [comment]
> > У меня где-то 70% fp. По большей части, это код из бсп следующего вида
> 
> БПО

Каюсь. Действительно БПО
