### ISSUE TITLE
[FP] Закомментированный код

### ISSUE THREAD

**Issue by qtLex** [1c-syntax/bsl-language-server#438]
**Диагностика**
CommentedCodeDiagnostic

**Версия**
develop

**Описание ошибки диагностики**
Слишком высокий приоритет для ";"

**Скриншоты**
![photo_2019-10-08_23-14-07](https://user-images.githubusercontent.com/5488710/66432458-c36f0300-ea26-11e9-9043-895f4a567423.jpg)

**Comment by asosnoviy** [comment]
Можно как то попытаться угадать что это описание метода, может по "Параметры:" и "Примеры:" из стандарта по описанию методов и не реагировать?

**Comment by asosnoviy** [comment]
А за ";"  и в жабе орет =)

**Comment by asosnoviy** [comment]
![image](https://user-images.githubusercontent.com/15638529/66462986-d44e6180-ea84-11e9-9155-a8b30abc2d1f.png)

Еще.

**Comment by zeegin** [comment]
Очень фонит.

**Comment by nixel2007** [comment]
Можно выбрасывать комментарии, которые находятся вне fileCodeBlock и sub

**Comment by nixel2007** [comment]
Но чтобы не потерять закоментированные процедуры между разными sub лучше внести описание процедуры в MethodSymbol (блок комментария, заканчивающийся ровно за строку до объявления метода), и проверять, что закоментированный код не входит в описание метода

**Comment by qtLex** [comment]
> Но чтобы не потерять закоментированные процедуры между разными sub лучше внести описание процедуры в MethodSymbol (блок комментария, заканчивающийся ровно за строку до объявления метода), и проверять, что закоментированный код не входит в описание метода

Как-то так и думал сделать. Только про MethodSymbol не догадался. Посмотрю

@nixel2007  На меня повесьте в ближайшее время займусь

**Comment by qtLex** [comment]
@nixel2007 Еще не крутил. Но в данном случае плохо получиться. Много FN будет на конструкциях вида // КонецПроцедуры

**Comment by qtLex** [comment]
@nixel2007 Я обязательно попробую.

В моей тестовой кодовой базе много единичных ошметков такого вида:
// КонецПроцедуры
// КонецЕсли
// КонецЦикла

 > Плюс никто не мешает ругаться на 1 токене. 2 идентифаеров подряд же нет, значит и фильтроваться не надо. 

А вот тут я не совсем понял. Можешь раскрыть?

**Comment by qtLex** [comment]
Мне кажется, что если реализовать первую часть с отсечение комментариев к процедурам и настроив правильно Footprint. Чего у меня сразу не получилось (. Можно будет обойтись без токенизатора. Но это на уровне идеи и ощущения.
