### ISSUE TITLE
Объект входит в несколько функциональных подсистем

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#45]

**Comment by asosnoviy** [comment]
https://its.1c.ru/db/v8std#content:2149184354:hdoc

**Comment by zeegin** [comment]
Объект входит хотя бы в одну функциональную в этой же проверке или отдельное правило?

**Comment by artbear** [comment]
есть более поздний ишуз- там лучше форматирование + больше кейсов
https://github.com/1c-syntax/bsl-language-server/issues/1127
удалите один из дублей.

**Comment by theshadowco** [comment]
закрываю дубль
