### ISSUE TITLE
Описание метода в MethodSymbol

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#480]

**Comment by qtLex** [comment]
Можно по подробнее описать, что хочется хранить?

**Comment by nixel2007** [comment]
в качестве MVP - полный текст неразрывного блока комментария над методом, без начальных `//`

в последствии - комментарий, разобранный на блоки параметры/описание/возвращаемое значение/примеры через новый мини-парсер из BSLParser

**Comment by qtLex** [comment]
В pr MVP. Обрезку ```//``` только добавить.
