### ISSUE TITLE
[FP] Хранение конфиденциальной информации в коде Пароль = "*******"

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#482]
**Диагностика**
Хранение конфиденциальной информации

**Версия**
0.11

**Описание ошибки диагностики**
FP, в коде ставится "заглушка" для поля формы, а не сам пароль

**Пример кода**
```Пароль = "**********";```

**Скриншоты**

![image](https://user-images.githubusercontent.com/32082417/66793113-46202280-ef3f-11e9-92a0-cd2ccd2f9267.png)

Возможно стоит добавить проверку что в пароле есть символы кроме "*"

**Comment by otymko** [comment]
![image](https://user-images.githubusercontent.com/11651847/66894746-6c1af500-f01b-11e9-8445-cdfb3793f380.png)
