### ISSUE TITLE
[FP] Ограничение на длину строки, тригерится на ";" в конец текста запроса, хотя по идее не должна

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#484]
**Диагностика**
Ограничение на длину строки

**Версия**
0.11

**Описание ошибки диагностики**
Ограничение на длину строки, тригерится на ";" в конец текста запроса, хотя по идее не должна

**Пример кода**
![image](https://user-images.githubusercontent.com/32082417/66801660-27308900-ef5d-11e9-9c59-b1377e4f4cdb.png)

**Comment by asosnoviy** [comment]
Делал заход, посмотрю

**Comment by asosnoviy** [comment]
Сюда же, ругаться на длинные комментарии.

**Comment by Stepa86** [comment]
А почему не должна то? Если вылазит, то это косяк, и пофик что именно вылазит
> Ограничение необходимой ширины окна редактора позволяет иметь несколько открытых файлов бок о бок, и хорошо работает при использовании инструментов анализа кода, которые предоставляют две версии в соседних столбцах. (ц) PEP8

**Comment by asosnoviy** [comment]
Конструктор запросов делает так. И когда там последняя строка  длиннющая из за имени метаданных, то исправить это нельзя.

**Comment by Stepa86** [comment]
В ЕДТ, кстати, переносит.
То, что это нельзя исправить не означает, что это FP
