### ISSUE TITLE
[FP] UsingHardcodePath Нюансы Используется хранение в коде пути к файлу или ip адреса

### ISSUE THREAD

**Issue by DmitriyKorotovskih** [1c-syntax/bsl-language-server#485]
1. Ложные срабатывания на части URI, часть URI может не отличаться от пути в linux
```bsl
АдресРесурса = СтрЗаменить(АдресРесурса, "/releases/", "/dev/releases/");
```
2. Ложные срабатывания OID
```bsl
Субъект.Вставить("РНСФСС"	, Строка(Свойства["OID.1.2.643.3.141.1.1"]));
```
3. Иногда OID не отличается от ipv4
```bsl
СвойстваНаселенныйПункт.Добавить("2.5.4.7");
```
можно обойти // BSLLS-off, но кажется что строки с точками это не всегда ip и такое может встречаться чаще чем хотелось бы.

**Comment by asosnoviy** [comment]
@otymko есть предложение разнести на 2 диагностики, что бы можно было отключать раздельно.

**Comment by DmitriyKorotovskih** [comment]
ребят, давайте я перенесу тогда ишуз в https://github.com/1c-syntax/bsl-language-server

**Comment by asosnoviy** [comment]
Я перенес уже

**Comment by nixel2007** [comment]
Отдельно отмечу, что вы можете настроить диагностику на игнорирование, например, добавив "Свойства" в список исключаемых идентификаторов при поиске.
Подробнее - в доке к диагностики

**Comment by mkconst** [comment]
Ругается еще на такое:
"ВЫБРАТЬ //// Себестоимость реализованного товара (Дт 20 :: Кт 76.09)"
Я так понял на "::" в тексте запроса.

**Comment by otymko** [comment]
@asosnoviy можно и на отдельные диагностики. Сейчас например можно отключать поиск сетевых путей.

**Comment by otymko** [comment]
Завтра посмотрю что к чему

**Comment by nixel2007** [comment]
Каков теперь статус по этому ишузу?

**Comment by theshadowco** [comment]
я так понимаю, надо распилить на два - часть выполненную закрыть

**Comment by otymko** [comment]
@DmitriyKorotovskih Отвечаю автору досады:
1. К сожалению dev это каталог и в linux тоже, его трудно отличить от части URl. Вы можете в диагностике в параметрах ключевых слов убрать "dev".
2. Теперь таких ложных не будет.
3. Пока что это не решаем, не отличить ip адрес от какого классификатора. Вы можете в слова исключения добавить название этой переменной.

**Comment by otymko** [comment]
@theshadowco мое мнение - из досады выжато все на максимум.

**Comment by theshadowco** [comment]
тогда закрываем, после твоего каммента вопросов не осталось
