### ISSUE TITLE
[FP] Некорректно работает проверка COM объекта

### ISSUE THREAD

**Issue by KrapivinAndrey** [1c-syntax/bsl-language-server#490]
**Диагностика**
server:UsingObjectNotAvailableUnix

**Тип ошибки**

- [x] Ложное срабатывание [FP]
- [ ] Ложное НЕ срабатывание [FN]
- [ ] Ошибка [BUG]

**Версия**
 https://github.com/1c-syntax/vsc-language-1c-bsl/blob/master/CHANGELOG.md#1180

**Описание ошибки диагностики**
Не удается подобрать корректное условие

**Пример кода**
```bsl
СистемнаяИнформация = Новый СистемнаяИнформация();
Если СистемнаяИнформация.ТипПлатформы = ТипПлатформы.Linux_x86 Тогда
	Возврат Новый comобъект("MSScriptControl.ScriptControl");
КонецЕсли;
```
**Скриншоты**
Срабатывает, а не должна
![image](https://user-images.githubusercontent.com/586025/66835184-818b1300-ef78-11e9-8946-9d2f5343bb3e.png)
Не срабатывает, но бессмыслено
![image](https://user-images.githubusercontent.com/586025/66835211-8fd92f00-ef78-11e9-998d-76565ee65f14.png)

**Comment by zeegin** [comment]
```bsl
Если СистемнаяИнформация.ТипПлатформы = ТипПлатформы.Linux_x86 Тогда
```

Тут как раз должна.

Не должна:

```bsl
Если СистемнаяИнформация.ТипПлатформы = ТипПлатформы.Windows_x86
И СистемнаяИнформация.ТипПлатформы = ТипПлатформы.Windows_x86_64 Тогда

КонецЕсли;

Если ОбщегоНазначения.ЭтоWindowsСервер() Тогда

КонецЕсли;

#Если Не ВебКлиент Тогда
Если ОбщегоНазначенияКлиент.ЭтоWindowsКлиент() Тогда

КонецЕсли;
#КонецЕсли
```

при этом использовать проверки `СистемнаяИнформация.ТипПлатформы <> ТипПлатформы.Linux_x86`  не рекомендуется, т.к. есть еще MacOS. В том числе на сервере не рекомендуется, потому что для файловых ИБ на маке серверный контекст будет исполнен на маке и его надо правильно выбраковывать.

**Comment by KrapivinAndrey** [comment]
Проблема не в этом. Диагностика НЕ сработает если написать любое условие с Linux_x86 и ** слева от Новый ComОбъект ничего не поставить**

**Comment by KrapivinAndrey** [comment]
В телеге есть гифка от меня

**Comment by asosnoviy** [comment]
https://t.me/bsl_language_server/21520

**Comment by otymko** [comment]
Завтра посмотрю что к чему

**Comment by otymko** [comment]
@zeegin пока в ядре нет символьных вычислений. Поэтому пока исключаем просто по наличию ключевых слов. Более пока сделать ничего не получится.
@KrapivinAndrey я пофиксил.
