### ISSUE TITLE
Код вне стандартной области

### ISSUE THREAD

**Issue by zeegin** [1c-syntax/bsl-language-server#498]
**Описание проблемы, ошибки, которую надо диагностировать**
Код вне стандартной области

1.1. В программном модуле (общие модули, модули объектов, модули менеджеров объектов, модули форм, команд и т.п.) в общем случае могут присутствовать следующие разделы в приведенной ниже последовательности:

    - заголовок модуля
    - раздел описания переменных
    - экспортные процедуры и функции модуля, составляющие его программный интерфейс
    - обработчики событий объекта (формы)
    - служебные процедуры и функции модуля
    - раздел инициализации 

Некоторые разделы могут присутствовать только в модулях определенного вида. Например, обработчики событий элементов форм могут присутствовать только в модулях форм, а раздел описания переменных и раздел инициализации не могут быть определены в неглобальных общих модулях, модулях менеджеров объектов, наборов записей, значений констант и модуле сеанса.

Требование о разделении кода модуля на разделы призвано повысить читаемость кода и упростить внесение изменений в код разными авторами (разработчиками) как при коллективной разработке, так и при доработке прикладных решений на конкретных внедрениях.

**Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы**
https://its.1c.ru/db/v8std#content:455:hdoc

**Параметры диагностики**

Тип (установите x у подходящего варианта)
* [ ] Ошибка
* [ ] Уязвимость
* [x] Качество кода
* [ ] Другое

Важность (установите x у подходящего варианта)
* [ ] Блокирующая / Blocker
* [ ] Критическая / Critical
* [x] Важная / Major
* [ ] Незначительная / Minor
* [ ] Информационная / Info
* [ ] Другое

**Comment by asosnoviy** [comment]
Эх. Для точного определения нужен тип модуля. Если схалтурить можно проверять что метод вне "любой" стандартной области.

**Comment by otymko** [comment]
@asosnoviy типы модулей в пр уже висят

**Comment by asosnoviy** [comment]
Тогда на ней и обкатать =)

**Comment by theshadowco** [comment]
По факту диагностика делится на несколько
 - код вне области как таковой
 - в модуле присутствуют левые области первого уровня \ области не подходящие для типа моуля
 - в модуле присутствуют дубли областей первого уровня
 - в модуле области в неправильном порядке
 - код располоен в областях, но не правильно
 -- можно уже сделать для переменных
 -- можно уже сделать для неэкспортных
 -- можно уже сделать для инициализации
 -- остальное пока отложить
