### ISSUE TITLE
Использование объектов не доступных в Linux-клиенте

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#50]
Ругаться на: Новый COMОбъект
Диагностика: Проверить, что задействованы аналоги COM объектов при работе в Linux-клиенте.

Ругаться на: Новый Почта
Диагностика: Проверить, что пользователю доступны аналоги объекта Почта при работе в Linux-клиенте.

**Comment by zeegin** [comment]
Добавлю еще стандарт
https://its.1c.ru/db/v8std#content:-2145782924:hdoc
И еще документация платформы
https://its.1c.ru/db/v8314doc#bookmark:dev:TI000001208
И еще особенности работы в режиме линукса
https://its.1c.ru/db/v8314doc#bookmark:dev:TI000001283

Например были бы хороши правила по этим пунктам:

> При разработке прикладных решений следует обратить внимание на следующий момент: в ОС Windows и ОС Linux используются разные разделители пути. В ОС Windows используется "\" («обратный слэш»), а в ОС Linux ‑ "/" («прямой слэш»). При работе с методами встроенного языка такую разницу учитывать нет необходимости, т. к. они корректно работают с любым разделителем. Но если требуется передавать путь во внешнее приложение, следует указывать те разделители пути, которые используются в той ОС, под управлением которой работает «1С:Предприятие». Для получения информации о разделителях пути предназначены функции ПолучитьРазделительПути(), ПолучитьРазделительПутиКлиента(), ПолучитьРазделительПутиСервера().

> Наряду с различными разделителями пути, ОС Windows и ОС Linux по разному обрабатывают файловые маски. Например, маска *.* означает указание всех файлов в ОС Windows и указание всех файлов, содержащих в имени "." ‑ в ОС Linux. Такое различие может приводить к неожиданному поведению методов встроенного языка НайтиФайлы(), УдалитьФайлы() и объекта ДиалогВыбораФайла. Особенности указания файловых масок в различных операционных системах отражены в синтакс-помощнике для функций НайтиФайлы(), УдалитьФайлы(). Для получения файловой маски, описывающей все файлы, предназначены функции ПолучитьМаскуВсеФайлы(), ПолучитьМаскуВсеФайлыКлиента(), ПолучитьМаскуВсеФайлыСервера().

**Comment by asosnoviy** [comment]
Пока не прочел, про оборачивание Com в попытку там есть?

**Comment by zeegin** [comment]
Не, наверное надо отдельное правило для оборачивания.
Хотя я вообще бы ругался впринципе что com существует.

Я веду реестр по БСП мест использования COM и стараюсь при первой возможности от него отказываться совсем.

**Comment by otymko** [comment]
Я забираю в реализацию
