### ISSUE TITLE
Квик-фикс: Перенесите выражение на новую строку

### ISSUE THREAD

**Issue by qtLex** [1c-syntax/bsl-language-server#508]
Есть диагностика OneStatementPerLine. Определяет, что в строке написано одно выражение. Хотелось бы иметь действие по автоматическому переносу лишних выражений на следующие строки

![Пример](https://user-images.githubusercontent.com/5488710/67071179-845d5200-f18a-11e9-9f0c-e12ff3b66cee.png)

До изменений:
```
Н.Отбор.ЗаказНаряд.Установить(ЗН); Н.Прочитать(); Н.Очистить(); Н.Загрузить(Т);
```

После изменения:
```
Н.Отбор.ЗаказНаряд.Установить(ЗН);
Н.Прочитать();
Н.Очистить();
Н.Загрузить(Т);
```

**Comment by theshadowco** [comment]
@qtLex 
можешь добавить в тело подробностей и примеров?

**Comment by qtLex** [comment]
@theshadowco дополнил

**Comment by nixel2007** [comment]
Мне нравится. @theshadowco ?

**Comment by asosnoviy** [comment]
При реализации плз обратить внимание на саму диагностику, есть ощущение, что оно иногда врет.

**Comment by theshadowco** [comment]
Мне нра!
