### ISSUE TITLE
Параметр allowMultipleCommas по умолчанию ложь

### ISSUE THREAD

**Issue by DmitriyKorotovskih** [1c-syntax/bsl-language-server#509]
Здравствуйте, хочу оставить обратную связь в части allowMultipleCommas по умолчанию Ложь.
Умолчание в пользу дефектности идущих подряд запятых относится, скорее к соглашениям написания кода, чем к поиску дефектов кода.
Кажется, что такой подход слишком жесток, к тому же этот параметр не изменить для сонар плагина.

**Comment by asosnoviy** [comment]
По чему не удалось поменять в сонаре? Копируете дефолтный профиль и меняете.

**Comment by asosnoviy** [comment]
![image](https://user-images.githubusercontent.com/15638529/67120698-7a6f3980-f1f2-11e9-838f-65f888bd42ca.png)

**Comment by asosnoviy** [comment]
Код смелы, они же дефекты - это и есть нарушения соглашений о написании кода, которые сами по себе не вызывают ошибок, но усложняют поддержку.

**Comment by nixel2007** [comment]
@otymko мне кажется, или параметр в сонаре является строкой? Это мы в бсл лс провафлили boolean или конвертер в сонаре работает некорректно?

**Comment by otymko** [comment]
@nixel2007 вот это поворот. Пойду проверю

**Comment by otymko** [comment]
Да, параметр в сонаре строка. Но тип то boolean. 
https://github.com/1c-syntax/sonar-bsl-plugin-community/blob/bd6cb360516d20eef56db385ae2511dd4f3a00f9/src/main/java/com/github/_1c_syntax/bsl/sonar/language/BSLLanguageServerRuleDefinition.java#L118

В итоге проверяем на диагностики путей и ip. Когда enableSearchNetworkAddresses = "true" ip адреса проверяются:
![image](https://user-images.githubusercontent.com/11651847/67136777-6c063980-f255-11e9-90c6-b10117c39fd9.png)

Когда значение "false":
![image](https://user-images.githubusercontent.com/11651847/67136783-88a27180-f255-11e9-84a5-b7bd7b77141e.png)

**Comment by DmitriyKorotovskih** [comment]
Спасибо, настроил параметры в сонаре, не знал что так можно =(

**Comment by asosnoviy** [comment]
> @otymko мне кажется, или параметр в сонаре является строкой? Это мы в бсл лс провафлили boolean или конвертер в сонаре работает некорректно?

Там реально тип строка. И походу так и должно быть. Позырил в java так же.
