### ISSUE TITLE
ЭтаФорма -> ЭтотОбъект

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#51]
Диагностика: Использовано устаревшее имя свойства "ЭтаФорма" (актуальное - "ЭтотОбъект").
8.3.3+

**Comment by zeegin** [comment]
При разработке правила надо понимать, что может быть фолс позитив на имени параметра формы.
Например в старом коде встречается вызов с клиента формы в общий модуль клиентский и в общем модуле функция имеет имя параметра ЭтаФорма.

По хорошему на такое наверное тоже надо ругаться, но это уже не будет ошибкой, в просто приведением к единому стилю. Потому важно что проверка должна понимать контекст того что это модуль формы или модуль другой.
