### ISSUE TITLE
(8.3.6+) Найти -> СтрНайти

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#52]
8.3.6+
Диагностика: Использование устаревшего метода глобального контекста

Использован устаревший глобальный метод "Найти" (актуальный - "СтрНайти").

**Comment by lChagelishvili** [comment]
Решением "в лоб" видится искать идентификатор с текстом "Найти" и отсеивать те перед которыми стоит точка. 
Парсер же ничего не знает о платформенных функциях?

**Comment by nixel2007** [comment]
1. Для вызовов глобальных функций должен быть отдельный узел, соответственно можно подписаться на него вместо поиска идентификаторов без точки. Если такого отдельного узла нет, то надо добавить в bsl parser.
2. @Labotamy пробовал искать НСтр похожим вариантом. И был ещё вариант добавить в лексер глобальные функции. Об итогах его исследования не знаю. Лех, расскажешь?
3. У этой диагностики ограниченная область применения - режимом совместимости конфигурации и работой в OneScript (хотя в него вроде тоже добавили уже СтрНайти). При запуске такой диагностики на старых конфигурациях будет много FP. Надо либо разрабатывать механизм отключения правил, либо механизм разграничения областей видимости, либо мириться с FP какое-то время.

**Comment by lChagelishvili** [comment]
Что-то не выходит каменный цветок, ни по  п.1 ни п.2 ничего похожего не нашел.
Ограничения в п.3 понятны, но нужно как-то с общим подходом определиться, т.к. это точно не единственная проверка, связанная с функциями глобального контекста.

**Comment by asosnoviy** [comment]
Вроде как все препятствия устранены. 
GlobalCall теперь есть
Отключение есть.

**Comment by nixel2007** [comment]
Режим совместимости?

@otymko как насчет подключить твою либу и в качестве MVP получать параметры Configuration.xml? Думаю, это должно хватить.

**Comment by asosnoviy** [comment]
И тогда уж MDO

**Comment by otymko** [comment]
@nixel2007 можно, но пока edt там нет и общего класса.

**Comment by otymko** [comment]
Можно попробовать прототип mdclasses из ветки dev.
