### ISSUE TITLE
[BUG] Диагностика "Использование свойства "ЭтаФорма" срабатывает дважды

### ISSUE THREAD

**Issue by ovcharenko-di** [1c-syntax/bsl-language-server#521]
**Диагностика**
Использование свойства "ЭтаФорма"

**Тип ошибки**
- [ ] Ложное срабатывание [FP]
- [ ] Ложное НЕ срабатывание [FN]
- [x] Ошибка [BUG]

**Версия**
1C (BSL) Community Plugin 1.2.0

**Описание ошибки диагностики**
Диагностика сработала дважды

**Пример кода**

```bsl
Процедура ПрочитатьФайл(Команда)

    Если НЕ ПроверкаПередЗагрузкойПройдена() Тогда
        Возврат;
    КонецЕсли;
    Режим = РежимДиалогаВопрос.ДаНет;
    Оповещение = Новый ОписаниеОповещения("ПослеЗакрытияВопроса_ПрочитатьФайл", ЭтаФорма, Параметры);

КонецПроцедуры
```

**Скриншоты**
![image](https://user-images.githubusercontent.com/24920942/67285974-383f4400-f4e1-11e9-8f6f-ffd35bf99322.png)

**Comment by asosnoviy** [comment]
Забрал
