### ISSUE TITLE
Обновление индекса диагностик в мердж PR

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#529]
Убрать обновление индекса диагностик из действий разработчиков, вместо этого создать GA для автоматического обновления при мердже pr.

**Comment by zeegin** [comment]
Всегда должно выполняться до экшна пэйджес.
Надо покурить как задавать зависимость или порядок выполнения экшенов.

**Comment by nixel2007** [comment]
А зачем?

**Comment by theshadowco** [comment]
@nixel2007 если вопрос к автору (то бишь мне), то надо убрать это действие по минимум двум причинам
1. действие автоматизировано, нафига делать разработчику
2. при одновременной разраотке эти файлы почти всегда причина мерджконфликтов.

**Comment by nixel2007** [comment]
из минусов - пункт 1 делает дополнительный коммит.

**Comment by theshadowco** [comment]
решено плагином и GA без коммитов
