### ISSUE TITLE
(8.3.10+) Использование устаревшего метода клиентского приложения

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#53]
Диагностика: Использован устаревший метод "%1" (актуальное - "%2").

Устаревший метод|Актуальный метод
------------ | -------------
УстановитьКраткийЗаголовокПриложения|КлиентскоеПриложение.УстановитьКраткийЗаголовок
ПолучитьКраткийЗаголовокПриложения|КлиентскоеПриложение.ПолучитьКраткийЗаголовок
УстановитьЗаголовокКлиентскогоПриложения|КлиентскоеПриложение.УстановитьЗаголовок
ПолучитьЗаголовокКлиентскогоПриложения|КлиентскоеПриложение.ПолучитьЗаголовок
ТекущийВариантОсновногоШрифтаКлиентскогоПриложения|КлиентскоеПриложение.ТекущийВариантОсновногоШрифта
ТекущийВариантИнтерфейсаКлиентскогоПриложения|КлиентскоеПриложение.ТекущийВариантИнтерфейса

**Comment by nixel2007** [comment]
Когда устарело?

**Comment by Stepa86** [comment]
@nixel2007 при переходе на совместимость 8.3.10
https://its.1c.ru/db/metod8dev#content:5293:hdoc:pereimenovaniya_metodov_i_svojstv
