### ISSUE TITLE
Шаблон областей модулей по умолчанию

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#531]
Нужна возможность добавлять в текст модуля шаблонные области на основании:
* Для bsl с поддержкой метаданных - на основе типов модулей. 
* Для os общий шаблон.

**Comment by otymko** [comment]
В перспективе хочется это добавить в phoenix и уметь работать уже с наполненным модулем (когда можно запрограммировать как будут раскидываться методы в различных типах модулей).

**Comment by nixel2007** [comment]
Кажется это задача для code action.
