### ISSUE TITLE
Теги в шаблоне ишуза на новую диагностику

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#533]
После написания диагностики, больше не хочу думать. хочу накопипастить теги из ишуза

**Comment by theshadowco** [comment]
пояснишь?

**Comment by asosnoviy** [comment]
![image](https://user-images.githubusercontent.com/15638529/67377932-18665980-f58f-11e9-9317-3604679ca930.png)

Чтобы и пообсуждать можно было.

**Comment by theshadowco** [comment]
Понял, добавлю
