### ISSUE TITLE
Исключать файлы на поддержке из анализа замечаний

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#537]
В mdclasses есть информация о состоянии поддержки модулей. Нужно добавить для текущего проекта в конфигурационный файл новое свойство, которое будет отвечать за включение фильтрации файлов. Если свойство = true, то исключать из проверки файлы на поддержке (замке).

**Comment by nixel2007** [comment]
свойство в конфиг. по умолчанию - не исключать.
