### ISSUE TITLE
Форматирование не убирает табы в конце строки-комментария

### ISSUE THREAD

**Issue by 1cgh** [1c-syntax/bsl-language-server#540]
**Версия**
Эм. Обнаружено на https://github.com/otymko/phoenixbsl/releases/tag/0.2.1, который юзает не знаю какой бсл лс)

**Описание ошибки диагностики**
При форматировании в конце строк-комментариев остаются табы

**Пример кода**
`//СтруктураФИО = ФизическиеЛицаКлиентСервер.ФамилияИмяОтчество(Контрагент.Наименование);туттаб`

**Скриншоты**
![image](https://user-images.githubusercontent.com/24507052/67459080-625b4800-f640-11e9-9f74-4490b543dbc8.png)

**Comment by nixel2007** [comment]
Спасибо за репорт.

У меня встречный вопрос - а должен ли форматировать? Сейчас комментарий берется as-is и переносится в код. Но можно сделать trimRight конечно.

**Comment by 1cgh** [comment]
@nixel2007 моё мнение - это мусор, надо подчищать
пытаюсь придумать, когда их надо оставлять - не придумывается

**Comment by nixel2007** [comment]
Closed by https://github.com/1c-syntax/bsl-language-server/commit/2902497f425ee90a62a87dd22981b5754ecf3cab
