### ISSUE TITLE
Лычка  JB в спасибках 

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#544]
https://avatars0.githubusercontent.com/u/878437?s=200&v=4

**Comment by asosnoviy** [comment]
https://www.jetbrains.com/company/brand/

**Comment by asosnoviy** [comment]
https://www.jetbrains.com/company/brand/logos/

**Comment by nixel2007** [comment]
https://www.jetbrains.com/company/brand/img/jetbrains_logo.png
