### ISSUE TITLE
(8.3.12+) ОриентацияМетокДиаграммы. Использование устаревшего системного перечисления

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#55]
Совместимость 8.3.12+
Диагностика: Использование устаревшего системного перечисления
Системное перечисление ОриентацияМетокДиаграммы более не доступно.
Актуальный вариант ОриентацияПодписейДиаграммы.

**Comment by theshadowco** [comment]
Я имел ввиду следующее - создать диагностики, объединяющие в себе проверки на использование устаревшей функциональности по версиям платформы. 
например в диагностике "DepricateInPlatform8310Diagnostic" будет проверка на использование ВариантОткрытияОкна и Устаревших методов клиентского приложения.


Возможно это плохо (я сам не согласен с собой окончательно) и это решается тэгами, про которые я писал в другой ишузе.

**Comment by nixel2007** [comment]
Понял, про что ты. Я не вижу минусов у такого подхода на данный момент. Что тебя смущает?

**Comment by theshadowco** [comment]
Даже не знаю, вроде же сам предложил
