### ISSUE TITLE
Все экспортные методы программного интерфейса должны иметь описание

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#559]
## Описание проблемы, ошибки, которую надо диагностировать

Все экспортные методы, располагающиеся в областях программного интерфейса, должны иметь описание.

Исключение - обработчики описаний оповещений.

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

https://its.1c.ru/db/v8std#content:453:hdoc

Пункт 2.

## Параметры диагностики

Стандарт требует заполнения описаний только для API-областей. Однако же можно добавить параметр, требующий описание у вообще всех экспортных методов, не являющимися обработчиками описаний оповещения - по умолчанию - false

Так же можно добавить параметр требующий описание метода у описаний оповещений - по умолчанию false.

### Тип [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](docs/contributing/DiagnosticTag.md)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [x] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"

### Время на исправление (минут)

`10min`

## Дополнительная информация

MethodSymbol содержит информацию об описании процедуры.

В диагностике на поиск неэкспортных методов в API-областях есть код по проверке вхождения метода в область. Можно его переиспользовать, завернув в хелпер.

**Comment by asosnoviy** [comment]
Исключение - обработчики описаний оповещений.
Располагающиеся в областях программного интерфейса

А когда тут будет ФП?

**Comment by nixel2007** [comment]
стандарт требует, чтобы все экспортные методы лежали в одной из областей программного интерфейса. здесь это - служебный программный интефрейс, т.е. это попадает под места срабатывания диагностики.

**Comment by asosnoviy** [comment]
> здесь это - служебный программный интерфейс

Может вот тут ФП, на обработчиках оповещений на Форме? =)

**Comment by nixel2007** [comment]
Я видимо не понимаю твоего вопроса. что ты имеешь ввиду под фп в данном случае?

я предлагаю из коробки игнорить все методы, являющиеся обработчиками описаний оповещений, но с возможностью форсить их проверку.

**Comment by asosnoviy** [comment]
Метод обработчик оповещения в том же модуле, что и конструктор? И это модуль формы. Там нет ПрограмногоИнтерфейса(и служебного)

```
1.6. Шаблон оформления разделов для модулей форм:

русск.

#Область ОбработчикиСобытийФормы
// Код процедур и функций
#КонецОбласти

#Область ОбработчикиСобытийЭлементовШапкиФормы
// Код процедур и функций
#КонецОбласти

#Область ОбработчикиСобытийЭлементовТаблицыФормы<ИмяТаблицыФормы>
// Код процедур и функций
#КонецОбласти

#Область ОбработчикиКомандФормы
// Код процедур и функций
#КонецОбласти

#Область СлужебныеПроцедурыИФункции
// Код процедур и функций
#КонецОбласти
```

Соответственно и сработки на `Располагающиеся в областях программного интерфейса` тоже

**Comment by asosnoviy** [comment]
Перечитал таску, да я туплю.

**Comment by Stepa86** [comment]
Зачем отдельная проверка на обработчики оповещения? Они вообще должны быть в служебном программном интерфейсе. А если это такой межподсистемный обработчик, то ему так же нужно описание по общим правилам.

**Comment by nixel2007** [comment]
> Зачем отдельная проверка на обработчики оповещения?

потому что в стандарте указано исключение для обработчиков оповещения
