### ISSUE TITLE
[NEW] Длина метода

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#565]
## Описание проблемы, ошибки, которую надо диагностировать

Метод может содержать большое количество строк, что в определенный момент приводит к усложнению его восприятия. Необходимо граничивать длину метода, разбивая длинные.

Какую выбрать оптимальную длину - ХЗ

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

Стандарта от 1С не нашел, есть рекомендации на других ресурсах

- https://refactoring.guru/ru/smells/long-method
- https://ru.wikipedia.org/wiki/%D0%9A%D0%BE%D0%B4_%D1%81_%D0%B7%D0%B0%D0%BF%D0%B0%D1%88%D0%BA%D0%BE%D0%BC (искать длинный метод)
- https://habr.com/ru/post/316708/

### Тип [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](docs/contributing/DiagnosticTag.md)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"

### Время на исправление (минут)

10-30 мин

## Дополнительная информация

Необходимо учесть запросы - они бывают аццки длинными, наверное стоит их считать как то иначе, в тоже время не как одну строку.

**Comment by Stepa86** [comment]
Так а есть же уже диагностика на 200+

**Comment by theshadowco** [comment]
сорри, слепой

**Comment by asosnoviy** [comment]
Ура! Пошли дубли уже реализованных диагностик! Значит их уже много =)
