### ISSUE TITLE
[MOD] Доработка диагностик ИспользованиеМодальныхОкон и Синхронных вызовов

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#566]
## Диагностика

- UsingModalWindows
- UsingSynchronousCalls

## Описание предлагаемых изменений

Доработать диагностики
 - добавить анализ режима совместимости (8.3.3)
 - добавить чтение параметра использования модальных окон
 - добавить чтение параметра использования синхронных вызовов

## Дополнительная информация

После доработок не будет FP на 8.2 и в конфах, в которых отключены ограничения использования

**Comment by nixel2007** [comment]
Хорошая идея!

**Comment by theshadowco** [comment]
@nixel2007
надо обновить mdclasses в bslls и профинуть свойства

**Comment by nixel2007** [comment]
@theshadowco с этим есть какие-то проблемы?

**Comment by theshadowco** [comment]
т.к. нет релиза, я  могу поднять только на хэш, что вроде как мы больше не используем + я раньше такглубо не залазил.
Следовательно вопрос: могу ли это сделать? Если нет, то кто и когда?

**Comment by nixel2007** [comment]
Пробуй поднять на хэш в фича бранче. Как устаканится апи, можно тэгать. Как таковой хэш в девелоп ветке - это не страшно. Страшно в релизе :)

**Comment by nixel2007** [comment]
По поводу могу-не могу - да, конечно, можешь
