### ISSUE TITLE
[FP] UnusedLocalMethod ругается на ПриСозданииОбъекта

### ISSUE THREAD

**Issue by arkuznetsov** [1c-syntax/bsl-language-server#574]
## Диагностика
UnusedLocalMethod

## Версия
develop

## Описание ложного срабатывания диагностики
Срабатывает на предопределенный обработчик ПриСозданииОбъекта()

## Пример кода
```
Процедура ПриСозданииОбъекта()
	// Что-то делаем
КонецПроцедуры
```

## Скриншоты
![image](https://user-images.githubusercontent.com/10762909/67941155-1e3ee900-fbe6-11e9-8e8a-e8a4f99938dd.png)

## Дополнительная информация
нет

**Comment by asosnoviy** [comment]
OnObjectCreate
