### ISSUE TITLE
[NEW] Магические даты

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#575]
## Описание проблемы, ошибки, которую надо диагностировать

Аналог Магических чисел, но для дат. По коду часту используется сравнение с некоторой датой, смысловое значение которой может быть утеряно с течением времени.

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

в стандартах не нашел

- https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)
- http://www.8bytes.net/2018/04/18/antipattern-1-magicheskoe-chislo/
- https://habr.com/ru/post/328244/

### Тип [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](docs/contributing/DiagnosticTag.md)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [x] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"

### Время на исправление (минут)

5 мин

**Comment by asosnoviy** [comment]
Ух БП удивиться, там такого должно быть полно =)

**Comment by theshadowco** [comment]
эт точно :)

**Comment by otymko** [comment]
Если никто не против, то я покапаюсь
