### ISSUE TITLE
[NEW] Использование информации метода ПользователиОС

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#576]
## Описание проблемы, ошибки, которую надо диагностировать

Метод ПользователиОС 
> предоставляет доступ к информации о доменах и пользователях операционной системы

Его использование может нести и вредоносную ф-ию ("Закладку"), следовательно необходимо обнаруживать все места и подсвечивать их. 

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

Увы нет, но как пример

- https://habr.com/ru/company/jetinfosystems/blog/449278/

### Тип [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :ant: Ошибка
* [x] :cop: Уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :broken_heart: Блокирующая / Blocker
* [x] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](docs/contributing/DiagnosticTag.md)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"

### Время на исправление (минут)

15

**Comment by asosnoviy** [comment]
Прям на globalCall вешаться?

**Comment by theshadowco** [comment]
думаю да

**Comment by nixel2007** [comment]
В SQ появилась SecurityHotspot. Возможно нам тоже стоит разделить однозначные уязвимости и "посмотрите и убедитесь"

**Comment by theshadowco** [comment]
а давай! но для этого нам надо малость доработаться

**Comment by zeegin** [comment]
SecurityHotspot прям надо, потому что много таких мест где надо проаудировать. Например всякие запустить приложение или подключить внешнюю компоненту.

**Comment by zeegin** [comment]
А еще УстановитьОтключениеБезопасногоРежима прям все надо в SecurityHotspot

**Comment by theshadowco** [comment]
> А еще УстановитьОтключениеБезопасногоРежима прям все надо в SecurityHotspot

Запостишь?

**Comment by zeegin** [comment]
@theshadowco  @nixel2007 
Давай сначала надо решить как Security Hotspot отмечать? Это же новый тип проверок?
Как я понял он только в 8.0 появился и я пока не понимаю как с ним работать и до того как добавлять новые ишью наверное надо пересмотреть правило определения типа ошибок и текущие проверки? Например текущие проверки зашитого пути и поиск адресов это относить к Vulnerability  или все же Security Hotspots?

**Comment by nixel2007** [comment]
Security Hotspot появился еще в 7.8, если мне не изменяет память. В текущем lts он точно есть.
Можно добавить новый DiagnosticType в BSL LS и мапить его один к одному в сонаре. Либо же просто все уязвимости сразу мапить на SH. Для принятия решения нужно почитать доку сонара и их определение и разницу V и SH.

Старые уязвимости (их у нас пока одна) перевесить на SH при необходимости несложно.

Понятия SH нет в LSP. Как и V. поэтому везде в протоколе они улетают просто как Error
