### ISSUE TITLE
[NEW] Использование СистемнаяИнформация

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#577]
## Описание проблемы, ошибки, которую надо диагностировать

Объект СистемнаяИнформация предоставляет данные о о компьютере и конфигурации в 1С, которая может быть использована в злонамерянных целях. 

Необходимо подсвечивать места использования. 

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

нет

### Тип [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :ant: Ошибка
* [x] :cop: Уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :broken_heart: Блокирующая / Blocker
* [x] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](docs/contributing/DiagnosticTag.md)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [x] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"

### Время на исправление (минут)

5

## Дополнительная информация

Для обсуждения: возможно стоит игнорировать места, где используется из объекта ТОЛЬКО ТипПлатформы.

**Comment by zeegin** [comment]
Возможно стоит игнорировать клиент, т.к. в большинстве случаев пользователь и так может узнать данные о своем компьютере, с которого выполняется подключение. Исключение системы виртуализации типа RemoteAPP или Citrix.

**Comment by zeegin** [comment]
Точно будут ложные срабатывания но определении браузера по ИнформацияПрограммыПросмотра  и рекомендации использовать 1С на компьютерах с больше чем 2 Гб на ОперативнаяПамять.

**Comment by theshadowco** [comment]
не уязвимость, а HotsPots
