### ISSUE TITLE
Приведение к числу в попытке

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#58]
Например, неправильно:
```Bsl
Попытка
 КоличествоДнейРазрешения = Число(Значение);
Исключение
 КоличествоДнейРазрешения = 0; // значение по умолчанию
КонецПопытки;
```
Правильно:
```Bsl
ОписаниеТипа = Новый ОписаниеТипов("Число");
КоличествоДнейРазрешения = ОписаниеТипа.ПривестиЗначение(Значение);
```

**Comment by asosnoviy** [comment]
https://its.1c.ru/db/v8std#content:2149184148:hdoc

**Comment by khorevaa** [comment]
Вау!! А я и не знал )))

**Comment by zeegin** [comment]
На паузу поставь. Я уже согласовал и принял стандарт, но он еще не опубликован.
Там правила сериализации.

**Comment by zeegin** [comment]
**Требования по локализации** -> **Форматирование даты, числа, Булево: требования по локализации**

_Пишу вырезку из нового стандарта:_

4. В случае, когда требуется передача значения в машиночитаемом виде, вне зависимости от информационной системы и настроек локализации, применяемых в ней, вместо локализации значения следует выполнить сериализацию. Локализацию дат нужно использовать всегда, когда это возможно. В тех случаях, когда это технически нецелесообразно, допускается отказываться от локализации. Например, при генерации файла формата XML, поддерживаемого банк-клиентом системы, специфичной для России.

В общем случае для сериализации рекомендуется использовать метод `XMLСтрока`.

Для десериализации `XMLЗначение`. Или метод `ПривестиЗначение` объекта `ОписаниеТипов`.

4.1. Сериализация дат

При разработке собственных форматов передачи данных между различными системами рекомендуется сериализовать дату в формате ISO: `ГГГГ-ММ-ДДTЧЧ:ММ:ССZ`, например `2009-02-15T00:00:00Z` (соответствует типу `dateTime` схемы XML см. http://www.w3.org/TR/xmlschema-2/#dateTime).

Неправильно:
```bsl
Строка = Формат(Дата, "ДФ=гггг-ММ-ддTЧЧ:мм:сс"); // Сериализация
```
Правильно:
```bsl
// Сериализация
Строка = XMLСтрока(Дата); // Сериализация
// Или
Строка = ЗаписатьДатуJSON(Дата, ФорматДатыJSON.ISO); // Сериализация
ОписаниеТипа = Новый ОписаниеТипов("Дата");
Дата = ОписаниеТипа.ПривестиЗначение(Строка);
// Десериализация
Дата = XMLЗначение(Тип("Дата"), Строка);
// Или
Дата = ПрочитатьДатуJSON(Строка, ФорматДатыJSON.ISO);
```
4.2. Сериализация числа

Неправильно:
```bsl
// Сериализация
Строка = Строка(Число);
// Или
Строка = Формат(Число);
```
Правильно:
```bsl
Строка = XMLСтрока(Число); // Сериализация
Число = XMLЗначение(Тип("Число"), Строка); // Десериализация
```
4.3. Сериализация Булево

Неправильно:
```bsl
// Сериализация
Строка = Строка(Булево);
// или
Строка = Формат(Булево);
// Или
Строка = Формат(Булево, "БЛ=off; БИ=on");
```
Правильно:
```bsl
// Сериализация
Строка = XMLСтрока(Булево);
// Или
Булево = XMLЗначение(Тип("Булево "), Строка);
// Или
Строка = ?(Булево, "on", "off");
```

**Comment by zeegin** [comment]
Тут надо понимать что кроме приведения в заголовке могут использоваться куча других способов и то какой реально нужен с выбросом исключения или нет надо выбирать по факту решения.

Может быть у тебя валидация принимаемого пакета на XMLЗначение должна все же падать, потому гасить ее попыткой нельзя. А может тебе надо без исключений всегда читать значение - тогда через ОписаниеТипов надо.

**Comment by lChagelishvili** [comment]
А остались сценарии когда **необходимо** использовать Число(Значение)?
Пока все выглядит так, что любое использование Число(Значение) можно диагностировать как ошибку, вне зависимости от того завернуто оно в попытку или нет.

**Comment by nixel2007** [comment]
Насколько я понимаю, приведение без попытки по стандарту ошибкой не является

**Comment by lChagelishvili** [comment]
А мне кажется, что приведенный пример одновременно иллюстрирует две ошибки:
1. Частный случай некорректной работы с попытка/исключение (именно из этого раздела its взят пример).
2. Некорректное приведение типов.
Что мы хотим реально проверить?

Вообще, диагностировать ошибку на, в целом, работающем коде и при этом пропускать Число(Значение) которое в любой момент может вывалится в исключение мне кажется странным.
По крайней мере, я пока не вижу кейсов когда прямое приведение типов может быть оправдано.

**Comment by zeegin** [comment]
> По крайней мере, я пока не вижу кейсов когда прямое приведение типов может быть оправдано.

Ну разбираешь ты какой-то пакет обмена. В одном случае тебе если пришло что-то не то надо все равно создать объект в системе получателе, в другом случае тебе надо завалиться на анализе пакета, потому что число используется в ключе поиска объекта, например. Потому ошибку разбора поля типа числа надо оставлять с выбросом исключения.

Другое дело, что лучше использовать `XMLЗначение` вместо `Число` для чтения.

**Comment by lChagelishvili** [comment]
> Другое дело, что лучше использовать `XMLЗначение` вместо `Число` для чтения.
О том и речь, что похоже не осталось рекомендаций к использованию Число(Значение)
