### ISSUE TITLE
[FP] UsingHardcodeSecretInformation на элементах формы

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#580]
## Диагностика

UsingHardcodeSecretInformation 

## Версия

0.11.0.225

## Описание ложного срабатывания диагностики

Считает ошибкой следующий код
```bsl
Элементы.Пароль.Заголовок		= "Пароль";

Элементы.Пароль.Заголовок		= "Пароль SMTP";
```

т.е. реагирует на установку заголовка

## Пример кода

```bsl
Элементы.Пароль.Заголовок		= "Пароль";

Элементы.Пароль.Заголовок		= "Пароль SMTP";
```

**Comment by nixel2007** [comment]
Кажется, имеет смысл смотреть, что сработавший идентификатор - последний.

**Comment by otymko** [comment]
беру на себя
