### ISSUE TITLE
[NEW] У подписки на событие отсутствует обработчик

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#581]
## Описание проблемы, ошибки, которую надо диагностировать
Если у подписки на события указан обработчик, которого не существует или метод не экспортный, то форма элемента объекта в режиме предприятия не откроется.

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы
Ошибка в режиме предприятия "При подписке **ТестоваяПодписка** на событие ПередЗаписью произошла ошибка. Обработчик события не найден.".
![image](https://user-images.githubusercontent.com/11651847/67967156-a9949a80-fc37-11e9-8df3-4709f5ecf666.png)

### Тип [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](docs/contributing/DiagnosticTag.md)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [x] `ERROR` - "Ошибочная конструкция"

### Время на исправление (минут)
5 минут

**Comment by otymko** [comment]
Нужно учесть, что метод может быть недоступен, например если у модуля нет свойства "вызов сервера".

**Comment by Stepa86** [comment]
> Нужно учесть, что метод может быть недоступен, например если у модуля нет свойства "вызов сервера".

для подписок модуля объекта наоборот нельзя, чтоб был вызов сервера. Упасть с мутабельностью может. Модуль должен быть серверным

**Comment by otymko** [comment]
> > Нужно учесть, что метод может быть недоступен, например если у модуля нет свойства "вызов сервера".
> 
> для подписок модуля объекта наоборот нельзя, чтоб был вызов сервера. Упасть с мутабельностью может. Модуль должен быть серверным

Согласен, неправильно написал я выше

**Comment by artbear** [comment]
связано с https://github.com/1c-syntax/bsl-language-server/issues/1078
