### ISSUE TITLE
[NEW] Использование Журнала регистрации

### ISSUE THREAD

**Issue by zeegin** [1c-syntax/bsl-language-server#582]
## Описание проблемы, ошибки, которую надо диагностировать

2.1

> Текст типа события – локализуем, при этом всегда задается основной язык конфигурации.

В первом параметре метода глобального контекста `ЗаписьЖурналаРегистрации` должен быть `НСтр` с заполненными двумя параметрами.

2.3

> Текст комментария – локализуем. Для записи в Журнал регистрации информации о возникшем исключении следует использовать конструкцию:

```bsl
ПодробноеПредставлениеОшибки(ИнформацияОбОшибке())
```

Если второй параметр метода `ЗаписьЖурналаРегистрации` содержит `УровеньЖурналаРегистрации.Ошибка` то 5 параметр должен содержать подробное представление ошибки, т.е. не содержать `КраткоеПредставлениеОшибки ` и `ОписаниеОшибки`.

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы
https://its.1c.ru/db/v8std#content:498:hdoc

### Тип [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](docs/contributing/DiagnosticTypeAndSeverity.md)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [x] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](docs/contributing/DiagnosticTag.md)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"

### Время на исправление (минут)

5

**Comment by nixel2007** [comment]
Ошибка?

**Comment by zeegin** [comment]
Ага. Потому что в случае если произойдет реальная ошибка то ты не сможешь ее диагностировать.
В первом пункте ты потеряешь ключ диагностики и не сможешь быстро найти в журнале ошибку.
Во втором пункте ты можешь потерять стек и не сможешь узнать место возникновения ошибки.
И то и то делает невозможным расследование, а запись в журнал бессмысленной.

**Comment by nixel2007** [comment]
Но как таковая не корректная запись не приводит к эксепшену или неправильно работающему коду. Это скорее про обслуживание. На мой взгляд - это код смелла

**Comment by zeegin** [comment]
Код смелом не может быть то, что влияет на данные. 
Можно разбить:
1. Если первый параметр без нстр то это действительно кодсмел, потому что запись будет в журнале всегда но без локализации. 
2. если первый параметр НСТР без указания языка,  то в общем случае это не ошибка,  а в случае когда в конфе два языка а нстр с одним переводом,  то это крит ошибка, потому что при попытке записи в журнал будет исключение.

**Comment by nixel2007** [comment]
На НСтр есть отдельная диагностика, и там это error

**Comment by zeegin** [comment]
здесь НСтр особенный, он должен быть с кодом языка

Все записи в журнал регистрации должны быть записаны на языке информационной базы.
Он указывается при создании базы и потом не меняется.

когда ты пишешь конфигурацию ты не знаешь с каким кодом языка создадут иб, потому события должны быть локализованны на все языки,  но записываться всегда на одном - языке иб.
если это не сделать и в базе работают одновременно пользователи с англ и русск интерфейсом то получается каша в журнале регистрации из разных языков. 

не указанный второй параметр для жр это наверное кодсмел

**Comment by artbear** [comment]
Отлично, что ишуз на эту тему уже существует.

Добавляю еще кейс - необходимо указывать уровень важности события, бессмысленно не указывать\пропускать этот параметр.
По умолчанию его можно пропустить, и будет использовано Примечание, что крайне подозрительно в блоке обработки исключения
Нашел в коде несколько таких участков, из-за чего поддержка просто пропускала часть ошибок (

**Comment by artbear** [comment]
>здесь НСтр особенный, он должен быть с кодом языка
>Все записи в журнал регистрации должны быть записаны на языке информационной базы.
Он указывается при создании базы и потом не меняется.
>когда ты пишешь конфигурацию ты не знаешь с каким кодом языка создадут иб, потому события должны быть локализованны на все языки, но записываться всегда на одном - языке иб.
если это не сделать и в базе работают одновременно пользователи с англ и русск интерфейсом то получается каша в журнале регистрации из разных языков.

@zeegin   тут я не соглашусь
- 1 этой информации в стандартах нет
 - во всех 3х статьях
   - https://its.1c.ru/db/v8std#content:498:hdoc
   - https://its.1c.ru/db/v8std#content:499:hdoc
   - https://its.1c.ru/db/v8std#content:761:hdoc (локализация и НСтр)

2 это ограничение больше похоже на код-смелл
3 описание проблем даже в ишузе вызывает вопросы. а уж в описании диагностики еще больше проблем будет с точки зрения понимания.

4 поэтому я предлагаю разделить ишуз на 2 правила
- 1 использование неверных параметров при ЗаписиЖР - уровень события + комментарий
- 2 неверное использование НСтр
  - либо прикрепить его к правилу про НСтр (ишуз есть)
  - или сделать отдельное правило

@nixel2007 а ты что скажешь?

**Comment by zeegin** [comment]
@artbear 

https://its.1c.ru/db/content/v8std/src/900/i8100784.htm
п 2.3.
> где переменная **КодОсновногоЯзыка** содержит код языка для хранения данных в информационной базе.

см подробнее тут
https://its.1c.ru/db/content/v8std/src/900/i8100784.htm

**Comment by artbear** [comment]
@zeegin ага, спасибо, увидел это описание. 
Интересно, буду знать.

но свое мнение я не поменял, предлагаю все-таки разбить на 2 правила.
Все-таки для НСтр лучше реализовывать отдельную диагностику.
В ней, например, можно проверять значение переменной, переданной в 1й параметр.

и тогда не придется переусложнять код проверки вызова метода ЗаписьЖР

**Comment by artbear** [comment]
Я взялся делать диагностику для ЗаписьЖР

но делаю именно проверку использования самого метода, его параметров, наличие ПодробноеПредставлениеОшибки в исключении и т.п.
основной код уже работает, один тест осталось добить.

Но доработку этого правила для НСтр делать не хочется, т.к.
- считаю, что диагностика для НСтр нужна отдельная
- я работаю с русскоязычными конфигурациями и мультиязычность не интересна совсем )

соответственно, мой ПР текущий ишуз не закроет полностью.

ВОПРОС - мне сделать отдельный ишуз, верно?
или что-то другое?

@nixel2007 @theshadowco @zeegin

**Comment by theshadowco** [comment]
в таске упоминается 2 замечания. Соответственно, либо разбить на 2 таски, либо делать все сразу...
@zeegin 
@nixel2007 что скажете

**Comment by nixel2007** [comment]
Я предлагаю текущую задачу закрыть пулл-реквестом от @artbear, а доработку НСтр сделать отдельно. Может быть в рамках той же диагностики, просто потом, когда дойдут руки.
