### ISSUE TITLE
[NEW] Неправильное использование ОтменитьТранзакцию

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#587]
## Описание проблемы, ошибки, которую надо диагностировать

НЕобходимо диагностировать 
 - отменить транзакци должно быть в попытке
 - между исключением и отменить транзакцию не должно быть кода

## Ссылка на источник, подтверждающее нарушение либо обоснование наличия проблемы

https://its.1c.ru/db/v8std#content:783:hdoc:_top

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [x] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [x] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"

### Время на исправление (минут)

15

**Comment by nixel2007** [comment]
Так есть же уже...

**Comment by nixel2007** [comment]
https://1c-syntax.github.io/bsl-language-server/dev/diagnostics/BeginTransactionBeforeTryCatch/

**Comment by nixel2007** [comment]
Вот ты хитрец! Переименовал ишуз :)

**Comment by theshadowco** [comment]
да, я разбирал старую таску
