### ISSUE TITLE
[BUG] Задваивает сообщение об ошибке для диагностики WorkingTimeoutWithExternalResources

### ISSUE THREAD

**Issue by arkuznetsov** [1c-syntax/bsl-language-server#591]
## Диагностика
WorkingTimeoutWithExternalResources

## Версия
0.11.0 + (develop от 29.10.2019)

## Описание ошибки диагностики
Задваивает сообщение об ошибке для диагностики WorkingTimeoutWithExternalResources

## Пример кода
```bsl
Эластик_Соединение = Новый HTTPСоединение(Эластик_Сервер, Эластик_Порт, Эластик_Пользователь, Эластик_Пароль);
```

## Скриншоты

![image](https://user-images.githubusercontent.com/10762909/68020266-0bdcb200-fcaf-11e9-9a86-7342bedc1833.png)

**Comment by asosnoviy** [comment]
Подозреваю, что проблема та же, что и в ЭтаФорма, в строке 2 стейтмента.

**Comment by asosnoviy** [comment]
Хм, тупо в тесте не повторяется =(

**Comment by otymko** [comment]
Проблема с вложенными блоками. Сейчас исправлю pr-ом
