### ISSUE TITLE
Каноническое написание ключевых слов

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#6]
https://its.1c.ru/db/v8std/content/2149184090/hdoc

**Comment by asosnoviy** [comment]
Каноническое | Часто используемое 
------------ | -------------
| Для каждого | Для Каждого |
| НЕ | Не |
| ИЛИ | Или |

**Comment by Stepa86** [comment]
Канон в модулях:

- Если
- Тогда
- Иначе
- ИначеЕсли
- КонецЕсли
- Для
- Каждого
- Цикл
- КонецЦикла
- Выполнить
- По
- Прервать
- Продолжить
- Из
- Новый
- Перейти
- Перем
- Пока
- Попытка
- Исключение
- КонецПопытки
- ВызватьИсключение
- Процедура
- КонецПроцедуры
- Функция
- КонецФункции
- Возврат
- ДобавитьОбработчик
- УдалитьОбработчик
- И
- ИЛИ
- НЕ
- Или
- Не
- каждого

Канон в запросе:

- ВЫБРАТЬ
- КАК
- ПО
- ПОМЕСТИТЬ
- АВТОУПОРЯДОЧИВАНИЕ
- ИЕРАРХИЯ
- ВЫБОР
- ТОГДА
- КОГДА
- ЕСЛИ
- КОНЕЦ
- ИНАЧЕ
- МЕЖДУ
- В
- В ИЕРАРХИИ
- ПОДОБНО
- ИМЕЮЩИЕ
- УПОРЯДОЧИТЬ
- ГДЕ
- ИЗ
- ИСТИНА
- ЛОЖЬ
- ПЕРВЫЕ
- РАЗРЕШЕННЫЕ
- ИТОГИ
- ПОЛНОЕ
- СОЕДИНЕНИЕ
- ЛЕВОЕ
- ПРАВОЕ
- ВНУТРЕННЕЕ
- РАЗЛИЧНЫЕ
- УБЫВ
- ВОЗР
- СГРУППИРОВАТЬ ПО
- ОБЩИЕ
- НЕ
- И
- ИЛИ
- ЕСТЬ NULL
- ОБЪЕДИНИТЬ

**Comment by nixel2007** [comment]
В запросах вроде нет разночтений - должно быть капсом)

а вот в модулях "исторически" стандарт и мнение большинства кодеров различаются.

**Comment by Stepa86** [comment]
Это копипаст из АПК. Там видно, что `Для Каждого` и `Для каждого` - допустимо, как и `ИЛИ` или `Или`. А вот капсом писать уже не по стандарту

**Comment by lChagelishvili** [comment]
В стандарте сказано, "как в документации или Синтакс-помощнике".
Беда в том, что автодополнение в конфигураторе не совпадает с тем, что написано в помощнике, видимо, поэтому АПК и поддерживает разные варианты для логических операций и для "каждого".
Я, кстати, обычно пользуюсь автодополнением, поэтому "Или" и "Каждого".

Собственно, я набросал черновик проверки, так что надо как-то найти общий знаменатель:
1. Поддерживаем оба варианта написания, как в АПК?
(предварительно да)
2. Англоязычными синонимы аналогично?
(предварительно да)
3. Я бы добавил еще "Экспорт" в этот список, не знаю почему его нет в АПК.
4. Насколько я понимаю, запросы делаем отдельной проверкой, так как для них дерево не строится.
(сейчас не проверяется)

**Comment by asosnoviy** [comment]
За первые три плюсану. А в 4й не понял вопроса =(

**Comment by Stepa86** [comment]
> В стандарте сказано, "как в документации или Синтакс-помощнике".
> Беда в том, что автодополнение в конфигураторе не совпадает с тем, что написано в помощнике. Видим, поэтому, АПК и поддерживает разные варианты для логических операций и для "каждого".
> Я, кстати, обычно пользуюсь автодополнением, поэтому "Или" и "Каждого".
> 
> Собственно, я набросал черновик проверки, так что надо как-то найти общий знаменатель:
> 
> 1. Поддерживаем оба варианта написания, как в АПК?
>    (предварительно да)
> 2. Англоязычными синонимы аналогично?
>    (предварительно да)
> 3. Я бы добавил еще "Экспорт" в этот список, не знаю почему его нет в АПК.
> 4. Насколько я понимаю, запросы делаем отдельной проверкой, так как для них дерево не строится.
>    (сейчас не проверяется)

А можно список каноновых слов параметризированным сделать? Чтоб свои добавлять можно было

**Comment by lChagelishvili** [comment]
> За первые три плюсану. А в 4й не понял вопроса =(

Я не уверен разбирается ли сейчас текст запроса на идентификаторы, просто не проверял.
Если он заходит одной строкой, то проверку делать сложнее.

**Comment by nixel2007** [comment]
> Я не уверен разбирается ли сейчас текст запроса на идентификаторы, просто не проверял.
Если он заходит одной строкой, то проверку делать сложнее.

пока не разбирается. оставим отдельно на будущее.

> 1. Поддерживаем оба варианта написания, как в АПК?

я бы добавил настройку. но так как интерфейса настроек пока нет, то да, пока поддерживаем оба варианта. но если начнешь делать, оставь, пожалуйста, место для простого отключения 

* ИЛИ или Или
* НЕ или Не
* Каждого или каждого

**Comment by lChagelishvili** [comment]
Кстати, посмотрел EDT там в автодополнении тоже: 
- Каждого
- Или
- Не
