### ISSUE TITLE
[FP] НСтр содержит все языки

### ISSUE THREAD

**Issue by qtLex** [1c-syntax/bsl-language-server#625]
## Диагностика

MultilingualStringHasAllDeclaredLanguages

## Версия

develop

## Описание ложного срабатывания диагностики

Если строка для НСтр содержит "" вместо ' или ='внутри текста срабатывает диагностика. А она срабатывать не должна, так как есть описание всех необходимых языков

## Пример кода
``` bsl
Порция = Сервис.Autocomplete(ИдентификаторАдресногоОбъекта, 0, НСтр("ru = 'ДОМ='"), 1, КодЯзыка, Метаданные.Имя);

ВычисляемоеПоле.Оформление.УстановитьЗначениеПараметра("Формат", НСтр("ru = 'ДФ=''д ММММ'''"));

Возврат НСтр("en=""You must specify the user's extension number to the PBX."";ru='Необходимо указать внутренний номер пользователя АТС.'");
```

## Скриншоты

![с двойными ковычками ](https://user-images.githubusercontent.com/5488710/68767294-80a9d780-0631-11ea-93d7-8e988b98b349.png)
![с равно и ковычкой ](https://user-images.githubusercontent.com/5488710/68767295-80a9d780-0631-11ea-8c01-b56c3c56b0d6.png)

**Comment by asosnoviy** [comment]
А должна другая?

**Comment by qtLex** [comment]
Вообще не должна. В изначальном тексте уточнил

**Comment by qtLex** [comment]
Повесьте на меня.

**Comment by asosnoviy** [comment]
```
НСтр("en=""You must specify the user's extension number to the PBX."")
```
Это валидная строка? `'` необязательна там?

**Comment by qtLex** [comment]
Тоже за сомневался сначала, но оказалась валидная.

**Comment by DitriXNew** [comment]
Так делать не правильно. Есть стандарты 1С, и есть они не зря. Прям оттуда скрины:
https://its.1c.ru/db/v8std/content/761/hdoc
![image](https://user-images.githubusercontent.com/11927866/68776876-725fb980-0639-11ea-9bd4-1e5f8ceaba96.png)

А на счет вот этого:
НСтр("ru = 'ДФ=''д ММММ'''")
То это просто помечается как ложное срабатываение и все. Потому что вы пытаетесь всунуть код программы в строку, и очевидно, что парсер себе ноги там поломает. 
Или попробуйте вот так:
НСтр("hash = 'ДФ=""д ММММ"" ' ")
Так как сама 1С советует писать на таком примере:
![image](https://user-images.githubusercontent.com/11927866/68778188-7db3e480-063b-11ea-9a04-4db49a70e5b8.png)

**Comment by qtLex** [comment]
Абсолютно согласен, что писать так не правильно. Но мне кажется на это должна указать другая диагностика с другим уровнем критичности и категорией. Так как такой код отработает и не вызовет проблем у пользователей.

Подобные "срывы" у парсера многоязычных строк будет мешать реализовывать остальные диагностики связанные с НСтр.

**Comment by DitriXNew** [comment]
А вот то, что эта проверка должна работать по другому - это да.
Как по мне - если нету строки на основном языке конфигурации - то это ошибка.
А если нету на дополнительных - то это не ошибка нифига.

Мы патчим конфигурацию переводами после тестов, в том числе и сонары. Т.е. у нас есть все языки в конфигурации, но тексты добавляются патчингом потом.
А тут получается что это фиксируется как ошибка. И тест не пройден :)
А отключить не могу, потому что если какой то кадр решит написать строку на ru, при том что основной язык en - то я эти места хочу выловить. Особенно при копипасте часто такое бывает.
Так что предлагаю разбить эту проверку на 2.
Чтобы можно было отключать проверку всех языков, кроме основного. И тут уровень ошибки можно сделать ниже. И вторая - нет перевода на основной язык конфы. Вот тут уже эррор, а если в строке еще есть и параметры типо %1, %2 - то тогад вообще критикал эррор.

**Comment by DitriXNew** [comment]
По поводу НСтр - не соглашусь. Ибо НСтр написан правильно, или не правильно. И все.
И если он написан не правильно - то там можеть лезть все что угодно и даже больше. 
А сидеть и всякие приколы добавлять в исключения - ну я даже не знаю.
Т.е. действительно ли может быть конфа, где таких мест тыщщщиии. И программист не может исправить это Г за пару минут? Чтобы оно не светило, а если не исправляет, то как бы - пусть правило вырубает. Ему тогда точно сонар нужен? ИМХО.

**Comment by asosnoviy** [comment]
@DitriXNew Думаю предложение в том, чтобы это нарушение, ловить отдельной диагностикой. В ней же может быть и квикфикс для быстрого исправления кавычек.
