### ISSUE TITLE
LineLength на методах

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#63]
Должно ли срабатывать на методах?
```bsl
Процедура Подключаемый_СвойстваВыполнитьКоманду(ЭлементИлиКоманда, НавигационнаяСсылка = Неопределено, СтандартнаяОбработка = Неопределено)
```
Имхо да, но даже на SSL зашкаливает количество срабатываний.

может под настройку?

**Comment by nixel2007** [comment]
Стандарт вроде отдельно даже говорит, что переносить параметры в сигнатуре надо.
