### ISSUE TITLE
[BUG] Кривые описания некоторых диагностик

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#649]
**Версия**
> Версия BSLLS либо плагина, который использует BSLLS

latest

**Описание ошибки диагностики**
> Описание ошибки, замечачания

Часть описаний диагностик не содержит информации отличной от автогенерируемой + есть описания, созданные без использования шаблона (например MultilingualStringHasAllDeclaredLanguages.md)

**Пример кода**
> Пример кода (в блоке code или прикрепленный файл), на котором ошибка воспроизводится

**Скриншоты**
> Скриншоты с подтверждением

**Дополнительная информация**
> Любая дополнительная информация, которая поможет в расследовании проблемы

**Comment by MironovDmitry** [comment]
Оставлю тут список диагностик без описания:

- https://gitlocalize.com/repo/1840/en/docs/diagnostics/EmptyStatement.md
- https://gitlocalize.com/repo/1840/en/docs/diagnostics/FunctionShouldHaveReturn.md
- https://gitlocalize.com/repo/1840/en/docs/diagnostics/SemicolonPresence.md
- https://gitlocalize.com/repo/1840/en/docs/diagnostics/UnknownPreprocessorSymbol.md
