### ISSUE TITLE
Неиспользуемый параметр

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#66]
С ошибкой:
```bsl
Функция СложитьДваЧисла(Знач ПервоеЧисло, Знач ВтороеЧисло, Знач ЛишнийПараметр)

    Возврат ПервоеЧисло+ВтороеЧисло;

КонецФункции
```
С ошибкой 2
```bsl
Функция СложитьДваЧисла(Знач ПервоеЧисло, Знач ВтороеЧисло, Знач ЛишнийПараметр = Неопределено)

Возврат ПервоеЧисло+ВтороеЧисло;

КонецФункции
```
Без ошибки
```bsl
Функция СложитьДваЧисла(Знач ПервоеЧисло, Знач ВтороеЧисло)

Возврат ПервоеЧисло+ВтороеЧисло;

КонецФункции
```

**Comment by asosnoviy** [comment]
Помню про "Отказ" и прочие параметры обработчиков.

**Comment by zeegin** [comment]
Без базы контекстов ты это сделать не сможешь. Надо знать описания всех обработчиков событий платформы.

А кроме платформы есть еще ДляВызоваИзДругихПодсистем - где библиотечные обработчики событий, там тоже может много сыпаться неиспользуемого.

А еще разные ОпсианиеОповещения тоже будут генерировать это событие, потому что некоторые их них много параметров содержат, например обработчики исключений целых три параметра.

**Comment by asosnoviy** [comment]
А если ограничится локальными методами, пока нет контекста?

**Comment by nixel2007** [comment]
@asosnoviy ПередЗаписью? Он не экспортный, но содержит редко-используемые параметры

**Comment by asosnoviy** [comment]
> @asosnoviy ПередЗаписью? Он не экспортный, но содержит редко-используемые параметры

Туда же куда и отказ.

**Comment by Stepa86** [comment]
В первой реализации можно без базы контекстов сделать, а с исключениями. Типа не проверять параметры Отказ, СтандартнаяОбработка, Кнопка, ТекущийОбъект, Элемент, ДополнительныеПараметры, НоваяСтрока, Копирование, Копирование, Родитель, Группа, Параметр, РежимЗаписи, РежимПроведения...
