### ISSUE TITLE
Неиспользуемый неэкспортный метод

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#67]
На обработчики событий и на Подключаемый_ не должно ругаться

**Comment by asosnoviy** [comment]
С костылем на обработчики комманд формы, можно сделать прямо сейчас.

**Comment by asosnoviy** [comment]
@zeegin @hawk911 может вы помните "Подключаемый_" в eng как?

**Comment by zeegin** [comment]
https://its.1c.ru/db/v8std#content:492

Подключаемый_ (англ. Attachable_)

**Comment by zeegin** [comment]
https://its.1c.ru/db/v8std#content:469

 "Переопределяемый" (англ. "Overridable")
