### ISSUE TITLE
DiagnosticParameter - описание из ресурсов

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#679]
Изменить интерфейс DiagnosticParameter таким образом, чтобы иметь возможность указывать описание параметра на русском и английском языках

**Comment by nixel2007** [comment]
казалось, что такой ишуз уже был

**Comment by theshadowco** [comment]
Не нашел

**Comment by nixel2007** [comment]
Ну и ладно. Надо, да. И генерилку документации под нее подпилить

**Comment by theshadowco** [comment]
Ага
