### ISSUE TITLE
FP: Диагностика объектов недоступных в Unix StrikeBack

### ISSUE THREAD

**Issue by KrapivinAndrey** [1c-syntax/bsl-language-server#687]
Все равно срабатывает #409 

Пример можно взять здесь
src/test/resources/diagnostics/UsingObjectNotAvailableUnixDiagnostic.bsl

**Comment by theshadowco** [comment]
@KrapivinAndrey 
На акутальной версии срабатывает? у меня не удалось пока повторить

**Comment by KrapivinAndrey** [comment]
На актуальной вроде работает

**Comment by theshadowco** [comment]
я тогда закрою.
