### ISSUE TITLE
[FP] Ошибка проверка метода СоздатьКаталог в модуле HTTP сервиса

### ISSUE THREAD

**Issue by Daabramov** [1c-syntax/bsl-language-server#688]
## Диагностика
Использование синхронных вызовов

## Версия
v0.12.2

## Описание ложного срабатывания диагностики
В модуле HTTP сервиса (выполняется на сервере) проверка ругается на метод СоздатьКаталог и предлагает использовать ассинхронный метод Начать...

## Пример кода
```

Функция MethodPost(Запрос)
   СоздатьКаталог(Константы.АдресХранилища.Получить()+"\"+XMLСтрока(ТекФайлРеквеста));
КонецФункции

```

**Comment by nixel2007** [comment]
Ась? Чего закрыл?

**Comment by Daabramov** [comment]
> Ась? Чего закрыл?

А вроде уже и нет FP

**Comment by nixel2007** [comment]
Хм. Ну ок :)
