### ISSUE TITLE
[FP] Используется хранение в коде ip-адреса

### ISSUE THREAD

**Issue by ovcharenko-di** [1c-syntax/bsl-language-server#691]
## Диагностика
Используется хранение в коде ip-адреса

## Версия
0.12.2

## Пример кода
```bsl
СтрокаСообщения = НСтр("ru = '%1
  |Параметры синхронизации данных для этой программы:
  |========================================================
  |%2%3Префикс информационной базы: %4
  |
  |Параметры синхронизации данных для другой программы::
  |========================================================
  |%5%6Префикс информационной базы: %7'");

```

## Скриншоты
![image](https://user-images.githubusercontent.com/24920942/69240547-c4f72380-0bad-11ea-8bbf-a6fb6a6a4685.png)

**Comment by DitriXNew** [comment]
Еще одно ложное:
`
FoundedElement =
		HTMLDocument.evaluate(".//img[ancestor::div[@aria-hidden=""False""]]", HTMLDocument.body, null, 0, null).iterateNext();
`
