### ISSUE TITLE
[FP] Ложное срабатывание на параметр Таймаут

### ISSUE THREAD

**Issue by astrizhachuk** [1c-syntax/bsl-language-server#694]
## Диагностика
TimeoutsInExternalResourcesDiagnostic

## Версия
0.12.2

## Описание ложного срабатывания диагностики
До версии платформы 8.3.7 положение параметра Таймаут в конструкторах HTTPСоединение, WSОпределения, WSПрокси было иным: 4-м слева, а не 5-м. (Реализован параметр ИспользоватьАутентификациюОС в конструкторе HTTPСоединение, WSОпределения, WSПрокси. Источник: https://dl03.1c.ru/content/Platform/8_3_16_1063/1cv8upd_8_3_16_1063.htm#bd3d298b-b1fc-11e4-a3f7-0050569f678a)

## Пример кода
`Сервис 				= Новый WSПрокси(ОпределениеСервиса, НеймСпейс, Имя, Порт, 50000);`

## Скриншоты
![photo_2019-11-20_21-37-28](https://user-images.githubusercontent.com/25724999/69275720-01e30a80-0bee-11ea-83f8-9e812a9bff5a.jpg)

**Comment by nixel2007** [comment]
@otymko
