### ISSUE TITLE
Включить ключ диагностики в страницу описания диагностики

### ISSUE THREAD

**Issue by Ndochp** [1c-syntax/bsl-language-server#697]
Сейчас поле ключ диагностики со страницы https://1c-syntax.github.io/bsl-language-server/diagnostics/ 
не отображается на самой странице диагностики (напр https://1c-syntax.github.io/bsl-language-server/diagnostics/CognitiveComplexity/  поле "CognitiveComplexity")
В результате при написании конфигурационного файла имя диагностики приходиться копипастить с одной страницы, а параметры - из другой.

Ожидаемое поведение:
На странице описания диагностики содержатся все данные, относящиеся к этой диагностике.

Ишш общий, а не предложение с исправлением, так как насколько я понимаю заголовки страниц диагностик генерируются автоматически.

**Comment by qtLex** [comment]
Может стоит для удобства сразу генерировать фрагмент для конфигурационного файла? Чтоб скопировал значение поменял и вперед.

**Например**

CognitiveComplexity:
```
CognitiveComplexity": {
    "complexityThreshold": 15,
    "checkModuleBody" : true
}
```
MissingSpace:
```
"MissingSpace" : {
  "allowMultipleCommas" : true
}
```
IfElseIfEndsWithElse:
```
"IfElseIfEndsWithElse": false
```

**Comment by asosnoviy** [comment]
Частично эту проблему призвана закрывает джсонСхема. Но ключ на странице описание надо.

**Comment by asosnoviy** [comment]
Сейчас можно воспользоваться этой -
`https://raw.githubusercontent.com/1c-syntax/bsl-language-server/develop/src/main/resources/com/github/_1c_syntax/bsl/languageserver/configuration/diagnostics-schema.json`

**Comment by theshadowco** [comment]
@Ndochp 
А можешь картинку нарисовать, где разместить? я дизайнер очень херовый

**Comment by theshadowco** [comment]
> Может стоит для удобства сразу генерировать фрагмент для конфигурационного файла? Чтоб скопировал, значение поменял и вперед.
> 
> **Например**
> 
> CognitiveComplexity:
> 
> ```
> CognitiveComplexity": {
>     "complexityThreshold": 15,
>     "checkModuleBody" : true
> }
> ```
> 
> MissingSpace:
> 
> ```
> "MissingSpace" : {
>   "allowMultipleCommas" : true
> }
> ```
> 
> IfElseIfEndsWithElse:
> 
> ```
> "IfElseIfEndsWithElse": false
> ```

аналогично комментарию выше

**Comment by zeegin** [comment]
И еще фрагмент с отключением в коде

**Comment by Ndochp** [comment]
> 
> 
> @Ndochp
> А можешь картинку нарисовать, где разместить? я дизайнер очень херовый
Я тоже дизайнер не фонтан, но поставил бы ключ на одном уровне с заголовком, например в скобках после или следующей строкой. А примеры кода после таблицы с параметрами напрашиваются

**Comment by qtLex** [comment]
Я бы предложил вставлять в конце после источников. Например https://github.com/qtLex/bsl-language-server/blob/temp/doc-template/docs/diagnostics/CognitiveComplexity.md

**Comment by Ndochp** [comment]
Ну вроде все до раздела "## Описание диагностики" заполняет робот, а ниже - человек.
Так что ключ наверное вверх, а вот примеры кода если нужны человеконаписанные, то можно вниз, а если робот, то наверное после таблицы параметров.

**Comment by theshadowco** [comment]
Такой результат? 
![image](https://user-images.githubusercontent.com/9591731/69811796-ea181180-11ff-11ea-991d-9b9efc7b40a3.png)

**Comment by otymko** [comment]
Отлично!

**Comment by qtLex** [comment]
Великолепно!!!
