### ISSUE TITLE
[FP] UsingHardcodeNetworkAddress срабатывает на версии ПО

### ISSUE THREAD

**Issue by acharushkin** [1c-syntax/bsl-language-server#699]
## Диагностика
server:UsingHardcodeNetworkAddress

## Версия
Sonar 1C (BSL) Community Plugin ver. 1.3.1

## Описание ложного срабатывания диагностики
Функция возвращает строковую константу с номером версии чего-либо, но диагностируется ошибка.

## Пример кода
```
Функция ВерсияМоегоПродукта()
    Возврат "1.2.3.4";
КонецФункции
```

## Скриншоты
Не сохранились)

## Дополнительная информация
Обошли так:
```
Функция ВерсияМоегоПродукта()
    Версия = "1.2.3.4";
    Возврат Версия;
КонецФункции
```

**Comment by acharushkin** [comment]
Кстати, было бы неплохо в проверке учитывать, соответствует ли строка маске ip-адреса.
Например, в строке "1.2.4.555" 4-й октет не влезает в маску.

**Comment by nixel2007** [comment]
В данном случае невозможно отличить версию от айпи-адреса. помечайте сразу в сонаре как FP или оборачивайте в `BSLLS:UsingHardcodeNetworkAddress-off`

**Comment by nixel2007** [comment]
Предлагаю закрыть.

**Comment by zeegin** [comment]
Предлагаю записать FN на
```bsl
Функция ВерсияМоегоПродукта()
    Версия = "1.2.3.4";
    Возврат Версия;
КонецФункции
```

**Comment by nixel2007** [comment]
@zeegin это не FN. "Верси" входит в список разрешённых идентификаторов в параметрах этой диагностики. Его можно оттуда исключить, и такая строка тоже будет ловиться

**Comment by asosnoviy** [comment]
> Кстати, было бы неплохо в проверке учитывать, соответствует ли строка маске ip-адреса.
> Например, в строке "1.2.4.555" 4-й октет не влезает в маску.

А вроде так и работает.
