### ISSUE TITLE
Отказ = Функция()

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#70]
https://its.1c.ru/db/v8std#content:2149184335:hdoc

**Comment by zeegin** [comment]
Если сформулировать формально:
Параметру `Отказ` запрещено присваивать что-либо кроме `Истина`.

**Comment by asosnoviy** [comment]
Еще есть "псевдо отказ". Когда это не параметр обработчика, а локальная переменная.

**Comment by zeegin** [comment]
В идеале надо по графу потока данных понять что это инициализация переменной в псевдослучае и требовать присвоение ей Ложь, в других случаях требовать присвоение Истина?

**Comment by asosnoviy** [comment]
Так же думаю. Если псевдо(нет в параметрах) первое присвоение инициализация остальное истина. Но псевдоОтказ поймается только по имени переменной((( А в нетленках чего только не встречается...

**Comment by asosnoviy** [comment]
Кстати у меня эта проверка стреляла, она прям полезная.

**Comment by asosnoviy** [comment]
Отказ = Отказ Или ЕстьОшибкиЗаполнения(); а стандарт поменялся с момента последнего перечитывания)

**Comment by nixel2007** [comment]
> В идеале надо по графу потока данных понять что это инициализация переменной в псевдослучае

проще. смотрим параметры метода, если среди них нет отказа - не стреляем.

**Comment by asosnoviy** [comment]
А я бы стрелял.

**Comment by nixel2007** [comment]
FP наловишь)
