### ISSUE TITLE
[BUG] Не работает параметр maxAllowedLevel в NestedStatementsDiagnostic

### ISSUE THREAD

**Issue by qtLex** [1c-syntax/bsl-language-server#701]
## Диагностика

NestedStatementsDiagnostic

## Версия

v0.12.2

## Описание ошибки диагностики

Для диагностики установлено значение больше чем по умолчанию, но все равно отрабатывает значение по умолчанию.

## Скриншоты

Настройка 8
![Настройка](https://user-images.githubusercontent.com/5488710/69436045-b21d5400-0d51-11ea-9665-02ea68ebdffb.png)

А ругается уже на вложенность 5
![Результат](https://user-images.githubusercontent.com/5488710/69436054-b77a9e80-0d51-11ea-8a6f-3ba7ea9a4b80.png)

**Comment by nixel2007** [comment]
Профиль для проекта активирован?

**Comment by qtLex** [comment]
Да.
В диагностике не переопределен метод ```configure```.

**Comment by qtLex** [comment]
Повесь на меня, поправлю.
