### ISSUE TITLE
[BUG] Если файл оканчивается на одну пустую строку, форматтер вставляет еще одну пустую строку

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#703]
**Версия**
> Версия BSLLS либо плагина, который использует BSLLS

0.12.2

**Описание ошибки диагностики**
> Описание ошибки, замечачания

При форматировании файла, заканчивающегося на пустую строку, единоразово добавляется еще одна пустая строка.

**Пример кода**
> Пример кода (в блоке code или прикрепленный файл), на котором ошибка воспроизводится

```bsl
Процедура ТестДолжен_ОтсортироватьТаблицуПоКолонке() Экспорт
	Сообщить("Привет, мир");
КонецПроцедуры

```

**Скриншоты**
> Скриншоты с подтверждением

![image](https://user-images.githubusercontent.com/1132840/69439104-535ad900-0d57-11ea-8b40-28a621a2056d.png)

**Дополнительная информация**
> Любая дополнительная информация, которая поможет в расследовании проблемы

**Comment by asosnoviy** [comment]
После появление EOF поведение может поменяться
