### ISSUE TITLE
[FP] Пробелы в комментариях фонят при срабатывании диагностики на закомментированный код

### ISSUE THREAD

**Issue by nixel2007** [1c-syntax/bsl-language-server#710]
## Диагностика

SpaceAtStartComment

## Версия

0.12.2

## Описание ложного срабатывания диагностики

При срабатывании диагностики CommentedCode на этом же блоке комментария было бы здорово, не фонить сообщениями от SpaceAtStartComment

## Скриншоты

![image](https://user-images.githubusercontent.com/1132840/69708822-56feaf00-110d-11ea-812c-29af00789b83.png)

**Comment by theshadowco** [comment]
А как? анализировать наличие замечаний одной диагностики в процессе работы другой?

**Comment by nixel2007** [comment]
у нас уже есть где-то диагностика, которая дергает CodeAnalyzer с целью понять, код это или нет. Тут нужно что-то такое же.
