### ISSUE TITLE
[FP] Есть локализованный текст для всех заявленных в конфигурации языков

### ISSUE THREAD

**Issue by sfaqer** [1c-syntax/bsl-language-server#712]
## Диагностика
MultilingualStringHasAllDeclaredLanguages

## Версия
0.12

## Описание ложного срабатывания диагностики
1. Срабатывает если локализованная строка начинается с ;
2. Срабатывает в случае если строка передаётся через переменную
3. Срабатывает на локализованную форматную строку

## Пример кода
1. 
```bsl
БыстрыйДоступПредставление = СтроковыеФункцииКлиентСервер.СтрокаСЧисломДляЛюбогоЯзыка(
	НСтр("ru = ';%1 пользователь;;%1 пользователя;%1 пользователей;%1 пользователя'"), КоличествоПользователей);
```
2.
```bsl
Для каждого КодЯзыка Из КодыЯзыков Цикл
	Элемент[ИмяЛокализуемогоРеквизита(ИмяРеквизита, КодЯзыка)] = НСтр(ИсходнаяСтрока, КодЯзыка);
КонецЦикла;
```
3.
```bsl
ДанныеИзмерения.Формат = НСтр("ru = 'ДФ=''yyyy ""г.""''; ДП=''Дата не задана'''");
```
```bsl
НСтр("ru = '[НаименованиеРассылки] от [ДатаВыполнения(ДЛФ=''D'')]'");
```
## Скриншоты
1. 
![image](https://user-images.githubusercontent.com/32082417/69837743-ff427e00-129b-11ea-80a5-8abf3c64e749.png)
2.
![image](https://user-images.githubusercontent.com/32082417/69837785-30bb4980-129c-11ea-8632-e96146ddd658.png)
3.
![image](https://user-images.githubusercontent.com/32082417/69837819-62341500-129c-11ea-8ea8-fecdb334c1f3.png)
![image](https://user-images.githubusercontent.com/32082417/69837875-bd660780-129c-11ea-96e6-c144ee64957d.png)

**Comment by nixel2007** [comment]
Третье вроде бы должно быть исправлено в 0.12.2, разве нет?

**Comment by qtLex** [comment]
![Замечания](https://user-images.githubusercontent.com/5488710/69857715-8e9e6000-12a1-11ea-941a-c18cce477e8b.png)

Исправлена. В vsc не ругается. Но в плагин из маркета это исправление не попало

**Comment by nixel2007** [comment]
Видимо, оно исправлено в 0.12.3. А в сонаре и в текущем релизе VSCode - 0.12.2

**Comment by nixel2007** [comment]
Тогда п.3 это дубликат #625

А что скажешь по 1 и 2 пунктам?

**Comment by qtLex** [comment]
FP.
1. Понятно где ошибка: ```';``` разделитель между разными языками, строка разрезалась и потерялся текст для языка. Пока не понятно как обходить, нужно подумать.

2. Тоже все ясно. Не проверил на тип параметра. Вижу два варианта:
  а. Не проверять если параметр не строковый литерал.
  б. Раскручивать токены до определения переменной и пытаться поверить строку там.

Склоняюсь к первому варианту, так как в большинстве случаев не получиться  получить "нормальную" строку для анализа.

Повесь на меня.

P. S.

Есть еще такой тип FP:
```
НСтр("ru='" + ПодразделениеКомпании.Наименование + " " +НСтр("ru = 'не принадлежит'") + " " + Организация.Наименование + "'")
```
С ним не понятно как поступать. У себя приняли решение, что ошибка и переписали. Благо всего десятка два набралось.

**Comment by asosnoviy** [comment]
А 2. это разве валидное использование Нстр ? Что будет отображено в строке для перевода?

**Comment by qtLex** [comment]
Вполне. По фрагменту не понятно чего хотели добиться, но работать будет. Все зависит от содержимого переменной. Если там будет валидный текст для НСтр то проблем не будет.
