### ISSUE TITLE
Таска на доку не переваривает сложные параметры

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#723]
@theshadowco посмотри на досуге плз, похоже тут парсер параметров ломается об List

_Originally posted by @asosnoviy in https://github.com/1c-syntax/bsl-language-server/pull/722#issuecomment-560523251_

**Comment by nixel2007** [comment]
А почему вообще тип параметра берется из определения переменой? там может быть что угодно. Тип должен парсится из аннотации

**Comment by asosnoviy** [comment]
Я только предположил.
