### ISSUE TITLE
Правило "Хранение ip-адресов в коде"

### ISSUE THREAD

**Issue by AlexPCRus** [1c-syntax/bsl-language-server#725]
Полагаю что все же ошибочно срабатывает на параметры функции с значением по умолчанию.
В моем случае это:

```bsl
Функция ПодготовитьСведенияОВнешнейОбработке(Вид, Назначение, Наименование, Версия, Информация, БезопасныйРежим = Ложь, ВерсияБСП = "1.2.1.4", РассылкаОтчетов = Ложь) Экспорт
КонецФункции
```
хотя в параметрах правила вроде как указано пропускать слова, начинающиеся с "Верси*".

**Comment by otymko** [comment]
@AlexPCRus Срабатывание именно на параметрах метода?

**Comment by AlexPCRus** [comment]
@otymko Похоже на то:
![Версия](https://user-images.githubusercontent.com/47207960/70030925-4477f000-15bb-11ea-9166-395faa84ad9d.PNG)

**Comment by nixel2007** [comment]
Ммм... я бы не сказал, что это FP. Действительно, в параметрах тоже можно забить ip-адрес по умолчанию и это тоже не очень хорошо.

В данном случае, я бы просто закрыл этот ишуз в сонаре, без доработки bsl ls. 

@otymko но странно, что не отработал фильтр на "Верси". Можешь проверить этот момент?

**Comment by otymko** [comment]
@nixel2007 да, я посмотрю почему не работает фильтр.

**Comment by zeegin** [comment]
На самом деле очень много срабатываний.
Предлагаю в случае когда первая цифра равна 1, 2, 3, 8, 11 не ругаться.

**Comment by asosnoviy** [comment]
192.168
8.8

**Comment by zeegin** [comment]
(1|2|3|11).*.*.*
8.3.*.*

**Comment by asosnoviy** [comment]
Функция ВерсияБиблиотеки() Экспорт
   Возврат "2.9.4.0";
КонецФункции
