### ISSUE TITLE
[MOD] LineLength отключить для описаний методов

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#726]
## Диагностика

LineLength 

## Описание предлагаемых изменений

Описания методов по правилам должны содержать перечень типов параметра. Если типов много, то строка превышает допустимое ограничение, но если перенести то EDT к сожалению перестает понимать тип.

Предложение в следующем: если строка комментария является описанием параметра / возвращаемого значения, то не мерять ее длину.

## Дополнительная информация

```
Пример 

// ВычестьУниверсальнуюКоллекцию
//  Процедура удаляет элементы одной коллекции из другой, если коллекции одинаковых типов
//
// Параметры:
//  Приемник - Массив, ФиксированныйМассив, СписокЗначений, Структура, ФиксированнаяСтруктура, Соответствие, ФиксированноеСоответствие, ТаблицаЗначений - Уменьшаемая коллекция
//  Источник - Массив, ФиксированныйМассив, СписокЗначений, Структура, ФиксированнаяСтруктура, Соответствие, ФиксированноеСоответствие, ТаблицаЗначений - Вычитаемая коллекция
//
Процедура ВычестьУниверсальнуюКоллекцию(Приемник, Источник) Экспорт

```

**Comment by asosnoviy** [comment]
Жбахни пример плз
