### ISSUE TITLE
[MOD] CommentedCode исключения

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#727]
## Диагностика

CommentedCode

## Описание предлагаемых изменений

В библиотечных методах требуется приводить пример использования, что диагностируется как закомментированный код. 
Предложение следующее: разработать некоторый формат выделения примеров кода как примеры и добавить такие блоки в исключение диагностики

**Comment by nixel2007** [comment]
Примеры использования по стандарту должны быть в описании метода. Закомментированный код в описании метода не триггерит эту диагностику. В чем вопрос? :)

**Comment by theshadowco** [comment]
пример: у меня есть переопредялемый модуль, который содержит пример кода, который в него можно вставить для того, чтобы правильно переопредлить стандартную функциональность.

**Comment by nixel2007** [comment]
почему это не поместить в документацию к методу?

**Comment by theshadowco** [comment]
честно? потому что модуль = шаблон с определенными вставками-аннотациями для пре/постпроцессинга.

Лан, согласен, для большинства это реально нафиг не нада, описания достаточно

**Comment by asosnoviy** [comment]
> почему это не поместить в документацию к методу?

Кажется это про:

///////////////////////////////////
// Модуль суперПупер
// Используется для всего на свете
// Пример:
// Суперметод()
