### ISSUE TITLE
[FP] UnreachableCode ругается на region

### ISSUE THREAD

**Issue by zeegin** [1c-syntax/bsl-language-server#730]
## Диагностика

`UnreachableCode`

## Версия

v0.12.3

## Описание ложного НЕ срабатывания диагностики

Если `#endregion` после `return`

## Пример кода

https://sonar.openbsl.ru/project/issues?id=tester&open=AW7NGnB_b__XJORGgbzf&resolved=false&types=BUG

## Скриншоты

![Screenshot_20191204-012622_Chrome](https://user-images.githubusercontent.com/729213/70095412-ba20a200-1635-11ea-99af-8774e6431fc4.jpg)

**Comment by asosnoviy** [comment]
и на конецЕсли

![image](https://user-images.githubusercontent.com/15638529/81336858-beecf480-90b2-11ea-9e1c-06d5bfaee882.png)
