### ISSUE TITLE
[NEW] Экранирование кавычек в текстах запросов

### ISSUE THREAD

**Issue by ovcharenko-di** [1c-syntax/bsl-language-server#738]
## Описание проблемы, ошибки, которую надо диагностировать
Разработчики допускают ошибки при редактировании текстов запросов: не экранируют двойные кавычки. Чаще всего это приводит к тому, что запрос становится некорректным и  разработчик сразу же его исправляет, однако при определенных условиях явная ошибка в режиме конфигуратора не определяется, т.к. запрос остается синтаксически правильным. При этом, во время его выполнения из выборки исключаются некоторые поля.

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [x] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [x] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"

### Время на исправление (минут)
1 минута

## Дополнительная информация
Ниже указан пример запроса, на котором должно быть срабатывание диагностики. Запрос примечателен тем, что при его выполнении в выборку попадут только поля `Номенклатура` и `НоменклатураНаименование`. Поле `НоменклатураКод` будет исключено из-за проблемы с кавычками.

```bsl
Запрос = Новый Запрос;
Запрос.Текст = "ВЫБРАТЬ
|	ПриходныйОрдерНоменклатура.Номенклатура КАК Номенклатура,
|	ЕСТЬNULL(ПриходныйОрдерНоменклатура.Номенклатура.Код, "") КАК НоменклатураКод,
|	ЕСТЬNULL(ПриходныйОрдерНоменклатура.Номенклатура.Код, "") КАК НоменклатураНаименование
|ИЗ
|	Документ.ПриходныйОрдер.Номенклатура КАК ПриходныйОрдерНоменклатура
|ГДЕ
|	ПриходныйОрдерНоменклатура.Ссылка = &Ссылка";
```

**Comment by artbear** [comment]
@ovcharenko-di отличный пример

ИМХО после исправления парсера в https://github.com/1c-syntax/bsl-parser/issues/75 такие запросы будут сразу считаться невалидными )
@theshadowco верно?

я вчера сделал ишуз на подобные подозрительные строки вообще в коде 1С https://github.com/1c-syntax/bsl-language-server/issues/1557
и добавил ссылку на твой пример.

**Comment by theshadowco** [comment]
> ИМХО после исправления парсера в [1c-syntax/bsl-parser#75](https://github.com/1c-syntax/bsl-parser/issues/75) такие запросы будут сразу считаться невалидными )
> @theshadowco верно?

да

**Comment by ovcharenko-di** [comment]
в 0.18.0 на запрос из примера вешается MultilineStringInQuery. я думаю, что можно закрывать issue

**Comment by theshadowco** [comment]
Вместе с https://github.com/1c-syntax/bsl-language-server/issues/1557
