### ISSUE TITLE
Позиционирование EmptyCodeBlock

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#75]
![image](https://user-images.githubusercontent.com/15638529/52850774-6506b480-3125-11e9-8bf5-09fccbb6060b.png)

![image](https://user-images.githubusercontent.com/15638529/52850788-70f27680-3125-11e9-8a35-bd23ae6cf8d2.png)

**Comment by nixel2007** [comment]
а куда? на предыдущий токен?

**Comment by asosnoviy** [comment]
Да, надо попробовать
