### ISSUE TITLE
[FP] Не видит УдалитьФайлы при использовании ПолучитьИмяВременногоФайла

### ISSUE THREAD

**Issue by DoublesunRUS** [1c-syntax/bsl-language-server#753]
## Диагностика
Нужно добавить удаление временного файла после использования

## Версия
0.12.3

## Описание ложного НЕ срабатывания диагностики
В приведенном коде есть удаление временного файла, но диагностика этого не видит.

## Пример кода
```
  А = Истина;
  Если А Тогда
    ИмяФайла = ПолучитьИмяВременногоФайла("json");
    
  Иначе
    ИмяФайла = "ААА";
    
  КонецЕсли;
  
  Если А Тогда
    УдалитьФайлы(ИмяФайла);
  КонецЕсли;
```

**Comment by nixel2007** [comment]
dup #592
