### ISSUE TITLE
Отсутствует парный вызов "НачатьТранзакцию" для метода "ОтменитьТранзакцию"

### ISSUE THREAD

**Issue by awk-kazmin** [1c-syntax/bsl-language-server#756]
Правило ложно срабатывает если между методом НачатьТранзакцию() и оператором Попытка есть пустая строка.

**Comment by otymko** [comment]
Перемещено в проект bsl-language-server

**Comment by theshadowco** [comment]
Не удается повторить

Ниже пример, на котором все успешно работает.

```
Процедура Проц10()
    НачатьТранзакцию();

    Попытка
    Исключение
        ОтменитьТранзакцию();
    КонецПопытки;
    ЗафиксироватьТранзакцию();
КонецПроцедуры
```

**Comment by theshadowco** [comment]
@awk-kazmin 
Приложи пример метода, на котором срабатывает.

И еще, я почти уверен, что у тебя в коде написно пример следующее

```
Процедура Проц10()
    НачатьТранзакцию();

    Попытка
        Если Условие Тогда
            ОтменитьТранзакцию(); // <-- Еще одна отмена транзакции
            Возврат;
        КонецЕсли;
    Исключение
        ОтменитьТранзакцию();
    КонецПопытки;
    ЗафиксироватьТранзакцию();
КонецПроцедуры
```

**Comment by awk-kazmin** [comment]
Привет. Именно так и написано (правда в типовой, а не у меня).

Процедура ОбновитьНаборыЗначенийДоступаЗадания(Параметры, ЗаданиеСсылка) 
	
	МодульУправлениеДоступом = ОбщегоНазначения.ОбщийМодуль("УправлениеДоступом");
	НачатьТранзакцию();
	
	Попытка
		// Блокируем объект от изменения другими сеансами.
		Блокировка = Новый БлокировкаДанных;
		ЭлементБлокировки = Блокировка.Добавить("БизнесПроцесс.Задание");
		ЭлементБлокировки.УстановитьЗначение("Ссылка", ЗаданиеСсылка);
		Блокировка.Заблокировать();
		
		ЗаданиеОбъект = ЗаданиеСсылка.ПолучитьОбъект();
		Если ЗаданиеОбъект = Неопределено
			Или ЗаданиеОбъект.ГруппаИсполнителейЗадач <> Справочники.ГруппыИсполнителейЗадач.ПустаяСсылка() Тогда
			ОтменитьТранзакцию();
			ОбновлениеИнформационнойБазы.ОтметитьВыполнениеОбработки(ЗаданиеСсылка);
			Возврат;
		КонецЕсли;
		
		ЗаданиеОбъект.ГруппаИсполнителейЗадач = ?(ТипЗнч(ЗаданиеОбъект.Исполнитель) = Тип("СправочникСсылка.РолиИсполнителей"), 
			БизнесПроцессыИЗадачиСервер.ГруппаИсполнителейЗадач(ЗаданиеОбъект.Исполнитель, 
			ЗаданиеОбъект.ОсновнойОбъектАдресации, ЗаданиеОбъект.ДополнительныйОбъектАдресации), 
			ЗаданиеОбъект.Исполнитель);
		ЗаданиеОбъект.ГруппаИсполнителейЗадачПроверяющий = ?(ТипЗнч(ЗаданиеОбъект.Проверяющий) = Тип("СправочникСсылка.РолиИсполнителей"), 
			БизнесПроцессыИЗадачиСервер.ГруппаИсполнителейЗадач(ЗаданиеОбъект.Проверяющий, 
				ЗаданиеОбъект.ОсновнойОбъектАдресацииПроверяющий, ЗаданиеОбъект.ДополнительныйОбъектАдресацииПроверяющий), 
			ЗаданиеОбъект.Проверяющий);
		
		МодульУправлениеДоступом.ОбновитьНаборыЗначенийДоступа(ЗаданиеОбъект);
		Если ЗаданиеОбъект.Модифицированность() Тогда
			ОбновлениеИнформационнойБазы.ЗаписатьДанные(ЗаданиеОбъект);
		Иначе
			ОбновлениеИнформационнойБазы.ОтметитьВыполнениеОбработки(ЗаданиеСсылка);
		КонецЕсли;
		
		ЗафиксироватьТранзакцию();
	Исключение
		ОтменитьТранзакцию();
Отсутствует парный вызов "НачатьТранзакцию" для метода "ОтменитьТранзакцию"See Rule

5 месяцев назад
L257
Ошибка

Важное

Открыто

Не назначено
15min усилий

Прокомментировать

standard
		ВызватьИсключение;
	КонецПопытки;
		
КонецПроцедуры

**Comment by nixel2007** [comment]
Это нарушение стандарта и диагностика ругается вполне обоснованно :)

**Comment by awk-kazmin** [comment]
Может правильнее было бы добавить правило: "Отмена транзакции вне блока исключения"?

Неправильно:

Попытка
 ...
 ОтменитьТранзакцию()

...

Исключение


Правильно:

Попытка
...
  ВызватьИсключение "Бла-бла-бла":
...
Исключение
  ОтменитьТранзакцию();

**Comment by awk-kazmin** [comment]
Это нарушение стандарта и диагностика ругается вполне обоснованно :)

Не совсем. Все сводится к пониманию слова: "парный" - в условиях нелинейного выполнения кода.

**Comment by theshadowco** [comment]
> Может правильнее было бы добавить правило: "Отмена транзакции вне блока исключения"?
> 
> Неправильно:
> 
> Попытка
> ...
> ОтменитьТранзакцию()
> 
> ...
> 
> Исключение
> 
> Правильно:
> 
> Попытка
> ...
> ВызватьИсключение "Бла-бла-бла":
> ...
> Исключение
> ОтменитьТранзакцию();

такая диагностика в планах есть

**Comment by theshadowco** [comment]
Итого, закрываю, т.к. не ошибка
