### ISSUE TITLE
Вложенные вызовы функций в параметрах

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#76]
6.1. Не рекомендуется при передаче параметров в одну функцию применять вложенные вызовы других функций.
Неправильно:

```BSL
СтруктураВложений.Вставить(
 ПрисоединенныйФайл.Наименование,
 Новый Картинка(ПолучитьИзВременногоХранилища(
  ПрисоединенныеФайлы.ПолучитьДанныеФайла(ПрисоединенныйФайл.Ссылка).СсылкаНаДвоичныеДанныеФайла)));
```
Правильно разбивать такие вызовы на отдельные операторы с помощью вспомогательных локальных переменных:
```BSL
АдресФайлаИзображения = ПрисоединенныеФайлы.ПолучитьДанныеФайла(ПрисоединенныйФайл.Ссылка).СсылкаНаДвоичныеДанныеФайла;
ДанныеИзображения = Новый Картинка(ПолучитьИзВременногоХранилища(АдресФайлаИзображения));
СтруктураВложений.Вставить(ПрисоединенныйФайл.Наименование, ДанныеИзображения);
```
В то же время, если код с вложенными вызовами получается компактным (не требует переноса выражений) и легко читаемым, то вложенные вызовы допустимы. 
Например:

```BSL
Предупреждение(НСтр("ru='Для выполнения операции необходимо установить расширение работы с файлами.'"));

ПеречитатьСуммуПоКурсу(Сумма, КурсВалютыНаДату(Валюта));
```

https://its.1c.ru/db/v8std#content:640:hdoc

**Comment by zeegin** [comment]
А как будет определятся "компактность"?

```bsl
Result = HTTPRequests.AsBinaryData(
    HTTPRequests.Get("http://httpbin.org/image/png")
);
Assert.IsInstanceOfType(Result, "BinaryData");
Assert.AreEqual(Cryptography.MD5(Result), "5cca6069f68fbf739fce37e0963f21e7");
```
Это считать компактно?

**Comment by asosnoviy** [comment]
(не требует переноса выражений)

**Comment by asosnoviy** [comment]
```
Result = HTTPRequests.AsBinaryData(HTTPRequests.Get("http://httpbin.org/image/png"));
```

**Comment by zeegin** [comment]
т.е. так нельзя?
```bsl
Assert.AreEqual(Cryptography.MD5(Result), "5cca6069f68fbf739fce37e0963f21e7");
```

**Comment by asosnoviy** [comment]
А тут вроде все красиво.

**Comment by theshadowco** [comment]
Если резюмировать правило, то: если есть вложенные вызовы, но все в однстроке - то хорошо. Если же строка будет длинной, сработает диагностика на длинную строку, а потом вложенные сразу станут плохими, ибо есть перенос.

**Comment by Stepa86** [comment]
Предлагаю агрится на `)))` в коде, а не на переносы. Все таки вызов со вложенными вызовами может быть нормальным.

```bsl
ОтправитьПочту(
    Тело(контекст),
    Тема(контекст),
    Адресаты(контекст),
    Файлы(контекст),
    НекоторыеДополнительныеПараметрыРадиДлины(контекст));
```

**Comment by asosnoviy** [comment]
Каждый вложенный должен быть на новой строке. И занимать не более одной строки.
