### ISSUE TITLE
[NEW] Изменение ТекущиеДанные на клиенте при модификации ТЧ/ТЗ в контекстном серверном вызове.

### ISSUE THREAD

**Issue by 240596448** [1c-syntax/bsl-language-server#762]
## Описание проблемы, ошибки, которую надо диагностировать
``` bsl

&НаКлиенте
.....
ТекущиеДанные = Элементы.ТЗ.ТекущиеДанные;
.....
ТЗНоменклатураПриИзмененииНаСервере(.....); // Контекстный серверный вызов

// ВНИМАНИЕ ! В серверном вызове произошло изменение ТЗ, 
// поэтому ТекущиеДанные <> Элементы.ТЗ.ТекущиеДанные;
.....
// Если здесь мы заново не присвоим переменную, 
// то СтавкаНДС будет расчитана в "первой" строке

// ТекущиеДанные = Элементы.ТЗ.ТекущиеДанные;

ТекущиеДанные.СтавкаНДС  = ЗаполнитьСтавкуНДС(ТекущиеДанные.Номенклатура);


```

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :ant: Ошибка
* [ ] :cop: Уязвимость
* [x] :guardsman: Потенциальная уязвимость
* [x] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [ ] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [x] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [x] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [ ] `ERROR` - "Ошибочная конструкция"

**Comment by zeegin** [comment]
Опиши подробнее, пожалуйста, причину и поведение.

**Comment by 240596448** [comment]
Погорячился... Для диагностики не подходит случай. Отбой.
PS: В тиражном плохокоде (Молокозавод для ЕРП) массовое явление: перезаполняют ТЗ в середине процедуры и поэтому "теряются" ТекущиеДанные (идентификатор строки перестает существовать).
