### ISSUE TITLE
[BUG] После вставки в VSC текста из буфера плагин ошибочно помечает весь файл как ошибочный.

### ISSUE THREAD

**Issue by EightM** [1c-syntax/bsl-language-server#778]
**Версия**
Последняя develop сборка.

**Описание ошибки**

1. Берем bsl файл c содержимым ниже. Он должен быть сохранен заранее;
2. Открываем файл в VSC. Ждем пока завершится анализ диагностик. Убеждаемся что на ```#Область ВнешняяНепустаяОбласть 
#Область ВнутренняяНепустаяОбласть``` нет срабатывания;
3. Делаем CTRL+A CTRL+X CTRL+V CTRL+S. Видим, что VSC помечает все области как пустые. Повторное сохранение не помогает, лечится только перезапуском VSC.

**Пример кода**
```#Область Тест
// должна упасть здесь
#КонецОбласти

#Область ВнешняяОбласть // срабатывание так как во внешней области нет функций
#Область ВнутренняяОбласть // срабатывание так как во внутренней области нет функций

#КонецОбласти
#КонецОбласти

#Область Тест3 // Нет срабатывания

Функция Тест()
КонецФункции

#КонецОбласти

#Область ВнешняяНепустаяОбласть // Нет срабатывания
#Область ВнутренняяНепустаяОбласть // Нет срабатывания

Функция Тест()
КонецФункции

#КонецОбласти
#КонецОбласти
```

**Comment by asosnoviy** [comment]
@EightM пофикшено же?

**Comment by EightM** [comment]
@asosnoviy На 0.14.1 не воспроизводится
