### ISSUE TITLE
[FP] CodeOutOfRegion на пустом модуле

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#804]
## Диагностика
CodeOutOfRegion

## Версия
13 alfa

## Описание ложного срабатывания диагностики
Пустой модуль

## Скриншоты

![image](https://user-images.githubusercontent.com/15638529/72448871-d5e89d80-37c8-11ea-8142-fe640bc880d6.png)

**Comment by nixel2007** [comment]
Ахах, это прекрасно)
