### ISSUE TITLE
[MOD] По умолчанию считать "Вставить содержимое обработчика" сервисным тэгом

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#810]
## Диагностика

UsingServiceTag

## Версия

0.13

## Описание ложного НЕ срабатывания диагностики

Не ловит комментарий `// Вставить содержимое обработчика.`

## Пример кода
```
&НаКлиенте
Процедура Отменить(Команда)
	// Вставить содержимое обработчика.
КонецПроцедуры

&НаКлиенте
Процедура Повторить(Команда)
	// Вставить содержимое обработчика.
	// TODO: Доделать
КонецПроцедуры
```

## Скриншоты

![image](https://user-images.githubusercontent.com/25096392/72505022-1c350f80-3850-11ea-8f67-512f6d21b600.png)

**Comment by theshadowco** [comment]
а ты его в параметр диагностики добавлял?

**Comment by nixel2007** [comment]
Спич про то, чтобы добавить его в дефолтные параметры.

**Comment by Stepa86** [comment]
Т.к. это генерируемая 1Ской штука - логичнее иметь ее в параметре по умолчанию. Я сам попробую эту непростую задачу сделать

**Comment by theshadowco** [comment]
Тогда добавь и английский вариант )
