### ISSUE TITLE
[FN] Пропускает пустые процедуры и функции

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#811]
## Диагностика

EmptyCodeBlock

## Версия

0.12.3, 0.13RC1

## Описание ложного НЕ срабатывания диагностики

Не выдает замечаний на пустые процедуры и функции

## Пример кода

```

Процедура Отменить(Команда)
	
КонецПроцедуры

Процедура Отменить2(Команда)
	ЛюбоеВыражение();
КонецПроцедуры

&НаКлиенте
Процедура Повторить(Команда)
	// Вставить содержимое обработчика.
	// TODO: Доделать
КонецПроцедуры

Функция НоваяФункция()
	
КонецФункции

Процедура НоваяПроцедура()

КонецПроцедуры

Процедура ЕщеНоваяПроцедура()

КонецПроцедуры
```

Функция ругается на на возврат, а не на пустоту.

## Скриншоты

![image](https://user-images.githubusercontent.com/25096392/72506183-78992e80-3852-11ea-9ff8-45093805f8b7.png)

**Comment by Stepa86** [comment]
Вот тут было отключено #21

**Comment by theshadowco** [comment]
тогда это не ошибка/FN

**Comment by Stepa86** [comment]
В общем случае пустой метод все же является ошибкой

**Comment by theshadowco** [comment]
надо определяться  - одни хотят пустые методы, другие нет :)

**Comment by asosnoviy** [comment]
Имхо надо заводить ихуз на диагностику пустых методов и там тереть

**Comment by theshadowco** [comment]
@Stepa86 
Запостишь?

**Comment by Stepa86** [comment]
Чот чем дальше, тем меньше я уверен, что такая проверка нужна.
В АПК я ее не смог найти, есть только "Ошибка платформенной проверки конфигурации: Пустой обработчик."

На пустые методы в которых торчит обработчик туду есть диагностика на эти самые туду. И получается что чаще бывает специально пустой метод, чем случайно пустой.
