### ISSUE TITLE
[FP] EmptyRegion

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#823]
## Диагностика
EmptyRegion

## Скриншоты

![image](https://user-images.githubusercontent.com/15638529/72731259-6f86c500-3ba4-11ea-8375-8e18bdcec7ac.png)

**Comment by asosnoviy** [comment]
Есть подозрение, что полечено магией с очисткой областей

**Comment by asosnoviy** [comment]
> Есть подозрение, что полечено магией с очисткой областе

Нет не полечено =(

**Comment by theshadowco** [comment]
они там не используются, я ловил этот FP но забыл зарегать. если никто не взял, беру себе
