### ISSUE TITLE
SelfAssign fp

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#83]
НовыйУникальныйИдентификатор = Новый УникальныйИдентификатор;

**Comment by nixel2007** [comment]
вайтспейсы?

**Comment by asosnoviy** [comment]
Вероятно текст позновато взял....

**Comment by nixel2007** [comment]
а проверь-ка на количество токенов слева и справа?

**Comment by asosnoviy** [comment]
Там еще препроцессор могет быть=(
