### ISSUE TITLE
Ограничение на использование метода Сообщить

### ISSUE THREAD

**Issue by lChagelishvili** [1c-syntax/bsl-language-server#85]
Для вывода сообщений пользователю во всех случаях следует использовать объект СообщениеПользователю, даже когда сообщение не «привязывается» к некоторому элементу управления формы. Метод Сообщить применять не следует.

[https://its.1c.ru/db/v8std#content:-2145783229:hdoc:_top:сообщить](https://its.1c.ru/db/v8std#content:-2145783229:hdoc:_top:сообщить)

**Comment by asosnoviy** [comment]
bsl only

**Comment by otymko** [comment]
Беру в работу, если никто не против

**Comment by asosnoviy** [comment]
Велкам, но впоришься в грамматику =)

**Comment by lChagelishvili** [comment]
Доберешься раньше меня до грамматики, дай знать ). Мне тоже надо для соседней задачи.

**Comment by otymko** [comment]
> Велкам, но впоришься в грамматику =)
> [1c-syntax/bsl-parser#22](https://github.com/1c-syntax/bsl-parser/issues/22)

Покурю на этой неделе

**Comment by zeegin** [comment]
Есть еще ряд функций, которые использовать не следует.
Часто это устаревшие функции.
Потому лучше сразу заложить, начиная с какого режима совместимости платформы не использовать, и что использовать взамен.
Могу сделать таблицу всего что использовать нельзя.

**Comment by zeegin** [comment]
А @Stepa86 уже их все отдельными ищьюсами сделал))

**Comment by nixel2007** [comment]
@otymko обращаю внимание, что @asosnoviy начал делать

**Comment by otymko** [comment]
@nixel2007 Хорошо

**Comment by lavelinevgeny** [comment]
Удобней будет, ИМХО, если расширить текущее сообщение об ошибке "Не следует использовать устаревший метод "Сообщить" указанием рекомендуемого к использвоанию метода, т.е. например "Вместо использования устаревшего метода "Сообщить" необходимо использовать объект "СообщениеПользователю"
