### ISSUE TITLE
Позиционирование canonicalKeyWord

### ISSUE THREAD

**Issue by asosnoviy** [1c-syntax/bsl-language-server#89]
![image](https://user-images.githubusercontent.com/15638529/53043239-18aad400-3499-11e9-8593-351a14549eed.png)

**Comment by lChagelishvili** [comment]
Я так понимаю, последний символ не добирает?

**Comment by nixel2007** [comment]
Да, похоже на то

**Comment by asosnoviy** [comment]
https://github.com/1c-syntax/bsl-language-server/blob/develop/src/main/java/org/github/_1c_syntax/bsl/languageserver/diagnostics/CanonicalSpellingKeywordsDiagnostic.java#L476

Может тут?

**Comment by nixel2007** [comment]
ванга говорит, что туда на просто передать token. и хелпер сам подсчитает
нужный range

ср, 20 февр. 2019 г. в 13:29, Alexey Sosnoviy <notifications@github.com>:

**Comment by lChagelishvili** [comment]
Да, я нашел уже, будет скоро PR )
