### ISSUE TITLE
[BUG] CyclomaticComplexityDiagnostic ошибка в позиционировании

### ISSUE THREAD

**Issue by theshadowco** [1c-syntax/bsl-language-server#900]
## Диагностика

CyclomaticComplexityDiagnostic 

## Версия

latest RC

## Описание ошибки диагностики

Обнаружено неверное позиционирование замечения + лишний элемент в релейшене

## Скриншоты

![image](https://user-images.githubusercontent.com/9591731/72964690-9b37c400-3dcb-11ea-804f-ff6bc5eccc27.png)

**Comment by nixel2007** [comment]
@theshadowco это не тот скрин)

**Comment by theshadowco** [comment]
поправил
