### ISSUE TITLE
[FP] CompilationDirectiveNeedLess. Cрабатывает на директивы в общих формах в формате edt

### ISSUE THREAD

**Issue by qtLex** [1c-syntax/bsl-language-server#902]
## Диагностика
CompilationDirectiveNeedLess

## Версия

v0.13.0-RC6

## Описание ложного НЕ срабатывания диагностики
Срабатывает на директивы в общих формах в формате edt

## Скриншоты
![2020-01-23_15-36-55](https://user-images.githubusercontent.com/5488710/72985368-eddaa580-3df6-11ea-8ec3-9096008a615e.png)
![2020-01-23_15-35-52](https://user-images.githubusercontent.com/5488710/72985370-eddaa580-3df6-11ea-97aa-6095ccaca5fa.png)

**Comment by otymko** [comment]
https://github.com/1c-syntax/mdclasses/issues/43

**Comment by qtLex** [comment]
Я так понял влили исправление этим pr #904 
Можно зыкрыть
