### ISSUE TITLE
[MOD] CodeOutOfRegion подвечивать только заголовки функций

### ISSUE THREAD

**Issue by DitriXNew** [1c-syntax/bsl-language-server#911]
## Диагностика
CodeOutOfRegion

## Описание предлагаемых изменений
Если в модуле нет областей, то подсвечивать только сами заголовки функции, а не весь модуль целиком.

**Comment by nixel2007** [comment]
помимо функций есть еще просто выражения в модуле. как подсвечивать их?

**Comment by theshadowco** [comment]
> помимо функций есть еще просто выражения в модуле. как подсвечивать их?

блок целиком, иначе никак
