### ISSUE TITLE
Повторный блок в условии

### ISSUE THREAD

**Issue by Stepa86** [1c-syntax/bsl-language-server#92]
Когда ИначеЕсли копипастят, то могут забыть поменять блок выполнения

```bsl
Если п = 0 Тогда
    т = 0;
ИначеЕсли п = 1 Тогда
    т = 1;
ИначеЕсли п = 2 Тогда
    т = 1;
Иначе
    т = -1;
КонецЕсли;
```

**Comment by lChagelishvili** [comment]
А скажите, как тут правильнее подобраться к решению.
Напрямую сравнивать тексты блоков исполнения или проверять деревья (блоки исполнения ) на эквивалентность?

**Comment by asosnoviy** [comment]
В прошлый раз у тебя с текстом получилось =)

**Comment by lChagelishvili** [comment]
Да, но в условии текста всего ничего, а вот кода может быть до черта

**Comment by nixel2007** [comment]
Сравнение деревьев ничего особо не даст, так как в двух разных ветках будут уникальные для них токены. Объекты разные, соответственно сравнивать надо по deep equal. Текст будет быстрее

**Comment by lChagelishvili** [comment]
> . Объекты разные, соответственно сравнивать надо по deep equal. Текст будет быстрее

Это если деревья в самом деле полностью совпадают и я в процессе сравнения доберусь до самого последнего узла, но кажется что в большинстве случаев проверка может закончится на чем то вроде: 
 
```java
if (leftNode.getChildCount() != rightNode.getChildCount()) {
      return false;
    }
```
А getText() гарантированно должен обойти дерево во всю глубину.

Мне просто сложно сходу оценить сколько на этом можно выйграть и стоит ли оно того. 
Разобраться что ли как профайлером в идее пользоваться...

**Comment by nixel2007** [comment]
Да, предварительная проверка детей может быть полезна. Только нужно не сразу же детей смотреть, а codeBlock().expressions().getChildCount() хотя бы.

**Comment by lChagelishvili** [comment]
> codeBlock().expressions().getChildCount() 

Наверное на свежую голову надо посмотреть, мне казалось, что 
```Jаva
BSLParser.IfStatementContext ctx;
ctx.codeBlock()
```
возвращает нужные деревья для анализа.
Попробую завтра набросать черновик сравнения по дереву, посмотрим что получится.

**Comment by nixel2007** [comment]
Да, я тоже мог напутать с просонья)
