### ISSUE TITLE
[FP] Ругается на область Инициализация в модуле набора записей регистров

### ISSUE THREAD

**Issue by qtLex** [1c-syntax/bsl-language-server#921]
## Диагностика
NonStandardRegion

## Версия
develop

## Описание ложного срабатывания диагностики
В модуле набора записей срабатывает на область Инициализация

## Пример кода
```bsl
#Область Инициализация

РежимПроведения = РежимПроведенияДокумента.Оперативный;

#КонецОбласти
```

## Скриншоты
![изображение](https://user-images.githubusercontent.com/5488710/73441147-9347c900-4363-11ea-9d83-fb2df499dd44.png)

**Comment by asosnoviy** [comment]
Раздел описания переменных и раздел инициализации не могут быть определены в неглобальных общих модулях, модулях менеджеров объектов, наборов записей, значений констант и модуле сеанса.

**Comment by qtLex** [comment]
В стандарте, как мне кажется, имеется ввиду модуль менеджера наборов записей. 
Если можно создать переменную то должны быть области для переменной и инициализации ее. На область переменных в этом же модуле не ругается.

**Comment by asosnoviy** [comment]
Согласен. Стандарт про модуль менеджера. В модуле набора записей область должна быть.
