### ISSUE TITLE
startLine = endLine в Diagnostic

### ISSUE THREAD

**Issue by otymko** [1c-syntax/bsl-language-server#93]
При экспорте возникает проблема:
![image](https://user-images.githubusercontent.com/11651847/53223989-ba9f0c00-36a5-11e9-9243-c82ed766ffe1.png)

![image](https://user-images.githubusercontent.com/11651847/53224000-bf63c000-36a5-11e9-8183-7ce1c449dcc4.png)

Пример файла:
[RecordSetModule.zip](https://github.com/1c-syntax/bsl-language-server/files/2892685/RecordSetModule.zip)

**Comment by otymko** [comment]
@asosnoviy вот пример

**Comment by lChagelishvili** [comment]
У меня не воспроизводится.
А что показывает в других форматах?

**Comment by otymko** [comment]
мб у меня просто косяк из-за сдвига для format generic?

**Comment by lChagelishvili** [comment]
Ну если с остальными форматами не совпадает, то точно да

**Comment by otymko** [comment]
@asosnoviy уже исправил.
