### ISSUE TITLE
[FP] Исключить проверку объектов по работе с внешними ресурсами, где таймаут задан по умолчанию

### ISSUE THREAD

**Issue by grumagargler** [1c-syntax/bsl-language-server#939]
## Диагностика
TimeoutsInExternalResources

## Описание ложного срабатывания диагностики
Пример кода, на котором срабатывает диагностика:

`profile = new InternetMailProfile ();`

Согласно документации, объект выше создается с таймаутом 30 секунд, что подавляющем большинстве случаев, устраивает. Диагностика должна принимать это во внимание, и не выдавать ошибку о не заданном таймауте.

**Comment by EightM** [comment]
Судя по всему, таймаут по умолчанию есть только у ИнтернетПочтовыйПрофиль, начиная с 8.1 https://its.1c.ru/db/metod8dev/content/2358/hdoc, так что исключать из проверки нужно только его.

**Comment by nixel2007** [comment]
насколько я понимаю, тогда этот объект целиком можно исключить из проверки?
или сделать пропертю (по умолчанию выключенную) - проверять ИнтернетПочтовыйПрофиль на явное указание таймаута?

**Comment by asosnoviy** [comment]
30 секунд не многовато ли для тайм аута?

**Comment by nixel2007** [comment]
главное, что он есть, а не вечный зависон.

**Comment by grumagargler** [comment]
> 30 секунд не многовато ли для тайм аута?

и по факту, он вообще до фени, вот такой код не завершится по таймауту через 3 секунды (8.3.14.1976):
```
profile = new InternetMailProfile ();
profile.Timeout = 3;
profile.SMTPServerAddress = "1and1.com";
profile.SMTPUser = "user";
profile.SMTPPassword = "password";

mail = new InternetMail ();
mail.Logon ( Profile );
mail.Logoff ();
```
Хотя к самой диагностике это отношения не имеет.
