### ISSUE TITLE
[FP] The iterator is not used in the For Each loop body

### ISSUE THREAD

**Issue by grumagargler** [1c-syntax/bsl-language-server#940]
## Диагностика
UseLessForEach

## Описание ошибки диагностики
Данная диагностика не принимает во внимание случай использования в качестве итератора, переменной области модуля.

## Пример кода
Код ниже приводит к ложному срабатыванию диагностики:
```
var Field;

procedure proc1 ()
    set = new Array ();
    for each Field in set do
        proc2 ();
    enddo;
endprocedure

procedure proc2 ()
    Message ( Field );
endprocedure
```

**Comment by MinimaJack** [comment]
При наличии сотни процедур кто будет смотреть в переменные модуля?
codesmells

**Comment by grumagargler** [comment]
> При наличии сотни процедур кто будет смотреть в переменные модуля?
> codesmells

Диагностика будет смотреть.
Сотни процедур в модуле это и есть codesmells. Переменные модуля для того и придуманы, чтобы разгружать логику, иначе можно использовать общие модуля. В любом случае, диагностика  с точки зрения правил языка срабатывать не должна.

**Comment by nixel2007** [comment]
если честно, я бы:
1) пофиксил эту проблему, т.к. это реально недосмотр
2) добавил бы диагностику на shadow-variable (тем более, что она уже есть и ждет окончания допилок по VariableSymbol)

Первое решит проблему Димы, второе даст возможность всем остальным все же отлавливать такие случаи. на моей практике от shadow-variables я больше страдаю, чем получаю пользы, но надо дать возможность это конфигурировать/давить.

**Comment by asosnoviy** [comment]
Эта диагностика про то, что цикл гоняется в холостую. В примере это явно не так. 
ФП который надо править.

**Comment by grumagargler** [comment]
> 2\. добавил бы диагностику на shadow-variable (тем более, что она уже есть и ждет окончания допилок по VariableSymbol)

Понимаешь, если бы в моем примере был еще и реквизит формы (или реквизит объекта) с именем Field, тогда это был бы классический shadow-variable, но в моем примере это не так. Я думаю сопротивление возникает в силу необычности конструкции, чем связанных реальных проблем, потому что никто не отрицает, что переменные уровня модуля - часть языка, и делать им присвоение внутри цикла или внутри выражения цикла дело техники.

**Comment by nixel2007** [comment]
> Понимаешь, если бы в моем примере был еще и реквизит формы (или реквизит объекта) с именем Field, тогда это был бы классический shadow-variable, но в моем примере это не так.

хм, а вот на это я не обратил внимания. действительно, shadow и выделения отдельного хранилища под переменную не происходит.

**Comment by asosnoviy** [comment]
Вроде в телеге еще какой то кейс был. Не могу понять полностью закрыть ишуз или нет

**Comment by grumagargler** [comment]
исправление #1063 закрывает мою проблему, поэтому с моей точки зрения, можно закрывать.

**Comment by grumagargler** [comment]
> Вроде в телеге еще какой то кейс был. Не могу понять полностью закрыть ишуз или нет

исправление #1063 закрывает мою проблему, поэтому с моей точки зрения, можно закрывать.
