### ISSUE TITLE
[FP] Исключить проверку на ДанныеФормыВЗначение в Процедурах/Функциях НаСервереБезКонтекста

### ISSUE THREAD

**Issue by velsevur** [1c-syntax/bsl-language-server#942]

**Comment by EightM** [comment]
А что насчёт НаКлиентеНаСервереБезКонтекста?

**Comment by velsevur** [comment]
Красная ошибка **Функция не определена** (Тонкий клиент)

**Comment by asosnoviy** [comment]
@velsevur Дай пример плз. Эта проверка действительно не должна реагировать на некоторые контексты...

**Comment by velsevur** [comment]
![image](https://user-images.githubusercontent.com/11294244/73932827-2a74c980-48ec-11ea-9a25-1456dd75c5c3.png)

**Comment by EightM** [comment]
Заберу себе
