### ISSUE TITLE
[MOD] Отключить по-умолчанию диагностику "Вложенный тернарный оператор"

### ISSUE THREAD

**Issue by shmalevoz** [1c-syntax/bsl-language-server#943]
## Диагностика
Вложенный тернарный оператор

## Описание предлагаемых изменений
По-умолчанию отключить - вложенный тернарный оператор имеет фактически двукратное преимущество по скорости выполнения по сравнению с конструкцией Если/ИначеЕсли/Иначе

## Дополнительная информация

Пример замера
```bsl
	ф1	= 1;
	ф2	= 2;
	
	Начало	= ТекущаяУниверсальнаяДатаВМиллисекундах();
	Для Номер = 1 По 1000000 Цикл
		Если ф1 = ф2 Тогда
			ф = 3;
	        ИначеЕсли ф1 > ф2 Тогда
			ф = 4;
		ИначеЕсли ф1 < ф2 Тогда
			ф = 5;
		Иначе
			ф = 6;
		КонецЕсли;
	КонецЦикла;
	Замер	= ТекущаяУниверсальнаяДатаВМиллисекундах() - Начало;
	Сообщить(Замер);
```
дает время выполнения **6047**
против
```bsl
	ф1	= 1;
	ф2	= 2;
	
	Начало	= ТекущаяУниверсальнаяДатаВМиллисекундах();
	Для Номер = 1 По 1000000 Цикл
		ф	= ?(ф1 = ф2
		, 3
		, ?(ф1 > ф2
		, 4
		, ?(ф1 < ф2
		, 5
		, 6)));
	КонецЦикла;
	Замер	= ТекущаяУниверсальнаяДатаВМиллисекундах() - Начало;
	Сообщить(Замер);
```
времени выполнения **3016**

**Comment by asosnoviy** [comment]
А реальный пример вместо синтетики есть?

**Comment by nixel2007** [comment]
использование вложенного тернарного оператора в целом значительно затрудняет чтение и понимание кода.

Склонен рекомендовать отключать это правило в вашем конфиг-файле проекта, а не менять умолчание для всех пользователей.

**Comment by Stepa86** [comment]
Если делать замеры без подключенного отладчика, то профит уже не такой большой.
![image](https://user-images.githubusercontent.com/25096392/73923087-5b98ce00-48db-11ea-8a21-02de4de4fcf7.png)

Оптимизированный код и сопровождаемый код это все таки разные концепции. Сонар про сопровождаемый код. А уже когда код работает, работает правильно, работает понятно, но скорость не устраивает, тогда уже код можно оптимизировать, сильно ухудшая читаемость.

**Comment by shmalevoz** [comment]
С отключением отладки дифферент конечно скрадывается, но тем не менее кажется существенным. Весь вопрос в экономическом эффекте, и 10% на время разработки кажутся дешевле 10% времени работы приложения =)
Сложно конечно спорить, что примерно такое 
```Результат	= ?(Условие1, Значение1, ?(Условие2, Значение2, ?(Условие3, Значение3, Умолчание)));```
сложночитаемо и режет глаз, но вот в таком виде вполне ложится на глаз
```
Результат	= ?(Условие1	// Если Условие1 Тогда
, Значение1				//	Значение1
, ?(Условие2				// ИначеЕсли Условие2
, Значение2				//	Значение2
, ?(Условие3				// ИначеЕсли Условие3
, Значение3				//	Значение3
, Умолчание)));			// Иначе Умолчание
```
комментарии показывают как читается, в чистом коде их конечно нет
Возможно вместо рекомендации использования Если/ИначеЕсли лучше была бы проверка на оформление тернарного оператора и рекомендация по его оформлению в случае неверной записи ?

**Comment by asosnoviy** [comment]
Производительность vs Поддерживаемость. 
В местах где производительность максимально важна, вольны хоть на асме писать.
В остальных местах, которые живые и шевелятся читаемость дороже.

**Comment by Stepa86** [comment]
Выигрыш не в 10% работы приложения, а в 0.1 секунды на 1000000 операций
