### ISSUE TITLE
[NEW] "ЭтотОбъект" в управляемых формах и общих модулях

### ISSUE THREAD

**Issue by freewms** [1c-syntax/bsl-language-server#967]
## Описание проблемы, ошибки, которую надо диагностировать
Режим совместимости 8.3.3 

В модулях управляемых форм и общих модулях не должно быть переменной
с именем "ЭтотОбъект"

Например:
```bsl
ЭтотОбъект = РеквизитФормыВЗначение("Объект");

```

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [x] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)

1

**Comment by nixel2007** [comment]
Проблема именно в присваивании в переменную с именем ЭтотОбъект?

**Comment by asosnoviy** [comment]
> Проблема именно в присваивании в переменную с именем ЭтотОбъект?

Ага

**Comment by asosnoviy** [comment]
с 8.3.3

**Comment by artbear** [comment]
На самом деле проблема здесь шире. баг будет не только в упр.формах и общих модулях

а в **любых модулях метаданных, где есть служебная переменная ЭтотОбъект**

- например, я проверил для модуля общей команды
  - ![image](https://user-images.githubusercontent.com/2920817/79075461-ad0a7280-7cfb-11ea-9b4d-5944b3664923.png)

- список метаданных с ЭтотОбъект
  - ![image](https://user-images.githubusercontent.com/2920817/79075408-513fe980-7cfb-11ea-9349-0222caa574e8.png)

**Comment by artbear** [comment]
создал ишуз на расширенную проблему - [NEW] Запрет присваивания служебным переменным модулей - ЭтотОбъект, ЭтаФорма, реквизиты формы и т.п. #1045

**Comment by nixel2007** [comment]
Расширить состав типов модулей - это не проблема

**Comment by asosnoviy** [comment]
Разясню немного. Свойство "ЭтотОбъект" в большинстве объектов было всегда и присваивать к нему, это надо быть очень талантливым.  Кроме УправляемыхФормы и Общего модуля, там этого свойства небыло. И код `ЭтотОбъект = РеквизитФормыВЗначение("Объект");` Это вполне валидный распространенный код до 8.3.3 

Теперь берем старую конфу и поднимаем режим совместимости, ловим проблему.
