### ISSUE TITLE
[BUG] Ошибка при анализе кода 1С7

### ISSUE THREAD

**Issue by Alser84** [1c-syntax/bsl-language-server#994]
**Версия**
1.4.2

**Описание ошибки диагностики**
При анализе кода 1С7 ( файл 1sm) через Jenkins, выходит ошибка:
00:00:09.295 13:26:34.579 INFO: ------------------------------------------------------------------------
00:00:09.295 13:26:34.579 INFO: EXECUTION FAILURE
00:00:09.295 13:26:34.579 INFO: ------------------------------------------------------------------------
00:00:09.295 13:26:34.579 INFO: Total time: 8.648s
00:00:09.558 13:26:34.842 INFO: Final Memory: 148M/616M
00:00:09.558 13:26:34.842 INFO: ------------------------------------------------------------------------
00:00:09.558 13:26:34.842 ERROR: Error during SonarQube Scanner execution
00:00:09.559 java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Start pointer [line=193, lineOffset=10] should be before end pointer [line=193, lineOffset=9]
00:00:09.560 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
00:00:09.560 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
00:00:09.560 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
00:00:09.560 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
00:00:09.560 	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:600)
00:00:09.560 	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
00:00:09.560 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:737)
00:00:09.560 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
00:00:09.560 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
00:00:09.560 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
00:00:09.560 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
00:00:09.560 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:661)
00:00:09.560 	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.lambda$execute$4(BSLCoreSensor.java:166)
00:00:09.560 	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
00:00:09.560 	at com.github._1c_syntax.bsl.sonar.BSLCoreSensor.execute(BSLCoreSensor.java:155)
00:00:09.560 	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
00:00:09.560 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
00:00:09.560 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
00:00:09.560 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
00:00:09.560 	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
00:00:09.560 	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
00:00:09.560 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
00:00:09.560 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
00:00:09.560 	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:400)
00:00:09.560 	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:395)
00:00:09.560 	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:358)
00:00:09.560 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
00:00:09.560 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
00:00:09.560 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:141)
00:00:09.560 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
00:00:09.560 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
00:00:09.560 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
00:00:09.560 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
00:00:09.560 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
00:00:09.560 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:00:09.561 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:00:09.561 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:00:09.561 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
00:00:09.561 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
00:00:09.561 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
00:00:09.561 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
00:00:09.561 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
00:00:09.561 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
00:00:09.561 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
00:00:09.561 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Пример кода**
`Процедура Выполнить()
	Если ПустоеЗначение(выбДок)=1 Тогда
		Возврат;
`
**Скриншоты**
![image](https://user-images.githubusercontent.com/12712626/76483654-66460600-6439-11ea-9ae4-d98905d49a1b.png)

**Дополнительная информация**
Ошибка пропала после того как заменили Выполнить() на другое т.к. Выполнить() это служебная конструкция в 1С8.

**Comment by zeegin** [comment]
Я думаю в исключение валиться не должно, а как ошибку показывать должно, наверное в рамках проверки на ключевые имена.

**Comment by asosnoviy** [comment]
Вчера показывало ошибку разбора, но не падало.

**Comment by asosnoviy** [comment]
Посмотрел в лог. Падает сонар из-за старт-енд. Посмотрю кто врет.

**Comment by artbear** [comment]
А что за "1С7 ( файл 1sm)" ? что за система?

**Comment by asosnoviy** [comment]
Дело было не в бабине.

```json
 "diagnostics": [
    {
      "range": {
        "start": {
          "line": 0,
          "character": 10
        },
        "end": {
          "line": 0,
          "character": 19
        }
      },
      "severity": 1,
      "code": "ParseError",
      "source": "bsl-language-server",
      "message": "Ошибка разбора исходного кода. Ожидался один из следующих токенов: "
    },
    {
      "range": {
        "start": {
          "line": 0,
          "character": 10
        },
        "end": {
          "line": 0,
          "character": 9
        }
      },
      "severity": 4,
      "code": "CodeOutOfRegion",
      "source": "bsl-language-server",
      "message": "Переместите код в область",
      "relatedInformation": [
        {
          "location": {
            "uri": "file:///C:/Users/Lab/Desktop/Module.bsl",
            "range": {
              "start": {
                "line": 0,
                "character": 10
              },
              "end": {
                "line": 0,
                "character": 9
              }
            }
          },
          "message": "+1"
        }
      ]
    }
  ]
```

**Comment by artbear** [comment]
т.е. ошибка в правиле? неверный диапазон возвращается?

у Сонар-АПИ есть универсальный метод-хелпер, проверяющий диапазон, при добавлении диагностики.
а у БСЛ-сервера, похоже, такого нет. или он отработал неверно.

**Comment by nixel2007** [comment]
> а у БСЛ-сервера, похоже, такого нет. или он отработал неверно.

есть тест на то, чтобы диагностики не кидали одинаковый ренж. но в парс-еррор нет тест кейса с такой ситуацией.

> у Сонар-АПИ есть универсальный метод-хелпер, проверяющий диапазон, при добавлении диагностики.

хелпера не знаю. знаю только метод, который сразу эксепшен кидает

**Comment by nixel2007** [comment]
@asosnoviy а, т.е. это `CodeOutOfRegion` косячит?

**Comment by asosnoviy** [comment]
> `CodeOutOfRegion`

Очень похоже.

**Comment by asosnoviy** [comment]
@nixel2007 дежавю, перепутанные токены при ошибке разбора уже точно попадались пару раз.
