### ISSUE TITLE
[NEW]Обращение к отсутствующему методу общего модуля

### ISSUE THREAD

**Issue by akabrr** [1c-syntax/bsl-language-server#995]
## Описание проблемы, ошибки, которую надо диагностировать
Почему то синтаксический контроль не отлавливает ошибку обращения к отсутствующему методу общего модуля. Был сильно удивлен когда сегодня нарвался в режиме предприятия, разработчик опечатался - 1С съело и не поморщилось. Такой диагностики не нашел.

### Тип [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :ant: Ошибка
* [ ] :cop: Уязвимость
* [ ] :guardsman: Потенциальная уязвимость
* [ ] :poop: Качество кода
* [ ] :trollface: Другое

### Важность [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTypeAndSeverity)

* [x] :broken_heart: Блокирующая / Blocker
* [ ] :heart: Критическая / Critical
* [ ] :yellow_heart: Важная / Major
* [ ] :blue_heart: Незначительная / Minor
* [ ] :green_heart: Информационная / Info
* [ ] :revolving_hearts: Другое

### Тэги [Статья на русском](https://1c-syntax.github.io/bsl-language-server/contributing/DiagnosticTag)

* [ ] `STANDARD` - "Нарушение стандартов 1С"
* [ ] `LOCKINOS` - "Не будет работать в другой ОС"
* [ ] `SQL` - "Проблема с запросом"
* [ ] `PERFORMANCE` - "Проблема производительности"
* [ ] `BRAINOVERLOAD` - "Непонятный код"
* [ ] `BADPRACTICE` - "Плохая практика программирования"
* [ ] `CLUMSY` - "Излишние действия"
* [ ] `DESIGN` - "Ошибка в проектировании"
* [ ] `SUSPICIOUS` - "Подозрительный код"
* [ ] `UNPREDICTABLE` - "Непредсказуемо работающий код"
* [ ] `DEPRECATED` - "Устаревшая функциональность"
* [x] `ERROR` - "Ошибочная конструкция"
* [ ] `LOCALIZE` - "Проблемы локализации"

### Время на исправление (минут)
1

**Comment by Stepa86** [comment]
В конфигураторе расширенной проверкой ловится должно. Но этот флаг иногда слетает в настройках.

**Comment by akabrr** [comment]
Подтверждаю, расширенной проверкой ловится. Тогда на усмотрение уважаемых разработчиков - закрыть или оставить задачу.

**Comment by asosnoviy** [comment]
Оставить конечно же =)

**Comment by TheDemonCat** [comment]
Идентификатор : CallToNonexistentMethod 
Такой тест кейс нормальный?

```bsl
// Русский
Функция МояФункция()
   
    А = ВызовCуществующейФункции();
    ВызовСуществующегоМетода();

    // Ошибка
    B = ВызовНесуществующейФункции();
    // ошибка
    ВызовНеСуществующегоМетода();
КонецФункции

Процедура МояПроцедура()
    А = ВызовCуществующейФункции();
    ВызовСуществующегоМетода();

    // Ошибка
    B = ВызовНесуществующейФункции();
    // ошибка
    ВызовНеСуществующегоМетода();
КонецПроцедуры

Функция ВызовCуществующейФункции()
   Возврат 5;
КонецФункции

Function MyFunction()
    A = CallExistentFunction();
    CallExistentProcedure();

    // Error
    B = CallNonexistentFunction();
    // Error
    CallNonexistentProcedure();
EndFunction

// English
Procedure MyProcedure() Export
    A = CallExistentFunction();
    CallExistentProcedure();

    // Error
    B = CallNonexistentFunction();
    // Error
    CallNonexistentProcedure();
EndProcedure

// Correct
Function CallExistentFunction()
    Return True;
EndFunction

Procedure CallExistentProcedure() Export
    A = 5;
EndProcedure


```

**Comment by artbear** [comment]
@nixel2007 Запиши на меня, правило практически готово.
